### ISSUE TITLE
InternalException: INTERNAL Error: Something went wrong when reading the CSV file, more positions than columns

### ISSUE THREAD

**Issue by djouallah** [duckdb/duckdb#10283]
### What happens?

I can't read this csv file, it has different number of columns (130), I manually defined the schema with all those columns but could not make it to works, it works fine with pandas using the options 

 ```
df = pd.read_csv(Path+filename,
     skiprows=1,
     dtype=str,
     engine='python',
     names=range(130))
```

attached a zipped example [PUBLIC_DAILY_202311170000_20231118040504.zip](https://github.com/duckdb/duckdb/files/13996466/PUBLIC_DAILY_202311170000_20231118040504.zip)

### To Reproduce

I am running this query
```py
import duckdb
duckdb.sql("""from read_csv("PUBLIC_DAILY_202311170000_20231118040504.CSV",
Skip=1,
header =0,
sample_size=-1,
all_varchar=1,
columns={
'C1': 'VARCHAR',
'C2': 'VARCHAR',
'C3': 'VARCHAR',
'C4': 'VARCHAR',
'C5': 'VARCHAR',
'C6': 'VARCHAR',
'C7': 'VARCHAR',
'C8': 'VARCHAR',
'C9': 'VARCHAR',
'C10': 'VARCHAR',
'C11': 'VARCHAR',
'C12': 'VARCHAR',
'C13': 'VARCHAR',
'C14': 'VARCHAR',
'C15': 'VARCHAR',
'C16': 'VARCHAR',
'C17': 'VARCHAR',
'C18': 'VARCHAR',
'C19': 'VARCHAR',
'C20': 'VARCHAR',
'C21': 'VARCHAR',
'C22': 'VARCHAR',
'C23': 'VARCHAR',
'C24': 'VARCHAR',
'C25': 'VARCHAR',
'C26': 'VARCHAR',
'C27': 'VARCHAR',
'C28': 'VARCHAR',
'C29': 'VARCHAR',
'C30': 'VARCHAR',
'C31': 'VARCHAR',
'C32': 'VARCHAR',
'C33': 'VARCHAR',
'C34': 'VARCHAR',
'C35': 'VARCHAR',
'C36': 'VARCHAR',
'C37': 'VARCHAR',
'C38': 'VARCHAR',
'C39': 'VARCHAR',
'C40': 'VARCHAR',
'C41': 'VARCHAR',
'C42': 'VARCHAR',
'C43': 'VARCHAR',
'C44': 'VARCHAR',
'C45': 'VARCHAR',
'C46': 'VARCHAR',
'C47': 'VARCHAR',
'C48': 'VARCHAR',
'C49': 'VARCHAR',
'C50': 'VARCHAR',
'C51': 'VARCHAR',
'C52': 'VARCHAR',
'C53': 'VARCHAR',
'C54': 'VARCHAR',
'C55': 'VARCHAR',
'C56': 'VARCHAR',
'C57': 'VARCHAR',
'C58': 'VARCHAR',
'C59': 'VARCHAR',
'C60': 'VARCHAR',
'C61': 'VARCHAR',
'C62': 'VARCHAR',
'C63': 'VARCHAR',
'C64': 'VARCHAR',
'C65': 'VARCHAR',
'C66': 'VARCHAR',
'C67': 'VARCHAR',
'C68': 'VARCHAR',
'C69': 'VARCHAR',
'C70': 'VARCHAR',
'C71': 'VARCHAR',
'C72': 'VARCHAR',
'C73': 'VARCHAR',
'C74': 'VARCHAR',
'C75': 'VARCHAR',
'C76': 'VARCHAR',
'C77': 'VARCHAR',
'C78': 'VARCHAR',
'C79': 'VARCHAR',
'C80': 'VARCHAR',
'C81': 'VARCHAR',
'C82': 'VARCHAR',
'C83': 'VARCHAR',
'C84': 'VARCHAR',
'C85': 'VARCHAR',
'C86': 'VARCHAR',
'C87': 'VARCHAR',
'C88': 'VARCHAR',
'C89': 'VARCHAR',
'C90': 'VARCHAR',
'C91': 'VARCHAR',
'C92': 'VARCHAR',
'C93': 'VARCHAR',
'C94': 'VARCHAR',
'C95': 'VARCHAR',
'C96': 'VARCHAR',
'C97': 'VARCHAR',
'C98': 'VARCHAR',
'C99': 'VARCHAR',
'C100': 'VARCHAR',
'C101': 'VARCHAR',
'C102': 'VARCHAR',
'C103': 'VARCHAR',
'C104': 'VARCHAR',
'C105': 'VARCHAR',
'C106': 'VARCHAR',
'C107': 'VARCHAR',
'C108': 'VARCHAR',
'C109': 'VARCHAR',
'C110': 'VARCHAR',
'C111': 'VARCHAR',
'C112': 'VARCHAR',
'C113': 'VARCHAR',
'C114': 'VARCHAR',
'C115': 'VARCHAR',
'C116': 'VARCHAR',
'C117': 'VARCHAR',
'C118': 'VARCHAR',
'C119': 'VARCHAR',
'C120': 'VARCHAR',
'C121': 'VARCHAR',
'C122': 'VARCHAR',
'C123': 'VARCHAR',
'C124': 'VARCHAR',
'C125': 'VARCHAR',
'C126': 'VARCHAR',
'C127': 'VARCHAR',
'C128': 'VARCHAR',
'C129': 'VARCHAR',
'C130': 'VARCHAR'

 },
ignore_errors=true,
auto_detect=false) """).show()
```

### OS:

Linux

### DuckDB Version:

duckdb-0.9.3.dev2938

### DuckDB Client:

Python

### Full Name:

mim

### Affiliation:

Personal

### Have you tried this on the latest `main` branch?

I have tested with a main build

### Have you tried the steps to reproduce? Do they include all relevant data and configuration? Does the issue you report still appear there?

- [X] Yes, I have

**Comment by szarnyasg** [comment]
Hi @djouallah thanks for reporting this. In your original code (which I've since edited) you referred to `PUBLIC_DAILY_201804050000_20180406040501.CSV` but the attached file contains `PUBLIC_DAILY_202311170000_20231118040504.CSV`. The latter file does not reproduce the issue for me. Can you please double check?

**Comment by djouallah** [comment]
I tried again with the same file (PUBLIC_DAILY_202311170000_20231118040504.CSV) and get the same error

File ~\AppData\Roaming\Python\Python312\site-packages\IPython\core\formatters.py:708, in PlainTextFormatter.__call__(self, obj)
    701 stream = StringIO()
    702 printer = pretty.RepresentationPrinter(stream, self.verbose,
    703     self.max_width, self.newline,
    704     max_seq_length=self.max_seq_length,
    705     singleton_pprinters=self.singleton_printers,
    706     type_pprinters=self.type_printers,
    707     deferred_pprinters=self.deferred_printers)
--> 708 printer.pretty(obj)
    709 printer.flush()
    710 return stream.getvalue()

```
File ~\AppData\Roaming\Python\Python312\site-packages\IPython\lib\pretty.py:410, in RepresentationPrinter.pretty(self, obj)
    407                         return meth(obj, self, cycle)
    408                 if cls is not object \
    409                         and callable(cls.__dict__.get('__repr__')):
--> 410                     return _repr_pprint(obj, self, cycle)
    412     return _default_pprint(obj, self, cycle)
    413 finally:

File ~\AppData\Roaming\Python\Python312\site-packages\IPython\lib\pretty.py:778, in _repr_pprint(obj, p, cycle)
    776 """A pprint that just redirects to the normal repr function."""
    777 # Find newlines and replace them with p.break_()
--> 778 output = repr(obj)
    779 lines = output.splitlines()
    780 with p.group():

InternalException: INTERNAL Error: Something went wrong when reading the CSV file, more positions than columns. Open an issue on the issue tracker.
```

**Comment by djouallah** [comment]
hahaha, now it works I had to add this option
null_padding = true,

**Comment by szarnyasg** [comment]
I did some digging. First, I had to add `.show()` to trigger the error, otherwise it did not fail for me.

I tried both the stable and nightly Python packages:

### duckdb-0.9.2 
```
Traceback (most recent call last):
  File "/Users/szarnyasg/tmp/iss10283.py", line 141, in <module>
    auto_detect=false) """).show()
                            ^^^^^^
duckdb.duckdb.InvalidInputException: Invalid Input Error: CSV File not supported for multithreading. This can be a problematic line in your CSV File or that this CSV can't be read in Parallel. Please, inspect if the line 1443 is correct. If so, please run single-threaded CSV Reading by setting parallel=false in the read_csv call.
```

### duckdb-0.9.3.dev2938
```
Traceback (most recent call last):
  File "/Users/szarnyasg/tmp/iss10283.py", line 141, in <module>
    auto_detect=false) """).show()
                            ^^^^^^
duckdb.duckdb.InternalException: INTERNAL Error: Something went wrong when reading the CSV file, more positions than columns. Open an issue on the issue tracker.
```

It's great that it's working for you with `null_padding`! Of course, it still shouldn't throw internal errors even without that option, so we'll look into this.

**Comment by pdet** [comment]
Yeah, I thought this line would never hit because would be caught by the sniffer before. That's why I set it as an internal error, but of course, you can hit it if you disable the sniffer. I will change it to a proper error message with suggestions like using `null_padding` or `ignore_errors`.

**Comment by djouallah** [comment]
ok, new error now with today night build

`InvalidInputException: Invalid Input Error: Mismatch between the number of columns (53) in the CSV file and what is expected in the scanner (54).`

**Comment by djouallah** [comment]
same, but it was working before, actually it does work with 0.9.2

**Comment by pdet** [comment]
Hey Mimoune, I've tried the following query with a `main` build, and it seems to work. Not sure if I might be missing something.

```sql
from read_csv("/Users/holanda/Desktop/pb.CSV",
Skip=1,
header =0,
sample_size=-1,
all_varchar=1,
columns={
'C1': 'VARCHAR',
'C2': 'VARCHAR',
'C3': 'VARCHAR',
'C4': 'VARCHAR',
'C5': 'VARCHAR',
'C6': 'VARCHAR',
'C7': 'VARCHAR',
'C8': 'VARCHAR',
'C9': 'VARCHAR',
'C10': 'VARCHAR',
'C11': 'VARCHAR',
'C12': 'VARCHAR',
'C13': 'VARCHAR',
'C14': 'VARCHAR',
'C15': 'VARCHAR',
'C16': 'VARCHAR',
'C17': 'VARCHAR',
'C18': 'VARCHAR',
'C19': 'VARCHAR',
'C20': 'VARCHAR',
'C21': 'VARCHAR',
'C22': 'VARCHAR',
'C23': 'VARCHAR',
'C24': 'VARCHAR',
'C25': 'VARCHAR',
'C26': 'VARCHAR',
'C27': 'VARCHAR',
'C28': 'VARCHAR',
'C29': 'VARCHAR',
'C30': 'VARCHAR',
'C31': 'VARCHAR',
'C32': 'VARCHAR',
'C33': 'VARCHAR',
'C34': 'VARCHAR',
'C35': 'VARCHAR',
'C36': 'VARCHAR',
'C37': 'VARCHAR',
'C38': 'VARCHAR',
'C39': 'VARCHAR',
'C40': 'VARCHAR',
'C41': 'VARCHAR',
'C42': 'VARCHAR',
'C43': 'VARCHAR',
'C44': 'VARCHAR',
'C45': 'VARCHAR',
'C46': 'VARCHAR',
'C47': 'VARCHAR',
'C48': 'VARCHAR',
'C49': 'VARCHAR',
'C50': 'VARCHAR',
'C51': 'VARCHAR',
'C52': 'VARCHAR',
'C53': 'VARCHAR',
'C54': 'VARCHAR',
'C55': 'VARCHAR',
'C56': 'VARCHAR',
'C57': 'VARCHAR',
'C58': 'VARCHAR',
'C59': 'VARCHAR',
'C60': 'VARCHAR',
'C61': 'VARCHAR',
'C62': 'VARCHAR',
'C63': 'VARCHAR',
'C64': 'VARCHAR',
'C65': 'VARCHAR',
'C66': 'VARCHAR',
'C67': 'VARCHAR',
'C68': 'VARCHAR',
'C69': 'VARCHAR',
'C70': 'VARCHAR',
'C71': 'VARCHAR',
'C72': 'VARCHAR',
'C73': 'VARCHAR',
'C74': 'VARCHAR',
'C75': 'VARCHAR',
'C76': 'VARCHAR',
'C77': 'VARCHAR',
'C78': 'VARCHAR',
'C79': 'VARCHAR',
'C80': 'VARCHAR',
'C81': 'VARCHAR',
'C82': 'VARCHAR',
'C83': 'VARCHAR',
'C84': 'VARCHAR',
'C85': 'VARCHAR',
'C86': 'VARCHAR',
'C87': 'VARCHAR',
'C88': 'VARCHAR',
'C89': 'VARCHAR',
'C90': 'VARCHAR',
'C91': 'VARCHAR',
'C92': 'VARCHAR',
'C93': 'VARCHAR',
'C94': 'VARCHAR',
'C95': 'VARCHAR',
'C96': 'VARCHAR',
'C97': 'VARCHAR',
'C98': 'VARCHAR',
'C99': 'VARCHAR',
'C100': 'VARCHAR',
'C101': 'VARCHAR',
'C102': 'VARCHAR',
'C103': 'VARCHAR',
'C104': 'VARCHAR',
'C105': 'VARCHAR',
'C106': 'VARCHAR',
'C107': 'VARCHAR',
'C108': 'VARCHAR',
'C109': 'VARCHAR',
'C110': 'VARCHAR',
'C111': 'VARCHAR',
'C112': 'VARCHAR',
'C113': 'VARCHAR',
'C114': 'VARCHAR',
'C115': 'VARCHAR',
'C116': 'VARCHAR',
'C117': 'VARCHAR',
'C118': 'VARCHAR',
'C119': 'VARCHAR',
'C120': 'VARCHAR',
'C121': 'VARCHAR',
'C122': 'VARCHAR',
'C123': 'VARCHAR',
'C124': 'VARCHAR',
'C125': 'VARCHAR',
'C126': 'VARCHAR',
'C127': 'VARCHAR',
'C128': 'VARCHAR',
'C129': 'VARCHAR',
'C130': 'VARCHAR'
 },
null_padding=true,
auto_detect=false)
```

**Comment by djouallah** [comment]
sorry, i may find the issue, it generate an error if you do filename =1, when you do filename =0 it works but there is another problem filtering does not work 
<img width="893" alt="image" src="https://github.com/duckdb/duckdb/assets/12554469/c0fda82c-1285-4aff-9869-c7bd84dff31c">

**Comment by pdet** [comment]
@djouallah Thanks for trying it out with the pre-release version ;-), if you could have another go at it, I would appreciate it.

**Comment by djouallah** [comment]
good news it works, bad new if I don't use show it does crash Python 
```
raw =duckdb.sql(f"""from read_csv("""+'"'+Source+"""",
Skip=1,header =0,all_varchar=1,sample_size=-1,
columns={
'I': 'VARCHAR','UNIT': 'VARCHAR','XX': 'VARCHAR','VERSION': 'VARCHAR','SETTLEMENTDATE': 'VARCHAR','RUNNO': 'VARCHAR',
'DUID': 'VARCHAR','INTERVENTION': 'VARCHAR','DISPATCHMODE': 'VARCHAR','AGCSTATUS': 'VARCHAR','INITIALMW': 'VARCHAR',
'TOTALCLEARED': 'VARCHAR','RAMPDOWNRATE': 'VARCHAR','RAMPUPRATE': 'VARCHAR','LOWER5MIN': 'VARCHAR',
'LOWER60SEC': 'VARCHAR','LOWER6SEC': 'VARCHAR','RAISE5MIN': 'VARCHAR','RAISE60SEC': 'VARCHAR',
'RAISE6SEC': 'VARCHAR','MARGINAL5MINVALUE': 'VARCHAR','MARGINAL60SECVALUE': 'VARCHAR',
'MARGINAL6SECVALUE': 'VARCHAR','MARGINALVALUE': 'VARCHAR','VIOLATION5MINDEGREE': 'VARCHAR',
'VIOLATION60SECDEGREE': 'VARCHAR','VIOLATION6SECDEGREE': 'VARCHAR','VIOLATIONDEGREE': 'VARCHAR',
'LOWERREG': 'VARCHAR','RAISEREG': 'VARCHAR','AVAILABILITY': 'VARCHAR','RAISE6SECFLAGS': 'VARCHAR',
'RAISE60SECFLAGS': 'VARCHAR','RAISE5MINFLAGS': 'VARCHAR','RAISEREGFLAGS': 'VARCHAR',
'LOWER6SECFLAGS': 'VARCHAR','LOWER60SECFLAGS': 'VARCHAR','LOWER5MINFLAGS': 'VARCHAR',
'LOWERREGFLAGS': 'VARCHAR','RAISEREGAVAILABILITY': 'VARCHAR','RAISEREGENABLEMENTMAX': 'VARCHAR',
'RAISEREGENABLEMENTMIN': 'VARCHAR','LOWERREGAVAILABILITY': 'VARCHAR','LOWERREGENABLEMENTMAX': 'VARCHAR',
'LOWERREGENABLEMENTMIN': 'VARCHAR','RAISE6SECACTUALAVAILABILITY': 'VARCHAR',
'RAISE60SECACTUALAVAILABILITY': 'VARCHAR','RAISE5MINACTUALAVAILABILITY': 'VARCHAR',
'RAISEREGACTUALAVAILABILITY': 'VARCHAR','LOWER6SECACTUALAVAILABILITY': 'VARCHAR',
'LOWER60SECACTUALAVAILABILITY': 'VARCHAR','LOWER5MINACTUALAVAILABILITY': 'VARCHAR',
'LOWERREGACTUALAVAILABILITY': 'VARCHAR'
 },
filename =1,null_padding = true,ignore_errors=1,auto_detect=false)
where I='D' and UNIT ='DUNIT' AND VERSION = 3        """)
raw.show()  
columns = list(set(raw.columns) - {'SETTLEMENTDATE','DUID','I','filename','UNIT'})
exprs = [
	duckdb.ColumnExpression(x).cast(duckdb.typing.DOUBLE).alias(x)
	for x in columns
]
rel2 = raw.select('SETTLEMENTDATE','DUID','I','XX','filename','UNIT',*exprs)
scada=duckdb.sql(""" select *exclude(SETTLEMENTDATE,I,XX,filename),cast (SETTLEMENTDATE as timestamp) as SETTLEMENTDATE,
split(filename,'\\')[7] as file,isoyear (cast (SETTLEMENTDATE as timestamp)) as YEAR  from rel2               
                  """)
```

**Comment by djouallah** [comment]
@pdet sorry, now it works but crash 
<img width="874" alt="image" src="https://github.com/duckdb/duckdb/assets/12554469/85de38dc-4fb0-4ea5-9e8b-65c8e0bf1e57">

**Comment by pdet** [comment]
@djouallah Thanks for giving it a try. This is an interesting case for sure.

To diminish our back-and-forth communication, could you provide me with your whole workload?

**Comment by djouallah** [comment]
```
Source      = 'C:/Users/mdjouallah/Desktop/R2/Daily_Reports2/PUBLIC_DAILY_201804130000_20180414040502.CSV'
import duckdb
raw =duckdb.sql(f"""from read_csv("""+'"'+Source+"""",
Skip=1,header =0,all_varchar=1,sample_size=-1,
columns={
'I': 'VARCHAR','UNIT': 'VARCHAR','XX': 'VARCHAR','VERSION': 'VARCHAR','SETTLEMENTDATE': 'VARCHAR','RUNNO': 'VARCHAR',
'DUID': 'VARCHAR','INTERVENTION': 'VARCHAR','DISPATCHMODE': 'VARCHAR','AGCSTATUS': 'VARCHAR','INITIALMW': 'VARCHAR',
'TOTALCLEARED': 'VARCHAR','RAMPDOWNRATE': 'VARCHAR','RAMPUPRATE': 'VARCHAR','LOWER5MIN': 'VARCHAR',
'LOWER60SEC': 'VARCHAR','LOWER6SEC': 'VARCHAR','RAISE5MIN': 'VARCHAR','RAISE60SEC': 'VARCHAR',
'RAISE6SEC': 'VARCHAR','MARGINAL5MINVALUE': 'VARCHAR','MARGINAL60SECVALUE': 'VARCHAR',
'MARGINAL6SECVALUE': 'VARCHAR','MARGINALVALUE': 'VARCHAR','VIOLATION5MINDEGREE': 'VARCHAR',
'VIOLATION60SECDEGREE': 'VARCHAR','VIOLATION6SECDEGREE': 'VARCHAR','VIOLATIONDEGREE': 'VARCHAR',
'LOWERREG': 'VARCHAR','RAISEREG': 'VARCHAR','AVAILABILITY': 'VARCHAR','RAISE6SECFLAGS': 'VARCHAR',
'RAISE60SECFLAGS': 'VARCHAR','RAISE5MINFLAGS': 'VARCHAR','RAISEREGFLAGS': 'VARCHAR',
'LOWER6SECFLAGS': 'VARCHAR','LOWER60SECFLAGS': 'VARCHAR','LOWER5MINFLAGS': 'VARCHAR',
'LOWERREGFLAGS': 'VARCHAR','RAISEREGAVAILABILITY': 'VARCHAR','RAISEREGENABLEMENTMAX': 'VARCHAR',
'RAISEREGENABLEMENTMIN': 'VARCHAR','LOWERREGAVAILABILITY': 'VARCHAR','LOWERREGENABLEMENTMAX': 'VARCHAR',
'LOWERREGENABLEMENTMIN': 'VARCHAR','RAISE6SECACTUALAVAILABILITY': 'VARCHAR',
'RAISE60SECACTUALAVAILABILITY': 'VARCHAR','RAISE5MINACTUALAVAILABILITY': 'VARCHAR',
'RAISEREGACTUALAVAILABILITY': 'VARCHAR','LOWER6SECACTUALAVAILABILITY': 'VARCHAR',
'LOWER60SECACTUALAVAILABILITY': 'VARCHAR','LOWER5MINACTUALAVAILABILITY': 'VARCHAR',
'LOWERREGACTUALAVAILABILITY': 'VARCHAR'
 },
filename =1,null_padding = true,ignore_errors=1,auto_detect=false)
where I='D' and UNIT ='DUNIT' AND VERSION = 3        """)

columns = list(set(raw.columns) - {'SETTLEMENTDATE','DUID','I','filename','UNIT'})
exprs = [
	duckdb.ColumnExpression(x).cast(duckdb.typing.DOUBLE).alias(x)
	for x in columns
]
rel2 = raw.select('SETTLEMENTDATE','DUID','I','XX','filename','UNIT',*exprs)
scada=duckdb.sql(""" select *exclude(SETTLEMENTDATE,I,XX,filename),cast (SETTLEMENTDATE as timestamp) as SETTLEMENTDATE,
split(filename,'\\')[7] as file,isoyear (cast (SETTLEMENTDATE as timestamp)) as YEAR  from rel2               
                  """)
```

`duckdb.sql(f"""  SELECT RAISEREG  FROM scada limit 4 """)`

**Comment by djouallah** [comment]
@pedroerp thanks, it works now

**Comment by pedroerp** [comment]
> @pedroerp thanks, it works now

different Pedro, I suppose :)

**Comment by djouallah** [comment]
@pdet ok, now it works fine in windows but not Linux, I build a reproducible example in colab, if you don't upgrade duckdb it works fine, actually great considering it is only 2 cores, if you upgrade it will crash
<img width="369" alt="image" src="https://github.com/duckdb/duckdb/assets/12554469/460fa8d9-154b-422f-a9e5-3d6a84855654">


https://colab.research.google.com/drive/13Y-Px1IZn3tLI1QWemBdeTNmT79BhPhP#scrollTo=OjmPm7hXuAZh

**Comment by djouallah** [comment]
@pdet using latest nightly with windows as Linux is broken, the error is fixed but get new errors with the parquet produced

`InvalidInputException: Invalid Input Error: No magic bytes found at end of file 'C:\Users\mim\Desktop\R2\export\scada\file_4312b18d-6d7c-41a9-b14f-fd026e169708.parquet'`

**Comment by pdet** [comment]
> @pdet using latest nightly with windows as Linux is broken, the error is fixed but get new errors with the parquet produced
> 
> `InvalidInputException: Invalid Input Error: No magic bytes found at end of file 'C:\Users\mim\Desktop\R2\export\scada\file_4312b18d-6d7c-41a9-b14f-fd026e169708.parquet'`

I guess that's when you read parquet files generated by the copy to? If so, it's potentially an issue with either the parquet writer or reader, I'll have a look in the coming days :-)

Thanks again for all the testing here Mimoune, highly appreciated!

**Comment by djouallah** [comment]
@pdet actually it works fine, the error was from a previous write, thanks for fixing the issue

**Comment by djouallah** [comment]
@pdet sorry to be a pain, it is very hard to reproduce, using the same code but processing a lot of files, I get occasionally this error,  using 0.10.2
`\InternalException: INTERNAL Error: CSV Buffer is not available to reconstruct CSV Line, please open an issue with your query and dataset.`

**Comment by djouallah** [comment]
@pdet Thanks, it is back to normal, the latest night release fix it
