### ISSUE TITLE
SIGSEGV while running unit test `test/sql/types/nested/list/list_aggregate_dict.test` sometimes

### ISSUE THREAD

**Issue by a-n-n-a-l-e-e** [duckdb/duckdb#10722]
### What happens?

issue happens sporadically.  [log](https://logs.ofborg.org/?key=nixos/nixpkgs.288913&attempt_id=e8c13877-5f11-4424-ab83-09d5410fad0a)

```console
[1001/2848] (35%): test/sql/types/nested/list/list_aggregate_dict.test          
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
unittest is a Catch v2.13.7 host application.
Run with -? for options
-------------------------------------------------------------------------------
test/sql/types/nested/list/list_aggregate_dict.test
-------------------------------------------------------------------------------
/tmp/nix-build-duckdb-0.10.0.drv-2/source/test/sqlite/test_sqllogictest.cpp:201
...............................................................................
/tmp/nix-build-duckdb-0.10.0.drv-2/source/test/sqlite/test_sqllogictest.cpp:201: FAILED:
  {Unknown expression after the reported line}
due to a fatal error condition:
  SIGSEGV - Segmentation violation signal
===============================================================================
test cases:   1002 |   1001 passed | 1 failed
assertions: 116969 | 116968 passed | 1 failed
```

### To Reproduce

note -- this is a CI build machine and i do not have direct access to any aarch64-darwin machines.

issue happens sporadically 
unit tests run on aarch64-darwin with cmake flags:
```
-GNinja -DCMAKE_FIND_USE_SYSTEM_PACKAGE_REGISTRY=OFF -DCMAKE_FIND_USE_PACKAGE_REGISTRY=OFF -DCMAKE_EXPORT_NO_PACKAGE_REGISTRY=ON -DCMAKE_BUILD_TYPE=Release -DBUILD_TESTING=OFF -DCMAKE_INSTALL_LOCALEDIR=/nix/store/7x8dk39k094nag1hfsj3m9a530dcirnb-duckdb-0.10.0/share/locale -DCMAKE_INSTALL_LIBEXECDIR=/nix/store/7x8dk39k094nag1hfsj3m9a530dcirnb-duckdb-0.10.0/libexec -DCMAKE_INSTALL_LIBDIR=/nix/store/7x8dk39k094nag1hfsj3m9a530dcirnb-duckdb-0.10.0/lib -DCMAKE_INSTALL_DOCDIR=/nix/store/7x8dk39k094nag1hfsj3m9a530dcirnb-duckdb-0.10.0/share/doc/DuckDB -DCMAKE_INSTALL_INFODIR=/nix/store/7x8dk39k094nag1hfsj3m9a530dcirnb-duckdb-0.10.0/share/info -DCMAKE_INSTALL_MANDIR=/nix/store/7x8dk39k094nag1hfsj3m9a530dcirnb-duckdb-0.10.0/share/man -DCMAKE_INSTALL_OLDINCLUDEDIR=/nix/store/7x8dk39k094nag1hfsj3m9a530dcirnb-duckdb-0.10.0/include -DCMAKE_INSTALL_INCLUDEDIR=/nix/store/7x8dk39k094nag1hfsj3m9a530dcirnb-duckdb-0.10.0/include -DCMAKE_INSTALL_SBINDIR=/nix/store/7x8dk39k094nag1hfsj3m9a530dcirnb-duckdb-0.10.0/sbin -DCMAKE_INSTALL_BINDIR=/nix/store/7x8dk39k094nag1hfsj3m9a530dcirnb-duckdb-0.10.0/bin -DCMAKE_INSTALL_NAME_DIR=/nix/store/7x8dk39k094nag1hfsj3m9a530dcirnb-duckdb-0.10.0/lib -DCMAKE_POLICY_DEFAULT_CMP0025=NEW -DCMAKE_OSX_SYSROOT= -DCMAKE_FIND_FRAMEWORK=LAST -DCMAKE_STRIP=/nix/store/k687y4hiraslz65qz8pli1wb5wmcabvn-clang-wrapper-16.0.6/bin/strip -DCMAKE_RANLIB=/nix/store/k687y4hiraslz65qz8pli1wb5wmcabvn-clang-wrapper-16.0.6/bin/ranlib -DCMAKE_AR=/nix/store/k687y4hiraslz65qz8pli1wb5wmcabvn-clang-wrapper-16.0.6/bin/ar -DCMAKE_C_COMPILER=clang -DCMAKE_CXX_COMPILER=clang++ -DCMAKE_INSTALL_PREFIX=/nix/store/7x8dk39k094nag1hfsj3m9a530dcirnb-duckdb-0.10.0 -DDUCKDB_EXTENSION_CONFIGS=/nix/store/xvfq059436bs48xb6dxwn8l0vqjk8bl3-source/.github/config/in_tree_extensions.cmake -DBUILD_ODBC_DRIVER=OFF -DJDBC_DRIVER=OFF -DBUILD_UNITTESTS=ON
```

```console
./test/unittest exclude:'[s3]' exclude:'Test closing database during long running query' exclude:'Test using a remote optimizer pass in case thats important to someone' exclude:'test/common/test_cast_hugeint.test' exclude:'test/sql/copy/csv/test_csv_remote.test' exclude:'test/sql/copy/parquet/test_parquet_remote.test' exclude:'test/sql/copy/parquet/test_parquet_remote_foreign_files.test' exclude:'test/sql/storage/compression/chimp/chimp_read.test' exclude:'test/sql/storage/compression/chimp/chimp_read_float.test' exclude:'test/sql/storage/compression/patas/patas_compression_ratio.test_coverage' exclude:'test/sql/storage/compression/patas/patas_read.test' exclude:'test/sql/json/read_json_objects.test' exclude:'test/sql/json/read_json.test' exclude:'test/sql/json/table/read_json_objects.test' exclude:'test/sql/json/table/read_json.test' exclude:'test/sql/copy/parquet/parquet_5968.test' exclude:'test/fuzzer/pedro/buffer_manager_out_of_memory.test' exclude:'test/sql/storage/compression/bitpacking/bitpacking_size_calculation.test' exclude:'test/sql/copy/parquet/delta_byte_array_length_mismatch.test' exclude:'test/sql/function/timestamp/test_icu_strptime.test' exclude:'test/sql/timezone/test_icu_timezone.test' exclude:'test/sql/copy/parquet/snowflake_lineitem.test' exclude:'test/sql/copy/parquet/test_parquet_force_download.test' exclude:'test/sql/copy/parquet/delta_byte_array_multiple_pages.test' exclude:'test/sql/copy/csv/test_csv_httpfs_prepared.test' exclude:'test/sql/copy/csv/test_csv_httpfs.test' exclude:'test/sql/settings/test_disabled_file_system_httpfs.test' exclude:'test/sql/copy/csv/parallel/test_parallel_csv.test' exclude:'test/sql/copy/csv/parallel/csv_parallel_httpfs.test' exclude:'test/common/test_cast_struct.test' exclude:'test/sql/copy/parquet/parquet_glob.test' exclude:'[!hide]' exclude:'test/sql/copy/csv/auto/test_csv_auto.test' exclude:'test/sql/table_function/read_text_and_blob.test' exclude:'test/sql/secrets/create_secret_non_writable_persistent_dir.test' exclude:'test/sql/aggregate/aggregates/test_kurtosis.test' exclude:'test/sql/aggregate/aggregates/test_skewness.test' exclude:'test/sql/function/list/aggregates/skewness.test'
```

### OS:

darwin aarch64 (nixpkgs)

### DuckDB Version:

0.10.0

### DuckDB Client:

./test/unittest

### Full Name:

annalee

### Affiliation:

none (building pkg for nixpkgs / NixOS)

### Have you tried this on the latest [nightly build](https://duckdb.org/docs/installation/?version=main)?

I have not tested with any build

### Have you tried the steps to reproduce? Do they include all relevant data and configuration? Does the issue you report still appear there?

- [X] Yes, I have

**Comment by a-n-n-a-l-e-e** [comment]
was able to reproduce while running unit tests in a loop on an x64 darwin machine and generated a core file, backtrace pasted below.

```console
[1001/2851] (35%): test/sql/types/nested/list/list_aggregate_dict.test
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
unittest is a Catch v2.13.7 host application.
Run with -? for options

-------------------------------------------------------------------------------
test/sql/types/nested/list/list_aggregate_dict.test
-------------------------------------------------------------------------------
/Users/anna/tmp/duckdb/source/test/sqlite/test_sqllogictest.cpp:201
...............................................................................

/Users/anna/tmp/duckdb/source/test/sqlite/test_sqllogictest.cpp:201: FAILED:
  {Unknown expression after the reported line}
due to a fatal error condition:
  SIGSEGV - Segmentation violation signal

===============================================================================
test cases:   1002 |   1001 passed | 1 failed
assertions: 116973 | 116972 passed | 1 failed

Segmentation fault: 11 (core dumped)
```

```console
(lldb) bt all
* thread #1
  * frame #0: 0x00007ff81d0a00da libsystem_kernel.dylib`__ulock_wait + 10
    frame #1: 0x00007ff81d0dcc95 libsystem_pthread.dylib`_pthread_join + 358
    frame #2: 0x000000010ee45258 libc++.1.0.dylib`std::__1::thread::join() + 24
    frame #3: 0x0000000112b4f1e3 libduckdb.dylib`duckdb::TaskScheduler::RelaunchThreadsInternal(int) + 291
    frame #4: 0x0000000112b4ef98 libduckdb.dylib`duckdb::TaskScheduler::~TaskScheduler() + 24
    frame #5: 0x0000000112ad8d33 libduckdb.dylib`duckdb::DatabaseInstance::~DatabaseInstance() + 211
    frame #6: 0x0000000112adb4b1 libduckdb.dylib`duckdb::DuckDB::~DuckDB() + 49
    frame #7: 0x000000010e831827 unittest`duckdb::SQLLogicTestRunner::~SQLLogicTestRunner() + 135
    frame #8: 0x000000010e84a7ec unittest`void testRunner<false, false>() + 1340
    frame #9: 0x000000010e86ec94 unittest`Catch::RunContext::invokeActiveTestCase() + 260
    frame #10: 0x000000010e86c93a unittest`Catch::RunContext::runCurrentTest(std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> >&, std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> >&) + 378
    frame #11: 0x000000010e86bf81 unittest`Catch::RunContext::runTest(Catch::TestCase const&) + 385
    frame #12: 0x000000010e872957 unittest`Catch::Session::runInternal() + 3879
    frame #13: 0x000000010e871962 unittest`Catch::Session::run() + 162
    frame #14: 0x000000010e88d5bd unittest`main + 4237
    frame #15: 0x000000011d32052e dyld`start + 462
  thread #2
    frame #0: 0x0000000112b566d0 libduckdb.dylib`duckdb::BufferHandle::~BufferHandle() + 32
    frame #1: 0x0000000112b90f14 libduckdb.dylib`duckdb::CompressedStringScanState::~CompressedStringScanState() + 132
    frame #2: 0x00000001123faa65 libduckdb.dylib`std::__1::vector<duckdb::ColumnScanState, std::__1::allocator<duckdb::ColumnScanState> >::~vector[abi:v160006]() + 197
    frame #3: 0x00000001123fa95a libduckdb.dylib`std::__1::unique_ptr<duckdb::ColumnScanState [], std::__1::default_delete<duckdb::ColumnScanState []> >::~unique_ptr[abi:v160006]() + 170
    frame #4: 0x00000001123fb500 libduckdb.dylib`duckdb::TableScanLocalState::~TableScanLocalState() + 144
    frame #5: 0x00000001123fb45e libduckdb.dylib`duckdb::TableScanLocalState::~TableScanLocalState() + 14
    frame #6: 0x00000001129ca59e libduckdb.dylib`duckdb::TableScanLocalSourceState::~TableScanLocalSourceState() + 46
    frame #7: 0x0000000112b50e41 libduckdb.dylib`duckdb::PipelineExecutor::~PipelineExecutor() + 321
    frame #8: 0x0000000112b4a22f libduckdb.dylib`duckdb::PipelineTask::ExecuteTask(duckdb::TaskExecutionMode) + 431
    frame #9: 0x0000000112b43a25 libduckdb.dylib`duckdb::ExecutorTask::Execute(duckdb::TaskExecutionMode) + 37
    frame #10: 0x0000000112b4f817 libduckdb.dylib`duckdb::TaskScheduler::ExecuteForever(std::__1::atomic<bool>*) + 375
    frame #11: 0x0000000112b561d2 libduckdb.dylib`void* std::__1::__thread_proxy[abi:v160006]<std::__1::tuple<std::__1::unique_ptr<std::__1::__thread_struct, std::__1::default_delete<std::__1::__thread_struct> >, void (*)(duckdb::TaskScheduler*, std::__1::atomic<bool>*), duckdb::TaskScheduler*, std::__1::atomic<bool>*> >(void*) + 66
    frame #12: 0x00007ff81d0db4e1 libsystem_pthread.dylib`_pthread_start + 125
    frame #13: 0x00007ff81d0d6f6b libsystem_pthread.dylib`thread_start + 15
```

**Comment by a-n-n-a-l-e-e** [comment]
another SIGSEGV on x64 linux. this time compiled using llvm16 toolchain (like on darwin) rather than the default gcc-13. SIGSEGV on iteration 434. machine was moderately loaded around time of SIGSEGV

```console
./build/test/unittest -a exclude:'[s3]' exclude:'Test closing database during long running query' exclude:'Test using a remote optimizer pass in case thats important to someone' exclude:'test/common/test_cast_hugeint.test' exclude:'test/sql/copy/csv/test_csv_remote.test' exclude:'test/sql/copy/parquet/test_parquet_remote.test' exclude:'test/sql/copy/parquet/test_parquet_remote_foreign_files.test' exclude:'test/sql/storage/compression/chimp/chimp_read.test' exclude:'test/sql/storage/compression/chimp/chimp_read_float.test' exclude:'test/sql/storage/compression/patas/patas_compression_ratio.test_coverage' exclude:'test/sql/storage/compression/patas/patas_read.test' exclude:'test/sql/json/read_json_objects.test' exclude:'test/sql/json/read_json.test' exclude:'test/sql/json/table/read_json_objects.test' exclude:'test/sql/json/table/read_json.test' exclude:'test/sql/copy/parquet/parquet_5968.test' exclude:'test/fuzzer/pedro/buffer_manager_out_of_memory.test' exclude:'test/sql/storage/compression/bitpacking/bitpacking_size_calculation.test' exclude:'test/sql/copy/parquet/delta_byte_array_length_mismatch.test' exclude:'test/sql/function/timestamp/test_icu_strptime.test' exclude:'test/sql/timezone/test_icu_timezone.test' exclude:'test/sql/copy/parquet/snowflake_lineitem.test' exclude:'test/sql/copy/parquet/test_parquet_force_download.test' exclude:'test/sql/copy/parquet/delta_byte_array_multiple_pages.test' exclude:'test/sql/copy/csv/test_csv_httpfs_prepared.test' exclude:'test/sql/copy/csv/test_csv_httpfs.test' exclude:'test/sql/settings/test_disabled_file_system_httpfs.test' exclude:'test/sql/copy/csv/parallel/test_parallel_csv.test' exclude:'test/sql/copy/csv/parallel/csv_parallel_httpfs.test' exclude:'test/common/test_cast_struct.test' exclude:'test/sql/copy/parquet/parquet_glob.test' exclude:'[!hide]' exclude:'test/sql/copy/csv/auto/test_csv_auto.test' exclude:'test/sql/table_function/read_text_and_blob.test' exclude:'test/sql/secrets/create_secret_non_writable_persistent_dir.test'
Filters: exclude:[s3] exclude:Test closing database during long running query exclude:Test using a remote optimizer pass in case thats important to someone exclude:test/common/test_cast_hugeint.test exclude:test/sql/copy/csv/test_csv_remote.test exclude:test/sql/copy/parquet/test_parquet_remote.test exclude:test/sql/copy/parquet/test_parquet_remote_foreign_files.test exclude:test/sql/storage/compression/chimp/chimp_read.test exclude:test/sql/storage/compression/chimp/chimp_read_float.test exclude:test/sql/storage/compression/patas/patas_compression_ratio.test_coverage exclude:test/sql/storage/compression/patas/patas_read.test exclude:test/sql/json/read_json_objects.test exclude:test/sql/json/read_json.test exclude:test/sql/json/table/read_json_objects.test exclude:test/sql/json/table/read_json.test exclude:test/sql/copy/parquet/parquet_5968.test exclude:test/fuzzer/pedro/buffer_manager_out_of_memory.test exclude:test/sql/storage/compression/bitpacking/bitpacking_size_calculation.test exclude:test/sql/copy/parquet/delta_byte_array_length_mismatch.test exclude:test/sql/function/timestamp/test_icu_strptime.test exclude:test/sql/timezone/test_icu_timezone.test exclude:test/sql/copy/parquet/snowflake_lineitem.test exclude:test/sql/copy/parquet/test_parquet_force_download.test exclude:test/sql/copy/parquet/delta_byte_array_multiple_pages.test exclude:test/sql/copy/csv/test_csv_httpfs_prepared.test exclude:test/sql/copy/csv/test_csv_httpfs.test exclude:test/sql/settings/test_disabled_file_system_httpfs.test exclude:test/sql/copy/csv/parallel/test_parallel_csv.test exclude:test/sql/copy/csv/parallel/csv_parallel_httpfs.test exclude:test/common/test_cast_struct.test exclude:test/sql/copy/parquet/parquet_glob.test exclude:[!hide] exclude:test/sql/copy/csv/auto/test_csv_auto.test exclude:test/sql/table_function/read_text_and_blob.test exclude:test/sql/secrets/create_secret_non_writable_persistent_dir.test
[164/2851] (5%): Issue #6931 - test windows unicode path
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
unittest is a Catch v2.13.7 host application.
Run with -? for options

-------------------------------------------------------------------------------
Issue #6931 - test windows unicode path
-------------------------------------------------------------------------------
/home/anna/tmp/duckdbclang/source/test/api/test_windows_unicode_path.cpp:34
...............................................................................

/home/anna/tmp/duckdbclang/source/test/api/test_windows_unicode_path.cpp:34: FAILED:
  {Unknown expression after the reported line}
due to a fatal error condition:
  SIGSEGV - Segmentation violation signal

===============================================================================
test cases:   165 |   164 passed | 1 failed
assertions: 69427 | 69426 passed | 1 failed

```

```console
(gdb) bt
#0  0x00007f7dfcdb204d in duckdb::BufferHandle::~BufferHandle() () from /home/anna/tmp/duckdbclang/source/build/src/libduckdb.so
#1  0x00007f7dfcdf9cdb in duckdb::BitpackingScanState<long, long>::~BitpackingScanState() () from /home/anna/tmp/duckdbclang/source/build/src/libduckdb.so
#2  0x00007f7dfc61e340 in std::__1::default_delete<duckdb::ColumnScanState []>::_EnableIfConvertible<duckdb::ColumnScanState>::type std::__1::default_delete<duckdb::ColumnScanState []>::operator()[abi:v160006]<duckdb::ColumnScanState>(duckdb::ColumnScanState*) const ()
   from /home/anna/tmp/duckdbclang/source/build/src/libduckdb.so
#3  0x00007f7dfc61ec9f in duckdb::TableScanLocalState::~TableScanLocalState() () from /home/anna/tmp/duckdbclang/source/build/src/libduckdb.so
#4  0x00007f7dfc61ecb9 in duckdb::TableScanLocalState::~TableScanLocalState() () from /home/anna/tmp/duckdbclang/source/build/src/libduckdb.so
#5  0x00007f7dfcc0eed9 in duckdb::TableScanLocalSourceState::~TableScanLocalSourceState() () from /home/anna/tmp/duckdbclang/source/build/src/libduckdb.so
#6  0x00007f7dfcdaa991 in duckdb::PipelineExecutor::~PipelineExecutor() () from /home/anna/tmp/duckdbclang/source/build/src/libduckdb.so
#7  0x00007f7dfcda2024 in duckdb::PipelineTask::ExecuteTask(duckdb::TaskExecutionMode) () from /home/anna/tmp/duckdbclang/source/build/src/libduckdb.so
#8  0x00007f7dfcd9c9e4 in duckdb::ExecutorTask::Execute(duckdb::TaskExecutionMode) () from /home/anna/tmp/duckdbclang/source/build/src/libduckdb.so
#9  0x00007f7dfcda6cc8 in duckdb::TaskScheduler::ExecuteForever(std::__1::atomic<bool>*) () from /home/anna/tmp/duckdbclang/source/build/src/libduckdb.so
#10 0x00007f7dfcdb1bce in void* std::__1::__thread_proxy[abi:v160006]<std::__1::tuple<std::__1::unique_ptr<std::__1::__thread_struct, std::__1::default_delete<std::__1::__thread_struct> >, void (*)(duckdb::TaskScheduler*, std::__1::atomic<bool>*), duckdb::TaskScheduler*, std::__1::atomic<bool>*> >(void*) () from /home/anna/tmp/duckdbclang/source/build/src/libduckdb.so
#11 0x00007f7dfa7c0383 in start_thread () from /nix/store/cyrrf49i2hm1w7vn2j945ic3rrzgxbqs-glibc-2.38-44/lib/libc.so.6
#12 0x00007f7dfa84300c in clone3 () from /nix/store/cyrrf49i2hm1w7vn2j945ic3rrzgxbqs-glibc-2.38-44/lib/libc.so.6
```

**Comment by fanvanzh** [comment]
I have also encountered this issue, this is the stack trace.
It crash at BufferHandle::Destroy, where `handle._M_ptr_` is 0x00.
Is `handle` is freed in another thread?

- thread 1

```
#3  0x00007fd59c0e4a18 in duckdb::BufferHandle::Destroy (this=0x7fd51c0139d8) at src/storage/buffer/buffer_handle.cpp:37
#4  0x00007fd59c0e4994 in duckdb::BufferHandle::~BufferHandle (this=0x7fd51c0139d8, __in_chrg=<optimized out>) at src/storage/buffer/buffer_handle.cpp:26
#5  0x00007fd59c1277c8 in duckdb::FixedSizeScanState::~FixedSizeScanState (this=0x7fd51c0139d0, __in_chrg=<optimized out>)
    at src/storage/compression/fixed_size_uncompressed.cpp:125
#6  0x00007fd59c1277f0 in duckdb::FixedSizeScanState::~FixedSizeScanState (this=0x7fd51c0139d0, __in_chrg=<optimized out>)
    at src/storage/compression/fixed_size_uncompressed.cpp:125
#7  0x00007fd59b724f92 in std::default_delete<duckdb::SegmentScanState>::operator() (this=0x7fd51c026648, __ptr=0x7fd51c0139d0) at /usr/include/c++/9/bits/unique_ptr.h:81
#8  0x00007fd59b71f2d8 in std::unique_ptr<duckdb::SegmentScanState, std::default_delete<duckdb::SegmentScanState> >::~unique_ptr (this=0x7fd51c026648, __in_chrg=<optimized out>)
    at /usr/include/c++/9/bits/unique_ptr.h:292
#9  0x00007fd59b717ada in duckdb::unique_ptr<duckdb::SegmentScanState, std::default_delete<duckdb::SegmentScanState>, true>::~unique_ptr (this=0x7fd51c026648, __in_chrg=<optimized out>)
    at src/include/duckdb/common/unique_ptr.hpp:13
#10 0x00007fd59b717b52 in duckdb::ColumnScanState::~ColumnScanState (this=0x7fd51c026628, __in_chrg=<optimized out>)
    at src/include/duckdb/storage/table/scan_state.hpp:70
#11 0x00007fd59b717ba4 in std::default_delete<duckdb::ColumnScanState []>::operator()<duckdb::ColumnScanState> (this=0x7fd51c010820, __ptr=0x7fd51c026628) at /usr/include/c++/9/bits/unique_ptr.h:115
#12 0x00007fd59b70e52b in std::unique_ptr<duckdb::ColumnScanState [], std::default_delete<duckdb::ColumnScanState []> >::~unique_ptr (this=0x7fd51c010820, __in_chrg=<optimized out>)
    at /usr/include/c++/9/bits/unique_ptr.h:559
#13 0x00007fd59b70657a in duckdb::unique_ptr<duckdb::ColumnScanState [], std::default_delete<duckdb::ColumnScanState>, false>::~unique_ptr (this=0x7fd51c010820, __in_chrg=<optimized out>)
    at src/include/duckdb/common/unique_ptr.hpp:57
#14 0x00007fd59b70659a in duckdb::CollectionScanState::~CollectionScanState (this=0x7fd51c010808, __in_chrg=<optimized out>)
    at src/include/duckdb/storage/table/scan_state.hpp:116
#15 0x00007fd59b706ae2 in duckdb::TableScanState::~TableScanState (this=0x7fd51c010808, __in_chrg=<optimized out>)
    at src/include/duckdb/storage/table/scan_state.hpp:154
#16 0x00007fd59b717d2e in duckdb::TableScanLocalState::~TableScanLocalState (this=0x7fd51c010800, __in_chrg=<optimized out>)
    at src/function/table/table_scan.cpp:30
```

- thread 2

```
#0  0x00007fd5b0008f97 in pthread_join () from /lib64/libpthread.so.0
#1  0x00007fd5b1ae9e37 in std::thread::join() () from /lib64/libstdc++.so.6
#2  0x00007fd59c0bd969 in duckdb::TaskScheduler::RelaunchThreadsInternal (this=0x566e2e0, n=0) at src/parallel/task_scheduler.cpp:289
#3  0x00007fd59c0bcd23 in duckdb::TaskScheduler::~TaskScheduler (this=0x566e2e0, __in_chrg=<optimized out>) at src/parallel/task_scheduler.cpp:105
#4  0x00007fd59c07ce16 in std::default_delete<duckdb::TaskScheduler>::operator() (this=0x58e6da0, __ptr=0x566e2e0) at /usr/include/c++/9/bits/unique_ptr.h:81
#5  0x00007fd59c062696 in std::unique_ptr<duckdb::TaskScheduler, std::default_delete<duckdb::TaskScheduler> >::~unique_ptr (this=0x58e6da0, __in_chrg=<optimized out>) at /usr/include/c++/9/bits/unique_ptr.h:292
#6  0x00007fd59c053c52 in duckdb::unique_ptr<duckdb::TaskScheduler, std::default_delete<duckdb::TaskScheduler>, true>::~unique_ptr (this=0x58e6da0, __in_chrg=<optimized out>)
    at src/include/duckdb/common/unique_ptr.hpp:13
#7  0x00007fd59bfd02a8 in duckdb::DatabaseInstance::~DatabaseInstance (this=0x58e69a0, __in_chrg=<optimized out>) at src/main/database.cpp:56
#8  0x00007fd59c0b2694 in __gnu_cxx::new_allocator<duckdb::DatabaseInstance>::destroy<duckdb::DatabaseInstance> (this=0x58e69a0, __p=0x58e69a0) at /usr/include/c++/9/ext/new_allocator.h:153
#9  0x00007fd59c0b1fb1 in std::allocator_traits<std::allocator<duckdb::DatabaseInstance> >::destroy<duckdb::DatabaseInstance> (__a=..., __p=0x58e69a0) at /usr/include/c++/9/bits/alloc_traits.h:497
#10 0x00007fd59c0b0bd9 in std::_Sp_counted_ptr_inplace<duckdb::DatabaseInstance, std::allocator<duckdb::DatabaseInstance>, (__gnu_cxx::_Lock_policy)2>::_M_dispose (this=0x58e6990)
    at /usr/include/c++/9/bits/shared_ptr_base.h:557
#11 0x00007fd59aaa1290 in std::_Sp_counted_base<(__gnu_cxx::_Lock_policy)2>::_M_release (this=0x58e6990) at /usr/include/c++/9/bits/shared_ptr_base.h:155
#12 0x00007fd59aa981d9 in std::__shared_count<(__gnu_cxx::_Lock_policy)2>::~__shared_count (this=0x5435dc8, __in_chrg=<optimized out>) at /usr/include/c++/9/bits/shared_ptr_base.h:730
#13 0x00007fd59c051618 in std::__shared_ptr<duckdb::DatabaseInstance, (__gnu_cxx::_Lock_policy)2>::~__shared_ptr (this=0x5435dc0, __in_chrg=<optimized out>) at /usr/include/c++/9/bits/shared_ptr_base.h:1169
#14 0x00007fd59c051634 in std::shared_ptr<duckdb::DatabaseInstance>::~shared_ptr (this=0x5435dc0, __in_chrg=<optimized out>) at /usr/include/c++/9/bits/shared_ptr.h:103
#15 0x00007fd59bfd14c2 in duckdb::DuckDB::~DuckDB (this=0x5435dc0, __in_chrg=<optimized out>) at src/main/database.cpp:264
#16 0x00007fd59bf28778 in std::default_delete<duckdb::DuckDB>::operator() (this=0x5467f30, __ptr=0x5435dc0) at /usr/include/c++/9/bits/unique_ptr.h:81
#17 0x00007fd59bf1d168 in std::unique_ptr<duckdb::DuckDB, std::default_delete<duckdb::DuckDB> >::~unique_ptr (this=0x5467f30, __in_chrg=<optimized out>) at /usr/include/c++/9/bits/unique_ptr.h:292
#18 0x00007fd59bf1ab56 in duckdb::unique_ptr<duckdb::DuckDB, std::default_delete<duckdb::DuckDB>, true>::~unique_ptr (this=0x5467f30, __in_chrg=<optimized out>)
    at src/include/duckdb/common/unique_ptr.hpp:13
#19 0x00007fd59bf1abb8 in duckdb::DatabaseData::~DatabaseData (this=0x5467f30, __in_chrg=<optimized out>) at src/include/duckdb/main/capi/capi_internal.hpp:30
#20 0x00007fd59bf1159b in duckdb_close (database=0x7fd5b177d728 <duckdb_db>) at src/main/capi/duckdb-c.cpp:54
```

**Comment by carlopi** [comment]
This is likely solved by this PR: https://github.com/duckdb/duckdb/pull/11021 and follow-ups, we had seen similar crashes in internal testing that have gone since that has been merged.

Could you give this a go with nightly / building from main?

I would close this for now, but please do reopen if you are still seeing this problems.
