### ISSUE TITLE
CLI: segmentation fault while reading multiple CSV files when progress_bar is enabled

### ISSUE THREAD

**Issue by chumbert2** [duckdb/duckdb#10913]
### What happens?

The command:
```
duckdb -s "SET enable_progress_bar = true; select count(*) from 'data*.csv'"
```
sometimes triggers a segmentation fault.

### To Reproduce

Create minimal data files:
```
echo 0 > data0.csv
echo 1 > data1.csv
```

`run.sh` script to reproduce the issue: 
```bash
#!/bin/sh
set -e
rm -f core.*
ulimit -c unlimited
while true; do  duckdb -s "SET enable_progress_bar = true; select count(*) from 'data*.csv'"; done
```

```
$ sudo sh ./run.sh
┌──────────────┐
│ count_star() │
│    int64     │
├──────────────┤
│            2 │
└──────────────┘
┌──────────────┐
│ count_star() │
│    int64     │
├──────────────┤
│            2 │
└──────────────┘
./run.sh: line 5: 211064 Segmentation fault      (core dumped) duckdb -s "SET enable_progress_bar = true;select count(*) from 'data*.csv'"
```

**NOTE.** No core bump is observed when `SET enable_progress_bar = false`.

-----

```
sudo gdb duckdb core.211064
(No debugging symbols found in duckdb)
[New LWP 211064]
[New LWP 211065]
[New LWP 211068]
[New LWP 211069]
[New LWP 211070]
[New LWP 211066]
[New LWP 211067]
[New LWP 211071]
[Thread debugging using libthread_db enabled]
Using host libthread_db library "/lib64/libthread_db.so.1".
Core was generated by `duckdb -s SET enable_progress_bar = true;select count(*) from 'data*.csv''.
Program terminated with signal SIGSEGV, Segmentation fault.
#0  0x0000aaaac13c5674 in duckdb::CSVGlobalState::GetProgress(duckdb::ReadCSVData const&) const ()
[Current thread is 1 (Thread 0xffff92ebb020 (LWP 211064))]
(gdb) bt
#0  0x0000aaaac13c5674 in duckdb::CSVGlobalState::GetProgress(duckdb::ReadCSVData const&) const ()
#1  0x0000aaaac0d130e4 in duckdb::Pipeline::GetProgress(double&, unsigned long&) ()
#2  0x0000aaaac0d1c17c in duckdb::Executor::GetPipelinesProgress(double&, unsigned long&, unsigned long&) ()
#3  0x0000aaaac125dd74 in duckdb::ProgressBar::Update(bool) ()
#4  0x0000aaaac0cd808c in duckdb::ClientContext::ExecuteTaskInternal(duckdb::ClientContextLock&, duckdb::BaseQueryResult&, bool) ()
#5  0x0000aaaac0cd8668 in duckdb::PendingQueryResult::ExecuteInternal(duckdb::ClientContextLock&) ()
#6  0x0000aaaac0cd8754 in duckdb::PendingQueryResult::Execute() ()
#7  0x0000aaaac0cda774 in duckdb::PreparedStatement::Execute(duckdb::vector<duckdb::Value, true>&, bool) ()
#8  0x0000aaaac0898d44 in duckdb_shell_sqlite3_print_duckbox ()
#9  0x0000aaaac088656c in exec_prepared_stmt ()
#10 0x0000aaaac0888f70 in shell_exec ()
#11 0x0000aaaac0864808 in main ()
Backtrace stopped: previous frame identical to this frame (corrupt stack?)
(gdb)
```

## System info

AWS EC2 instance, 8 CPU, ARM.

```
lscpu
Architecture:           aarch64
  CPU op-mode(s):       32-bit, 64-bit
  Byte Order:           Little Endian
CPU(s):                 8
  On-line CPU(s) list:  0-7
Vendor ID:              ARM
  Model:                1
  Thread(s) per core:   1
  Core(s) per socket:   8
...
```

### OS:

Amazon Linux 2023, aarch64

### DuckDB Version:

v0.10.0 20b1486d11

### DuckDB Client:

CLI

### Full Name:

Cyril Humbert

### Affiliation:

Air Liquide

### Have you tried this on the latest [nightly build](https://duckdb.org/docs/installation/?version=main)?

I have tested with a nightly build

### Have you tried the steps to reproduce? Do they include all relevant data and configuration? Does the issue you report still appear there?

- [X] Yes, I have

**Comment by Mytherin** [comment]
Thanks for the report! Could you try this on the latest main? This has likely been fixed as part of https://github.com/duckdb/duckdb/pull/10884

**Comment by szarnyasg** [comment]
I could reproduce on stable but it no longer crashes with the latest main.

**Comment by chumbert2** [comment]
I confirm. No crash with v0.10.1-dev595 a1d67ed985 .
