### ISSUE TITLE
NullPointerException when reading JDBC ResultSet.getDate() from a Timestamp column

### ISSUE THREAD

**Issue by lukaseder** [duckdb/duckdb#11274]
### What happens?

This error occurs:

```
Exception in thread "main" java.lang.NullPointerException: Cannot load from object array because "this.varlen_data" is null
	at org.duckdb.DuckDBVector.getLazyString(DuckDBVector.java:224)
	at org.duckdb.DuckDBVector.getDate(DuckDBVector.java:280)
	at org.duckdb.DuckDBResultSet.getDate(DuckDBResultSet.java:366)
	at org.jooq.testscripts.JDBC.main(JDBC.java:42)
```

### To Reproduce

```java
try (Statement s = connection.createStatement();
    ResultSet rs = s.executeQuery("select now()")
) {
    while (rs.next()) {
        System.out.println(rs.getDate(1));
    }
}
```

Replace the call to `rs.getDate(1)` by `rs.getTimestamp(1)` as a workaround.

**Note**: I couldn't test with 0.10.1-SNAPSHOT due to https://github.com/duckdb/duckdb/issues/11244

### OS:

Microsoft Windows [Version 10.0.22631.3296]

### DuckDB Version:

0.10.0

### DuckDB Client:

JDBC

### Full Name:

Lukas Eder

### Affiliation:

Data Geekery

### Have you tried this on the latest [nightly build](https://duckdb.org/docs/installation/?version=main)?

I have tested with a release build (and could not test with a nightly build)

### Have you tried the steps to reproduce? Do they include all relevant data and configuration? Does the issue you report still appear there?

- [X] Yes, I have

**Comment by lukaseder** [comment]
Related issue:

- https://github.com/duckdb/duckdb/issues/7218

I think it would be worth reviewing all of these reasonable type conversions in the JDBC `ResultSet`.
