### ISSUE TITLE
Segmentation fault when computing a recursive query over a CSV.

### ISSUE THREAD

**Issue by mima-hlavacek** [duckdb/duckdb#11598]
### What happens?

When computing a recursive query over a CSV, duckdb segfaults. When the CSV is read first and the query computed later, everything works normally.

Sorry for the largish example, don't really know what precisely the trigger is to make the input smaller and the query simpler.

### To Reproduce

1. Download an example CSV from https://data.ct.gov/api/views/5mzw-sjtu/rows.csv
2. Run the following query and observe a segfault.

```sql
with recursive
     base as
     ( select *
       from 'Real_Estate_Sales_2001-2021_GL.csv'
       where '2003-01-01' < "date recorded" and  "date recorded" < '2010-01-01' and "sale amount" > 1000000
     )
   , chains as
     (
         select
           town
         , "date recorded" as begTS
         , "date recorded" as endTS
         , [struct_pack(date:= "date recorded", amt:="sale amount", type:="property type")] as chain
         from base
         where "property type" = 'Condo'
       union all
         select
           chains.town
         , chains.begTS
         , base."date recorded" as endTS
         , list_append(chains.chain, struct_pack(date:= "date recorded", amt:="sale amount", type:="property type")) as chain
         from base, chains
         where
               base.town = chains.town
           and
           (
                (len(chains.chain) = 1 and list_contains(['Residential', 'Single Family'], base."property type"))
             or (len(chains.chain) = 2 and base."property type" = 'Condo')
             or (len(chains.chain) = 3 and list_contains(['Residential', 'Single Family'], base."property type"))
           )
           and chains.endTS < base."date recorded"
           and base."date recorded" < (chains.endTS + interval 6 days)
     )
   select * from chains;
```

Backtrace from 0.10.1:

```
#0  0x000000000123521a in duckdb::CSVBuffer::Pin(duckdb::CSVFileHandle&, bool&) ()
#1  0x0000000001236282 in duckdb::CSVBufferManager::GetBuffer(unsigned long) ()
#2  0x000000000126b110 in duckdb::CSVGlobalState::CSVGlobalState(duckdb::ClientContext&, std::shared_ptr<duckdb::CSVBufferManager> const&, duckdb::CSVReaderOptions const&, unsigned long, duckdb::vector<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, true> const&, duckdb::vector<unsigned long, true>, duckdb::ReadCSVData const&) ()
#3  0x0000000001088400 in duckdb::ReadCSVInitGlobal(duckdb::ClientContext&, duckdb::TableFunctionInitInput&) ()
#4  0x00000000012df9f3 in duckdb::PhysicalTableScan::GetGlobalSourceState(duckdb::ClientContext&) const ()
#5  0x0000000000af228e in duckdb::Pipeline::ResetSource(bool) ()
#6  0x0000000000af8caa in duckdb::Executor::SchedulePipeline(std::shared_ptr<duckdb::MetaPipeline> const&, duckdb::ScheduleEventData&) ()
#7  0x0000000000af8f2a in duckdb::Executor::ScheduleEventsInternal(duckdb::ScheduleEventData&) ()
#8  0x0000000000af9ac4 in duckdb::Executor::ReschedulePipelines(duckdb::vector<std::shared_ptr<duckdb::MetaPipeline>, true> const&, duckdb::vector<std::shared_ptr<duckdb::Event>, true>&) ()
#9  0x00000000012ea4f7 in duckdb::PhysicalRecursiveCTE::ExecuteRecursivePipelines(duckdb::ExecutionContext&) const ()
#10 0x00000000012ea8a6 in duckdb::PhysicalRecursiveCTE::GetData(duckdb::ExecutionContext&, duckdb::DataChunk&, duckdb::OperatorSourceInput&) const ()
#11 0x0000000000af24d5 in duckdb::PipelineExecutor::FetchFromSource(duckdb::DataChunk&) ()
#12 0x0000000000afb27b in duckdb::PipelineExecutor::Execute(unsigned long) ()
#13 0x0000000000afb4dc in duckdb::PipelineTask::ExecuteTask(duckdb::TaskExecutionMode) ()
#14 0x0000000000af3e47 in duckdb::ExecutorTask::Execute(duckdb::TaskExecutionMode) ()
#15 0x0000000000af2981 in duckdb::TaskScheduler::ExecuteForever(std::atomic<bool>*) ()
#16 0x00007ffff78fe3d4 in execute_native_thread_routine () from /nix/store/ccv4xpqyldgvx3sdf9bl0h98ghj1lv18-gcc-11.3.0-lib/lib/libstdc++.so.6
#17 0x00007ffff75a4e86 in start_thread () from /nix/store/y5g49l31saa0h89ybx6vak9pnqcrgm4g-glibc-2.35-163/lib/libc.so.6
#18 0x00007ffff762bc60 in clone3 () from /nix/store/y5g49l31saa0h89ybx6vak9pnqcrgm4g-glibc-2.35-163/lib/libc.so.6
```

When the `base` clause is materialized, the segfault goes away.

```
with recursive
  base as materialized
   ( select *
...
```

### OS:

Ubuntu x64 in WSL on Windows 11

### DuckDB Version:

0.10.1, v0.10.2-dev677 652756f1a4

### DuckDB Client:

cli

### Full Name:

Míma Hlaváček

### Affiliation:

Blindspot.ai

### What is the latest build you tested with? If possible, we recommend testing with the latest nightly build.

I have tested with a source build

### Did you include all relevant data sets for reproducing the issue?

Yes

### Did you include all code required to reproduce the issue?

- [X] Yes, I have

### Did you include all relevant configuration (e.g., CPU architecture, Python version, Linux distribution) to reproduce the issue?

- [X] Yes, I have

**Comment by szarnyasg** [comment]
@mima-hlavacek, thanks, I could reproduce this on macOS too.

**Comment by Mytherin** [comment]
Should be fixed by https://github.com/duckdb/duckdb/pull/11631
