### ISSUE TITLE
jdbc connect to spark with error `Unrecognized configuration property "path"`

### ISSUE THREAD

**Issue by chaozwn** [duckdb/duckdb#11651]
### What happens?

through jdbc connect to spark.
system info:
<img width="248" alt="image" src="https://github.com/duckdb/duckdb/assets/51357674/fccbf6f9-8d9a-4fd2-ab24-5e5c795ea404">

```sql
create table default.movies  
using jdbc
options (url "jdbc:duckdb:database/duckdb.db" , driver "org.duckdb.DuckDBDriver" , dbtable "duckdb.movies")as
select movieid movie_id, title title, genres genres
from movies_view
```

log:
```
16:28:57    Runtime Error in model movies (models/sources/movies.sql)
  An error occurred while calling o40.sql.
  : java.sql.SQLException: Invalid Input Error: Unrecognized configuration property "path"
        at org.duckdb.DuckDBNative.duckdb_jdbc_startup(Native Method)
        at org.duckdb.DuckDBConnection.newConnection(DuckDBConnection.java:48)
        at org.duckdb.DuckDBDriver.connect(DuckDBDriver.java:41)
        at org.apache.spark.sql.execution.datasources.jdbc.connection.BasicConnectionProvider.getConnection(BasicConnectionProvider.scala:49)
        at org.apache.spark.sql.execution.datasources.jdbc.connection.ConnectionProviderBase.create(ConnectionProvider.scala:102)
        at org.apache.spark.sql.jdbc.JdbcDialect.$anonfun$createConnectionFactory$1(JdbcDialects.scala:123)
        at org.apache.spark.sql.jdbc.JdbcDialect.$anonfun$createConnectionFactory$1$adapted(JdbcDialects.scala:119)
        at org.apache.spark.sql.execution.datasources.jdbc.JdbcRelationProvider.createRelation(JdbcRelationProvider.scala:50)
        at org.apache.spark.sql.execution.datasources.DataSource.writeAndRead(DataSource.scala:506)
        at org.apache.spark.sql.execution.command.CreateDataSourceTableAsSelectCommand.saveDataIntoTable(createDataSourceTables.scala:228)
        at org.apache.spark.sql.execution.command.CreateDataSourceTableAsSelectCommand.run(createDataSourceTables.scala:183)
        at org.apache.spark.sql.execution.command.ExecutedCommandExec.sideEffectResult$lzycompute(commands.scala:75)
        at org.apache.spark.sql.execution.command.ExecutedCommandExec.sideEffectResult(commands.scala:73)
        at org.apache.spark.sql.execution.command.ExecutedCommandExec.executeCollect(commands.scala:84)
        at org.apache.spark.sql.execution.QueryExecution$$anonfun$eagerlyExecuteCommands$1.$anonfun$applyOrElse$1(QueryExecution.scala:98)
        at org.apache.spark.sql.execution.SQLExecution$.$anonfun$withNewExecutionId$6(SQLExecution.scala:118)
        at org.apache.spark.sql.execution.SQLExecution$.withSQLConfPropagated(SQLExecution.scala:195)
        at org.apache.spark.sql.execution.SQLExecution$.$anonfun$withNewExecutionId$1(SQLExecution.scala:103)
        at org.apache.spark.sql.SparkSession.withActive(SparkSession.scala:827)
        at org.apache.spark.sql.execution.SQLExecution$.withNewExecutionId(SQLExecution.scala:65)
        at org.apache.spark.sql.execution.QueryExecution$$anonfun$eagerlyExecuteCommands$1.applyOrElse(QueryExecution.scala:98)
        at org.apache.spark.sql.execution.QueryExecution$$anonfun$eagerlyExecuteCommands$1.applyOrElse(QueryExecution.scala:94)
        at org.apache.spark.sql.catalyst.trees.TreeNode.$anonfun$transformDownWithPruning$1(TreeNode.scala:512)
        at org.apache.spark.sql.catalyst.trees.CurrentOrigin$.withOrigin(TreeNode.scala:104)
        at org.apache.spark.sql.catalyst.trees.TreeNode.transformDownWithPruning(TreeNode.scala:512)
        at org.apache.spark.sql.catalyst.plans.logical.LogicalPlan.org$apache$spark$sql$catalyst$plans$logical$AnalysisHelper$$super$transformDownWithPruning(LogicalPlan.scala:31)
        at org.apache.spark.sql.catalyst.plans.logical.AnalysisHelper.transformDownWithPruning(AnalysisHelper.scala:267)
        at org.apache.spark.sql.catalyst.plans.logical.AnalysisHelper.transformDownWithPruning$(AnalysisHelper.scala:263)
        at org.apache.spark.sql.catalyst.plans.logical.LogicalPlan.transformDownWithPruning(LogicalPlan.scala:31)
        at org.apache.spark.sql.catalyst.plans.logical.LogicalPlan.transformDownWithPruning(LogicalPlan.scala:31)
        at org.apache.spark.sql.catalyst.trees.TreeNode.transformDown(TreeNode.scala:488)
        at org.apache.spark.sql.execution.QueryExecution.eagerlyExecuteCommands(QueryExecution.scala:94)
        at org.apache.spark.sql.execution.QueryExecution.commandExecuted$lzycompute(QueryExecution.scala:81)
        at org.apache.spark.sql.execution.QueryExecution.commandExecuted(QueryExecution.scala:79)
        at org.apache.spark.sql.Dataset.<init>(Dataset.scala:219)
        at org.apache.spark.sql.Dataset$.$anonfun$ofRows$2(Dataset.scala:99)
        at org.apache.spark.sql.SparkSession.withActive(SparkSession.scala:827)
        at org.apache.spark.sql.Dataset$.ofRows(Dataset.scala:96)
        at org.apache.spark.sql.SparkSession.$anonfun$sql$1(SparkSession.scala:640)
        at org.apache.spark.sql.SparkSession.withActive(SparkSession.scala:827)
        at org.apache.spark.sql.SparkSession.sql(SparkSession.scala:630)
        at org.apache.spark.sql.SparkSession.sql(SparkSession.scala:662)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.base/java.lang.reflect.Method.invoke(Method.java:566)
        at py4j.reflection.MethodInvoker.invoke(MethodInvoker.java:244)
        at py4j.reflection.ReflectionEngine.invoke(ReflectionEngine.java:374)
        at py4j.Gateway.invoke(Gateway.java:282)
        at py4j.commands.AbstractCommand.invokeMethod(AbstractCommand.java:132)
        at py4j.commands.CallCommand.execute(CallCommand.java:79)
        at py4j.ClientServerConnection.waitForCommands(ClientServerConnection.java:182)
        at py4j.ClientServerConnection.run(ClientServerConnection.java:106)
        at java.base/java.lang.Thread.run(Thread.java:829)
```

### To Reproduce

spark sql
```sql
create table default.movies  
using jdbc
options (url "jdbc:duckdb:database/duckdb.db" , driver "org.duckdb.DuckDBDriver" , dbtable "duckdb.movies")as
select movieid movie_id, title title, genres genres
from movies_view
```

### OS:

macos

### DuckDB Version:

0.10.1

### DuckDB Client:

jdbc

### Full Name:

Jayce Zhao

### Affiliation:

Byzer

### What is the latest build you tested with? If possible, we recommend testing with the latest nightly build.

I have not tested with any build

### Did you include all relevant data sets for reproducing the issue?

No - Other reason (please specify in the issue body)

### Did you include all code required to reproduce the issue?

- [X] Yes, I have

### Did you include all relevant configuration (e.g., CPU architecture, Python version, Linux distribution) to reproduce the issue?

- [X] Yes, I have

**Comment by chaozwn** [comment]
reproduce python code:
```python
from pyspark.sql import SparkSession

if __name__ == '__main__':
    spark = SparkSession.builder \
        .appName("Example Application") \
        .config("spark.master", "local") \
        .config("spark.jars.packages",
                "io.delta:delta-core_2.12:2.4.0,org.xerial:sqlite-jdbc:3.45.2.0,org.duckdb:duckdb_jdbc:0.9.2") \
        .getOrCreate()

    spark.sql(
        f"""
            create table default.movies  
            using jdbc
            options (url "jdbc:duckdb:database/duckdb.db" , driver "org.duckdb.DuckDBDriver" , dbtable "duckdb.main.test");
            """
    )

    spark.sql("select * from default.movies").show()

    spark.stop()
```

**Comment by Mause** [comment]
I've looked into this, and the error seems to be correct from our side - we don't support a `path` configuration parameter, and it's not clear what we'd do with it even if we did. I recommend raising this with Spark instead.

**Comment by chaozwn** [comment]
> org.duckdb.DuckDBNative.duckdb_jdbc_startup(Native Method)

From my point, when did Spark start to pass in a 'path' parameter? This error is thrown from inside `org.duckdb.DuckDBNative.duckdb_jdbc_startup(Native Method)`.

```sql
create table movies  
using jdbc
options (url "jdbc:duckdb:database/duckdb.db", driver "org.duckdb.DuckDBDriver" , query " SELECT t.* FROM main.test t");

```

**Comment by Mause** [comment]
They pass it from here: https://github.com/apache/spark/blob/e6b7950f553cff5adc02b8b5195e79cffff3c97c/sql/core/src/main/scala/org/apache/spark/sql/execution/command/createDataSourceTables.scala#L64

It's not clear why they pass that to all generic jdbc drivers

**Comment by chaozwn** [comment]
> They pass it from here: https://github.com/apache/spark/blob/e6b7950f553cff5adc02b8b5195e79cffff3c97c/sql/core/src/main/scala/org/apache/spark/sql/execution/command/createDataSourceTables.scala#L64
> 
> It's not clear why they pass that to all generic jdbc drivers

thank you, i will create a issue to spark. can we keep this issue open, although it may not be an issue with duckdb.

**Comment by chaozwn** [comment]
> I've looked into this, and the error seems to be correct from our side - we don't support a `path` configuration parameter, and it's not clear what we'd do with it even if we did. I recommend raising this with Spark instead.

Actually, there's another question: when encountering properties that are not needed, should we not throw a RuntimeException?

**Comment by chaozwn** [comment]
link: https://issues.apache.org/jira/projects/SPARK/issues/SPARK-47853?filter=reportedbyme

**Comment by Mause** [comment]
> > I've looked into this, and the error seems to be correct from our side - we don't support a `path` configuration parameter, and it's not clear what we'd do with it even if we did. I recommend raising this with Spark instead.
> 
> Actually, there's another question: when encountering properties that are not needed, should we not throw a RuntimeException?

Why would we throw a `RuntimeException`? The JDBC spec requires an `SQLException`

**Comment by chaozwn** [comment]
> > > I've looked into this, and the error seems to be correct from our side - we don't support a `path` configuration parameter, and it's not clear what we'd do with it even if we did. I recommend raising this with Spark instead.
> > 
> > 
> > Actually, there's another question: when encountering properties that are not needed, should we not throw a RuntimeException?
> 
> Why would we throw a `RuntimeException`? The JDBC spec requires an `SQLException`

 can we ignore the extra parameters and throw a warning instead of an exception?

**Comment by chaozwn** [comment]
> > > I've looked into this, and the error seems to be correct from our side - we don't support a `path` configuration parameter, and it's not clear what we'd do with it even if we did. I recommend raising this with Spark instead.
> > 
> > 
> > Actually, there's another question: when encountering properties that are not needed, should we not throw a RuntimeException?
> 
> Why would we throw a `RuntimeException`? The JDBC spec requires an `SQLException`

On this issue, I don't know if duckdb can be optimized. What I mean is pass in the path parameter, do not report an error. Because of this current setting, spark jdbc writes to duckdb are abnormal.
from my point, passing in superfluous properties arguments should not directly make the program throw a RuntimeException, which is a bit too strict.

**Comment by chaozwn** [comment]
> > > > I've looked into this, and the error seems to be correct from our side - we don't support a `path` configuration parameter, and it's not clear what we'd do with it even if we did. I recommend raising this with Spark instead.
> > > 
> > > 
> > > Actually, there's another question: when encountering properties that are not needed, should we not throw a RuntimeException?
> > 
> > 
> > Why would we throw a `RuntimeException`? The JDBC spec requires an `SQLException`
> 
> On this issue, I don't know if duckdb can be optimized. What I mean is pass in the path parameter, do not report an error. 
Because of this current setting, spark jdbc writes to duckdb are abnormal. from my point, passing in superfluous properties arguments should not directly make the program throw a RuntimeException, which is a bit too strict.
and path is an indispensable parameter of spark.
