### ISSUE TITLE
CREATE AS SELECT segmentation faults

### ISSUE THREAD

**Issue by smonkewitz** [duckdb/duckdb#11968]
### What happens?

In some circumstances, CREATE AS SELECT segmentation faults.

### To Reproduce

```
build/debug/duckdb test.duckdb
v..1-dev 5a43c89f16
Enter ".help" for usage hints.
```
```sql
create table bug(x int[]);
insert into bug select case when x <= 520 then [0, 0] else [0] end from generate_series(1, 2048) s(x);
checkpoint;
```
```
┌─────────┐
│ Success │
│ boolean │
├─────────┤
│ 0 rows  │
└─────────┘
```
```sql
create table kaboom as select x from bug;
```
```
=================================================================
==28587==ERROR: AddressSanitizer: global-buffer-overflow on address 0x00010d9e3c80 at pc 0x0001002dc874 bp 0x00016fd36e30 sp 0x00016fd36e28
READ of size 4 at 0x00010d9e3c80 thread T0
    #0 0x1002dc870 in duckdb::SelectionVector::get_index(unsigned long long) const selection_vector.hpp:95
    #1 0x10983c2b4 in void duckdb::StandardFixedSizeAppend::Append<int>(duckdb::SegmentStatistics&, unsigned char*, unsigned long long, duckdb::UnifiedVectorFormat&, unsigned long long, unsigned long long) fixed_size_uncompressed.cpp:211
    #2 0x10983b6b8 in unsigned long long duckdb::FixedSizeAppend<int, duckdb::StandardFixedSizeAppend>(duckdb::CompressionAppendState&, duckdb::ColumnSegment&, duckdb::SegmentStatistics&, duckdb::UnifiedVectorFormat&, unsigned long long, unsigned long long) fixed_size_uncompressed.cpp:243
    #3 0x109e9a0b4 in duckdb::ColumnSegment::Append(duckdb::ColumnAppendState&, duckdb::UnifiedVectorFormat&, unsigned long long, unsigned long long) column_segment.cpp:175
    #4 0x109e98f84 in duckdb::ColumnData::AppendData(duckdb::BaseStatistics&, duckdb::ColumnAppendState&, duckdb::UnifiedVectorFormat&, unsigned long long) column_data.cpp:340
    #5 0x109f61f70 in duckdb::StandardColumnData::AppendData(duckdb::BaseStatistics&, duckdb::ColumnAppendState&, duckdb::UnifiedVectorFormat&, unsigned long long) standard_column_data.cpp:103
    #6 0x109e934f8 in duckdb::ColumnData::Append(duckdb::BaseStatistics&, duckdb::ColumnAppendState&, duckdb::Vector&, unsigned long long) column_data.cpp:265
    #7 0x109edbe7c in duckdb::ListColumnData::Append(duckdb::BaseStatistics&, duckdb::ColumnAppendState&, duckdb::Vector&, unsigned long long) list_column_data.cpp:227
    #8 0x109e93eb8 in duckdb::ColumnData::Append(duckdb::ColumnAppendState&, duckdb::Vector&, unsigned long long) column_data.cpp:273
    #9 0x109f1b058 in duckdb::RowGroup::Append(duckdb::RowGroupAppendState&, duckdb::DataChunk&, unsigned long long) row_group.cpp:742
    #10 0x109f3b5e4 in duckdb::RowGroupCollection::Append(duckdb::DataChunk&, duckdb::TableAppendState&) row_group_collection.cpp:345
    #11 0x108507828 in duckdb::PhysicalBatchInsert::Sink(duckdb::ExecutionContext&, duckdb::DataChunk&, duckdb::OperatorSinkInput&) const physical_batch_insert.cpp:505
    #12 0x1094efce0 in duckdb::PipelineExecutor::Sink(duckdb::DataChunk&, duckdb::OperatorSinkInput&) pipeline_executor.cpp:485
    #13 0x1094eb090 in duckdb::PipelineExecutor::ExecutePushInternal(duckdb::DataChunk&, unsigned long long) pipeline_executor.cpp:297
    #14 0x1094d7938 in duckdb::PipelineExecutor::Execute(unsigned long long) pipeline_executor.cpp:225
    #15 0x1094d5748 in duckdb::PipelineTask::ExecuteTask(duckdb::TaskExecutionMode) pipeline.cpp:40
    #16 0x1094ab620 in duckdb::ExecutorTask::Execute(duckdb::TaskExecutionMode) executor_task.cpp:32
    #17 0x1094c89d0 in duckdb::Executor::ExecuteTask(bool) executor.cpp:517
    #18 0x10901f650 in duckdb::ClientContext::ExecuteTaskInternal(duckdb::ClientContextLock&, duckdb::BaseQueryResult&, bool) client_context.cpp:540
    #19 0x10909b0bc in duckdb::PendingQueryResult::ExecuteTaskInternal(duckdb::ClientContextLock&) pending_query_result.cpp:63
    #20 0x1090292a4 in duckdb::PendingQueryResult::ExecuteInternal(duckdb::ClientContextLock&) pending_query_result.cpp:73
    #21 0x109033314 in duckdb::PendingQueryResult::Execute() pending_query_result.cpp:86
    #22 0x109061ef4 in duckdb::PreparedStatement::Execute(duckdb::vector<duckdb::Value, true>&, bool) prepared_statement.cpp:85
    #23 0x1003067e4 in duckdb_shell_sqlite3_print_duckbox sqlite3_api_wrapper.cpp:249
    #24 0x10028676c in exec_prepared_stmt shell.c:12746
    #25 0x1001d66d8 in shell_exec shell.c:13081
    #26 0x10029620c in runOneSqlLine shell.c:19499
    #27 0x1001d9be4 in process_input shell.c:19610
    #28 0x1001908a0 in main shell.c:20432
    #29 0x19d1b60dc  (<unknown module>)

0x00010d9e3c80 is located 0 bytes after global variable 'duckdb::ConstantVector::ZERO_VECTOR' defined in '/Users/serge/Desktop/awake/smonkewitz/duckdb/build/debug/src/common/types/ub_duckdb_common_types.cpp' (0x10d9e1c80) of size 8192
SUMMARY: AddressSanitizer: global-buffer-overflow selection_vector.hpp:95 in duckdb::SelectionVector::get_index(unsigned long long) const
Shadow bytes around the buggy address:
  0x00010d9e3a00: 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00
  0x00010d9e3a80: 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00
  0x00010d9e3b00: 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00
  0x00010d9e3b80: 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00
  0x00010d9e3c00: 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00
=>0x00010d9e3c80:[f9]f9 f9 f9 f9 f9 f9 f9 f9 f9 f9 f9 f9 f9 f9 f9
  0x00010d9e3d00: f9 f9 f9 f9 f9 f9 f9 f9 f9 f9 f9 f9 f9 f9 f9 f9
  0x00010d9e3d80: f9 f9 f9 f9 f9 f9 f9 f9 f9 f9 f9 f9 f9 f9 f9 f9
  0x00010d9e3e00: f9 f9 f9 f9 f9 f9 f9 f9 f9 f9 f9 f9 f9 f9 f9 f9
  0x00010d9e3e80: f9 f9 f9 f9 f9 f9 f9 f9 f9 f9 f9 f9 f9 f9 f9 f9
  0x00010d9e3f00: f9 f9 f9 f9 f9 f9 f9 f9 f9 f9 f9 f9 f9 f9 f9 f9
Shadow byte legend (one shadow byte represents 8 application bytes):
  Addressable:           00
  Partially addressable: 01 02 03 04 05 06 07 
  Heap left redzone:       fa
  Freed heap region:       fd
  Stack left redzone:      f1
  Stack mid redzone:       f2
  Stack right redzone:     f3
  Stack after return:      f5
  Stack use after scope:   f8
  Global redzone:          f9
  Global init order:       f6
  Poisoned by user:        f7
  Container overflow:      fc
  Array cookie:            ac
  Intra object redzone:    bb
  ASan internal:           fe
  Left alloca redzone:     ca
  Right alloca redzone:    cb
==28587==ABORTING
[1]    28587 abort      build/debug/duckdb test.duckdb
```

### OS:

macOS 14.4.1

### DuckDB Version:

main, 0.10.2

### DuckDB Client:

CLI

### Full Name:

Serge Monkewitz

### Affiliation:

Arista Networks

### What is the latest build you tested with? If possible, we recommend testing with the latest nightly build.

I have tested with a source build

### Did you include all relevant data sets for reproducing the issue?

Yes

### Did you include all code required to reproduce the issue?

- [X] Yes, I have

### Did you include all relevant configuration (e.g., CPU architecture, Python version, Linux distribution) to reproduce the issue?

- [X] Yes, I have

**Comment by szarnyasg** [comment]
Thanks for the reporting – I could reproduce it – and also thanks for the PR!
