### ISSUE TITLE
fail to query from a Pandas data frame named "df"

### ISSUE THREAD

**Issue by chumbert2** [duckdb/duckdb#12228]
### What happens?

Hello.

With DuckDB 0.10.3, if `df` is as Pandas data frame, queries such as

```python
duckdb.sql("select * from df").df()
```

return the following error:

```
duckdb.duckdb.InvalidInputException: Invalid Input Error: Python Object "df" of type "builtin_function_or_method"
found on line ".../venv/lib/python3.11/site-packages/duckdb/__init__.py:457" not suitable for replacement scans.
Make sure that "df" is either a pandas.DataFrame, duckdb.DuckDBPyRelation, pyarrow Table, Dataset, RecordBatchReader,
Scanner, or NumPy ndarrays with supported format
```

### To Reproduce

Test script:
```python
#!/usr/bin/env python3
import pandas as pd
import duckdb

print("Pandas version:", pd.__version__)
print("DuckDB version:", duckdb.__version__)

data = {'col_1': [3, 2, 1, 0], 'col_2': ['a', 'b', 'c', 'd']}
df = pd.DataFrame.from_dict(data)
print(df)

df2 = duckdb.sql("select * from df").df()
print(df2)
```

Output:
````
Pandas version: 2.2.2
DuckDB version: 0.10.3
   col_1 col_2
0      3     a
1      2     b
2      1     c
3      0     d
Traceback (most recent call last):
  File "/home/user/src/notes/data-dis-aws/./aa.py", line 12, in <module>
    df2 = duckdb.sql("select * from df").df()
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/user/src/notes/data-dis-aws/venv/lib/python3.11/site-packages/duckdb/__init__.py", line 457, in sql
    return conn.sql(query, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^
duckdb.duckdb.InvalidInputException: Invalid Input Error: Python Object "df" of type "builtin_function_or_method" found on line "/home/user/src/notes/data-dis-aws/venv/lib/python3.11/site-packages/duckdb/__init__.py:457" not suitable for replacement scans.
Make sure that "df" is either a pandas.DataFrame, duckdb.DuckDBPyRelation, pyarrow Table, Dataset, RecordBatchReader, Scanner, or NumPy ndarrays with supported format
````

* It works with DuckDB 0.10.2
* It works if the data frame is not named `df`

### OS:

Debian 12, amd64

### DuckDB Version:

0.10.3 and 0.10.4-dev20

### DuckDB Client:

Python

### Full Name:

Cyril Humbert

### Affiliation:

Air Liquide

### What is the latest build you tested with? If possible, we recommend testing with the latest nightly build.

I have tested with a stable release

### Did you include all relevant data sets for reproducing the issue?

Yes

### Did you include all code required to reproduce the issue?

- [X] Yes, I have

### Did you include all relevant configuration (e.g., CPU architecture, Python version, Linux distribution) to reproduce the issue?

- [X] Yes, I have

**Comment by Tishj** [comment]
Thanks, already fixed by https://github.com/duckdb/duckdb/pull/12208

**Comment by Tishj** [comment]
The work around is to first create a connection
```py
con = duckdb.connect()
con.sql(...)
```
