### ISSUE TITLE
java.sql.SQLException: java.sql.SQLException: types argument is not supported

### ISSUE THREAD

**Issue by qiuwei** [duckdb/duckdb#1258]
I am trying out debezium to sync a mysql database to duckdb.
However, I got the folloing errors:
```
connect_1    | java.sql.SQLException: types argument is not supported
connect_1    | 	at org.duckdb.DuckDBDatabaseMetaData.getTables(DuckDBDatabaseMetaData.java:663)
connect_1    | 	at io.confluent.connect.jdbc.dialect.GenericDatabaseDialect.tableExists(GenericDatabaseDialect.java:524)
connect_1    | 	at io.confluent.connect.jdbc.util.TableDefinitions.get(TableDefinitions.java:61)
connect_1    | 	at io.confluent.connect.jdbc.sink.DbStructure.createOrAmendIfNecessary(DbStructure.java:58)
connect_1    | 	at io.confluent.connect.jdbc.sink.BufferedRecords.add(BufferedRecords.java:121)
connect_1    | 	at io.confluent.connect.jdbc.sink.JdbcDbWriter.write(JdbcDbWriter.java:66)
connect_1    | 	at io.confluent.connect.jdbc.sink.JdbcSinkTask.put(JdbcSinkTask.java:74)
connect_1    | 	at org.apache.kafka.connect.runtime.WorkerSinkTask.deliverMessages(WorkerSinkTask.java:539)
connect_1    | 	at org.apache.kafka.connect.runtime.WorkerSinkTask.poll(WorkerSinkTask.java:322)
connect_1    | 	at org.apache.kafka.connect.runtime.WorkerSinkTask.iteration(WorkerSinkTask.java:224)
connect_1    | 	at org.apache.kafka.connect.runtime.WorkerSinkTask.execute(WorkerSinkTask.java:192)
connect_1    | 	at org.apache.kafka.connect.runtime.WorkerTask.doRun(WorkerTask.java:177)
connect_1    | 	at org.apache.kafka.connect.runtime.WorkerTask.run(WorkerTask.java:227)
connect_1    | 	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515)
connect_1    | 	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
connect_1    | 	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
connect_1    | 	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
connect_1    | 	at java.base/java.lang.Thread.run(Thread.java:834)
```
I understand that DuckDB does not implement the full JDBC api.
However, I am still wondering whether it is technically feasible to achieve synchronization from MySQL to DuckDB.

**Comment by hannesmuehleisen** [comment]
Its certainly possible, we just need to support the API calls that debezium wants. Happy to review a PR!

**Comment by hannesmuehleisen** [comment]
We merged a fix for this, can you please check whether this is fixed with the JDBC driver from the master branch? The binaries are here: https://github.com/cwida/duckdb/releases/tag/master-builds
