### ISSUE TITLE
Can't create a view with prepared parameteres

### ISSUE THREAD

**Issue by dmmartins** [duckdb/duckdb#13069]
### What happens?

Creating a view with prepared parameters fails, while creating a table the same way works

### To Reproduce

```
import csv
import duckdb

with open('test.csv', 'w') as f:
    writer = csv.writer(f)
    writer.writerow(('a', 'b'))
    writer.writerow((1, 2))

with duckdb.connect() as con:
    # Works ok
    con.execute('CREATE TABLE "test1" AS SELECT * FROM read_csv(?)', ['test.csv'])
    # Fails
    con.execute('CREATE VIEW "test2" AS SELECT * FROM read_csv(?)', ['test.csv'])
```

Creating the view fails with
```
Traceback (most recent call last):
  File "/app/uploads/duckdb_parameter.py", line 9, in <module>
    with duckdb.connect() as con:
  File "/app/uploads/duckdb_parameter.py", line 13, in <module>
    con.execute('CREATE VIEW "test2" AS SELECT * FROM read_csv(?)', ['test.csv'])
duckdb.duckdb.BinderException: Binder Error: Unexpected prepared parameter. This type of statement can't be prepared!
```

### OS:

macOS 13.6.7 (22G720) aarch64

### DuckDB Version:

1.0.0

### DuckDB Client:

Python

### Full Name:

Diego Manenti Martins

### Affiliation:

Stem

### What is the latest build you tested with? If possible, we recommend testing with the latest nightly build.

I have tested with a stable release

### Did you include all relevant data sets for reproducing the issue?

Yes

### Did you include all code required to reproduce the issue?

- [X] Yes, I have

### Did you include all relevant configuration (e.g., CPU architecture, Python version, Linux distribution) to reproduce the issue?

- [X] Yes, I have

**Comment by hannes** [comment]
There can't be a ? in the file name there because DuckDB needs to know the result schema at query preparation time.

**Comment by hannes** [comment]
Thanks for reporting, indeed it should be possible to prepare `CREATE VIEW`

**Comment by va3093** [comment]
We ran into https://github.com/duckdb/duckdb/issues/9548 and thought a workaround would be to create a `View` with the params and then use that in the Pivot stmt. But then ran into this issue 😬.

**Comment by va3093** [comment]
Please don't close this. This is still an issue for us.

**Comment by amachanic** [comment]
Just hit this today and came here to file an issue.

**Comment by avouacr** [comment]
Running into the same issue here with the `R` client

**Comment by diegoimbert** [comment]
still have this issue with the Rust client

**Comment by virgesmith** [comment]
also with latest python client (as of today 1.4.4)

**Comment by arjentraas** [comment]
Also ran into this today. Still a relevant issue.
