### ISSUE TITLE
Parquet Null values impala (parquet tools) read issue 

### ISSUE THREAD

**Issue by daniarleagk** [duckdb/duckdb#13464]
### What happens?

Impala (CDH 7.1.9) has sometimes issues to read parquet files (which contain null values) generated by duckdb. 
```bash
Parquet file '.../test.parquet': metadata is corrupt. Dictionary page (offset=4) must come before any data pages (offset=4)
```
parquet-tools jars (org.apache.parquet bundle) can process these parquet files however they log a warning 
```
WARN parquet.CorruptStatistics: Ignoring statistics because created_by could not be parsed (see PARQUET-251): DuckDB
org.apache.parquet.VersionParser$VersionParseException: Could not parse created_by: DuckDB using format: (.*?)\s+version\s*(?:([^(]*?)\s*(?:\(\s*build\s*([^)]*?)\s*\))?)?
        at org.apache.parquet.VersionParser.parse(VersionParser.java:112)
        at org.apache.parquet.CorruptStatistics.shouldIgnoreStatistics(CorruptStatistics.java:72)
        at org.apache.parquet.format.converter.ParquetMetadataConverter.fromParquetStatisticsInternal(ParquetMetadataConverter.java:662)
        at org.apache.parquet.format.converter.ParquetMetadataConverter.fromParquetStatistics(ParquetMetadataConverter.java:682)
        at org.apache.parquet.format.converter.ParquetMetadataConverter.fromParquetMetadata(ParquetMetadataConverter.java:1227)
        at org.apache.parquet.format.converter.ParquetMetadataConverter.readParquetMetadata(ParquetMetadataConverter.java:1190)
        at org.apache.parquet.hadoop.ParquetFileReader.readFooter(ParquetFileReader.java:543)
        at org.apache.parquet.hadoop.ParquetFileReader.<init>(ParquetFileReader.java:707)
        at org.apache.parquet.hadoop.ParquetFileReader.open(ParquetFileReader.java:606)
        at org.apache.parquet.hadoop.ParquetReader.initReader(ParquetReader.java:162)
        at org.apache.parquet.hadoop.ParquetReader.read(ParquetReader.java:135)
        at org.apache.parquet.tools.command.HeadCommand.execute(HeadCommand.java:87)
        at org.apache.parquet.tools.Main.main(Main.java:223)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.base/java.lang.reflect.Method.invoke(Method.java:566)
        at org.apache.hadoop.util.RunJar.run(RunJar.java:318)
        at org.apache.hadoop.util.RunJar.main(RunJar.java:232)
``` 
Other parquet tools that we use can read these files without the problem.

Sample file to reproduce the problem:
[sample.csv](https://github.com/user-attachments/files/16657815/sample.csv)

It seems to be  related to this issue: https://github.com/duckdb/duckdb/issues/12958
Could you please check?

### To Reproduce

Please find attached csv file that generates the warning using java parquet-tools command and throws an error trying to read using impala

### OS:

RHEL

### DuckDB Version:

1.0.0

### DuckDB Client:

python

### Full Name:

Daniar Achakeev

### Affiliation:

HMS Analytical Software GmbH

### What is the latest build you tested with? If possible, we recommend testing with the latest nightly build.

I have not tested with any build

### Did you include all relevant data sets for reproducing the issue?

Yes

### Did you include all code required to reproduce the issue?

- [ ] Yes, I have

### Did you include all relevant configuration (e.g., CPU architecture, Python version, Linux distribution) to reproduce the issue?

- [ ] Yes, I have

**Comment by Tishj** [comment]
(without reading fully) I wonder if <https://github.com/duckdb/duckdb/pull/11774> is relevant to mention here ?

**Comment by szarnyasg** [comment]
Hi @daniarleagk, thanks for opening this issue. I tried to reproduce it but there are two missing pieces of information:

1) How is the CSV file converted to Parquet? I converted it by issuing the following DuckDB command:

    ```sql
    copy 'sample.csv' to 'sample.parquet';
    ```

    Is this the correct conversion command to use?

2) Then, I built version 1.14.1 from the https://github.com/apache/parquet-java repository and ran it as follows. It did not return a warning - what repository / version / command should I use?

```bash
java -cp 'target/parquet-cli-1.14.1.jar:target/dependency/*' org.apache.parquet.cli.Main meta ~/Downloads/sample.parquet
```
```
File path:  /Users/gabor/Downloads/sample.parquet
Created by: DuckDB
Properties: (none)
Schema:
message duckdb_schema {
  optional binary MDL_PRV (STRING);
  optional binary MDL_KEY (STRING);
  optional binary FREQ (STRING);
  optional binary BIS_TOPIC (STRING);
  optional binary REF_AREA (STRING);
  optional int64 BIS_SUFFIX (INTEGER(64,true));
  optional int32 TIME_PERIOD (DATE);
  optional double OBS_VALUE;
  optional binary TIME_FORMAT (STRING);
  optional binary OBS_STATUS (STRING);
  optional binary OBS_CONF (STRING);
  optional binary OBS_PRE_BREAK (STRING);
  optional binary AGG_EQUN (STRING);
  optional binary AVAILABILITY (STRING);
  optional binary BIS_DOC_DATE (STRING);
  optional binary BIS_UNIT (STRING);
  optional binary BREAKS (STRING);
  optional binary COLLECTION (STRING);
  optional binary COLLECTION_DETAIL (STRING);
  optional binary COMPILATION (STRING);
  optional binary COVERAGE (STRING);
  optional int64 DECIMALS (INTEGER(64,true));
  optional binary DOM_SER_IDS (STRING);
  optional binary METHOD_REF (STRING);
  optional binary NAT_TITLE (STRING);
  optional binary OBS_COM (STRING);
  optional binary REP_DELAY (STRING);
  optional binary SOURCE_REF (STRING);
  optional binary TITLE (STRING);
  optional binary TITLE_COMPL (STRING);
  optional binary UNIT_DETAIL (STRING);
  optional binary UNIT_MULT (STRING);
  optional binary MDL_SUB_ID (STRING);
  optional binary MDL_SRC (STRING);
  optional binary MDL_ACTION (STRING);
  optional binary MDL_PER_BEG (STRING);
  optional int64 MDL_PER_END (TIMESTAMP(MICROS,false));
  optional int64 MDL_EFF_DATE (INTEGER(64,true));
}


Row group 0:  count: 7  215.14 B records  start: 4  total(compressed): 1.471 kB total(uncompressed):1.096 MB
--------------------------------------------------------------------------------
                   type      encodings count     avg size   nulls   min / max
MDL_PRV            BINARY    S RRR_    7         7.14 B     0       "1A0" / "1A0"
MDL_KEY            BINARY    S RR_     7         12.57 B    0       "E.BCDE.XY.12.2020-05-27" / "E.BCDE.XY.12.2020-06-02"
FREQ               BINARY    S RRR_    7         6.86 B     0       "E" / "E"
BIS_TOPIC          BINARY    S RRR_    7         7.29 B     0       "BCDE" / "BCDE"
REF_AREA           BINARY    S RRR_    7         7.00 B     0       "XY" / "XY"
BIS_SUFFIX         INT64     S RR_     7         4.57 B     0       "12" / "12"
TIME_PERIOD        INT32     S RR_     7         7.57 B     0       "2020-05-27" / "2020-06-02"
OBS_VALUE          DOUBLE    S RR_     7         8.86 B     2
TIME_FORMAT        BINARY    S RR_     7         3.57 B     7
OBS_STATUS         BINARY    S RRR_    7         6.86 B     0       "M" / "M"
OBS_CONF           BINARY    S RR_     7         3.57 B     7
OBS_PRE_BREAK      BINARY    S RR_     7         3.57 B     7
AGG_EQUN           BINARY    S RR_     7         3.57 B     7
AVAILABILITY       BINARY    S RR_     7         3.57 B     7
BIS_DOC_DATE       BINARY    S RR_     7         3.57 B     7
BIS_UNIT           BINARY    S RR_     7         3.57 B     7
BREAKS             BINARY    S RR_     7         3.57 B     7
COLLECTION         BINARY    S RR_     7         3.57 B     7
COLLECTION_DETAIL  BINARY    S RR_     7         3.57 B     7
COMPILATION        BINARY    S RR_     7         3.57 B     7
COVERAGE           BINARY    S RR_     7         3.57 B     7
DECIMALS           INT64     S RR_     7         4.57 B     0       "7" / "7"
DOM_SER_IDS        BINARY    S RR_     7         3.57 B     7
METHOD_REF         BINARY    S RR_     7         3.57 B     7
NAT_TITLE          BINARY    S RR_     7         3.57 B     7
OBS_COM            BINARY    S RR_     7         3.57 B     7
REP_DELAY          BINARY    S RR_     7         3.57 B     7
SOURCE_REF         BINARY    S RR_     7         3.57 B     7
TITLE              BINARY    S RR_     7         3.57 B     7
TITLE_COMPL        BINARY    S RR_     7         3.57 B     7
UNIT_DETAIL        BINARY    S RR_     7         3.57 B     7
UNIT_MULT          BINARY    S RR_     7         3.57 B     7
MDL_SUB_ID         BINARY    S RRR_    7         11.86 B    0       "04ea2bf8-2195-42f0-8959-6..." / "04ea2bf8-2195-42f0-8959-6..."
MDL_SRC            BINARY    S RRR_    7         13.14 B    0       "/raw/dt=2024-05/171690258..." / "/raw/dt=2024-05/171690258..."
MDL_ACTION         BINARY    S RRR_    7         6.86 B     0       "H" / "H"
MDL_PER_BEG        BINARY    S RR_     7         15.29 B    0       "2020-05-28T00:00:00.000Z" / "2020-05-27T00:00:00.000Z"
MDL_PER_END        INT64     S RR_     7         11.00 B    0       "2020-05-27T23:59:59.000000" / "2020-06-02T23:59:59.000000"
MDL_EFF_DATE       INT64     S RR_     7         5.14 B     0       "1716902652661899" / "1716902652661899"
```

**Comment by daniarleagk** [comment]
Hi @szarnyasg, 

Than you for prompt reply: We used parquet-tools-1.10.99.7.1.9.19-3.jar version. 
In order to reproduce the warning:
```sql
COPY (SELECT * FROM 'sample.csv') TO 'sample.parquet' (FORMAT PARQUET)
```
Thank you!

**Comment by szarnyasg** [comment]
Hi @daniarleagk can you please provide a link to the parquet-tools JAR file / source code? There are many Parquet CLI tools out there and I cannot find this specific one.

**Comment by daniarleagk** [comment]
Hi @szarnyasg, 

please find attached jars (I uploaded them here https://github.com/daniarleagk/jars) from cloudera distribution (CDH 7.1.9). Both of them log the warning above. Please let me know as soon as you downloaded the file. Thank you! I hope this would help.

**Comment by szarnyasg** [comment]
Hi @daniarleagk, thanks, I cloned the repo, so you can delete it.

Here's my output for the `meta` command:

```bash
java -jar parquet-tools-1.10.99.7.1.9.9-1.jar meta sample.parquet
```

```text
file:              file:/Users/gabor/git/jars/sample.parquet
creator:           DuckDB

file schema:       duckdb_schema
--------------------------------------------------------------------------------
MDL_PRV:           OPTIONAL BINARY L:STRING R:0 D:1
MDL_KEY:           OPTIONAL BINARY L:STRING R:0 D:1
FREQ:              OPTIONAL BINARY L:STRING R:0 D:1
BIS_TOPIC:         OPTIONAL BINARY L:STRING R:0 D:1
REF_AREA:          OPTIONAL BINARY L:STRING R:0 D:1
BIS_SUFFIX:        OPTIONAL INT64 L:INTEGER(64,true) R:0 D:1
TIME_PERIOD:       OPTIONAL INT32 L:DATE R:0 D:1
OBS_VALUE:         OPTIONAL DOUBLE R:0 D:1
TIME_FORMAT:       OPTIONAL BINARY L:STRING R:0 D:1
OBS_STATUS:        OPTIONAL BINARY L:STRING R:0 D:1
OBS_CONF:          OPTIONAL BINARY L:STRING R:0 D:1
OBS_PRE_BREAK:     OPTIONAL BINARY L:STRING R:0 D:1
AGG_EQUN:          OPTIONAL BINARY L:STRING R:0 D:1
AVAILABILITY:      OPTIONAL BINARY L:STRING R:0 D:1
BIS_DOC_DATE:      OPTIONAL BINARY L:STRING R:0 D:1
BIS_UNIT:          OPTIONAL BINARY L:STRING R:0 D:1
BREAKS:            OPTIONAL BINARY L:STRING R:0 D:1
COLLECTION:        OPTIONAL BINARY L:STRING R:0 D:1
COLLECTION_DETAIL: OPTIONAL BINARY L:STRING R:0 D:1
COMPILATION:       OPTIONAL BINARY L:STRING R:0 D:1
COVERAGE:          OPTIONAL BINARY L:STRING R:0 D:1
DECIMALS:          OPTIONAL INT64 L:INTEGER(64,true) R:0 D:1
DOM_SER_IDS:       OPTIONAL BINARY L:STRING R:0 D:1
METHOD_REF:        OPTIONAL BINARY L:STRING R:0 D:1
NAT_TITLE:         OPTIONAL BINARY L:STRING R:0 D:1
OBS_COM:           OPTIONAL BINARY L:STRING R:0 D:1
REP_DELAY:         OPTIONAL BINARY L:STRING R:0 D:1
SOURCE_REF:        OPTIONAL BINARY L:STRING R:0 D:1
TITLE:             OPTIONAL BINARY L:STRING R:0 D:1
TITLE_COMPL:       OPTIONAL BINARY L:STRING R:0 D:1
UNIT_DETAIL:       OPTIONAL BINARY L:STRING R:0 D:1
UNIT_MULT:         OPTIONAL BINARY L:STRING R:0 D:1
MDL_SUB_ID:        OPTIONAL BINARY L:STRING R:0 D:1
MDL_SRC:           OPTIONAL BINARY L:STRING R:0 D:1
MDL_ACTION:        OPTIONAL BINARY L:STRING R:0 D:1
MDL_PER_BEG:       OPTIONAL BINARY L:STRING R:0 D:1
MDL_PER_END:       OPTIONAL INT64 L:TIMESTAMP(MICROS,false) R:0 D:1
MDL_EFF_DATE:      OPTIONAL INT64 L:INTEGER(64,true) R:0 D:1

row group 1:       RC:7 TS:1149315 OFFSET:4
--------------------------------------------------------------------------------
MDL_PRV:            BINARY SNAPPY DO:4 FPO:26 SZ:50/46/0.92 VC:7 ENC:RLE_DICTIONARY,PLAIN ST:[min: 1A0, max: 1A0, num_nulls: 0]
MDL_KEY:            BINARY SNAPPY DO:0 FPO:54 SZ:88/214/2.43 VC:7 ENC:PLAIN ST:[min: E.BCDE.XY.12.2020-05-27, max: E.BCDE.XY.12.2020-06-02, num_nulls: 0]
FREQ:               BINARY SNAPPY DO:142 FPO:162 SZ:48/44/0.92 VC:7 ENC:RLE_DICTIONARY,PLAIN ST:[min: E, max: E, num_nulls: 0]
BIS_TOPIC:          BINARY SNAPPY DO:190 FPO:213 SZ:51/47/0.92 VC:7 ENC:RLE_DICTIONARY,PLAIN ST:[min: BCDE, max: BCDE, num_nulls: 0]
REF_AREA:           BINARY SNAPPY DO:241 FPO:262 SZ:49/45/0.92 VC:7 ENC:RLE_DICTIONARY,PLAIN ST:[min: XY, max: XY, num_nulls: 0]
BIS_SUFFIX:         INT64 SNAPPY DO:0 FPO:290 SZ:32/79/2.47 VC:7 ENC:PLAIN ST:[min: 12, max: 12, num_nulls: 0]
TIME_PERIOD:        INT32 SNAPPY DO:0 FPO:322 SZ:53/51/0.96 VC:7 ENC:PLAIN ST:[min: 2020-05-27, max: 2020-06-02, num_nulls: 0]
OBS_VALUE:          DOUBLE SNAPPY DO:0 FPO:375 SZ:62/67/1.08 VC:7 ENC:PLAIN ST:[num_nulls: 2, min/max not defined]
TIME_FORMAT:        BINARY SNAPPY DO:0 FPO:437 SZ:25/23/0.92 VC:7 ENC:PLAIN ST:[num_nulls: 7, min/max not defined]
OBS_STATUS:         BINARY SNAPPY DO:462 FPO:482 SZ:48/44/0.92 VC:7 ENC:RLE_DICTIONARY,PLAIN ST:[min: M, max: M, num_nulls: 0]
OBS_CONF:           BINARY SNAPPY DO:0 FPO:510 SZ:25/23/0.92 VC:7 ENC:PLAIN ST:[num_nulls: 7, min/max not defined]
OBS_PRE_BREAK:      BINARY SNAPPY DO:0 FPO:535 SZ:25/23/0.92 VC:7 ENC:PLAIN ST:[num_nulls: 7, min/max not defined]
AGG_EQUN:           BINARY SNAPPY DO:0 FPO:560 SZ:25/23/0.92 VC:7 ENC:PLAIN ST:[num_nulls: 7, min/max not defined]
AVAILABILITY:       BINARY SNAPPY DO:0 FPO:585 SZ:25/23/0.92 VC:7 ENC:PLAIN ST:[num_nulls: 7, min/max not defined]
BIS_DOC_DATE:       BINARY SNAPPY DO:0 FPO:610 SZ:25/23/0.92 VC:7 ENC:PLAIN ST:[num_nulls: 7, min/max not defined]
BIS_UNIT:           BINARY SNAPPY DO:0 FPO:635 SZ:25/23/0.92 VC:7 ENC:PLAIN ST:[num_nulls: 7, min/max not defined]
BREAKS:             BINARY SNAPPY DO:0 FPO:660 SZ:25/23/0.92 VC:7 ENC:PLAIN ST:[num_nulls: 7, min/max not defined]
COLLECTION:         BINARY SNAPPY DO:0 FPO:685 SZ:25/23/0.92 VC:7 ENC:PLAIN ST:[num_nulls: 7, min/max not defined]
COLLECTION_DETAIL:  BINARY SNAPPY DO:0 FPO:710 SZ:25/23/0.92 VC:7 ENC:PLAIN ST:[num_nulls: 7, min/max not defined]
COMPILATION:        BINARY SNAPPY DO:0 FPO:735 SZ:25/23/0.92 VC:7 ENC:PLAIN ST:[num_nulls: 7, min/max not defined]
COVERAGE:           BINARY SNAPPY DO:0 FPO:760 SZ:25/23/0.92 VC:7 ENC:PLAIN ST:[num_nulls: 7, min/max not defined]
DECIMALS:           INT64 SNAPPY DO:0 FPO:785 SZ:32/79/2.47 VC:7 ENC:PLAIN ST:[min: 7, max: 7, num_nulls: 0]
DOM_SER_IDS:        BINARY SNAPPY DO:0 FPO:817 SZ:25/23/0.92 VC:7 ENC:PLAIN ST:[num_nulls: 7, min/max not defined]
METHOD_REF:         BINARY SNAPPY DO:0 FPO:842 SZ:25/23/0.92 VC:7 ENC:PLAIN ST:[num_nulls: 7, min/max not defined]
NAT_TITLE:          BINARY SNAPPY DO:0 FPO:867 SZ:25/23/0.92 VC:7 ENC:PLAIN ST:[num_nulls: 7, min/max not defined]
OBS_COM:            BINARY SNAPPY DO:0 FPO:892 SZ:25/23/0.92 VC:7 ENC:PLAIN ST:[num_nulls: 7, min/max not defined]
REP_DELAY:          BINARY SNAPPY DO:0 FPO:917 SZ:25/23/0.92 VC:7 ENC:PLAIN ST:[num_nulls: 7, min/max not defined]
SOURCE_REF:         BINARY SNAPPY DO:0 FPO:942 SZ:25/23/0.92 VC:7 ENC:PLAIN ST:[num_nulls: 7, min/max not defined]
TITLE:              BINARY SNAPPY DO:0 FPO:967 SZ:25/23/0.92 VC:7 ENC:PLAIN ST:[num_nulls: 7, min/max not defined]
TITLE_COMPL:        BINARY SNAPPY DO:0 FPO:992 SZ:25/23/0.92 VC:7 ENC:PLAIN ST:[num_nulls: 7, min/max not defined]
UNIT_DETAIL:        BINARY SNAPPY DO:0 FPO:1017 SZ:25/23/0.92 VC:7 ENC:PLAIN ST:[num_nulls: 7, min/max not defined]
UNIT_MULT:          BINARY SNAPPY DO:0 FPO:1042 SZ:25/23/0.92 VC:7 ENC:PLAIN ST:[num_nulls: 7, min/max not defined]
MDL_SUB_ID:         BINARY SNAPPY DO:1067 FPO:1122 SZ:83/79/0.95 VC:7 ENC:RLE_DICTIONARY,PLAIN ST:[min: 04ea2bf8-2195-42f0-8959-676a7917baa8, max: 04ea2bf8-2195-42f0-8959-676a7917baa8, num_nulls: 0]
MDL_SRC:            BINARY SNAPPY DO:1150 FPO:1214 SZ:92/88/0.96 VC:7 ENC:RLE_DICTIONARY,PLAIN ST:[min: /raw/dt=2024-05/1716902589656_tmp0j72n985.csv, max: /raw/dt=2024-05/1716902589656_tmp0j72n985.csv, num_nulls: 0]
MDL_ACTION:         BINARY SNAPPY DO:1242 FPO:1262 SZ:48/44/0.92 VC:7 ENC:RLE_DICTIONARY,PLAIN ST:[min: H, max: H, num_nulls: 0]
MDL_PER_BEG:        BINARY SNAPPY DO:0 FPO:1290 SZ:107/224/2.09 VC:7 ENC:PLAIN ST:[min: 2020-05-28T00:00:00.000Z, max: 2020-05-27T00:00:00.000Z, num_nulls: 0]
MDL_PER_END:        INT64 SNAPPY DO:0 FPO:1397 SZ:77/79/1.03 VC:7 ENC:PLAIN ST:[min: 2020-05-27T23:59:59.000000, max: 2020-06-02T23:59:59.000000, num_nulls: 0]
MDL_EFF_DATE:       INT64 SNAPPY DO:0 FPO:1474 SZ:36/79/2.19 VC:7 ENC:PLAIN ST:[min: 1716902652661899, max: 1716902652661899, num_nulls: 0]
```

This is my JVM version:

```text
openjdk version "17.0.7" 2023-04-18
OpenJDK Runtime Environment Temurin-17.0.7+7 (build 17.0.7+7)
OpenJDK 64-Bit Server VM Temurin-17.0.7+7 (build 17.0.7+7, mixed mode)
```

**Comment by szarnyasg** [comment]
I tried running a `head` command

```
$ java -jar parquet-tools-1.10.99.7.1.9.19-3.jar head sample.parquet
```

On macOS, this fails because of the inavailability of native libraries:

```console
org.xerial.snappy.SnappyError: [FAILED_TO_LOAD_NATIVE_LIBRARY] no native library is found for os.name=Mac and os.arch=aarch64
```

On Linux (Ubuntu, x86_64), it succeeds:

```
MDL_PRV = 1A0
MDL_KEY = E.BCDE.XY.12.2020-05-27
FREQ = E
BIS_TOPIC = BCDE
REF_AREA = XY
BIS_SUFFIX = 12
TIME_PERIOD = 18409
OBS_VALUE = 123.0
OBS_STATUS = M
DECIMALS = 7
MDL_SUB_ID = 04ea2bf8-2195-42f0-8959-676a7917baa8
MDL_SRC = /raw/dt=2024-05/1716902589656_tmp0j72n985.csv
MDL_ACTION = H
MDL_PER_BEG = 2020-05-27T00:00:00.000Z
MDL_PER_END = 1590623999000000
MDL_EFF_DATE = 1716902652661899

MDL_PRV = 1A0
MDL_KEY = E.BCDE.XY.12.2020-05-28
FREQ = E
BIS_TOPIC = BCDE
REF_AREA = XY
BIS_SUFFIX = 12
TIME_PERIOD = 18410
OBS_STATUS = M
DECIMALS = 7
MDL_SUB_ID = 04ea2bf8-2195-42f0-8959-676a7917baa8
MDL_SRC = /raw/dt=2024-05/1716902589656_tmp0j72n985.csv
MDL_ACTION = H
MDL_PER_BEG = 2020-05-28T00:00:00.000Z
MDL_PER_END = 1590710399000000
MDL_EFF_DATE = 1716902652661899

MDL_PRV = 1A0
MDL_KEY = E.BCDE.XY.12.2020-05-29
FREQ = E
BIS_TOPIC = BCDE
REF_AREA = XY
BIS_SUFFIX = 12
TIME_PERIOD = 18411
OBS_STATUS = M
DECIMALS = 7
MDL_SUB_ID = 04ea2bf8-2195-42f0-8959-676a7917baa8
MDL_SRC = /raw/dt=2024-05/1716902589656_tmp0j72n985.csv
MDL_ACTION = H
MDL_PER_BEG = 2020-05-29T00:00:00.000Z
MDL_PER_END = 1590796799000000
MDL_EFF_DATE = 1716902652661899

MDL_PRV = 1A0
MDL_KEY = E.BCDE.XY.12.2020-05-30
FREQ = E
BIS_TOPIC = BCDE
REF_AREA = XY
BIS_SUFFIX = 12
TIME_PERIOD = 18412
OBS_VALUE = 456.0
OBS_STATUS = M
DECIMALS = 7
MDL_SUB_ID = 04ea2bf8-2195-42f0-8959-676a7917baa8
MDL_SRC = /raw/dt=2024-05/1716902589656_tmp0j72n985.csv
MDL_ACTION = H
MDL_PER_BEG = 2020-05-30T00:00:00.000Z
MDL_PER_END = 1590883199000000
MDL_EFF_DATE = 1716902652661899

MDL_PRV = 1A0
MDL_KEY = E.BCDE.XY.12.2020-05-31
FREQ = E
BIS_TOPIC = BCDE
REF_AREA = XY
BIS_SUFFIX = 12
TIME_PERIOD = 18413
OBS_VALUE = NaN
OBS_STATUS = M
DECIMALS = 7
MDL_SUB_ID = 04ea2bf8-2195-42f0-8959-676a7917baa8
MDL_SRC = /raw/dt=2024-05/1716902589656_tmp0j72n985.csv
MDL_ACTION = H
MDL_PER_BEG = 2020-05-31T00:00:00.000Z
MDL_PER_END = 1590969599000000
MDL_EFF_DATE = 1716902652661899
```

Can you please provide the flags for the Parquet CLI code that trigger the warning?

**Comment by daniarleagk** [comment]
Hi @szarnyasg, 

on hadoop we run hadoop jar /pkgs/cdh/cloudera/parcels/CDH-7.1.9-1.cdh7.1.9.p19.54389010/jars/parquet-tools-1.10.99.7.1.9.19-3.jar head --debug hdfs://.../test.parquet (Linux RHEL 8.10)

could you try `head --debug` ? Thank you!

**Comment by daniarleagk** [comment]
Hi @szarnyasg, 

our observation is:  the files that cannot be read by impala are those ones with log output "warning" from parquet-tools (additionally these files contain NULL values).   I hope this helps.

**Comment by szarnyasg** [comment]
Hi, here's my output:

```bash
$ java -jar parquet-tools-1.10.99.7.1.9.19-3.jar head --debug sample.parquet
```
```
MDL_PRV = 1A0
MDL_KEY = E.BCDE.XY.12.2020-05-27
FREQ = E
BIS_TOPIC = BCDE
REF_AREA = XY
BIS_SUFFIX = 12
TIME_PERIOD = 18409
OBS_VALUE = 123.0
OBS_STATUS = M
DECIMALS = 7
MDL_SUB_ID = 04ea2bf8-2195-42f0-8959-676a7917baa8
MDL_SRC = /raw/dt=2024-05/1716902589656_tmp0j72n985.csv
MDL_ACTION = H
MDL_PER_BEG = 2020-05-27T00:00:00.000Z
MDL_PER_END = 1590623999000000
MDL_EFF_DATE = 1716902652661899

MDL_PRV = 1A0
MDL_KEY = E.BCDE.XY.12.2020-05-28
FREQ = E
BIS_TOPIC = BCDE
REF_AREA = XY
BIS_SUFFIX = 12
TIME_PERIOD = 18410
OBS_STATUS = M
DECIMALS = 7
MDL_SUB_ID = 04ea2bf8-2195-42f0-8959-676a7917baa8
MDL_SRC = /raw/dt=2024-05/1716902589656_tmp0j72n985.csv
MDL_ACTION = H
MDL_PER_BEG = 2020-05-28T00:00:00.000Z
MDL_PER_END = 1590710399000000
MDL_EFF_DATE = 1716902652661899

MDL_PRV = 1A0
MDL_KEY = E.BCDE.XY.12.2020-05-29
FREQ = E
BIS_TOPIC = BCDE
REF_AREA = XY
BIS_SUFFIX = 12
TIME_PERIOD = 18411
OBS_STATUS = M
DECIMALS = 7
MDL_SUB_ID = 04ea2bf8-2195-42f0-8959-676a7917baa8
MDL_SRC = /raw/dt=2024-05/1716902589656_tmp0j72n985.csv
MDL_ACTION = H
MDL_PER_BEG = 2020-05-29T00:00:00.000Z
MDL_PER_END = 1590796799000000
MDL_EFF_DATE = 1716902652661899

MDL_PRV = 1A0
MDL_KEY = E.BCDE.XY.12.2020-05-30
FREQ = E
BIS_TOPIC = BCDE
REF_AREA = XY
BIS_SUFFIX = 12
TIME_PERIOD = 18412
OBS_VALUE = 456.0
OBS_STATUS = M
DECIMALS = 7
MDL_SUB_ID = 04ea2bf8-2195-42f0-8959-676a7917baa8
MDL_SRC = /raw/dt=2024-05/1716902589656_tmp0j72n985.csv
MDL_ACTION = H
MDL_PER_BEG = 2020-05-30T00:00:00.000Z
MDL_PER_END = 1590883199000000
MDL_EFF_DATE = 1716902652661899

MDL_PRV = 1A0
MDL_KEY = E.BCDE.XY.12.2020-05-31
FREQ = E
BIS_TOPIC = BCDE
REF_AREA = XY
BIS_SUFFIX = 12
TIME_PERIOD = 18413
OBS_VALUE = NaN
OBS_STATUS = M
DECIMALS = 7
MDL_SUB_ID = 04ea2bf8-2195-42f0-8959-676a7917baa8
MDL_SRC = /raw/dt=2024-05/1716902589656_tmp0j72n985.csv
MDL_ACTION = H
MDL_PER_BEG = 2020-05-31T00:00:00.000Z
MDL_PER_END = 1590969599000000
MDL_EFF_DATE = 1716902652661899
```

That said, we're happy to adjust the metadata of the `created_by` field, so we'll take a look.

**Comment by daniarleagk** [comment]
Hi @szarnyasg, 

Thank you very much! :-)
Let's hope  this would fix impala read problem (since parquet-tools warning is the observation we made with files that were rejected by impala).

**Comment by hannes** [comment]
I could also not reproduce the warning but we're happy to add version info to the Parquet metadata that satisfies this regex: https://github.com/duckdb/duckdb/pull/13992

I don't think https://github.com/duckdb/duckdb/issues/12958 is related

Now to somehow reanimate Impala to test the other issue you reported.

**Comment by hannes** [comment]
I've managed to get the latest version of Impala (58fd45f20c22f8a062f603d6b96f62ee57d85ca9) running and it works perfectly file with the sample you provided. So we would need additional information to proceed.

**Comment by daniarleagk** [comment]
Thank you very much @hannes! I will double check with which version we observed errors. And get back to you.

**Comment by daniarleagk** [comment]
Hello @hannes, the version that my colleagues used is v4.0.0.7.1.9.9-1 (part of Cloudera CDH 7.2.3).  I hope it will help.

**Comment by daniarleagk** [comment]
Hi all, sorry for inconvenience , from our side this error not relevant anymore.
