### ISSUE TITLE
Overture's address dataset's sources column struct raises internal error: Requested allocation size of # is out of range on Windows, WSL2 and VMs running on 14900K but not macOS or the Steamdeck

### ISSUE THREAD

**Issue by marklit** [duckdb/duckdb#13505]
### What happens?

I'm getting one of the following issues after I run the SQL below:

```
Invalid Input Error: Malformed JSON at byte 105 of input: unexpected end of data.  Input: [{"property":"","dataset":"OpenAddresses/MAA-AM...
```

after a reboot I'm seeing the following:

```
Invalid Input Error: Malformed JSON at byte 115 of input: unexpected character.  Input: [{"property":"","dataset":"OpenAddresses/Addres...
```

Others I've spoken to whom are using the same version of DuckDB are able to run the query without issue for some reason: https://github.com/OvertureMaps/data/issues/208#issuecomment-2303084499

The dataset was produced with Sonoma 14.5.

### To Reproduce

```sql
SELECT   country,
         COUNT(*) AS num_addrs,
         sources->0->'dataset' AS source
FROM     READ_PARQUET('s3://overturemaps-us-west-2/release/2024-08-20.0/theme=addresses/type=address/*.parquet',
                      hive_partitioning=1)
WHERE    country != 'US'
GROUP BY 1, 3
ORDER BY 1, 2 DESC;
```

### OS:

Ubuntu for Windows on Windows 11 (WSL)

### DuckDB Version:

v1.0.0 1f98600c2c

### DuckDB Client:

CLI

### Full Name:

Mark Litwintschik

### Affiliation:

Green Idea

### What is the latest build you tested with? If possible, we recommend testing with the latest nightly build.

I have tested with a stable release

### Did you include all relevant data sets for reproducing the issue?

Yes

### Did you include all code required to reproduce the issue?

- [X] Yes, I have

### Did you include all relevant configuration (e.g., CPU architecture, Python version, Linux distribution) to reproduce the issue?

- [X] Yes, I have

**Comment by szarnyasg** [comment]
The query also works for me:

```
┌─────────┬───────────┬──────────────────────────────────────────────────────────┐
│ country │ num_addrs │                          source                          │
│ varchar │   int64   │                           json                           │
├─────────┼───────────┼──────────────────────────────────────────────────────────┤
│ AT      │   2492155 │ "OpenAddresses/Bundesamt für Eich- und Vermessungswesen" │
│ AU      │  15608317 │ "OpenAddresses/Geosacape Australia"                      │
│ CA      │  16457790 │ "OpenAddresses/Statistics Canada"                        │
│ CH      │   3147964 │ "OpenAddresses/Swisstopo"                                │
│ CO      │   7786046 │ "OpenAddresses/AddressForAll/DANE"                       │
│ DK      │   3920253 │ "OpenAddresses/DAWA"                                     │
│ EE      │   2210423 │ "OpenAddresses/MAA-AMET"                                 │
│ FR      │  26041499 │ "OpenAddresses/adresse.data.gouv.fr"                     │
│ LT      │   1036251 │ "OpenAddresses/Registrų Centras"                         │
│ LU      │    164415 │ "OpenAddresses/data.public.lu"                           │
│ MX      │  30278896 │ "OpenAddresses/AddressForAll/INEGI"                      │
│ NL      │   9750341 │ "OpenAddresses/NGR"                                      │
│ NZ      │   2351461 │ "OpenAddresses/LINZ"                                     │
│ PT      │   5911139 │ "OpenAddresses/INE"                                      │
├─────────┴───────────┴──────────────────────────────────────────────────────────┤
│ 14 rows                                                              3 columns │
└────────────────────────────────────────────────────────────────────────────────┘
```
```
Run Time (s): real 40.124 user 50.773064 sys 0.478836
```

**Comment by marklit** [comment]
I'm using a 6 GHz Intel Core i9-14900K CPU. I'm able to get this error to come up repeatedly and it was a problem a few weeks ago when I first started looking at this dataset.

**Comment by szarnyasg** [comment]
I tried reproducing this on Windows Server 2022 (`r6d.4xlarge`, 16 Intel Xeon cores and 128GB RAM) but it worked fine.

**Comment by marklit** [comment]
From https://github.com/isaacbrodsky/h3-duckdb/issues/122

> Windows Server might be different enough to warrant its own testing and not great for uncovering Windows 11 issues.

**Comment by szarnyasg** [comment]
Understood. Unfortunately, AWS doesn't have Win11 images. The laptop I have available for testing has an AMD Ryzen CPU with 8 cores, and also did not reproduce the issue.

**Comment by marklit** [comment]
This is still an issue in v1.1.1 af39bd0dcf

```sql
SELECT   country,
         COUNT(*) AS num_addrs,
         sources->0->'dataset' AS source
FROM     READ_PARQUET('s3://overturemaps-us-west-2/release/2024-08-20.0/theme=addresses/type=address/*.parquet',
                      hive_partitioning=1)
WHERE    country != 'US'
GROUP BY 1, 3
ORDER BY 1, 2 DESC;
```

```
 83% ▕█████████████████████████████████████████████████▊          ▏ Invalid Input Error: Malformed JSON at byte 25 of input: unexpected character.  Input: [{"property":"","dataset"OpenAddresses/DAWA","r...
```

The local version of this dataset works without issue in v1.1.1 as per #13504, it only seems to be triggered when calling from S3.

**Comment by marklit** [comment]
Yeah, WSL 2. I can reproduce the issue between reboots. I'll see if I can compile DuckDB and run gdb to get something more substantial to share.

**Comment by marklit** [comment]
I created an Ubuntu 22 VM via VirtualBox on my Windows machine and compiled DuckDB v1.1.3.

The VM has 16 GB of RAM, 100 GB of storage and access to 4 of my Intel i9 14900K's 24 cores.

```bash
$ git clone https://github.com/duckdb/duckdb.git ~/duckdb_source
$ cd ~/duckdb_source
$ git checkout v1.1.3

$ mkdir -p build/debug
$ cmake \
    ./CMakeLists.txt \
    -DCMAKE_BUILD_TYPE=DEBUG \
    -DEXTENSION_STATIC_BUILD=1 \
    -B build/debug
```

```
-- git hash 19864453f7, version v1.1.3, extension folder v1.1.3
-- Extensions will be deployed to: /home/mark/duckdb_source/build/debug/repository
-- Load extension 'parquet' from '/home/mark/duckdb_source/extensions' @ v1.1.3
-- Load extension 'jemalloc' from '/home/mark/duckdb_source/extensions' @ v1.1.3
-- Extensions linked into DuckDB: [parquet, jemalloc]
-- Configuring done (0.7s)
-- Generating done (0.3s)
-- Build files have been written to: /home/mark/duckdb_source/build/debug
```

```bash
$ CMAKE_BUILD_PARALLEL_LEVEL=$(nproc) \
    CORE_EXTENSIONS='httpfs' \
    cmake --build build/debug

$ gdb build/debug/duckdb
```

```
(gdb) run
```

```sql
SET autoinstall_known_extensions=1;
SET autoload_known_extensions=1;

SELECT   country,
         COUNT(*) AS num_addrs,
         sources->0->'dataset' AS source
FROM     READ_PARQUET('s3://overturemaps-us-west-2/release/2024-08-20.0/theme=addresses/type=address/*.parquet',
                      hive_partitioning=1)
WHERE    country = 'US'
GROUP BY 1, 3
ORDER BY 1, 2 DESC;
```

```
[Thread 0x7fffc9a22640 (LWP 32113) exited]
[Thread 0x7fffc9221640 (LWP 32114) exited]
[Thread 0x7fffc8a20640 (LWP 32115) exited]
 11% ▕██████▌                                                     ▏
Thread 4 "duckdb" received signal SIGSEGV, Segmentation fault.
[Switching to Thread 0x7fffef5c1640 (LWP 32027)]
0x00005555680f6a70 in duckdb::StringVector::AddStringOrBlob (vector=..., data=<error reading variable: Cannot access memory at address 0xf5f5f5f5f5f5f5b5>) at /home/mark/duckdb_source/src/common/types/vector.cpp:1942
1942    string_t StringVector::AddStringOrBlob(Vector &vector, string_t data) {
```

```
(gdb) backtrace
```

```
#0  0x00005555680f6a70 in duckdb::StringVector::AddStringOrBlob (vector=...,
    data=<error reading variable: Cannot access memory at address 0xf5f5f5f5f5f5f5b5>)
    at /home/mark/duckdb_source/src/common/types/vector.cpp:1942
#1  0x0000000045e0360e in ?? ()
#2  0x0000000000000000 in ?? ()
```

I started gdb again and re-ran the query:

```
[Thread 0x7fffd77d1640 (LWP 32207) exited]
[Thread 0x7fffd5fce640 (LWP 32210) exited]
[Thread 0x7fffd57cd640 (LWP 32211) exited]
=================================================================
==32120==ERROR: AddressSanitizer: stack-buffer-overflow on address 0x7fffef5bc188 at pc 0x5555677e3f32 bp 0x7fffef5bc100 sp 0x7fffef5bc0f0
READ of size 8 at 0x7fffef5bc188 thread T3
    #0 0x5555677e3f31 in duckdb::TemplatedValidityMask<unsigned long>::RowIsValidUnsafe(unsigned long) const /home/mark/duckdb_source/src/include/duckdb/common/types/validity_mask.hpp:187
    #1 0x5555677d9052 in duckdb::TemplatedValidityMask<unsigned long>::RowIsValid(unsigned long) const /home/mark/duckdb_source/src/include/duckdb/common/types/validity_mask.hpp:196
    #2 0x5555680ef2e5 in duckdb::Vector::Verify(duckdb::Vector&, duckdb::SelectionVector const&, unsigned long) /home/mark/duckdb_source/src/common/types/vector.cpp:1453
    #3 0x5555680f0386 in duckdb::Vector::Verify(duckdb::Vector&, duckdb::SelectionVector const&, unsigned long) /home/mark/duckdb_source/src/common/types/vector.cpp:1557
    #4 0x5555680f1d67 in duckdb::Vector::Verify(duckdb::Vector&, duckdb::SelectionVector const&, unsigned long) /home/mark/duckdb_source/src/common/types/vector.cpp:1642
    #5 0x5555680f219c in duckdb::Vector::Verify(unsigned long) /home/mark/duckdb_source/src/common/types/vector.cpp:1654
    #6 0x55556907b611 in duckdb::ExpressionExecutor::Verify(duckdb::Expression const&, duckdb::Vector&, unsigned long) /home/mark/duckdb_source/src/execution/expression_executor.cpp:133
    #7 0x55556907f3a8 in duckdb::ExpressionExecutor::Execute(duckdb::Expression const&, duckdb::ExpressionState*, duckdb::SelectionVector const*, unsigned long, duckdb::Vector&) /home/mark/duckdb_source/src/execution/expression_executor.cpp:228
    #8 0x555568b5a03e in duckdb::ExpressionExecutor::Execute(duckdb::BoundCastExpression const&, duckdb::ExpressionState*, duckdb::SelectionVector const*, unsigned long, duckdb::Vector&) /home/mark/duckdb_source/src/execution/expression_executor/execute_cast.cpp:31
    #9 0x55556907e62c in duckdb::ExpressionExecutor::Execute(duckdb::Expression const&, duckdb::ExpressionState*, duckdb::SelectionVector const*, unsigned long, duckdb::Vector&) /home/mark/duckdb_source/src/execution/expression_executor.cpp:205
    #10 0x555568b65957 in duckdb::ExpressionExecutor::Execute(duckdb::BoundFunctionExpression const&, duckdb::ExpressionState*, duckdb::SelectionVector const*, unsigned long, duckdb::Vector&) /home/mark/duckdb_source/src/execution/expression_executor/execute_function.cpp:67
    #11 0x55556907ee64 in duckdb::ExpressionExecutor::Execute(duckdb::Expression const&, duckdb::ExpressionState*, duckdb::SelectionVector const*, unsigned long, duckdb::Vector&) /home/mark/duckdb_source/src/execution/expression_executor.cpp:217
    #12 0x555568b65957 in duckdb::ExpressionExecutor::Execute(duckdb::BoundFunctionExpression const&, duckdb::ExpressionState*, duckdb::SelectionVector const*, unsigned long, duckdb::Vector&) /home/mark/duckdb_source/src/execution/expression_executor/execute_function.cpp:67
    #13 0x55556907ee64 in duckdb::ExpressionExecutor::Execute(duckdb::Expression const&, duckdb::ExpressionState*, duckdb::SelectionVector const*, unsigned long, duckdb::Vector&) /home/mark/duckdb_source/src/execution/expression_executor.cpp:217
    #14 0x55556907a765 in duckdb::ExpressionExecutor::ExecuteExpression(unsigned long, duckdb::Vector&) /home/mark/duckdb_source/src/execution/expression_executor.cpp:102
    #15 0x555569079c3e in duckdb::ExpressionExecutor::Execute(duckdb::DataChunk*, duckdb::DataChunk&) /home/mark/duckdb_source/src/execution/expression_executor.cpp:76
    #16 0x55556903068e in duckdb::ExpressionExecutor::Execute(duckdb::DataChunk&, duckdb::DataChunk&) /home/mark/duckdb_source/src/include/duckdb/execution/expression_executor.hpp:50
    #17 0x55556dd80006 in duckdb::PhysicalProjection::Execute(duckdb::ExecutionContext&, duckdb::DataChunk&, duckdb::DataChunk&, duckdb::GlobalOperatorState&, duckdb::OperatorState&) const /home/mark/duckdb_source/src/execution/operator/projection/physical_projection.cpp:31
    #18 0x555569ae5d48 in duckdb::PipelineExecutor::Execute(duckdb::DataChunk&, duckdb::DataChunk&, unsigned long) /home/mark/duckdb_source/src/parallel/pipeline_executor.cpp:418
    #19 0x555569ae2fa4 in duckdb::PipelineExecutor::ExecutePushInternal(duckdb::DataChunk&, unsigned long) /home/mark/duckdb_source/src/parallel/pipeline_executor.cpp:295
    #20 0x555569ae1464 in duckdb::PipelineExecutor::Execute(unsigned long) /home/mark/duckdb_source/src/parallel/pipeline_executor.cpp:226
    #21 0x555569ae1a00 in duckdb::PipelineExecutor::Execute() /home/mark/duckdb_source/src/parallel/pipeline_executor.cpp:254
    #22 0x555569acc266 in duckdb::PipelineTask::ExecuteTask(duckdb::TaskExecutionMode) /home/mark/duckdb_source/src/parallel/pipeline.cpp:51
    #23 0x555569aafd24 in duckdb::ExecutorTask::Execute(duckdb::TaskExecutionMode) /home/mark/duckdb_source/src/parallel/executor_task.cpp:44
    #24 0x555569aee80d in duckdb::TaskScheduler::ExecuteForever(std::atomic<bool>*) /home/mark/duckdb_source/src/parallel/task_scheduler.cpp:189
    #25 0x555569aeffc8 in ThreadExecuteTasks /home/mark/duckdb_source/src/parallel/task_scheduler.cpp:279
    #26 0x555569bdd878 in void std::__invoke_impl<void, void (*)(duckdb::TaskScheduler*, std::atomic<bool>*), duckdb::TaskScheduler*, std::atomic<bool>*>(std::__invoke_other, void (*&&)(duckdb::TaskScheduler*, std::atomic<bool>*), duckdb::TaskScheduler*&&, std::atomic<bool>*&&) /usr/include/c++/11/bits/invoke.h:61
    #27 0x555569bdd63e in std::__invoke_result<void (*)(duckdb::TaskScheduler*, std::atomic<bool>*), duckdb::TaskScheduler*, std::atomic<bool>*>::type std::__invoke<void (*)(duckdb::TaskScheduler*, std::atomic<bool>*), duckdb::TaskScheduler*, std::atomic<bool>*>(void (*&&)(duckdb::TaskScheduler*, std::atomic<bool>*), duckdb::TaskScheduler*&&, std::atomic<bool>*&&) /usr/include/c++/11/bits/invoke.h:96
    #28 0x555569bdd22d in void std::thread::_Invoker<std::tuple<void (*)(duckdb::TaskScheduler*, std::atomic<bool>*), duckdb::TaskScheduler*, std::atomic<bool>*> >::_M_invoke<0ul, 1ul, 2ul>(std::_Index_tuple<0ul, 1ul, 2ul>) /usr/include/c++/11/bits/std_thread.h:259
    #29 0x555569bdbfed in std::thread::_Invoker<std::tuple<void (*)(duckdb::TaskScheduler*, std::atomic<bool>*), duckdb::TaskScheduler*, std::atomic<bool>*> >::operator()() (/home/mark/duckdb_source/build/debug/duckdb+0x14687fed)
    #30 0x555569bd76ac in std::thread::_State_impl<std::thread::_Invoker<std::tuple<void (*)(duckdb::TaskScheduler*, std::atomic<bool>*), duckdb::TaskScheduler*, std::atomic<bool>*> > >::_M_run() (/home/mark/duckdb_source/build/debug/duckdb+0x146836ac)
    #31 0x7ffff747c252  (/lib/x86_64-linux-gnu/libstdc++.so.6+0xdc252)
    #32 0x7ffff6acfac2 in start_thread nptl/pthread_create.c:442
    #33 0x7ffff6b6184f  (/lib/x86_64-linux-gnu/libc.so.6+0x12684f)

Address 0x7fffef5bc188 is located in stack of thread T3 at offset 104 in frame
    #0 0x5555677e3da1 in duckdb::TemplatedValidityMask<unsigned long>::RowIsValidUnsafe(unsigned long) const /home/mark/duckdb_source/src/include/duckdb/common/types/validity_mask.hpp:183

  This frame has 3 object(s):
    [32, 40) 'entry_idx' (line 185)
    [64, 72) 'idx_in_entry' (line 185)
    [96, 104) 'entry' (line 187) <== Memory access at offset 104 overflows this variable
HINT: this may be a false positive if your program uses some custom stack unwind mechanism, swapcontext or vfork
      (longjmp and C++ exceptions *are* supported)
Thread T3 created by T0 here:
    #0 0x7ffff7624685 in __interceptor_pthread_create ../../../../src/libsanitizer/asan/asan_interceptors.cpp:216
    #1 0x7ffff747c328 in std::thread::_M_start_thread(std::unique_ptr<std::thread::_State, std::default_delete<std::thread::_State> >, void (*)()) (/lib/x86_64-linux-gnu/libstdc++.so.6+0xdc328)
    #2 0x555569b243b9 in duckdb::TemplatedUniqueIf<std::thread, true>::templated_unique_single_t duckdb::make_uniq<std::thread, void (&)(duckdb::TaskScheduler*, std::atomic<bool>*), duckdb::TaskScheduler*, std::atomic<bool>*>(void (&)(duckdb::TaskScheduler*, std::atomic<bool>*), duckdb::TaskScheduler*&&, std::atomic<bool>*&&) (/home/mark/duckdb_source/build/debug/duckdb+0x145d03b9)
    #3 0x555569af198d in duckdb::TaskScheduler::RelaunchThreadsInternal(int) /home/mark/duckdb_source/src/parallel/task_scheduler.cpp:399
    #4 0x555569af0be2 in duckdb::TaskScheduler::RelaunchThreads() /home/mark/duckdb_source/src/parallel/task_scheduler.cpp:366
    #5 0x5555695b21cf in duckdb::DatabaseInstance::Initialize(char const*, duckdb::DBConfig*) /home/mark/duckdb_source/src/main/database.cpp:320
    #6 0x5555695b2466 in duckdb::DuckDB::DuckDB(char const*, duckdb::DBConfig*) /home/mark/duckdb_source/src/main/database.cpp:324
    #7 0x5555677db2f6 in duckdb::TemplatedUniqueIf<duckdb::DuckDB, true>::templated_unique_single_t duckdb::make_uniq<duckdb::DuckDB, char const*&, duckdb::DBConfig*>(char const*&, duckdb::DBConfig*&&) (/home/mark/duckdb_source/build/debug/duckdb+0x122872f6)
    #8 0x5555677b6e6c in duckdb_shell_sqlite3_open_v2 /home/mark/duckdb_source/tools/sqlite3_api_wrapper/sqlite3_api_wrapper.cpp:123
    #9 0x55556771bcfb in open_db /home/mark/duckdb_source/tools/shell/shell.c:14076
    #10 0x555567746869 in runOneSqlLine /home/mark/duckdb_source/tools/shell/shell.c:19266
    #11 0x555567747fda in process_input /home/mark/duckdb_source/tools/shell/shell.c:19384
    #12 0x55556774cefb in main /home/mark/duckdb_source/tools/shell/shell.c:20206
    #13 0x7ffff6a64d8f in __libc_start_call_main ../sysdeps/nptl/libc_start_call_main.h:58

SUMMARY: AddressSanitizer: stack-buffer-overflow /home/mark/duckdb_source/src/include/duckdb/common/types/validity_mask.hpp:187 in duckdb::TemplatedValidityMask<unsigned long>::RowIsValidUnsafe(unsigned long) const
Shadow bytes around the buggy address:
  0x10007deaf7e0: 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00
  0x10007deaf7f0: 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00
  0x10007deaf800: 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00
  0x10007deaf810: 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00
  0x10007deaf820: 00 00 00 00 f1 f1 f1 f1 00 f2 f2 f2 00 f2 f2 f2
=>0x10007deaf830: 00[f3]f3 f3 00 00 00 00 00 00 00 00 00 00 00 00
  0x10007deaf840: 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00
  0x10007deaf850: 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00
  0x10007deaf860: 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00
  0x10007deaf870: 00 00 00 00 00 00 00 00 00 00 00 00 00 00 f1 f1
  0x10007deaf880: f1 f1 00 f2 f2 f2 00 f2 f2 f2 00 f2 f2 f2 00 f2
Shadow byte legend (one shadow byte represents 8 application bytes):
  Addressable:           00
  Partially addressable: 01 02 03 04 05 06 07
  Heap left redzone:       fa
  Freed heap region:       fd
  Stack left redzone:      f1
  Stack mid redzone:       f2
  Stack right redzone:     f3
  Stack after return:      f5
  Stack use after scope:   f8
  Global redzone:          f9
  Global init order:       f6
  Poisoned by user:        f7
  Container overflow:      fc
  Array cookie:            ac
  Intra object redzone:    bb
  ASan internal:           fe
  Left alloca redzone:     ca
  Right alloca redzone:    cb
  Shadow gap:              cc
==32120==ABORTING
[Thread 0x7ffff05ef640 (LWP 32121) exited]
[Thread 0x7ffff6a37280 (LWP 32120) exited]
[Thread 0x7fffefdd8640 (LWP 32122) exited]
[Thread 0x7fffef5c1640 (LWP 32123) exited]
[New process 32120]
[Inferior 1 (process 32120) exited with code 01]
```

I restarted gdb again and re-ran the query:

```
Thread 2 "duckdb" received signal SIGILL, Illegal instruction.
[Switching to Thread 0x7ffff05ef640 (LWP 32222)]
0x0000555567efd1bd in std::vector<std::pair<char const*, unsigned short>, std::allocator<std::pair<char const*, unsigned short> > >::_M_realloc_insert<char const*&, unsigned short const&> (this=0x7ffff05e9c80, __position=non-dereferenceable iterator for std::vector) at /usr/include/c++/11/bits/vector.tcc:464
464                   ++__new_finish;
```

I restarted gdb again and re-ran the query:

```
  0% ▕                                                            ▏ =================================================================
==32320==ERROR: AddressSanitizer: stack-buffer-overflow on address 0x7fffffff9928 at pc 0x5555677e3f32 bp 0x7fffffff98a0 sp 0x7fffffff9890
READ of size 8 at 0x7fffffff9928 thread T0
    #0 0x5555677e3f31 in duckdb::TemplatedValidityMask<unsigned long>::RowIsValidUnsafe(unsigned long) const /home/mark/duckdb_source/src/include/duckdb/common/types/validity_mask.hpp:187
    #1 0x5555677d9052 in duckdb::TemplatedValidityMask<unsigned long>::RowIsValid(unsigned long) const /home/mark/duckdb_source/src/include/duckdb/common/types/validity_mask.hpp:196
    #2 0x5555680ef2e5 in duckdb::Vector::Verify(duckdb::Vector&, duckdb::SelectionVector const&, unsigned long) /home/mark/duckdb_source/src/common/types/vector.cpp:1453
    #3 0x5555680f0386 in duckdb::Vector::Verify(duckdb::Vector&, duckdb::SelectionVector const&, unsigned long) /home/mark/duckdb_source/src/common/types/vector.cpp:1557
    #4 0x5555680f1d67 in duckdb::Vector::Verify(duckdb::Vector&, duckdb::SelectionVector const&, unsigned long) /home/mark/duckdb_source/src/common/types/vector.cpp:1642
    #5 0x5555680f219c in duckdb::Vector::Verify(unsigned long) /home/mark/duckdb_source/src/common/types/vector.cpp:1654
    #6 0x555568038776 in duckdb::DataChunk::Verify() /home/mark/duckdb_source/src/common/types/data_chunk.cpp:361
    #7 0x555569ae7c48 in duckdb::PipelineExecutor::EndOperator(duckdb::PhysicalOperator&, duckdb::optional_ptr<duckdb::DataChunk, true>) /home/mark/duckdb_source/src/parallel/pipeline_executor.cpp:530
    #8 0x555569ae727c in duckdb::PipelineExecutor::FetchFromSource(duckdb::DataChunk&) /home/mark/duckdb_source/src/parallel/pipeline_executor.cpp:509
    #9 0x555569ae101f in duckdb::PipelineExecutor::Execute(unsigned long) /home/mark/duckdb_source/src/parallel/pipeline_executor.cpp:204
    #10 0x555569acc15f in duckdb::PipelineTask::ExecuteTask(duckdb::TaskExecutionMode) /home/mark/duckdb_source/src/parallel/pipeline.cpp:40
    #11 0x555569aafd24 in duckdb::ExecutorTask::Execute(duckdb::TaskExecutionMode) /home/mark/duckdb_source/src/parallel/executor_task.cpp:44
    #12 0x555569ac25d6 in duckdb::Executor::ExecuteTask(bool) /home/mark/duckdb_source/src/parallel/executor.cpp:580
    #13 0x55556956c43c in duckdb::ClientContext::ExecuteTaskInternal(duckdb::ClientContextLock&, duckdb::BaseQueryResult&, bool) /home/mark/duckdb_source/src/main/client_context.cpp:557
    #14 0x5555695d22ff in duckdb::PendingQueryResult::ExecuteTaskInternal(duckdb::ClientContextLock&) /home/mark/duckdb_source/src/main/pending_query_result.cpp:68
    #15 0x5555695d287b in duckdb::PendingQueryResult::ExecuteInternal(duckdb::ClientContextLock&) /home/mark/duckdb_source/src/main/pending_query_result.cpp:75
    #16 0x5555695d31b0 in duckdb::PendingQueryResult::Execute() /home/mark/duckdb_source/src/main/pending_query_result.cpp:95
    #17 0x5555695d602a in duckdb::PreparedStatement::Execute(duckdb::vector<duckdb::Value, true>&, bool) /home/mark/duckdb_source/src/main/prepared_statement.cpp:85
    #18 0x5555677ba73c in duckdb_shell_sqlite3_print_duckbox /home/mark/duckdb_source/tools/sqlite3_api_wrapper/sqlite3_api_wrapper.cpp:249
    #19 0x555567711487 in exec_prepared_stmt /home/mark/duckdb_source/tools/shell/shell.c:12752
    #20 0x555567714cda in shell_exec /home/mark/duckdb_source/tools/shell/shell.c:13087
    #21 0x555567746b2c in runOneSqlLine /home/mark/duckdb_source/tools/shell/shell.c:19273
    #22 0x555567747fda in process_input /home/mark/duckdb_source/tools/shell/shell.c:19384
    #23 0x55556774cefb in main /home/mark/duckdb_source/tools/shell/shell.c:20206
    #24 0x7ffff6a64d8f in __libc_start_call_main ../sysdeps/nptl/libc_start_call_main.h:58
    #25 0x7ffff6a64e3f in __libc_start_main_impl ../csu/libc-start.c:392
    #26 0x5555676aec84 in _start (/home/mark/duckdb_source/build/debug/duckdb+0x1215ac84)

Address 0x7fffffff9928 is located in stack of thread T0 at offset 104 in frame
    #0 0x5555677e3da1 in duckdb::TemplatedValidityMask<unsigned long>::RowIsValidUnsafe(unsigned long) const /home/mark/duckdb_source/src/include/duckdb/common/types/validity_mask.hpp:183

  This frame has 3 object(s):
    [32, 40) 'entry_idx' (line 185)
    [64, 72) 'idx_in_entry' (line 185)
    [96, 104) 'entry' (line 187) <== Memory access at offset 104 overflows this variable
HINT: this may be a false positive if your program uses some custom stack unwind mechanism, swapcontext or vfork
      (longjmp and C++ exceptions *are* supported)
SUMMARY: AddressSanitizer: stack-buffer-overflow /home/mark/duckdb_source/src/include/duckdb/common/types/validity_mask.hpp:187 in duckdb::TemplatedValidityMask<unsigned long>::RowIsValidUnsafe(unsigned long) const
Shadow bytes around the buggy address:
  0x10007fff72d0: 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00
  0x10007fff72e0: 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00
  0x10007fff72f0: 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00
  0x10007fff7300: 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00
  0x10007fff7310: 00 00 00 00 00 00 00 00 f1 f1 f1 f1 00 f2 f2 f2
=>0x10007fff7320: 00 f2 f2 f2 00[f3]f3 f3 00 00 00 00 00 00 00 00
  0x10007fff7330: 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00
  0x10007fff7340: 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00
  0x10007fff7350: 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00
  0x10007fff7360: 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00
  0x10007fff7370: 00 00 f1 f1 f1 f1 00 f2 f2 f2 00 f2 f2 f2 00 f2
Shadow byte legend (one shadow byte represents 8 application bytes):
  Addressable:           00
  Partially addressable: 01 02 03 04 05 06 07
  Heap left redzone:       fa
  Freed heap region:       fd
  Stack left redzone:      f1
  Stack mid redzone:       f2
  Stack right redzone:     f3
  Stack after return:      f5
  Stack use after scope:   f8
  Global redzone:          f9
  Global init order:       f6
  Poisoned by user:        f7
  Container overflow:      fc
  Array cookie:            ac
  Intra object redzone:    bb
  ASan internal:           fe
  Left alloca redzone:     ca
  Right alloca redzone:    cb
  Shadow gap:              cc
==32320==ABORTING
[Thread 0x7fffefdd8640 (LWP 32324) exited]
[Thread 0x7ffff6a37280 (LWP 32320) exited]
[Thread 0x7ffff05ef640 (LWP 32323) exited]
[Thread 0x7fffef5c1640 (LWP 32325) exited]
[New process 32320]
[Inferior 1 (process 32320) exited with code 01]
```

**Comment by marklit** [comment]
I built a new AMD Ryzen 9 9950X CPU machine to get away from the instability issues I was having with the 14900K.

As a last throw of the dice, I updated the BIOS on my ASRock Z790 Pro RS WiFi Motherboard my 14900K lives on to version 14.02 which was released on 2025/1/15. The crashing symptoms I had in Windows 11 went away. For instance, in the past year I couldn't scroll my LinkedIn feed without it crashing. Now I can scroll the feed without issue.

I tested the query at the top of this issue with DuckDB v1.1.3 and it brought up the same error.

I then installed DuckDB v1.2.1 and it runs without issue.
