### ISSUE TITLE
Nested Structs with Many Keys Cast as JSON and Converted to String in Parquet Output

### ISSUE THREAD

**Issue by maitlandmarshall** [duckdb/duckdb#13734]
### What happens?

**Description:**
I've encountered an issue with DuckDB when handling nested structs with a large number of unique keys. It appears that DuckDB automatically interprets these nested structs as JSON, which results in the column being cast as a `STRING` when the data is written to Parquet. This behavior seems to occur once the number of different keys in the struct exceeds a certain threshold.

I've attached a json file which reproduces this behaviour when queried.
[fragment=0.json](https://github.com/user-attachments/files/16866244/fragment.0.json)

**Expected Behavior:**
The `data` column should retain its nested struct format and not be automatically cast as the JSON data type. This would fix parquet from serializing the data column as a json serialized string.

**Actual Behavior:**
The `data` column is cast as a `STRING` in the Parquet output and as JSON in duckdb.

**Additional Context:**
- This issue seems to arise when the nested struct contains a large number of unique keys.
- The cutoff point for when DuckDB starts interpreting the struct as JSON is unclear, but it seems to be related to the number of keys.

### To Reproduce

1. Generate a nested struct with a significant number of unique keys (e.g., 100 keys).
2. Create multiple rows with these nested structs.
3. DESCRIBE query the file with duckdb

![image](https://github.com/user-attachments/assets/143f0cee-87d5-4665-9332-2accd2430b4b)

**Code Example:**
```python
async def test_nested_structs_with_many_keys_should_not_cast_to_string():
    def generate_unique_dict(keys):
        return {f"{key}@somewhere.com": ["creator", "editor"] for key in keys}

    def generate_random_keys(count):
        return [
            "".join(random.choices(string.ascii_lowercase + string.digits, k=10))
            for _ in range(count)
        ]

    def generate_rows(num_rows):
        rows = []
        for i in range(num_rows):
            keys = generate_random_keys(100)
            rows.append(
                {
                    "id": str(i + 1),
                    "data": generate_unique_dict(keys),
                }
            )
        return rows

    @asset("dict_array_asset_1.parquet")
    async def dict_array_asset_1():
        yield generate_rows(50)
        yield generate_rows(50)

    # Query the composed asset to check its contents
    composed_query = await dict_array_asset_1.query("SELECT * FROM dict_array_asset_1")

    assert composed_query

    # The second column is named data
    assert composed_query.description[1][0] == "data"

    # And it not a string type
    assert composed_query.description[1][1] != "STRING"
```

### OS:

amd64

### DuckDB Version:

1.0.0

### DuckDB Client:

Python

### Full Name:

Maitland Marshall

### Affiliation:

MAIT DEV

### What is the latest build you tested with? If possible, we recommend testing with the latest nightly build.

I have tested with a stable release

### Did you include all relevant data sets for reproducing the issue?

Yes

### Did you include all code required to reproduce the issue?

- [x] Yes, I have

### Did you include all relevant configuration (e.g., CPU architecture, Python version, Linux distribution) to reproduce the issue?

- [x] Yes, I have

**Comment by szarnyasg** [comment]
Hi @maitlandmarshall, thanks for opening this issue. Can you please turn the code snippet into a self-contained script that I can re-run? Thanks!

**Comment by maitlandmarshall** [comment]
Hey @szarnyasg, no worries. If you place this script and [fragment=0.json](https://github.com/user-attachments/files/16874051/fragment.0.json) inside the same cwd it should replicate the isuse.

```python
import duckdb


def demo_issue():
    struct_json = duckdb.query("SELECT * FROM 'fragment=0.json'")

    # Type is picked up as a JSON instead of a struct or map
    assert struct_json.description[1][0] == "data"
    assert struct_json.description[1][1] == "JSON"
    
    # When copied to parquet, it causes the field to be serialized as a json string instead of a struct
    duckdb.query("COPY struct_json to 'output.parquet'")
    query = duckdb.query("SELECT * FROM 'output.parquet'")
    
    assert query.description[1][0] == "data"
    assert query.description[1][1] != "STRING"
    
if __name__ == "__main__":
    demo_issue()
```

**Comment by maitlandmarshall** [comment]
Let me know if I can help out any further. I have developed a partial columns= api to work around this, allowing me to override the columns types inferred by duckdb after read_json_auto:

```python
def _create_query(self, globs: list[str], filetype: ARTIFACT_FILE_TYPES):
        artifact_base_query: str

        if filetype == "json":
            artifact_base_query = f"SELECT * FROM read_json_auto({globs}, hive_partitioning = true, union_by_name = true, maximum_object_size = 33554432)"
        elif filetype == "parquet":
            # Parquet's columns cannot be provided while reading like json,
            # as parquet stores column data type metadata already
            return duckdb.query(
                f"SELECT * FROM read_parquet({globs}, hive_partitioning = true, union_by_name = true)"
            )
        else:
            raise ValueError(f"Unsupported file format {self.filetype}")

        # If the artifact has been provided columns, we override the default
        # auto-detected duckdb columns with any provided
        duckdb_columns_map = ""
        if self.columns:
            asset_query_describe = duckdb.query(f"DESCRIBE {artifact_base_query}")
            asset_query_schema = asset_query_describe.fetchall()

            # Convert the describe query into a dict of { column: {describe row} }
            asset_query_schema = {
                tuple[0]: dict(zip(asset_query_describe.columns, tuple))
                for tuple in asset_query_schema
            }

            # Loop through each supplied column and override the existing data type
            for col_name, new_col_type in self.columns.items():
                existing_col = asset_query_schema.get(col_name, None)

                if not existing_col:
                    raise ValueError(f"Column {col_name} not found in artifact schema")

                existing_col["column_type"] = new_col_type

            # Convert the new columns into a map format as duckdb expects
            duckdb_columns_dict = {
                col_name: col_type
                for col_name, col_data in asset_query_schema.items()
                for col_type in [col_data["column_type"]]
            }

            duckdb_columns_map = f"{duckdb_columns_dict}"

        # If we had a new map, let's insert that into our query
        if duckdb_columns_map:
            if filetype == "json":
                artifact_base_query = f"SELECT * FROM read_json({globs}, format='auto', columns={duckdb_columns_map}, hive_partitioning = true, union_by_name = true, maximum_object_size = 33554432)"
            else:
                raise ValueError(f"Unsupported file format {self.filetype}")

        artifact_query = duckdb.query(artifact_base_query)
        return artifact_query
```

**Comment by szarnyasg** [comment]
Hi @maitlandmarshall thanks for getting back with an example. With DuckDB 1.0.0, I can reproduce

```console
Traceback (most recent call last):
  File "/Users/gabor/Downloads/my.py", line 20, in <module>
    demo_issue()
  File "/Users/gabor/Downloads/my.py", line 17, in demo_issue
    assert query.description[1][1] != "STRING"
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
```

However, with 1.1.0 (that was just released today), I get:

```console
Traceback (most recent call last):
  File "/Users/gabor/Downloads/my.py", line 20, in <module>
    demo_issue()
  File "/Users/gabor/Downloads/my.py", line 10, in demo_issue
    assert struct_json.description[1][1] == "JSON"
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
AssertionError
```

**Comment by lnkuiper** [comment]
DuckDB 1.1.0 now reads this as `id VARCHAR, data MAP(VARCHAR, VARCHAR[]`. If you read it like so, you can force DuckDB to read `data` as a _really large struct_:
```sql
from read_json('~/Downloads/fragment.0.json', field_appearance_threshold=0, map_inference_threshold=-1);
```

**Comment by maitlandmarshall** [comment]
Thank you, this is fixed now!
