### ISSUE TITLE
Arrow datatype Extension("arrow.json", Utf8, Some("")) not supported by Polars exception

### ISSUE THREAD

**Issue by OneCyrus** [duckdb/duckdb#13967]
### What happens?

with duckdb 1.1.0 I get the following error when selecting over a json file. multiple different json files. also some json files work.

`pyo3_runtime.PanicException: Arrow datatype Extension("arrow.json", Utf8, Some("")) not supported by Polars. You probably need to activate that data-type feature.`

with duckdb 1.0.0 everything works fine

### To Reproduce

connect(":memory:").sql("SELECT unnest(entry, recursive := true) FROM read_json_auto('s3://mybucket/test.json', filename=true)").pl()

### OS:

Ubuntu 22.04

### DuckDB Version:

1.1.0

### DuckDB Client:

Python

### Full Name:

Daniel Gut

### Affiliation:

Aveniq

### What is the latest build you tested with? If possible, we recommend testing with the latest nightly build.

I have tested with a stable release

### Did you include all relevant data sets for reproducing the issue?

No - I cannot share the data sets because they are confidential

### Did you include all code required to reproduce the issue?

- [ ] Yes, I have

### Did you include all relevant configuration (e.g., CPU architecture, Python version, Linux distribution) to reproduce the issue?

- [X] Yes, I have

**Comment by szarnyasg** [comment]
Hi @OneCyrus, thanks for reporting this issue. Is there a chance you can reduce the confidential data set to a non-confidential reproducer? That would go help a lot in getting this resolved.

**Comment by OneCyrus** [comment]
@szarnyasg looks like the issue is with the null property.

i reduced the dataset to the following:

```
{
    "entry": [
        {
            "content": {
                "ManagedSystem": {
                    "test": null
                }
            }
        }
    ]
}
```

```
from duckdb import connect

db = connect(":memory:")
test = db.sql(
    "SELECT entry FROM read_json_auto('test.json', filename=true)"
).pl()
```

**Comment by Tishj** [comment]
Thanks, what's the Polars version?

**Comment by Tishj** [comment]
I can reproduce it (sort of) 👍 

```
➜  duckdb git:(main) ✗ python3 tmp/polars_json2.py
thread '<unnamed>' panicked at crates/polars-core/src/datatypes/field.rs:189:19:
Arrow datatype Extension("arrow.json", Utf8, Some("")) not supported by Polars. You probably need to activate that data-type feature.
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
Traceback (most recent call last):
  File "/Users/thijs/DuckDBLabs/duckdb/tmp/polars_json2.py", line 6, in <module>
    ).pl()
      ^^^^
  File "/Users/thijs/.pyenv/versions/3.12.1/lib/python3.12/site-packages/polars/dataframe/frame.py", line 394, in __init__
    self._df = arrow_to_pydf(
               ^^^^^^^^^^^^^^
  File "/Users/thijs/.pyenv/versions/3.12.1/lib/python3.12/site-packages/polars/_utils/construction/dataframe.py", line 1209, in arrow_to_pydf
    pydf = PyDataFrame.from_arrow_record_batches(tbl.to_batches())
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
pyo3_runtime.PanicException: Arrow datatype Extension("arrow.json", Utf8, Some("")) not supported by Polars. You probably need to activate that data-type feature.
```

```
>>> import polars
>>> polars.__version__
'1.5.0'
```

**Comment by OneCyrus** [comment]
also i have encountered a similiar issue where it tries to find arrow.uuid. probably the same issue where a property is resolved to an uuid. so far i have no dataset which is easy reproducible.

**Comment by OneCyrus** [comment]
@Tishj ok, got a reproduction with an empty object

```
[
    {
        "ipspace": {
            "_links": {}
        }
    }
]
```

```
thread 'polars-0' panicked at crates/polars-core/src/datatypes/field.rs:188:19:
Arrow datatype Map(Field { name: "entries", dtype: Struct([Field { name: "key", dtype: Utf8, is_nullable: false, metadata: {} }, Field { name: "value", dtype: Utf8, is_nullable: true, metadata: {} }]), is_nullable: false, metadata: {} }, false) not supported by Polars. You probably need to activate that data-type feature.
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
Traceback (most recent call last):
  File "test.py", line 6, in <module>
    ).pl()
      ^^^^
  File "/workspaces/automation-data/.venv/lib/python3.11/site-packages/polars/dataframe/frame.py", line 395, in __init__
    self._df = arrow_to_pydf(
               ^^^^^^^^^^^^^^
  File "/workspaces/automation-data/.venv/lib/python3.11/site-packages/polars/_utils/construction/dataframe.py", line 1209, in arrow_to_pydf
    pydf = PyDataFrame.from_arrow_record_batches(tbl.to_batches())
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
pyo3_runtime.PanicException: Arrow datatype Map(Field { name: "entries", dtype: Struct([Field { name: "key", dtype: Utf8, is_nullable: false, metadata: {} }, Field { name: "value", dtype: Utf8, is_nullable: true, metadata: {} }]), is_nullable: false, metadata: {} }, false) not supported by Polars. You probably need to activate that data-type feature.
```
