### ISSUE TITLE
DuckDB Assertion Error: !distinct.target_distincts.empty()

### ISSUE THREAD

**Issue by SteveLeungYL** [duckdb/duckdb#15199]
### What happens?

The latest version of the DuckDB (latest main: v1.1.4-dev2916 9da182a939) triggers Assertion Failure when running the following SQL statement: 

```sql
SET order_by_non_integer_literal=true;
CREATE TABLE v00 (c01 INT);
SELECT ALL ( SELECT DISTINCT ON ( 'string') 'string' AS c02 GROUP BY ( ), WINDOW window_name AS ( PARTITION BY c01 ) );
```

Stacktrace from the latest main (9da182a939): 

```
#0  duckdb::InternalException::InternalException (this=0x60d000008fc0, Python Exception <class 'gdb.error'> There is no member named _M_dataplus.: 
msg=) at /home/duckdb/duckdb/src/common/exception.cpp:333
#1  0x000000000202bcca in duckdb::InternalException::InternalException<char const*, int, char const*, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > > (this=0x60d000008fc0, msg=..., params=<incomplete type>, params=<incomplete type>, params=<incomplete type>, 
    params=<incomplete type>) at ../../src/include/duckdb/common/exception.hpp:313
#2  0x0000000001de5530 in duckdb::DuckDBAssertInternal (condition=<optimized out>, condition_name=<optimized out>, file=<optimized out>, 
    linenr=<optimized out>) at /home/duckdb/duckdb/src/common/assert.cpp:13
#3  0x000000000ac5cd5f in duckdb::Binder::BindModifiers (this=0x61900000b490, result=..., table_index=<optimized out>, names=..., sql_types=..., 
    bind_state=...) at /home/duckdb/duckdb/src/planner/binder/query_node/bind_select_node.cpp:313
#4  0x000000000ac70e59 in duckdb::Binder::BindSelectNode (this=0x61900000b480, statement=..., from_table=...)
    at /home/duckdb/duckdb/src/planner/binder/query_node/bind_select_node.cpp:681
#5  0x000000000ac626d5 in duckdb::Binder::BindNode (this=<optimized out>, statement=...)
    at /home/duckdb/duckdb/src/planner/binder/query_node/bind_select_node.cpp:373
#6  0x0000000005ef101d in duckdb::Binder::BindNode (this=0x61900000b480, node=...) at /home/duckdb/duckdb/src/planner/binder.cpp:328
#7  0x000000000594a89c in duckdb::ExpressionBinder::BindExpression (this=0x7ffc40ed86b0, expr=..., depth=<optimized out>)
    at /home/duckdb/duckdb/src/planner/binder/expression/bind_subquery_expression.cpp:46
#8  0x0000000005ebeed5 in duckdb::ExpressionBinder::BindExpression (this=0x7ffc40ed86b0, expr=..., depth=<optimized out>, root_expression=<optimized out>)
    at /home/duckdb/duckdb/src/planner/expression_binder.cpp:96
#9  0x0000000005d2b387 in duckdb::BaseSelectBinder::BindExpression (this=0x7ffc40ed86b0, expr_ptr=..., depth=<optimized out>, 
    root_expression=<optimized out>) at /home/duckdb/duckdb/src/planner/expression_binder/base_select_binder.cpp:38
#10 0x0000000005ec4408 in duckdb::ExpressionBinder::Bind (this=0x7ffc40ed86b0, expr=..., depth=<optimized out>, root_expression=<optimized out>)
    at /home/duckdb/duckdb/src/planner/expression_binder.cpp:365
#11 0x0000000005ec605f in duckdb::ExpressionBinder::BindChild (this=0x7ffc40ed86b0, expr=..., depth=<optimized out>, error=...)
    at /home/duckdb/duckdb/src/planner/expression_binder.cpp:223
#12 0x000000000590c6e6 in duckdb::ExpressionBinder::BindExpression (this=0x7ffc40ed86b0, op=..., depth=<optimized out>)
    at /home/duckdb/duckdb/src/planner/binder/expression/bind_operator_expression.cpp:96
#13 0x0000000005ebf0db in duckdb::ExpressionBinder::BindExpression (this=0x7ffc40ed86b0, expr=..., depth=<optimized out>, root_expression=<optimized out>)
    at /home/duckdb/duckdb/src/planner/expression_binder.cpp:94
#14 0x0000000005d2b387 in duckdb::BaseSelectBinder::BindExpression (this=0x7ffc40ed86b0, expr_ptr=..., depth=<optimized out>, 
    root_expression=<optimized out>) at /home/duckdb/duckdb/src/planner/expression_binder/base_select_binder.cpp:38
#15 0x0000000005ec4408 in duckdb::ExpressionBinder::Bind (this=0x7ffc40ed86b0, expr=..., depth=<optimized out>, root_expression=<optimized out>)
    at /home/duckdb/duckdb/src/planner/expression_binder.cpp:365
#16 0x0000000005ecac7e in duckdb::ExpressionBinder::Bind (this=<optimized out>, expr=..., result_type=..., root_expression=<optimized out>)
    at /home/duckdb/duckdb/src/planner/expression_binder.cpp:317
#17 0x000000000ac6acab in duckdb::Binder::BindSelectNode (this=0x61900000af80, statement=..., from_table=...)
    at /home/duckdb/duckdb/src/planner/binder/query_node/bind_select_node.cpp:555
#18 0x000000000ac626d5 in duckdb::Binder::BindNode (this=<optimized out>, statement=...)
    at /home/duckdb/duckdb/src/planner/binder/query_node/bind_select_node.cpp:373
#19 0x0000000005ef101d in duckdb::Binder::BindNode (this=0x61900000af80, node=...) at /home/duckdb/duckdb/src/planner/binder.cpp:328
#20 0x0000000005ef2586 in duckdb::Binder::Bind (this=0x61900000af80, node=...) at /home/duckdb/duckdb/src/planner/binder.cpp:365
#21 0x00000000059f8678 in duckdb::Binder::Bind (this=0x61900000af80, stmt=...) at /home/duckdb/duckdb/src/planner/binder/statement/bind_select.cpp:11
#22 0x0000000005ee5e0d in duckdb::Binder::Bind (this=<optimized out>, statement=...) at /home/duckdb/duckdb/src/planner/binder.cpp:150
#23 0x0000000005f3a3bc in duckdb::Planner::CreatePlan (this=0x7ffc40ed9ff0, statement=...) at /home/duckdb/duckdb/src/planner/planner.cpp:43
#24 0x0000000005f43543 in duckdb::Planner::CreatePlan (this=0x60d000008fc0, statement=...) at /home/duckdb/duckdb/src/planner/planner.cpp:142
#25 0x00000000033b22bc in duckdb::ClientContext::CreatePreparedStatementInternal (this=0x616000074490, lock=..., query=..., statement=..., values=...)
    at /home/duckdb/duckdb/src/main/client_context.cpp:340
#26 0x00000000033b8884 in duckdb::ClientContext::CreatePreparedStatement (this=0x616000074490, lock=..., query=..., statement=..., values=..., 
    mode=<optimized out>) at /home/duckdb/duckdb/src/main/client_context.cpp:426
#27 0x00000000033da8ea in duckdb::ClientContext::PendingStatementInternal (this=0x616000074490, lock=..., query=..., statement=..., parameters=...)
    at /home/duckdb/duckdb/src/main/client_context.cpp:745
#28 0x00000000033e7514 in duckdb::ClientContext::PendingStatementOrPreparedStatement (this=0x616000074490, lock=..., query=..., statement=..., 
--Type <RET> for more, q to quit, c to continue without paging--
    prepared=..., parameters=...) at /home/duckdb/duckdb/src/main/client_context.cpp:863
#29 0x00000000033d5ff8 in duckdb::ClientContext::PendingStatementOrPreparedStatementInternal (this=0x616000074490, lock=..., query=..., statement=..., 
    prepared=..., parameters=...) at /home/duckdb/duckdb/src/main/client_context.cpp:837
#30 0x00000000033ddd4b in duckdb::ClientContext::PendingQueryInternal (this=0x616000074490, lock=..., statement=..., parameters=..., verify=<optimized out>)
    at /home/duckdb/duckdb/src/main/client_context.cpp:1054
#31 0x00000000033f3e0e in duckdb::ClientContext::PendingQuery (this=0x616000074490, statement=..., values=..., allow_stream_result=<optimized out>)
    at /home/duckdb/duckdb/src/main/client_context.cpp:1041
#32 0x00000000033eb320 in duckdb::ClientContext::PendingQuery (this=0x616000074490, statement=..., allow_stream_result=<optimized out>)
    at /home/duckdb/duckdb/src/main/client_context.cpp:1001
#33 0x000000000343a1d8 in duckdb::Connection::PendingQuery (this=<optimized out>, statement=..., allow_stream_result=<optimized out>)
    at /home/duckdb/duckdb/src/main/connection.cpp:140
#34 0x0000000000704784 in duckdb_shell_sqlite3_prepare_v2 (db=0x60f0000006d0, zSql=<optimized out>, nByte=<optimized out>, ppStmt=<optimized out>, 
    pzTail=<optimized out>) at ../../tools/sqlite3_api_wrapper/sqlite3_api_wrapper.cpp:224
#35 0x000000000066cab6 in duckdb_shell::ShellState::ExecuteSQL (this=0x7ffc40edc6a0, 
    zSql=0x60d000000d40 "SELECT 'string' <= ALL ( SELECT DISTINCT ON ( 'string') 'string' AS c02 GROUP BY ( ), WINDOW window_name AS ( PARTITION BY c01 ) );", pzErrMsg=<optimized out>) at ../../tools/shell/shell.cpp:3524
#36 0x0000000000698023 in duckdb_shell::ShellState::RunOneSqlLine (this=<optimized out>, zSql=<optimized out>) at ../../tools/shell/shell.cpp:8706
#37 0x000000000068d610 in duckdb_shell::ShellState::ProcessInput (this=0x7ffc40edc6a0) at ../../tools/shell/shell.cpp:8936
#38 0x000000000069e28d in main (argc=<optimized out>, argv=<optimized out>) at ../../tools/shell/shell.cpp:10152
```

### To Reproduce

1. Clone the DuckDB Git from the official repo.
2. Checkout to the latest main (9da182a939).
3. Compile the DuckDB binary by using `make relassert`. Assertion is necessary here. 
4. Run the compiled DuckDB and input the following SQL:

```sql
SET order_by_non_integer_literal=true;
CREATE TABLE v00 (c01 INT);
SELECT ALL ( SELECT DISTINCT ON ( 'string') 'string' AS c02 GROUP BY ( ), WINDOW window_name AS ( PARTITION BY c01 ) );
```

### OS:

Ubuntu 24.04 LTS

### DuckDB Version:

9da182a939

### DuckDB Client:

cli

### Full Name:

Yu Liang

### Affiliation:

The Pennsylvania State University

### What is the latest build you tested with? If possible, we recommend testing with the latest nightly build.

I have tested with a stable release

### Did you include all relevant data sets for reproducing the issue?

Yes

### Did you include all code required to reproduce the issue?

- [X] Yes, I have

### Did you include all relevant configuration (e.g., CPU architecture, Python version, Linux distribution) to reproduce the issue?

- [X] Yes, I have

**Comment by szarnyasg** [comment]
Thanks, I could reproduce this on the latest main on Linux (aarch64):

```
ubuntu@ip-172-31-19-0:~/duckdb$ build/relassert/duckdb
v1.1.4-dev3069 c4a286b642
Enter ".help" for usage hints.
Connected to a transient in-memory database.
Use ".open FILENAME" to reopen on a persistent database.
D SET order_by_non_integer_literal=true;
D CREATE TABLE v00 (c01 INT);
D SELECT ALL ( SELECT DISTINCT ON ( 'string') 'string' AS c02 GROUP BY ( ), WINDOW window_name AS ( PARTITION BY c01 ) );
INTERNAL Error:
Assertion triggered in file "/home/ubuntu/duckdb/src/planner/binder/query_node/bind_select_node.cpp" on line 313: !distinct.target_distincts.empty()
This error signals an assertion failure within DuckDB. This usually occurs due to unexpected conditions or errors in the program's logic.
For more information, see https://duckdb.org/docs/dev/internal_errors
```

**Comment by szarnyasg** [comment]
Also reproduce on macOS now:

```
build/relassert/duckdb
duckdb(55563,0x1eb3ef840) malloc: nano zone abandoned due to inability to reserve vm space.
-- Loading resources from /Users/szarnyasg/.duckdbrc
v1.1.3-dev3234 c4a286b642
Enter ".help" for usage hints.
Connected to a transient in-memory database.
Use ".open FILENAME" to reopen on a persistent database.
D pragma platform;
┌───────────┐
│ platform  │
│  varchar  │
├───────────┤
│ osx_arm64 │
└───────────┘
Run Time (s): real 0.006 user 0.002569 sys 0.003481
D SET order_by_non_integer_literal=true;
Run Time (s): real 0.004 user 0.003207 sys 0.000995
D CREATE TABLE v00 (c01 INT);
Run Time (s): real 0.004 user 0.002694 sys 0.001302
D SELECT ALL ( SELECT DISTINCT ON ( 'string') 'string' AS c02 GROUP BY ( ), WINDOW window_name AS ( PARTITION BY c01 ) );
Run Time (s): real 0.004 user 0.002468 sys 0.001449
INTERNAL Error:
Assertion triggered in file "/Users/szarnyasg/git/duckdb/src/planner/binder/query_node/bind_select_node.cpp" on line 313: !distinct.target_distincts.empty()
This error signals an assertion failure within DuckDB. This usually occurs due to unexpected conditions or errors in the program's logic.
For more information, see https://duckdb.org/docs/dev/internal_errors
```
