### ISSUE TITLE
DuckDB Internal Error: Attempted to dereference unique_ptr that is NULL!

### ISSUE THREAD

**Issue by SteveLeungYL** [duckdb/duckdb#15195]
### What happens?

The latest version of the DuckDB (latest main: v1.1.4-dev3057 1db3def66e and released version: v1.1.3 19864453f7) triggers Internal Error when running the following SQL statement: 

```sql
CREATE TABLE t0 AS SELECT 'string';
INSERT INTO t0 BY NAME DEFAULT VALUES ON CONFLICT DO UPDATE SET any_name = any_name WHERE 'any_string' NOT IN CASE WHEN any_name THEN any_name END;
```

Backtrace from v1.1.4-dev3057 1db3def66e:

```
#0  duckdb::InternalException::InternalException (this=0x3719a3e0, Python Exception <class 'gdb.error'> There is no member named _M_dataplus.:
msg=) at /home/duckdb/duckdb/src/common/exception.cpp:333
#1  0x00000000005d6890 in duckdb::unique_ptr<duckdb::SelectStatement, std::default_delete<duckdb::SelectStatement>, true>::AssertNotNull (
    null=<optimized out>) at ../../src/include/duckdb/common/unique_ptr.hpp:25
#2  0x0000000002687870 in duckdb::unique_ptr<duckdb::SelectStatement, std::default_delete<duckdb::SelectStatement>, true>::operator* (this=0x370b1c78)
    at ../../src/include/duckdb/common/unique_ptr.hpp:34
#3  duckdb::Binder::Bind (this=0x370b07e0, stmt=...) at /home/duckdb/duckdb/src/planner/binder/statement/bind_insert.cpp:504
#4  0x000000000294b19c in duckdb::Binder::BindWithCTE<duckdb::InsertStatement> (this=0x370b07e0, statement=...)
    at /home/duckdb/duckdb/src/planner/binder.cpp:141
#5  0x00000000028f0314 in duckdb::Binder::Bind (this=0x370b07e0, statement=...) at /home/duckdb/duckdb/src/planner/binder.cpp:152
#6  0x00000000029203c0 in duckdb::Planner::CreatePlan (this=0xfffff317d360, statement=...) at /home/duckdb/duckdb/src/planner/planner.cpp:43
#7  0x0000000001890fc8 in duckdb::ClientContext::CreatePreparedStatementInternal (this=<optimized out>, lock=..., Python Exception <class 'gdb.error'> There is no member named _M_dataplus.:
query=, statement=..., values=...)
    at /home/duckdb/duckdb/src/main/client_context.cpp:340
#8  0x0000000001895214 in duckdb::ClientContext::CreatePreparedStatement (this=<optimized out>, lock=..., Python Exception <class 'gdb.error'> There is no member named _M_dataplus.:
query=, statement=..., values=...,
    mode=duckdb::PreparedStatementMode::PREPARE_AND_EXECUTE) at /home/duckdb/duckdb/src/main/client_context.cpp:426
#9  0x00000000018ab804 in duckdb::ClientContext::PendingStatementInternal (this=0x36f15640, lock=..., Python Exception <class 'gdb.error'> There is no member named _M_dataplus.:
query=, statement=..., parameters=...)
    at /home/duckdb/duckdb/src/main/client_context.cpp:745
#10 0x00000000018b50d0 in duckdb::ClientContext::PendingStatementOrPreparedStatement (this=<optimized out>, lock=..., Python Exception <class 'gdb.error'> There is no member named _M_dataplus.:
query=, statement=..., prepared=...,
    parameters=...) at /home/duckdb/duckdb/src/main/client_context.cpp:863
#11 0x00000000018a93d4 in duckdb::ClientContext::PendingStatementOrPreparedStatementInternal (this=0x36f15640, lock=..., Python Exception <class 'gdb.error'> There is no member named _M_dataplus.:
query=, statement=...,
    prepared=..., parameters=...) at /home/duckdb/duckdb/src/main/client_context.cpp:837
#12 0x00000000018adc34 in duckdb::ClientContext::PendingQueryInternal (this=0x36f15640, lock=..., statement=..., parameters=..., verify=<optimized out>)
    at /home/duckdb/duckdb/src/main/client_context.cpp:1054
#13 0x00000000018be110 in duckdb::ClientContext::PendingQuery (this=0x36f15640, statement=..., values=std::unordered_map with 0 elements,
    allow_stream_result=<optimized out>) at /home/duckdb/duckdb/src/main/client_context.cpp:1041
#14 0x00000000018b7dfc in duckdb::ClientContext::PendingQuery (this=0x2ad8, statement=..., allow_stream_result=false)
    at /home/duckdb/duckdb/src/main/client_context.cpp:1001
#15 0x00000000018ec7d4 in duckdb::Connection::PendingQuery (this=<optimized out>, statement=..., allow_stream_result=false)
    at /home/duckdb/duckdb/src/main/connection.cpp:140
#16 0x00000000004b40f0 in duckdb_shell_sqlite3_prepare_v2 (db=0x36e73b80, zSql=<optimized out>, nByte=<optimized out>, ppStmt=<optimized out>,
    pzTail=<optimized out>) at ../../tools/sqlite3_api_wrapper/sqlite3_api_wrapper.cpp:224
#17 0x000000000046f9dc in duckdb_shell::ShellState::ExecuteSQL (this=<optimized out>,
    zSql=0x370c13c0 "INSERT INTO t0 BY NAME DEFAULT VALUES ON CONFLICT DO UPDATE SET any_name = any_name WHERE 'any_string' NOT IN CASE WHEN any_name THEN any_name END;", pzErrMsg=<optimized out>) at ../../tools/shell/shell.cpp:1762
#18 0x0000000000485b74 in duckdb_shell::ShellState::RunOneSqlLine (this=0xfffff317e618,
    zSql=0x370c13c0 "INSERT INTO t0 BY NAME DEFAULT VALUES ON CONFLICT DO UPDATE SET any_name = any_name WHERE 'any_string' NOT IN CASE WHEN any_name THEN any_name END;") at ../../tools/shell/shell.cpp:4353
#19 0x0000000000480480 in duckdb_shell::ShellState::ProcessInput (this=<optimized out>) at ../../tools/shell/shell.cpp:4468
#20 0x0000000000489dac in main (argc=1, argv=0xfffff317e968) at ../../tools/shell/shell.cpp:5076
```

### To Reproduce

1. Clone the DuckDB Git from the official repo.
2. Checkout to the latest main (1db3def66e).
3. Compile the DuckDB binary by using `make relassert`.
4. Run the compiled DuckDB and input the following SQL:

```sql
CREATE TABLE t0 AS SELECT 'string';
INSERT INTO t0 BY NAME DEFAULT VALUES ON CONFLICT DO UPDATE SET any_name = any_name WHERE 'any_string' NOT IN CASE WHEN any_name THEN any_name END;
```

### OS:

Ubuntu 24.04 LTS

### DuckDB Version:

1.1.3 and latest main: 1db3def66e

### DuckDB Client:

cli

### Full Name:

Yu Liang

### Affiliation:

Pennsylvania State University

### What is the latest build you tested with? If possible, we recommend testing with the latest nightly build.

I have tested with a stable release

### Did you include all relevant data sets for reproducing the issue?

Yes

### Did you include all code required to reproduce the issue?

- [X] Yes, I have

### Did you include all relevant configuration (e.g., CPU architecture, Python version, Linux distribution) to reproduce the issue?

- [X] Yes, I have

**Comment by szarnyasg** [comment]
Thanks for both new issues, I could reproduce them! We'll take a look.
