### ISSUE TITLE
DuckDB Internal Error: Attempting to dereference an optional pointer that is not set

### ISSUE THREAD

**Issue by SteveLeungYL** [duckdb/duckdb#15205]
### What happens?

The latest version of the DuckDB (latest main: v1.1.4-dev3057 1db3def66e) triggers Internal Error when running the following SQL statement: 

```sql
CREATE TABLE v00 (c01 INT, c02 STRING);
PIVOT_WIDER ident : ( ( v00 AS ta29401 INNER JOIN 'string' : ( ( v00 AS ta10600 INNER JOIN v00 AS ta10601 USING ( c02, c01, ) ) ta10602 ANTI JOIN v00 AS ta52101 USING ( c02, c01 ) ) USING ( c01, ) ) ) SEMI JOIN v00 AS ta1901 USING ( c02, c01, ) NATURAL JOIN v00 AS ta35101 USING 'string' GROUP BY c02, c01 ORDER BY ALL ASC FOR READ ONLY;
```

Stacktrace for the latest main (1db3def66e):

```
#0  duckdb::InternalException::InternalException (this=0x426abb40, Python Exception <class 'gdb.error'> There is no member named _M_dataplus.:
msg=) at /home/duckdb/duckdb/src/common/exception.cpp:333
#1  0x0000000004a62bbc in duckdb::optional_ptr<duckdb::JoinRelationSet, true>::CheckValid (this=<optimized out>)
    at ../../src/include/duckdb/common/optional_ptr.hpp:34
#2  0x0000000004a06d14 in duckdb::optional_ptr<duckdb::JoinRelationSet, true>::operator* (this=0xffffeb569f80)
    at ../../src/include/duckdb/common/optional_ptr.hpp:43
#3  duckdb::CardinalityEstimator::CalculateUpdatedDenom (this=<optimized out>, left=..., right=..., filter=...)
    at /home/duckdb/duckdb/src/optimizer/join_order/cardinality_estimator.cpp:265
#4  0x0000000004a095a0 in duckdb::CardinalityEstimator::GetDenominator (this=0xffffeb56aac0, set=...)
    at /home/duckdb/duckdb/src/optimizer/join_order/cardinality_estimator.cpp:348
#5  0x0000000004a0cba4 in duckdb::CardinalityEstimator::EstimateCardinalityWithSet<double> (this=0xffffeb56aac0, new_set=...)
    at /home/duckdb/duckdb/src/optimizer/join_order/cardinality_estimator.cpp:387
#6  0x0000000004a10a30 in duckdb::CostModel::ComputeCost (this=<optimized out>, left=..., right=...)
    at /home/duckdb/duckdb/src/optimizer/join_order/cost_model.cpp:13
#7  duckdb::PlanEnumerator::CreateJoinTree (this=0xffffeb56aa28, set=..., possible_connections=..., left=..., right=...)
    at /home/duckdb/duckdb/src/optimizer/join_order/plan_enumerator.cpp:135
#8  0x0000000004a1149c in duckdb::PlanEnumerator::EmitPair (this=0xffffeb56aa28, left=..., right=..., info=...)
    at /home/duckdb/duckdb/src/optimizer/join_order/plan_enumerator.cpp:151
#9  0x0000000004a13b28 in duckdb::PlanEnumerator::TryEmitPair (this=0xffffeb56aa28, left=..., right=..., info=...)
    at /home/duckdb/duckdb/src/optimizer/join_order/plan_enumerator.cpp:180
#10 duckdb::PlanEnumerator::EmitCSG (this=0xffffeb56aa28, node=...) at /home/duckdb/duckdb/src/optimizer/join_order/plan_enumerator.cpp:222
#11 0x0000000004a18bfc in duckdb::PlanEnumerator::EnumerateCSGRecursive (this=0xffffeb56aa28, node=...,
    exclusion_set=std::unordered_set with 3 elements = {...}) at /home/duckdb/duckdb/src/optimizer/join_order/plan_enumerator.cpp:296
#12 0x0000000004a193bc in duckdb::PlanEnumerator::EnumerateCSGRecursive (this=0xffffeb56aa28, node=...,
    exclusion_set=std::unordered_set with 1 element = {...}) at /home/duckdb/duckdb/src/optimizer/join_order/plan_enumerator.cpp:311
#13 0x0000000004a19fe0 in duckdb::PlanEnumerator::SolveJoinOrderExactly (this=<optimized out>)
    at /home/duckdb/duckdb/src/optimizer/join_order/plan_enumerator.cpp:334
#14 0x00000000049fa7b4 in duckdb::PlanEnumerator::SolveJoinOrder (this=0xffffeb56aa28)
    at /home/duckdb/duckdb/src/optimizer/join_order/plan_enumerator.cpp:477
#15 0x00000000049f76b4 in duckdb::JoinOrderOptimizer::Optimize (this=0xffffeb56b0d8, plan=..., stats=...)
    at /home/duckdb/duckdb/src/optimizer/join_order/join_order_optimizer.cpp:47
#16 0x0000000004a22408 in duckdb::RelationManager::ExtractJoinRelations (this=0xffffeb56bba0, optimizer=..., input_op=..., filter_operators=..., parent=...)
    at /home/duckdb/duckdb/src/optimizer/join_order/relation_manager.cpp:244
#17 0x00000000049f9058 in duckdb::QueryGraphManager::Build (this=0xffffeb56bba0, optimizer=..., op=...)
    at /home/duckdb/duckdb/src/optimizer/join_order/query_graph_manager.cpp:25
#18 0x00000000049f7428 in duckdb::JoinOrderOptimizer::Optimize (this=0xffffeb56bb98, plan=..., stats=...)
    at /home/duckdb/duckdb/src/optimizer/join_order/join_order_optimizer.cpp:31
#19 0x0000000004a21da0 in duckdb::RelationManager::ExtractJoinRelations (this=0xffffeb56c188, optimizer=..., input_op=..., filter_operators=..., parent=...)
    at /home/duckdb/duckdb/src/optimizer/join_order/relation_manager.cpp:359
#20 0x00000000049f9058 in duckdb::QueryGraphManager::Build (this=0xffffeb56c188, optimizer=..., op=...)
    at /home/duckdb/duckdb/src/optimizer/join_order/query_graph_manager.cpp:25
#21 0x00000000049f7428 in duckdb::JoinOrderOptimizer::Optimize (this=0xffffeb56c180, plan=..., stats=...)
    at /home/duckdb/duckdb/src/optimizer/join_order/join_order_optimizer.cpp:31
#22 0x00000000024c27d0 in duckdb::Optimizer::RunBuiltInOptimizers()::$_21::operator()() const (this=<optimized out>)
    at /home/duckdb/duckdb/src/optimizer/optimizer.cpp:172
#23 std::_Function_handler<void (), duckdb::Optimizer::RunBuiltInOptimizers()::$_21>::_M_invoke(std::_Any_data const&) (__functor=...)
    at /usr/bin/../lib/gcc/aarch64-linux-gnu/9/../../../../include/c++/9/bits/std_function.h:300
#24 0x0000000002475c64 in std::function<void ()>::operator()() const (this=0xffffeb56c558)
    at /usr/bin/../lib/gcc/aarch64-linux-gnu/9/../../../../include/c++/9/bits/std_function.h:688
#25 duckdb::Optimizer::RunOptimizer(duckdb::OptimizerType, std::function<void ()> const&) (this=0xffffeb56c6a8, type=<optimized out>, callback=...)
    at /home/duckdb/duckdb/src/optimizer/optimizer.cpp:89
#26 0x0000000002477d20 in duckdb::Optimizer::RunBuiltInOptimizers (this=0xffffeb56c6a8) at /home/duckdb/duckdb/src/optimizer/optimizer.cpp:170
#27 0x000000000247b9c0 in duckdb::Optimizer::Optimize (this=0xffffeb56c6a8, plan_p=...) at /home/duckdb/duckdb/src/optimizer/optimizer.cpp:268
#28 0x00000000018918dc in duckdb::ClientContext::CreatePreparedStatementInternal (this=<optimized out>, lock=..., Python Exception <class 'gdb.error'> There is no member named _M_dataplus.:
query=, statement=..., values=...)
    at /home/duckdb/duckdb/src/main/client_context.cpp:359
#29 0x0000000001895214 in duckdb::ClientContext::CreatePreparedStatement (this=<optimized out>, lock=..., Python Exception <class 'gdb.error'> There is no member named _M_dataplus.:
query=, statement=..., values=...,
    mode=duckdb::PreparedStatementMode::PREPARE_AND_EXECUTE) at /home/duckdb/duckdb/src/main/client_context.cpp:426
#30 0x00000000018ab804 in duckdb::ClientContext::PendingStatementInternal (this=0x4250e5e0, lock=..., Python Exception <class 'gdb.error'> There is no member named _M_dataplus.:
query=, statement=..., parameters=...)
    at /home/duckdb/duckdb/src/main/client_context.cpp:745
#31 0x00000000018b50d0 in duckdb::ClientContext::PendingStatementOrPreparedStatement (this=<optimized out>, lock=..., Python Exception <class 'gdb.error'> There is no member named _M_dataplus.:
query=, statement=..., prepared=...,
    parameters=...) at /home/duckdb/duckdb/src/main/client_context.cpp:863
#32 0x00000000018a93d4 in duckdb::ClientContext::PendingStatementOrPreparedStatementInternal (this=0x4250e5e0, lock=..., Python Exception <class 'gdb.error'> There is no member named _M_dataplus.:
query=, statement=...,
    prepared=..., parameters=...) at /home/duckdb/duckdb/src/main/client_context.cpp:837
#33 0x00000000018adc34 in duckdb::ClientContext::PendingQueryInternal (this=0x4250e5e0, lock=..., statement=..., parameters=..., verify=<optimized out>)
    at /home/duckdb/duckdb/src/main/client_context.cpp:1054
#34 0x00000000018be110 in duckdb::ClientContext::PendingQuery (this=0x4250e5e0, statement=..., values=std::unordered_map with 0 elements,
    allow_stream_result=<optimized out>) at /home/duckdb/duckdb/src/main/client_context.cpp:1041
#35 0x00000000018b7dfc in duckdb::ClientContext::PendingQuery (this=0x2ad8, statement=..., allow_stream_result=false)
    at /home/duckdb/duckdb/src/main/client_context.cpp:1001
#36 0x00000000018ec7d4 in duckdb::Connection::PendingQuery (this=<optimized out>, statement=..., allow_stream_result=false)
    at /home/duckdb/duckdb/src/main/connection.cpp:140
#37 0x00000000004b40f0 in duckdb_shell_sqlite3_prepare_v2 (db=0x4246c700, zSql=<optimized out>, nByte=<optimized out>, ppStmt=<optimized out>,
    pzTail=<optimized out>) at ../../tools/sqlite3_api_wrapper/sqlite3_api_wrapper.cpp:224
#38 0x000000000046f9dc in duckdb_shell::ShellState::ExecuteSQL (this=<optimized out>,
    zSql=0x426ae040 "PIVOT_WIDER ident : ( ( v00 AS ta29401 INNER JOIN 'string' : ( ( v00 AS ta10600 INNER JOIN v00 AS ta10601 USING ( c02, c01, ) ) ta10602 ANTI JOIN v00 AS ta52101 USING ( c02, c01 ) ) USING ( c01, ) ) )"..., pzErrMsg=<optimized out>) at ../../tools/shell/shell.cpp:1762
#39 0x0000000000485b74 in duckdb_shell::ShellState::RunOneSqlLine (this=0xffffeb56da38,
    zSql=0x426ae040 "PIVOT_WIDER ident : ( ( v00 AS ta29401 INNER JOIN 'string' : ( ( v00 AS ta10600 INNER JOIN v00 AS ta10601 USING ( c02, c01, ) ) ta10602 ANTI JOIN v00 AS ta52101 USING ( c02, c01 ) ) USING ( c01, ) ) )"...) at ../../tools/shell/shell.cpp:4353
#40 0x0000000000480480 in duckdb_shell::ShellState::ProcessInput (this=<optimized out>) at ../../tools/shell/shell.cpp:4468
#41 0x0000000000489dac in main (argc=1, argv=0xffffeb56dd88) at ../../tools/shell/shell.cpp:5076
```

### To Reproduce

1. Clone the DuckDB Git from the official repo.
2. Checkout to the latest main (1db3def66e).
3. Compile the DuckDB binary by using `make relassert`.
4. Run the compiled DuckDB and input the following SQL:

```sql
CREATE TABLE v00 (c01 INT, c02 STRING);
PIVOT_WIDER ident : ( ( v00 AS ta29401 INNER JOIN 'string' : ( ( v00 AS ta10600 INNER JOIN v00 AS ta10601 USING ( c02, c01, ) ) ta10602 ANTI JOIN v00 AS ta52101 USING ( c02, c01 ) ) USING ( c01, ) ) ) SEMI JOIN v00 AS ta1901 USING ( c02, c01, ) NATURAL JOIN v00 AS ta35101 USING 'string' GROUP BY c02, c01 ORDER BY ALL ASC FOR READ ONLY;
```

### OS:

Ubuntu 24.04 LTS

### DuckDB Version:

latest main (1db3def66e)

### DuckDB Client:

cli

### Full Name:

Yu Liang

### Affiliation:

The Pennsylvania State University

### What is the latest build you tested with? If possible, we recommend testing with the latest nightly build.

I have tested with a nightly build

### Did you include all relevant data sets for reproducing the issue?

Yes

### Did you include all code required to reproduce the issue?

- [X] Yes, I have

### Did you include all relevant configuration (e.g., CPU architecture, Python version, Linux distribution) to reproduce the issue?

- [X] Yes, I have

**Comment by carlopi** [comment]
Solved on main! Thanks
