### ISSUE TITLE
DuckDB Internal Error: Failed to bind column reference

### ISSUE THREAD

**Issue by SteveLeungYL** [duckdb/duckdb#15200]
### What happens?

The latest version of the DuckDB (latest main: v1.1.4-dev3057 1db3def66e) triggers Internal Error when running the following SQL statement: 

```sql
CREATE TABLE v00 (c01 STRING);
INSERT INTO v00 OVERRIDING USER VALUE PIVOT ( ( v00 AS ta02 NATURAL FULL OUTER JOIN v00 AS ta03 ASOF JOIN v00 AS ta04 USING ( c01 ) ) ) GROUP BY ( c01 );
```

Stacktrace from the latest main (1db3def66e1):

```
#0  duckdb::InternalException::InternalException (this=0xea14430, Python Exception <class 'gdb.error'> There is no member named _M_dataplus.:
msg=) at /home/duckdb/duckdb/src/common/exception.cpp:333
#1  0x00000000016c6aa0 in duckdb::InternalException::InternalException<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, unsigned long, unsigned long, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > > (this=0xea14430, Python Exception <class 'gdb.error'> There is no member named _M_dataplus.:
msg=, params=..., params=...,
    params=..., params=...) at ../../src/include/duckdb/common/exception.hpp:313
#2  0x000000000165a8b0 in duckdb::ColumnBindingResolver::VisitReplace (this=<optimized out>, expr=..., expr_ptr=<optimized out>)
    at /home/duckdb/duckdb/src/execution/column_binding_resolver.cpp:165
#3  0x000000000292f88c in duckdb::LogicalOperatorVisitor::VisitExpression (this=0xffffc1a0a268, expression=<optimized out>)
    at /home/duckdb/duckdb/src/planner/logical_operator_visitor.cpp:200
#4  0x00000000028c2a1c in std::function<void (duckdb::unique_ptr<duckdb::Expression, std::default_delete<duckdb::Expression>, true>&)>::operator()(duckdb::unique_ptr<duckdb::Expression, std::default_delete<duckdb::Expression>, true>&) const (this=0xffffc1a09b60, __args=...)
    at /usr/bin/../lib/gcc/aarch64-linux-gnu/9/../../../../include/c++/9/bits/std_function.h:688
#5  duckdb::ExpressionIterator::EnumerateChildren(duckdb::Expression&, std::function<void (duckdb::unique_ptr<duckdb::Expression, std::default_delete<duckdb::Expression>, true>&)> const&) (expr=..., callback=...) at /home/duckdb/duckdb/src/planner/expression_iterator.cpp:85
#6  0x0000000002930bfc in duckdb::LogicalOperatorVisitor::VisitExpressionChildren (this=<optimized out>, expr=...)
    at /home/duckdb/duckdb/src/planner/logical_operator_visitor.cpp:247
#7  0x0000000002930168 in duckdb::LogicalOperatorVisitor::VisitExpression (this=0xffffc1a0a268, expression=<optimized out>)
    at /home/duckdb/duckdb/src/planner/logical_operator_visitor.cpp:242
#8  0x00000000016570e8 in duckdb::ColumnBindingResolver::VisitOperator (this=0xffffc1a0a268, op=...)
    at /home/duckdb/duckdb/src/execution/column_binding_resolver.cpp:27
#9  0x0000000002929de8 in duckdb::LogicalOperatorVisitor::VisitOperatorChildren (this=0xffffc1a0a268, op=...)
    at /home/duckdb/duckdb/src/planner/logical_operator_visitor.cpp:19
#10 0x000000000165975c in duckdb::ColumnBindingResolver::VisitOperator (this=0xffffc1a0a268, op=...)
    at /home/duckdb/duckdb/src/execution/column_binding_resolver.cpp:142
#11 0x0000000002929de8 in duckdb::LogicalOperatorVisitor::VisitOperatorChildren (this=0xffffc1a0a268, op=...)
    at /home/duckdb/duckdb/src/planner/logical_operator_visitor.cpp:19
#12 0x000000000165975c in duckdb::ColumnBindingResolver::VisitOperator (this=0xffffc1a0a268, op=...)
    at /home/duckdb/duckdb/src/execution/column_binding_resolver.cpp:142
#13 0x0000000002929de8 in duckdb::LogicalOperatorVisitor::VisitOperatorChildren (this=0xffffc1a0a268, op=...)
    at /home/duckdb/duckdb/src/planner/logical_operator_visitor.cpp:19
#14 0x000000000165975c in duckdb::ColumnBindingResolver::VisitOperator (this=0xffffc1a0a268, op=...)
    at /home/duckdb/duckdb/src/execution/column_binding_resolver.cpp:142
#15 0x0000000002929de8 in duckdb::LogicalOperatorVisitor::VisitOperatorChildren (this=0xffffc1a0a268, op=...)
    at /home/duckdb/duckdb/src/planner/logical_operator_visitor.cpp:19
#16 0x000000000165975c in duckdb::ColumnBindingResolver::VisitOperator (this=0xffffc1a0a268, op=...)
    at /home/duckdb/duckdb/src/execution/column_binding_resolver.cpp:142
#17 0x0000000002929de8 in duckdb::LogicalOperatorVisitor::VisitOperatorChildren (this=0xffffc1a0a268, op=...)
    at /home/duckdb/duckdb/src/planner/logical_operator_visitor.cpp:19
#18 0x000000000165975c in duckdb::ColumnBindingResolver::VisitOperator (this=0xffffc1a0a268, op=...)
    at /home/duckdb/duckdb/src/execution/column_binding_resolver.cpp:142
#19 0x000000000169df90 in duckdb::PhysicalPlanGenerator::CreatePlan (this=0xffffc1a0a318, op=...)
    at /home/duckdb/duckdb/src/execution/physical_plan_generator.cpp:28
#20 0x0000000001891b4c in duckdb::ClientContext::CreatePreparedStatementInternal (this=<optimized out>, lock=..., Python Exception <class 'gdb.error'> There is no member named _M_dataplus.:
query=, statement=..., values=...)
    at /home/duckdb/duckdb/src/main/client_context.cpp:371
#21 0x0000000001895214 in duckdb::ClientContext::CreatePreparedStatement (this=<optimized out>, lock=..., Python Exception <class 'gdb.error'> There is no member named _M_dataplus.:
query=, statement=..., values=...,
    mode=duckdb::PreparedStatementMode::PREPARE_AND_EXECUTE) at /home/duckdb/duckdb/src/main/client_context.cpp:426
#22 0x00000000018ab804 in duckdb::ClientContext::PendingStatementInternal (this=0xe78d9f0, lock=..., Python Exception <class 'gdb.error'> There is no member named _M_dataplus.:
query=, statement=..., parameters=...)
    at /home/duckdb/duckdb/src/main/client_context.cpp:745
#23 0x00000000018b50d0 in duckdb::ClientContext::PendingStatementOrPreparedStatement (this=<optimized out>, lock=..., Python Exception <class 'gdb.error'> There is no member named _M_dataplus.:
query=, statement=..., prepared=...,
    parameters=...) at /home/duckdb/duckdb/src/main/client_context.cpp:863
#24 0x00000000018a93d4 in duckdb::ClientContext::PendingStatementOrPreparedStatementInternal (this=0xe78d9f0, lock=..., query=Python Exception <class 'gdb.error'> There is no member named _M_dataplus.:
, statement=..., prepared=..., parameters=...) at /home/duckdb/duckdb/src/main/client_context.cpp:837
#25 0x00000000018adc34 in duckdb::ClientContext::PendingQueryInternal (this=0xe78d9f0, lock=..., statement=..., parameters=..., verify=<optimized out>) at /home/duckdb/duckdb/src/main/client_context.cpp:1054
#26 0x00000000018be110 in duckdb::ClientContext::PendingQuery (this=0xe78d9f0, statement=..., values=std::unordered_map with 0 elements, allow_stream_result=<optimized out>) at /home/duckdb/duckdb/src/main/client_context.cpp:1041
#27 0x00000000018b7dfc in duckdb::ClientContext::PendingQuery (this=0x2ad8, statement=..., allow_stream_result=false) at /home/duckdb/duckdb/src/main/client_context.cpp:1001
#28 0x00000000018ec7d4 in duckdb::Connection::PendingQuery (this=<optimized out>, statement=..., allow_stream_result=false) at /home/duckdb/duckdb/src/main/connection.cpp:140
#29 0x00000000004b40f0 in duckdb_shell_sqlite3_prepare_v2 (db=0xe6ec440, zSql=<optimized out>, nByte=<optimized out>, ppStmt=<optimized out>, pzTail=<optimized out>) at ../../tools/sqlite3_api_wrapper/sqlite3_api_wrapper.cpp:224
#30 0x000000000046f9dc in duckdb_shell::ShellState::ExecuteSQL (this=<optimized out>, zSql=0xe92c7d0 "INSERT INTO v00 OVERRIDING USER VALUE PIVOT ( ( v00 AS ta400 NATURAL FULL OUTER JOIN v00 AS ta401 ASOF JOIN v00 AS ta5201 USING ( c01 ) ) ) GROUP BY ( c01 );", pzErrMsg=<optimized out>) at ../../tools/shell/shell.cpp:1762
#31 0x0000000000485b74 in duckdb_shell::ShellState::RunOneSqlLine (this=0xffffc1a0b6a8, zSql=0xe92c7d0 "INSERT INTO v00 OVERRIDING USER VALUE PIVOT ( ( v00 AS ta400 NATURAL FULL OUTER JOIN v00 AS ta401 ASOF JOIN v00 AS ta5201 USING ( c01 ) ) ) GROUP BY ( c01 );") at ../../tools/shell/shell.cpp:4353
#32 0x0000000000480480 in duckdb_shell::ShellState::ProcessInput (this=<optimized out>) at ../../tools/shell/shell.cpp:4468
#33 0x0000000000489dac in main (argc=1, argv=0xffffc1a0b9f8) at ../../tools/shell/shell.cpp:5076
```

### To Reproduce

1. Clone the DuckDB Git from the official repo.
2. Checkout to the latest main (1db3def66e).
3. Compile the DuckDB binary by using `make relassert`.
4. Run the compiled DuckDB and input the following SQL:

```sql
CREATE TABLE v00 (c01 STRING);
INSERT INTO v00 OVERRIDING USER VALUE PIVOT ( ( v00 AS ta02 NATURAL FULL OUTER JOIN v00 AS ta03 ASOF JOIN v00 AS ta04 USING ( c01 ) ) ) GROUP BY ( c01 );
```

### OS:

Ubuntu 24.04 LTS

### DuckDB Version:

v1.1.4-dev3057 1db3def

### DuckDB Client:

cli

### Full Name:

Yu Liang

### Affiliation:

The Pennsylvania State University

### What is the latest build you tested with? If possible, we recommend testing with the latest nightly build.

I have tested with a nightly build

### Did you include all relevant data sets for reproducing the issue?

Yes

### Did you include all code required to reproduce the issue?

- [X] Yes, I have

### Did you include all relevant configuration (e.g., CPU architecture, Python version, Linux distribution) to reproduce the issue?

- [X] Yes, I have

**Comment by carlopi** [comment]
Also this looks to be solved on main, via https://github.com/duckdb/duckdb/pull/15230, thanks!
