### ISSUE TITLE
DuckDB Assertion Error: colref.depth == 0

### ISSUE THREAD

**Issue by SteveLeungYL** [duckdb/duckdb#15204]
### What happens?

The latest version of the DuckDB (latest main: v1.1.4-dev2916 9da182a939) triggers Internal Error when running the following SQL statement: 

```sql
CREATE TABLE v00 (c01 INT, c02 STRING);
CREATE TABLE IF NOT EXISTS v300 ON COMMIT PRESERVE ROWS AS ( PIVOT_WIDER ( v00 AS ta3100 JOIN ( v00 AS ta25700 ASOF FULL JOIN ( v00 AS ta4000 SEMI JOIN v00 AS ta4001 USING ( c02, c01 ) ) AS ta4002 USING ( c01, c02, ) ) ta25702 USING ( c02, c01, ) ) ta3802 GROUP BY ( c02 ) ) WITH NO DATA;
```

Stacktrace for (9da182a939):

```
#0  duckdb::InternalException::InternalException (this=0x60d00000a0d0, Python Exception <class 'gdb.error'> There is no member named _M_dataplus.: 
msg=) at /home/duckdb/duckdb/src/common/exception.cpp:333
#1  0x000000000202bcca in duckdb::InternalException::InternalException<char const*, int, char const*, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > > (this=0x60d00000a0d0, msg=..., params=<incomplete type>, params=<incomplete type>, params=<incomplete type>, 
    params=<incomplete type>) at ../../src/include/duckdb/common/exception.hpp:313
#2  0x0000000001de5530 in duckdb::DuckDBAssertInternal (condition=<optimized out>, condition_name=<optimized out>, file=<optimized out>, 
    linenr=<optimized out>) at /home/duckdb/duckdb/src/common/assert.cpp:13
#3  0x0000000005e1c7fb in duckdb::LogicalJoin::GetExpressionBindings (expr=..., bindings=...)
    at /home/duckdb/duckdb/src/planner/operator/logical_join.cpp:63
#4  0x0000000005e8c553 in duckdb::ExpressionIterator::EnumerateChildren(duckdb::Expression&, std::function<void (duckdb::unique_ptr<duckdb::Expression, std::default_delete<duckdb::Expression>, true>&)> const&) (expr=..., callback=...) at /home/duckdb/duckdb/src/planner/expression_iterator.cpp:126
#5  0x0000000005e91a64 in duckdb::ExpressionIterator::EnumerateChildren(duckdb::Expression&, std::function<void (duckdb::Expression&)> const&) (expr=..., 
    callback=...) at /home/duckdb/duckdb/src/planner/expression_iterator.cpp:20
#6  0x0000000005e1cca8 in duckdb::LogicalJoin::GetExpressionBindings (expr=..., bindings=...)
    at /home/duckdb/duckdb/src/planner/operator/logical_join.cpp:66
#7  0x00000000055a86a6 in duckdb::FilterPushdown::GenerateFilters()::$_11::operator()(duckdb::unique_ptr<duckdb::Expression, std::default_delete<duckdb::Expression>, true>) const (this=<optimized out>, filter=...) at /home/duckdb/duckdb/src/optimizer/filter_pushdown.cpp:187
#8  std::_Function_handler<void (duckdb::unique_ptr<duckdb::Expression, std::default_delete<duckdb::Expression>, true>), duckdb::FilterPushdown::GenerateFilters()::$_11>::_M_invoke(std::_Any_data const&, duckdb::unique_ptr<duckdb::Expression, std::default_delete<duckdb::Expression>, true>&&) (__functor=..., 
    __args=...) at /usr/bin/../lib/gcc/x86_64-linux-gnu/9/../../../../include/c++/9/bits/std_function.h:300
#9  0x00000000054c2d1e in duckdb::FilterCombiner::GenerateFilters(std::function<void (duckdb::unique_ptr<duckdb::Expression, std::default_delete<duckdb::Expression>, true>)> const&) (this=<optimized out>, callback=...) at /home/duckdb/duckdb/src/optimizer/filter_combiner.cpp:120
#10 0x000000000550090b in duckdb::FilterPushdown::GenerateFilters (this=<optimized out>) at /home/duckdb/duckdb/src/optimizer/filter_pushdown.cpp:184
#11 0x000000000aba5c50 in duckdb::FilterPushdown::PushdownFilter (this=0x7ffeefb30c80, op=...)
    at /home/duckdb/duckdb/src/optimizer/pushdown/pushdown_filter.cpp:22
#12 0x0000000005489ee8 in duckdb::FilterPushdown::Rewrite (this=0x7ffeefb2f3a0, op=...) at /home/duckdb/duckdb/src/optimizer/filter_pushdown.cpp:75
#13 0x000000000ab9a323 in duckdb::FilterPushdown::PushdownAggregate (this=<optimized out>, op=...)
    at /home/duckdb/duckdb/src/optimizer/pushdown/pushdown_aggregate.cpp:95
#14 0x000000000548a3a4 in duckdb::FilterPushdown::Rewrite (this=0x7ffeefb2f3a0, op=...) at /home/duckdb/duckdb/src/optimizer/filter_pushdown.cpp:73
#15 0x000000000abbc449 in duckdb::FilterPushdown::PushdownProjection (this=<optimized out>, op=...)
    at /home/duckdb/duckdb/src/optimizer/pushdown/pushdown_projection.cpp:72
#16 0x000000000548a2b4 in duckdb::FilterPushdown::Rewrite (this=0x7ffeefb2f3a0, op=...) at /home/duckdb/duckdb/src/optimizer/filter_pushdown.cpp:84
#17 0x00000000054fe207 in duckdb::FilterPushdown::FinishPushdown (this=0x7ffeefb326c0, op=...) at /home/duckdb/duckdb/src/optimizer/filter_pushdown.cpp:227
#18 0x000000000548a1c1 in duckdb::FilterPushdown::Rewrite (this=0x7ffeefb2f3a0, op=...) at /home/duckdb/duckdb/src/optimizer/filter_pushdown.cpp:112
#19 0x00000000055ae7dd in duckdb::Optimizer::RunBuiltInOptimizers()::$_15::operator()() const (this=<optimized out>)
    at /home/duckdb/duckdb/src/optimizer/optimizer.cpp:137
#20 std::_Function_handler<void (), duckdb::Optimizer::RunBuiltInOptimizers()::$_15>::_M_invoke(std::_Any_data const&) (__functor=...)
    at /usr/bin/../lib/gcc/x86_64-linux-gnu/9/../../../../include/c++/9/bits/std_function.h:300
#21 0x000000000551cb76 in duckdb::Optimizer::RunOptimizer(duckdb::OptimizerType, std::function<void ()> const&) (this=0x7ffeefb338a0, type=<optimized out>, 
    callback=...) at /home/duckdb/duckdb/src/optimizer/optimizer.cpp:89
#22 0x000000000551e56f in duckdb::Optimizer::RunBuiltInOptimizers (this=<optimized out>) at /home/duckdb/duckdb/src/optimizer/optimizer.cpp:133
#23 0x000000000552480f in duckdb::Optimizer::Optimize (this=0x7ffeefb338a0, plan_p=...) at /home/duckdb/duckdb/src/optimizer/optimizer.cpp:268
#24 0x00000000033b2f70 in duckdb::ClientContext::CreatePreparedStatementInternal (this=0x616000074490, lock=..., query=..., statement=..., values=...)
    at /home/duckdb/duckdb/src/main/client_context.cpp:359
#25 0x00000000033b8884 in duckdb::ClientContext::CreatePreparedStatement (this=0x616000074490, lock=..., query=..., statement=..., values=..., 
    mode=<optimized out>) at /home/duckdb/duckdb/src/main/client_context.cpp:426
#26 0x00000000033da8ea in duckdb::ClientContext::PendingStatementInternal (this=0x616000074490, lock=..., query=..., statement=..., parameters=...)
    at /home/duckdb/duckdb/src/main/client_context.cpp:745
#27 0x00000000033e7514 in duckdb::ClientContext::PendingStatementOrPreparedStatement (this=0x616000074490, lock=..., query=..., statement=..., 
    prepared=..., parameters=...) at /home/duckdb/duckdb/src/main/client_context.cpp:863
#28 0x00000000033d5ff8 in duckdb::ClientContext::PendingStatementOrPreparedStatementInternal (this=0x616000074490, lock=..., query=..., statement=..., 
    prepared=..., parameters=...) at /home/duckdb/duckdb/src/main/client_context.cpp:837
#29 0x00000000033ddd4b in duckdb::ClientContext::PendingQueryInternal (this=0x616000074490, lock=..., statement=..., parameters=..., verify=<optimized out>)
    at /home/duckdb/duckdb/src/main/client_context.cpp:1054
#30 0x00000000033f3e0e in duckdb::ClientContext::PendingQuery (this=0x616000074490, statement=..., values=..., allow_stream_result=<optimized out>)
    at /home/duckdb/duckdb/src/main/client_context.cpp:1041
#31 0x00000000033eb320 in duckdb::ClientContext::PendingQuery (this=0x616000074490, statement=..., allow_stream_result=<optimized out>)
    at /home/duckdb/duckdb/src/main/client_context.cpp:1001
#32 0x000000000343a1d8 in duckdb::Connection::PendingQuery (this=<optimized out>, statement=..., allow_stream_result=<optimized out>)
    at /home/duckdb/duckdb/src/main/connection.cpp:140
#33 0x0000000000704784 in duckdb_shell_sqlite3_prepare_v2 (db=0x60f0000007c0, zSql=<optimized out>, nByte=<optimized out>, ppStmt=<optimized out>, 
    pzTail=<optimized out>) at ../../tools/sqlite3_api_wrapper/sqlite3_api_wrapper.cpp:224
#34 0x000000000066cab6 in duckdb_shell::ShellState::ExecuteSQL (this=0x7ffeefb35ce0, 
    zSql=0x614000019840 "CREATE LOCAL TEMPORARY TABLE IF NOT EXISTS v300 ON COMMIT PRESERVE ROWS AS ( PIVOT_WIDER ( v00 AS ta3100 JOIN ( v00 AS ta25700 ASOF FULL JOIN ( v00 AS ta4000 SEMI JOIN v00 AS ta4001 USING ( c02, c01 )"..., pzErrMsg=<optimized out>) at ../../tools/shell/shell.cpp:3524
#35 0x0000000000698023 in duckdb_shell::ShellState::RunOneSqlLine (this=<optimized out>, zSql=<optimized out>) at ../../tools/shell/shell.cpp:8706
#36 0x000000000068d610 in duckdb_shell::ShellState::ProcessInput (this=0x7ffeefb35ce0) at ../../tools/shell/shell.cpp:8936
#37 0x000000000069e28d in main (argc=<optimized out>, argv=<optimized out>) at ../../tools/shell/shell.cpp:10152
```

### To Reproduce

1. Clone the DuckDB Git from the official repo.
2. Checkout to the latest main (9da182a939).
3. Compile the DuckDB binary by using `make relassert`.
4. Run the compiled DuckDB and input the following SQL:

```sql
CREATE TABLE v00 (c01 INT, c02 STRING);
CREATE TABLE IF NOT EXISTS v300 ON COMMIT PRESERVE ROWS AS ( PIVOT_WIDER ( v00 AS ta3100 JOIN ( v00 AS ta25700 ASOF FULL JOIN ( v00 AS ta4000 SEMI JOIN v00 AS ta4001 USING ( c02, c01 ) ) AS ta4002 USING ( c01, c02, ) ) ta25702 USING ( c02, c01, ) ) ta3802 GROUP BY ( c02 ) ) WITH NO DATA;
```

### OS:

Ubuntu 24.04 LTS

### DuckDB Version:

9da182a

### DuckDB Client:

cli

### Full Name:

Yu Liang

### Affiliation:

The Pennsylvania State University

### What is the latest build you tested with? If possible, we recommend testing with the latest nightly build.

I have tested with a nightly build

### Did you include all relevant data sets for reproducing the issue?

Yes

### Did you include all code required to reproduce the issue?

- [X] Yes, I have

### Did you include all relevant configuration (e.g., CPU architecture, Python version, Linux distribution) to reproduce the issue?

- [X] Yes, I have

**Comment by szarnyasg** [comment]
Thanks!

```
ubuntu@ip-172-31-19-0:~/duckdb$ build/relassert/duckdb
v1.1.4-dev3069 c4a286b642
Enter ".help" for usage hints.
Connected to a transient in-memory database.
Use ".open FILENAME" to reopen on a persistent database.
D
D CREATE TABLE v00 (c01 INT, c02 STRING);
D CREATE TABLE IF NOT EXISTS v300 ON COMMIT PRESERVE ROWS AS ( PIVOT_WIDER ( v00 AS ta3100 JOIN ( v00 AS ta25700 ASOF FULL JOIN ( v00 AS ta4000 SEMI JOIN v00 AS ta4001 USING ( c02, c01 ) ) AS ta4002 USING ( c01, c02, ) ) ta25702 USING ( c02, c01, ) ) ta3802 GROUP BY ( c02 ) ) WITH NO DATA;
INTERNAL Error:
Assertion triggered in file "/home/ubuntu/duckdb/src/planner/operator/logical_join.cpp" on line 63: colref.depth == 0
This error signals an assertion failure within DuckDB. This usually occurs due to unexpected conditions or errors in the program's logic.
For more information, see https://duckdb.org/docs/dev/internal_errors
```

**Comment by szarnyasg** [comment]
```
$  build/relassert/duckdb
duckdb(55688,0x1eb3ef840) malloc: nano zone abandoned due to inability to reserve vm space.
-- Loading resources from /Users/szarnyasg/.duckdbrc
v1.1.3-dev3234 c4a286b642
Enter ".help" for usage hints.
Connected to a transient in-memory database.
Use ".open FILENAME" to reopen on a persistent database.
D pragma platform;
┌───────────┐
│ platform  │
│  varchar  │
├───────────┤
│ osx_arm64 │
└───────────┘
Run Time (s): real 0.004 user 0.002658 sys 0.001840
D CREATE TABLE v00 (c01 INT, c02 STRING);
Run Time (s): real 0.002 user 0.001569 sys 0.000574
D CREATE TABLE IF NOT EXISTS v300 ON COMMIT PRESERVE ROWS AS ( PIVOT_WIDER ( v00 AS ta3100 JOIN ( v00 AS ta25700 ASOF FULL JOIN ( v00 AS ta4000 SEMI JOIN v00 AS ta4001 USING ( c02, c01 ) ) AS ta4002 USING ( c01, c02, ) ) ta25702 USING ( c02, c01, ) ) ta3802 GROUP BY ( c02 ) ) WITH NO DATA;
Run Time (s): real 0.010 user 0.006347 sys 0.001999
INTERNAL Error:
Assertion triggered in file "/Users/szarnyasg/git/duckdb/src/planner/operator/logical_join.cpp" on line 63: colref.depth == 0
This error signals an assertion failure within DuckDB. This usually occurs due to unexpected conditions or errors in the program's logic.
For more information, see https://duckdb.org/docs/dev/internal_errors
```

**Comment by carlopi** [comment]
Solved on main, thanks!
