### ISSUE TITLE
DuckDB triggers Assertion Failure with duplicated aliases: BindContext::RemoveContext - no more tables that refer to this using binding

### ISSUE THREAD

**Issue by SteveLeungYL** [duckdb/duckdb#15311]
### What happens?

The latest version of the DuckDB (latest main: v1.1.4-dev3300 4a8188effc) triggers Assertion Failure when running the following SQL statement: 

```sql
CREATE TABLE v00 (c01 INT);
FROM ( v00 AS ta02 /* The same alias as after */ NATURAL SEMI JOIN /* NATURAL SEMI JOIN is necessary */ v00 AS ta02 /* The same alias as before */ );
```

DuckDB is working correctly without assertions, maybe just a faulty assertion?

The stack trace from (4a8188effc): 

```
#0  duckdb::InternalException::InternalException (this=0x60d000007b70, Python Exception <class 'gdb.error'> There is no member named _M_dataplus.: 
msg=) at /home/duckdb/duckdb/src/common/exception.cpp:333
#1  0x000000000602b24f in duckdb::BindContext::RemoveContext (this=0x61900000b048, aliases=...) at /home/duckdb/duckdb/src/planner/bind_context.cpp:729
#2  0x0000000005ced2ce in duckdb::Binder::Bind (this=0x61900000af80, ref=...) at /home/duckdb/duckdb/src/planner/binder/tableref/bind_joinref.cpp:341
#3  0x0000000005fe5fbb in duckdb::Binder::Bind (this=0x61900000af80, ref=...) at /home/duckdb/duckdb/src/planner/binder.cpp:398
#4  0x0000000005ce333e in duckdb::Binder::BindJoin (this=<optimized out>, parent_binder=..., ref=...) at /home/duckdb/duckdb/src/planner/binder/tableref/bind_joinref.cpp:127
#5  0x0000000005ce46a0 in duckdb::Binder::Bind (this=0x61900000aa80, ref=...) at /home/duckdb/duckdb/src/planner/binder/tableref/bind_joinref.cpp:140
#6  0x0000000005fe5fbb in duckdb::Binder::Bind (this=0x61900000aa80, ref=...) at /home/duckdb/duckdb/src/planner/binder.cpp:398
#7  0x000000000ad5f4d9 in duckdb::Binder::BindNode (this=0x7ffc909d3680, statement=...) at /home/duckdb/duckdb/src/planner/binder/query_node/bind_select_node.cpp:371
#8  0x0000000005fe1b7d in duckdb::Binder::BindNode (this=0x61900000aa80, node=...) at /home/duckdb/duckdb/src/planner/binder.cpp:328
#9  0x0000000005cd3c00 in duckdb::Binder::Bind (this=0x61900000a580, ref=..., cte=...) at /home/duckdb/duckdb/src/planner/binder/tableref/bind_subqueryref.cpp:13
#10 0x0000000005fe6400 in duckdb::Binder::Bind (this=0x61900000a580, ref=...) at /home/duckdb/duckdb/src/planner/binder.cpp:401
#11 0x000000000ad5f4d9 in duckdb::Binder::BindNode (this=0x7ffc909d3680, statement=...) at /home/duckdb/duckdb/src/planner/binder/query_node/bind_select_node.cpp:371
#12 0x0000000005fe1b7d in duckdb::Binder::BindNode (this=0x61900000a580, node=...) at /home/duckdb/duckdb/src/planner/binder.cpp:328
#13 0x0000000005fe30e6 in duckdb::Binder::Bind (this=0x61900000a580, node=...) at /home/duckdb/duckdb/src/planner/binder.cpp:365
#14 0x0000000005ae6448 in duckdb::Binder::Bind (this=0x61900000a580, stmt=...) at /home/duckdb/duckdb/src/planner/binder/statement/bind_select.cpp:11
#15 0x0000000005fd696d in duckdb::Binder::Bind (this=<optimized out>, statement=...) at /home/duckdb/duckdb/src/planner/binder.cpp:150
#16 0x000000000602c77c in duckdb::Planner::CreatePlan (this=0x7ffc909d85f0, statement=...) at /home/duckdb/duckdb/src/planner/planner.cpp:43
#17 0x0000000006035903 in duckdb::Planner::CreatePlan (this=0x60d000007b70, statement=...) at /home/duckdb/duckdb/src/planner/planner.cpp:142
#18 0x00000000033c500c in duckdb::ClientContext::CreatePreparedStatementInternal (this=0x616000074790, lock=..., query=..., statement=..., values=...) at /home/duckdb/duckdb/src/main/client_context.cpp:340
#19 0x00000000033cb5d4 in duckdb::ClientContext::CreatePreparedStatement (this=0x616000074790, lock=..., query=..., statement=..., values=..., mode=<optimized out>) at /home/duckdb/duckdb/src/main/client_context.cpp:426
#20 0x00000000033ed63a in duckdb::ClientContext::PendingStatementInternal (this=0x616000074790, lock=..., query=..., statement=..., parameters=...) at /home/duckdb/duckdb/src/main/client_context.cpp:745
#21 0x00000000033fa264 in duckdb::ClientContext::PendingStatementOrPreparedStatement (this=0x616000074790, lock=..., query=..., statement=..., prepared=..., parameters=...) at /home/duckdb/duckdb/src/main/client_context.cpp:863
#22 0x00000000033e8d48 in duckdb::ClientContext::PendingStatementOrPreparedStatementInternal (this=0x616000074790, lock=..., query=..., statement=..., prepared=..., parameters=...)
    at /home/duckdb/duckdb/src/main/client_context.cpp:837
#23 0x00000000033f0a9b in duckdb::ClientContext::PendingQueryInternal (this=0x616000074790, lock=..., statement=..., parameters=..., verify=<optimized out>) at /home/duckdb/duckdb/src/main/client_context.cpp:1054
#24 0x0000000003406b5e in duckdb::ClientContext::PendingQuery (this=0x616000074790, statement=..., values=..., allow_stream_result=<optimized out>) at /home/duckdb/duckdb/src/main/client_context.cpp:1041
#25 0x00000000033fe070 in duckdb::ClientContext::PendingQuery (this=0x616000074790, statement=..., allow_stream_result=<optimized out>) at /home/duckdb/duckdb/src/main/client_context.cpp:1001
#26 0x000000000344cf38 in duckdb::Connection::PendingQuery (this=<optimized out>, statement=..., allow_stream_result=<optimized out>) at /home/duckdb/duckdb/src/main/connection.cpp:140
#27 0x0000000000705ab4 in duckdb_shell_sqlite3_prepare_v2 (db=0x60f000000310, zSql=<optimized out>, nByte=<optimized out>, ppStmt=<optimized out>, pzTail=<optimized out>)
    at ../../tools/sqlite3_api_wrapper/sqlite3_api_wrapper.cpp:224
#28 0x000000000066db46 in duckdb_shell::ShellState::ExecuteSQL (this=0x7ffc909daca0, 
    zSql=0x6120000a48c0 "FROM ( v00 AS ta02 /* The same alias as after */ NATURAL SEMI JOIN v00 AS ta02 /* The same alias as before */ NATURAL FULL JOIN v00 AS ta03 ) AS ta04 WINDOW TRIM AS ( RANGE CURRENT ROW);", 
    pzErrMsg=<optimized out>) at ../../tools/shell/shell.cpp:3524
#29 0x00000000006990b3 in duckdb_shell::ShellState::RunOneSqlLine (this=<optimized out>, zSql=<optimized out>) at ../../tools/shell/shell.cpp:8706
#30 0x000000000068e6a0 in duckdb_shell::ShellState::ProcessInput (this=0x7ffc909daca0) at ../../tools/shell/shell.cpp:8936
#31 0x000000000069f31d in main (argc=<optimized out>, argv=<optimized out>) at ../../tools/shell/shell.cpp:10152
```

### To Reproduce

1. Clone the DuckDB Git from the official repo.
2. Checkout to the latest main (4a8188effc).
3. Compile the DuckDB binary by using `make relassert`. Assertion is necessary to reproduce the bug. 
4. Run the compiled DuckDB and input the following SQL:

```sql
CREATE TABLE v00 (c01 INT);
FROM ( v00 AS ta02 /* The same alias as after */ NATURAL SEMI JOIN /* NATURAL SEMI JOIN is necessary */ v00 AS ta02 /* The same alias as before */ );
```

### OS:

Ubuntu 24.04 LTS

### DuckDB Version:

v1.1.4-dev3300 4a8188effc

### DuckDB Client:

cli

### Full Name:

Yu Liang

### Affiliation:

The Pennsylvania State University

### What is the latest build you tested with? If possible, we recommend testing with the latest nightly build.

I have tested with a source build

### Did you include all relevant data sets for reproducing the issue?

Yes

### Did you include all code required to reproduce the issue?

- [X] Yes, I have

### Did you include all relevant configuration (e.g., CPU architecture, Python version, Linux distribution) to reproduce the issue?

- [X] Yes, I have

**Comment by taniabogatsch** [comment]
```sql
 % duckdb
DuckDB v1.4.3 (Andium) d1dc88f950
Enter ".help" for usage hints.
Connected to a transient in-memory database.
Use ".open FILENAME" to reopen on a persistent database.
D CREATE TABLE v00 (c01 INT);
D FROM ( v00 AS ta02 /* The same alias as after */ NATURAL SEMI JOIN /* NATURAL SEMI JOIN is necessary */ v00 AS ta02 /* The same alias as before */ );
Binder Error:
* expression without FROM clause!
D 

```
