### ISSUE TITLE
Crash when deleting rows

### ISSUE THREAD

**Issue by akdor1154** [duckdb/duckdb#1624]
Hiya,
Ran into this this morning.
I have a table,
```sql
create table odap_tx (
    transaction_id text primary key,
    conformed_id text
);
```

I also have a similar auxiliary table,
```sql
create table legacy_tx (
    transaction_id text primary key,
    new_consolidated_id text
);
```

The tables in question has about 6 million rows in them each. When I delete from `odap_tx`, I get a segfault:
```sql
delete from odap_tx o
where not exists (
    select l.transaction_id
    from legacy_tx l
    where l.transaction_id = o.transaction_id
);
```
```
#0  duckdb::VersionDeleteState::Delete (this=0x7fffffffa090, row_id=103424)
    at /home/jarrad/src/web/duckdb/src/storage/table/morsel_info.cpp:159
#1  0x0000555556dafb98 in duckdb::MorselInfo::Delete (this=0x555557e05380, transaction=..., 
    table=0x555557e4df40, row_ids=..., count=960)
    at /home/jarrad/src/web/duckdb/src/storage/table/morsel_info.cpp:140
#2  0x00005555567b7362 in duckdb::DataTable::Delete (this=0x555557e4df40, table=..., 
    context=..., row_identifiers=..., count=960)
    at /home/jarrad/src/web/duckdb/src/storage/data_table.cpp:842
#3  0x0000555556d35935 in duckdb::PhysicalDelete::Sink (this=0x555557ea3570, context=..., 
    state=..., lstate=..., input=...)
    at /home/jarrad/src/web/duckdb/src/execution/operator/persistent/physical_delete.cpp:27
#4  0x00005555567985bb in duckdb::Pipeline::Execute (this=0x555557df98a0, task=...)
    at /home/jarrad/src/web/duckdb/src/parallel/pipeline.cpp:102
#5  0x000055555679ae59 in duckdb::PipelineTask::Execute (this=0x555557ecb570)
    at /home/jarrad/src/web/duckdb/src/parallel/pipeline.cpp:28
#6  0x0000555556796c7b in duckdb::Executor::Initialize (this=0x5555c2ae80b8, plan=0x555557ea3570)
    at /home/jarrad/src/web/duckdb/src/parallel/executor.cpp:49
#7  0x000055555673f8bf in duckdb::ClientContext::ExecutePreparedStatement (this=0x5555c2ae7f40, 
    lock=..., 
    query="delete\nfrom odap_tx o\nwhere not exists (\n    select l.transaction_id\n    from legacy_tx l\n    where l.transaction_id = o.transaction_id\n);", 
    statement_p=std::shared_ptr<duckdb::PreparedStatementData> (use count 2, weak count 0) = {...}, bound_values=std::vector of length 0, capacity 0, allow_stream_result=false)
    at /home/jarrad/src/web/duckdb/src/main/client_context.cpp:218
#8  0x000055555674124e in duckdb::ClientContext::RunStatementOrPreparedStatement (
    this=0x5555c2ae7f40, lock=..., 
    query="delete\nfrom odap_tx o\nwhere not exists (\n    select l.transaction_id\n    from legacy_tx l\n    where l.transaction_id = o.transaction_id\n);", 
    statement=std::unique_ptr<duckdb::SQLStatement> = {...}, 
    prepared=std::shared_ptr<duckdb::PreparedStatementData> (use count 2, weak count 0) = {...}, 
    values=0x555557eb01f8, allow_stream_result=false)
    at /home/jarrad/src/web/duckdb/src/main/client_context.cpp:395
#9  0x0000555556740927 in duckdb::ClientContext::Execute (this=0x5555c2ae7f40, 
    query="delete\nfrom odap_tx o\nwhere not exists (\n    select l.transaction_id\n    from legacy_tx l\n    where l.transaction_id = o.transaction_id\n);", 
    prepared=std::shared_ptr<duckdb::PreparedStatementData> (use count 2, weak count 0) = {...}, 
    values=std::vector of length 0, capacity 0, allow_stream_result=false)
    at /home/jarrad/src/web/duckdb/src/main/client_context.cpp:334
#10 0x0000555556748774 in duckdb::PreparedStatement::Execute (this=0x555557eaa930, 
    values=std::vector of length 0, capacity 0, allow_stream_result=false)
    at /home/jarrad/src/web/duckdb/src/main/prepared_statement.cpp:45
#11 0x0000555556419e54 in sqlite3_step (pStmt=0x555557eb01b0)
    at /home/jarrad/src/web/duckdb/tools/sqlite3_api_wrapper/sqlite3_api_wrapper.cpp:219
#12 0x0000555556402a30 in exec_prepared_stmt_columnar (p=0x7fffffffcaa0, pStmt=0x555557eb01b0)
    at /home/jarrad/src/web/duckdb/tools/shell/shell.c:12708
#13 0x0000555556403867 in exec_prepared_stmt (pArg=0x7fffffffcaa0, pStmt=0x555557eb01b0)
    at /home/jarrad/src/web/duckdb/tools/shell/shell.c:12884
#14 0x0000555556404590 in shell_exec (pArg=0x7fffffffcaa0, 
    zSql=0x555557eaa6f0 "delete\nfrom odap_tx o\nwhere not exists (\n    select l.transaction_id\n    from legacy_tx l\n    where l.transaction_id = o.transaction_id\n);", 
    pzErrMsg=0x7fffffffc928) at /home/jarrad/src/web/duckdb/tools/shell/shell.c:13200
#15 0x00005555564131ff in runOneSqlLine (p=0x7fffffffcaa0, 
    zSql=0x555557eaa6f0 "delete\nfrom odap_tx o\nwhere not exists (\n    select l.transaction_id\n    from legacy_tx l\n    where l.transaction_id = o.transaction_id\n);", in=0x0, startline=1)
    at /home/jarrad/src/web/duckdb/tools/shell/shell.c:20022
#16 0x0000555556413718 in process_input (p=0x7fffffffcaa0)
    at /home/jarrad/src/web/duckdb/tools/shell/shell.c:20122
#17 0x000055555641528c in main (argc=2, argv=0x7fffffffdd98)
    at /home/jarrad/src/web/duckdb/tools/shell/shell.c:20906
```

This is from a debug build of tag v0.2.5, and I noticed it in the 0.2.5 Python release (have not used previous released).

The table is created in the same session and in a fresh db as the deletion is attempted (so no cross version shenannigans).

I can provide the database privately if needed, it's about 2GiB.

**Comment by akdor1154** [comment]
stacktrace from duckdb itself with sanitizers enabled:
```
==3215140==ERROR: AddressSanitizer: heap-buffer-overflow on address 0x618000009ba0 at pc 0x563484051316 bp 0x7ffe00f4f9e0 sp 0x7ffe00f4f9d0                                                         
READ of size 8 at 0x618000009ba0 thread T0                                                        
    #0 0x563484051315 in std::__uniq_ptr_impl<duckdb::ChunkInfo, std::default_delete<duckdb::ChunkInfo> >::_M_ptr() const /usr/include/c++/10/bits/unique_ptr.h:173
    #1 0x5634840493e5 in std::unique_ptr<duckdb::ChunkInfo, std::default_delete<duckdb::ChunkInfo> >::get() const /usr/include/c++/10/bits/unique_ptr.h:422
    #2 0x56348407fe6e in std::unique_ptr<duckdb::ChunkInfo, std::default_delete<duckdb::ChunkInfo> >::operator bool() const /usr/include/c++/10/bits/unique_ptr.h:436
    #3 0x563484071f4b in duckdb::VersionDeleteState::Delete(long) /home/jarrad/src/web/duckdb/src/storage/table/morsel_info.cpp:155
    #4 0x5634840718e7 in duckdb::MorselInfo::Delete(duckdb::Transaction&, duckdb::DataTable*, duckdb::Vector&, unsigned long) /home/jarrad/src/web/duckdb/src/storage/table/morsel_info.cpp:140
    #5 0x563482b6275c in duckdb::DataTable::Delete(duckdb::TableCatalogEntry&, duckdb::ClientContext&, duckdb::Vector&, unsigned long) /home/jarrad/src/web/duckdb/src/storage/data_table.cpp:842
    #6 0x563483e6b5a1 in duckdb::PhysicalDelete::Sink(duckdb::ExecutionContext&, duckdb::GlobalOperatorState&, duckdb::LocalSinkState&, duckdb::DataChunk&) /home/jarrad/src/web/duckdb/src/execution/operator/persistent/physical_delete.cpp:27
    #7 0x563482ab4b78 in duckdb::Pipeline::Execute(duckdb::TaskContext&) /home/jarrad/src/web/duckdb/src/parallel/pipeline.cpp:102
    #8 0x563482ac1147 in duckdb::PipelineTask::Execute() (/home/jarrad/src/web/duckdb/build/debug/duckdb+0x83e8147)
    #9 0x563482aac7c0 in duckdb::Executor::Initialize(duckdb::PhysicalOperator*) /home/jarrad/src/web/duckdb/src/parallel/executor.cpp:49
    #10 0x56348295bef6 in duckdb::ClientContext::ExecutePreparedStatement(duckdb::ClientContextLock&, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, std::shared_ptr<duckdb::PreparedStatementData>, std::vector<duckdb::Value, std::allocator<duckdb::Value> >, bool) /home/jarrad/src/web/duckdb/src/main/client_context.cpp:218
    #11 0x563482961aab in duckdb::ClientContext::RunStatementOrPreparedStatement(duckdb::ClientContextLock&, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, std::unique_ptr<duckdb::SQLStatement, std::default_delete<duckdb::SQLStatement> >, std::shared_ptr<duckdb::PreparedStatementData>&, std::vector<duckdb::Value, std::allocator<duckdb::Value> >*, bool) /home/jarrad/src/web/duckdb/src/main/client_context.cpp:395
    #12 0x56348295f923 in duckdb::ClientContext::Execute(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, std::shared_ptr<duckdb::PreparedStatementData>&, std::vector<duckdb::Value, std::allocator<duckdb::Value> >&, bool) /home/jarrad/src/web/duckdb/src/main/client_context.cpp:334
    #13 0x563482980891 in duckdb::PreparedStatement::Execute(std::vector<duckdb::Value, std::allocator<duckdb::Value> >&, bool) /home/jarrad/src/web/duckdb/src/main/prepared_statement.cpp:45
    #14 0x563481dc76ad in sqlite3_step /home/jarrad/src/web/duckdb/tools/sqlite3_api_wrapper/sqlite3_api_wrapper.cpp:219
    #15 0x563481d72243 in exec_prepared_stmt_columnar /home/jarrad/src/web/duckdb/tools/shell/shell.c:12708
    #16 0x563481d768cc in exec_prepared_stmt /home/jarrad/src/web/duckdb/tools/shell/shell.c:12884
    #17 0x563481d799e7 in shell_exec /home/jarrad/src/web/duckdb/tools/shell/shell.c:13200
    #18 0x563481dafda3 in runOneSqlLine /home/jarrad/src/web/duckdb/tools/shell/shell.c:20022
    #19 0x563481db1163 in process_input /home/jarrad/src/web/duckdb/tools/shell/shell.c:20122
    #20 0x563481db5718 in main /home/jarrad/src/web/duckdb/tools/shell/shell.c:20906
    #21 0x7f89cafcbcb1 in __libc_start_main (/lib/x86_64-linux-gnu/libc.so.6+0x28cb1)
    #22 0x563481d1720d in _start (/home/jarrad/src/web/duckdb/build/debug/duckdb+0x763e20d)

0x618000009ba0 is located 0 bytes to the right of 800-byte region [0x618000009880,0x618000009ba0)
allocated by thread T0 here:                                                                      
    #0 0x7f89cbf1af17 in operator new(unsigned long) (/usr/lib/x86_64-linux-gnu/libasan.so.6+0xb1f17)
    #1 0x56348404abfe in std::unique_ptr<duckdb::VersionNode, std::default_delete<duckdb::VersionNode> > duckdb::make_unique<duckdb::VersionNode>() /home/jarrad/src/web/duckdb/src/include/duckdb/common/helper.hpp:22
    #2 0x563484042bfe in duckdb::TableDataReader::ReadTableData() /home/jarrad/src/web/duckdb/src/storage/checkpoint/table_data_reader.cpp:72
    #3 0x563482b4095c in duckdb::CheckpointManager::ReadTable(duckdb::ClientContext&, duckdb::MetaBlockReader&) /home/jarrad/src/web/duckdb/src/storage/checkpoint_manager.cpp:276
    #4 0x563482b3e30e in duckdb::CheckpointManager::ReadSchema(duckdb::ClientContext&, duckdb::MetaBlockReader&) /home/jarrad/src/web/duckdb/src/storage/checkpoint_manager.cpp:192
    #5 0x563482b3aec8 in duckdb::CheckpointManager::LoadFromStorage() /home/jarrad/src/web/duckdb/src/storage/checkpoint_manager.cpp:119
    #6 0x563482b8aba2 in duckdb::StorageManager::LoadDatabase() /home/jarrad/src/web/duckdb/src/storage/storage_manager.cpp:112
    #7 0x563482b88bb1 in duckdb::StorageManager::Initialize() /home/jarrad/src/web/duckdb/src/storage/storage_manager.cpp:75
    #8 0x56348297b0f5 in duckdb::DatabaseInstance::Initialize(char const*, duckdb::DBConfig*) /home/jarrad/src/web/duckdb/src/main/database.cpp:115
    #9 0x56348297b3e9 in duckdb::DuckDB::DuckDB(char const*, duckdb::DBConfig*) /home/jarrad/src/web/duckdb/src/main/database.cpp:119
    #10 0x563481ddfe95 in std::unique_ptr<duckdb::DuckDB, std::default_delete<duckdb::DuckDB> > duckdb::make_unique<duckdb::DuckDB, char const*&, duckdb::DBConfig*>(char const*&, duckdb::DBConfig*&&) (/home/jarrad/src/web/duckdb/build/debug/duckdb+0x7706e95)
    #11 0x563481dc480d in sqlite3_open_v2 /home/jarrad/src/web/duckdb/tools/sqlite3_api_wrapper/sqlite3_api_wrapper.cpp:94
    #12 0x563481d80d45 in open_db /home/jarrad/src/web/duckdb/tools/shell/shell.c:14239
    #13 0x563481db387c in main /home/jarrad/src/web/duckdb/tools/shell/shell.c:20674
    #14 0x7f89cafcbcb1 in __libc_start_main (/lib/x86_64-linux-gnu/libc.so.6+0x28cb1)

SUMMARY: AddressSanitizer: heap-buffer-overflow /usr/include/c++/10/bits/unique_ptr.h:173 in std::__uniq_ptr_impl<duckdb::ChunkInfo, std::default_delete<duckdb::ChunkInfo> >::_M_ptr() const
Shadow bytes around the buggy address:
  0x0c307fff9320: 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00
  0x0c307fff9330: 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00
  0x0c307fff9340: 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00
  0x0c307fff9350: 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00
  0x0c307fff9360: 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00
=>0x0c307fff9370: 00 00 00 00[fa]fa fa fa fa fa fa fa fa fa fa fa
  0x0c307fff9380: fa fa fa fa fa fa fa fa fa fa fa fa fa fa fa fa
  0x0c307fff9390: 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00
  0x0c307fff93a0: 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00
  0x0c307fff93b0: 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00
  0x0c307fff93c0: 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00
Shadow byte legend (one shadow byte represents 8 application bytes):
  Addressable:           00
  Partially addressable: 01 02 03 04 05 06 07 
  Heap left redzone:       fa
  Freed heap region:       fd
  Stack left redzone:      f1
  Stack mid redzone:       f2
  Stack right redzone:     f3
  Stack after return:      f5
  Stack use after scope:   f8
  Global redzone:          f9
  Global init order:       f6
  Poisoned by user:        f7
  Container overflow:      fc
  Array cookie:            ac
  Intra object redzone:    bb
  ASan internal:           fe
  Left alloca redzone:     ca
  Right alloca redzone:    cb
  Shadow gap:              cc
==3215140==ABORTING
```

**Comment by Mytherin** [comment]
Thanks for the report! I tried to reproduce this with dummy data but was not successful. Is there any chance you could share an (anonymized) version of the dataset for reproduction purposes?

**Comment by akdor1154** [comment]
Yes, how best to contact?

**Comment by Mytherin** [comment]
You can send them to my email: m.raasveldt@cwi.nl

**Comment by akdor1154** [comment]
Will do tomorrow.

**Comment by akdor1154** [comment]
Interestingly, I attempted to hash the values in these tables
to try and prepare a public repro dataset. After doing this, I could
not reproduce the crash, however the problematic delete instead threw an
error, "Conflict on tuple deletion!"

**Comment by hannes** [comment]
Closing because there has been no activity on this in a year. Feel free to comment or reopen if the issue persists.
