### ISSUE TITLE
centos 7 (multiple libs) not found

### ISSUE THREAD

**Issue by sdmcallister** [duckdb/duckdb#1708]
**What does happen?**

Tried to run the compiled linux duckdb binary. seeing messages like `version `GLIBC_2.23' not found (required by ./duckdb)`.  

**What should happen?**

Assumed it would run. 

**To Reproduce**
Steps to reproduce the behavior. Bonus points if those are only SQL queries.
1.  Download latest binary cli for linux
2.  Run.

**Environment (please complete the following information):**
 - CentOS Linux release 7.9.2009 (Core)
 - DuckDB Version 0.2.5

**Comment by hannesmuehleisen** [comment]
Can you compile from source?

**Comment by sdmcallister** [comment]
I gave it a try but the build fails. I can try to provide more details if
necessary but many libs are frustratingly outdated on centos 7.
Unfortunately I don't think I am  able to do all the updates without
breaking things.

**Comment by hannesmuehleisen** [comment]
frustratingly outdated indeed. Why exactly does the build fail?

**Comment by hannesmuehleisen** [comment]
We have actually tried this ourselves and found some issues related to the old `cmake` versions on CentOS. Will be fixed shortly.

**Comment by hannesmuehleisen** [comment]
Could you try compiling the latest `master` branch from DuckDB on your CentOS installation? We just merged a PR that should address this issue.

**Comment by hannesmuehleisen** [comment]
@sdmcallister could you confirm you can compile from source now please?

**Comment by sdmcallister** [comment]
I will try on Monday!

**Comment by sdmcallister** [comment]
@hannesmuehleisen  

Can confirm that it successfully compiled and ran.

**Comment by szarnyasg** [comment]
Since version 0.2.4, the glibc versions do not align. For a while, this has been masked by issue #1741 but not it's back:

```bash
for i in `seq 3 9`; do
    rm -f *.zip duckdb
    echo "v0.2.${i}"
    wget -q https://github.com/cwida/duckdb/releases/download/v0.2.${i}/duckdb_cli-linux-amd64.zip -O duckdb_cli-linux-amd64.zip
    unzip duckdb_cli-linux-amd64.zip
    ./duckdb
done
```

```
v0.2.3
Archive:  duckdb_cli-linux-amd64.zip
  inflating: duckdb                  
0.2.4-dev0 436f6455f
Enter ".help" for usage hints.
Connected to a transient in-memory database.
Use ".open FILENAME" to reopen on a persistent database.
D 
D 

v0.2.4
Archive:  duckdb_cli-linux-amd64.zip
  inflating: duckdb                  
./duckdb: /lib64/libm.so.6: version `GLIBC_2.23' not found (required by ./duckdb)
v0.2.5
Archive:  duckdb_cli-linux-amd64.zip
  inflating: duckdb                  
./duckdb: error while loading shared libraries: libssl.so.1.1: cannot open shared object file: No such file or directory
v0.2.6
Archive:  duckdb_cli-linux-amd64.zip
  inflating: duckdb                  
./duckdb: error while loading shared libraries: libssl.so.1.0.0: cannot open shared object file: No such file or directory
v0.2.7
Archive:  duckdb_cli-linux-amd64.zip
  inflating: duckdb                  
./duckdb: error while loading shared libraries: libssl.so.1.1: cannot open shared object file: No such file or directory
v0.2.8
Archive:  duckdb_cli-linux-amd64.zip
  inflating: duckdb                  
./duckdb: error while loading shared libraries: libssl.so.1.1: cannot open shared object file: No such file or directory
v0.2.9
Archive:  duckdb_cli-linux-amd64.zip
  inflating: duckdb                  
./duckdb: error while loading shared libraries: libssl.so.1.1: cannot open shared object file: No such file or directory
```

**Comment by kiwimg** [comment]
CentOS Linux release 7.8.2003 (Core)
Tried to run the compiled linux duckdb binary. seeing messages like version GLIBC_2.23' not found (required by ./duckdb)`.

**Comment by kiwimg** [comment]
Caused by: java.lang.UnsatisfiedLinkError: /tmp/libduckdb_java14323493553335981.so: /lib64/libm.so.6: version `GLIBC_2.23' not found (required by /tmp/libduckdb_java14323493553335981.so)
	at java.base/java.lang.ClassLoader$NativeLibrary.load0(Native Method) ~[na:na]
	at java.base/java.lang.ClassLoader$NativeLibrary.load(ClassLoader.java:2430) ~[na:na]
	at java.base/java.lang.ClassLoader$NativeLibrary.loadLibrary(ClassLoader.java:2487) ~[na:na]
	at java.base/java.lang.ClassLoader.loadLibrary0(ClassLoader.java:2684) ~[na:na]
	at java.base/java.lang.ClassLoader.loadLibrary(ClassLoader.java:2617) ~[na:na]
	at java.base/java.lang.Runtime.load0(Runtime.java:765) ~[na:na]
	at java.base/java.lang.System.load(System.java:1835) ~[na:na]
	at org.duckdb.DuckDBNative.<clinit>(DuckDBNative.java:43) ~[duckdb_jdbc-0.3.3.jar!/:na]
	at org.duckdb.DuckDBDatabase.<init>(DuckDBDatabase.java:22) ~[duckdb_jdbc-0.3.3.jar!/:na]
	at org.duckdb.DuckDBDriver.connect(DuckDBDriver.java:35) ~[duckdb_jdbc-0.3.3.jar!/:na]
	at com.alibaba.druid.filter.FilterChainImpl.connection_connect(FilterChainImpl.java:156) ~[druid-1.2.8.jar!/:1.2.8]
	at com.alibaba.druid.filter.stat.StatFilter.connection_connect(StatFilter.java:251) ~[druid-1.2.8.jar!/:1.2.8]
	at com.alibaba.druid.filter.FilterChainImpl.connection_connect(FilterChainImpl.java:150) ~[druid-1.2.8.jar!/:1.2.8]
	at com.alibaba.druid.pool.DruidAbstractDataSource.createPhysicalConnection(DruidAbstractDataSource.java:1659) ~[druid-1.2.8.jar!/:1.2.8]
	at com.alibaba.druid.pool.DruidAbstractDataSource.createPhysicalConnection(DruidAbstractDataSource.java:1723) ~[druid-1.2.8.jar!/:1.2.8]
	at com.alibaba.druid.pool.DruidDataSource.init(DruidDataSource.java:927) ~[druid-1.2.8.jar!/:1.2.8]
	at com.alibaba.druid.pool.DruidDataSource.getConnection(DruidDataSource.java:1401) ~[druid-1.2.8.jar!/:1.2.8]

**Comment by hannes** [comment]
> Caused by: java.lang.UnsatisfiedLinkError: /tmp/libduckdb_java14323493553335981.so: /lib64/libm.so.6: version `GLIBC_2.23' not found (required by /tmp/libduckdb_java14323493553335981.so)

Can you recompile on your platform to address this?

**Comment by darked89** [comment]
Hello,

No idea if this is a viable option, but at least few command line utils written in Rust (ripgrep, choose, bat) provide executables linked to musl library. 

Since old Centos can be found on at least a handful of HPC clusters at times with extra restrictions compiling programs can be problematic. 

Best,

DK

**Comment by hannes** [comment]
@darked89 its an interesting option to get out of this glib hell @Mytherin @samansmink lets discuss

**Comment by cebaa** [comment]
Note that this seems to be the case with Red Hat line of distributions. Looks like they tend to keep the same glibc across minor versions. 

[RHEL release dates](https://access.redhat.com/articles/3078)

RHEL 8.0 released on 2019-05-07 has [glibc-2.28-42.el8.x86_64.rpm](https://distrowatch.com/table.php?distribution=redhat&pkglist=true&version=rhel-8.0#pkglist)

RHEL 8.6 released on 2022-05-10 has [glibc-2.28-189.1.el8.x86_64.rpm](https://distrowatch.com/table.php?distribution=redhat&pkglist=true&version=rhel-8.6#pkglist)

RHEL 9.0 released on 2022-05-17 has [glibc-2.34-28.el9_0.x86_64.rpm](https://distrowatch.com/table.php?distribution=redhat&pkglist=true&version=rhel-9.0#pkglist)

Apparently, duckdb requires at least glibc 2.29:

```
Error: /lib64/libm.so.6: version `GLIBC_2.29' not found
```

Given how recent RHEL 9.0 is and how risk-averse / slow many places are with regards to upgrades, it's safe to assume stock duckdb build will not be usable for people on RHEL (and probably derivatives) for a very long time. At which time, it will probably stop working because a newer glibc will be released. :)

So hopefully a musl build is an option. Or perhaps having another build with an older glibc.

**Comment by darked89** [comment]
While precompiled  (with musl?) single duckDB executable would be a desired solution, maybe there can be some stop gap hack:
https://stackoverflow.com/questions/847179/multiple-glibc-libraries-on-a-single-host

meaning: 
1. duckDB compiled with some newish X version of glibc
2. instructions how to get  & compile  without sudo the required by duckdb glibc 

I assume that going back in time and trying to modify duckdb code to be compatible with ancient P, Q, R versions of glibc possible to encounter in the wild is more costly than compile some new version of glibc. But frankly I have not checked it.

I would also suggest putting duckDB image on DockerHub. Most of the HPCs should have Singularity installed, so this is another way to run it.

Hope it helps,

Darek Kedra

**Comment by kiwimg** [comment]
update to centos 8 ok?

**Comment by zerbfra** [comment]
I'm revaming this closed issue since the same error happens on AWS Lambda (even with a custom Dockerfile with their image).

`Error: /lib64/libm.so.6: version `GLIBC_2.29' not found`

Amazon Linux 2 is running glibc 2.26.

Any help?

**Comment by pbowyer** [comment]
Having to build from source for a Centos 7 machine, a MUSL build would be greatly appreciated 🙏
