### ISSUE TITLE
Arrow Error Propagation Causing Query Hangs

### ISSUE THREAD

**Issue by pdet** [duckdb/duckdb#2055]
When an Arrow Scan fails, the error is not propagated up to DuckDB, causing the arrow_array_stream.get_next call to hang forever.

I've only managed to reproduce this error on Arrow's Taxi Dataset Example. I've tried handcrafting this error for test cases, but then they were correctly captured in our GetNextChunk function.
``` cpp
unique_ptr<ArrowArrayWrapper> ArrowArrayStreamWrapper::GetNextChunk() {
	auto current_chunk = make_unique<ArrowArrayWrapper>();
	if (arrow_array_stream.get_next(&arrow_array_stream, &current_chunk->arrow_array)) { // LCOV_EXCL_START
		throw InvalidInputException("arrow_scan: get_next failed(): %s", string(GetError()));
	} // LCOV_EXCL_STOP

	return current_chunk;
}
```
To download the dataset:
``` R
library(arrow)
dir <- "taxi-data-sample"
copy_files("s3://ursa-labs-taxi-data/2018", file.path(dir, "2018"))
``` 

The code that hangs when snappy is not installed (Error that should be propagated NotImplemented: Support for codec 'snappy' not built):
``` R
library(arrow)
library(duckdb)

dir <- "taxi-data-sample"

ds <- open_dataset(dir, partitioning = c("year", "day"))

con <- dbConnect(duckdb::duckdb())
dbExecute(con, "PRAGMA threads=8")
duckdb_register_arrow(con, "mydatasetreader", ds)
result <- dbGetQuery(con, "SELECT count(*) FROM mydatasetreader")
```

This problem seems to be error-agnostic as well since the following will also hang but due to a different error (Error that should be propagated NotImplemented: Unsupported cast from string to null using function cast_null):

``` R
library(arrow)
library(duckdb)

dir <- "taxi-data-sample"

ds <- open_dataset(dir, partitioning = c("year", "day"))

con <- dbConnect(duckdb::duckdb())
dbExecute(con, "PRAGMA threads=8")
duckdb_register_arrow(con, "mydatasetreader", ds)
result <- dbGetQuery(con, " SELECT rate_code_id FROM mydatasetreader")
```

cc @jonkeane @nealrichardson

**Comment by jonkeane** [comment]
This matches exactly what I've seen+experienced as well. How were you handcrafting the errors in tests? Maybe there's some way that that slightly differs from the implementation for raising that we use.

**Comment by pdet** [comment]
One of the things I tried was to just open a problematic parquet file and generate another file from a subset of the data.

``` python
ds_dir = "taxi-data-sample/2018/01/data.parquet"
userdata_parquet_dataset = ds.dataset(ds_dir, format = "parquet").to_table()
pq.write_to_dataset(userdata_parquet_dataset,"data.parquet")
```

What is interesting here, is that I basically read and write the whole file, but the written one emits errors as expected. 

I've also tried to remove the partitioning when reading the dataset but that does not have any effect
``` R
ds <- open_dataset(dir, partitioning = c("year", "day"))
```

``` R
ds <- open_dataset(dir)
```

**Comment by jonkeane** [comment]
Aaah yeah, the null column is due to a slight schema change at some point in the first year (I don't remember exactly which month it's in off the top of my head).

However thinking about this more I realized that since it's a casting error, we can actually trigger it with an even smaller dataset by purposefully mis-specifying the schema. Below I create a dataset with the userdata1.parquet from the duckdb r package tests repeated 25 times. I use `rep("duckdb/tools/rpkg/tests/testthat/userdata1.parquet", 25)` so that there are multiple files that the scanning iterates over. The behavior I experienced with one file was that most of the time it propagated the error correctly, though it would hang from time to time. But if I used more files it would hang much more reliably.

```
library(arrow)
library(dplyr)
library(duckdb)

tab <- open_dataset(rep("duckdb/tools/rpkg/tests/testthat/userdata1.parquet", 25), schema = schema(id = null()))

tab %>% 
  to_duckdb() %>%
  collect()
```

**Comment by pdet** [comment]
Thanks Jon! That indeed hangs! This is the test case I have for this 
``` R
library("testthat")
library("DBI")
library ("dplyr")

test_that("does this hang", {
    skip_on_os("windows")
    skip_if_not_installed("arrow", "4.0.1")
    
    con <- dbConnect(duckdb::duckdb())
    a <- rep("userdata1.parquet", 25)
    arrow_table <- arrow::open_dataset(a, arrow::schema(first_name=arrow::null()))
    # arrow_table %>% select(first_name) %>% collect()
    duckdb::duckdb_register_arrow(con, "testarrow", arrow_table)
    
    # Try ==
    dbGetQuery(con, "SELECT first_name from testarrow")

    duckdb::duckdb_unregister_arrow(con, "testarrow")
    dbDisconnect(con, shutdown = T)
}) 
```
Will check what happens on python land as well

**Comment by hannesmuehleisen** [comment]
Indeed @pdets case hangs for me too. Looks like we found our culprit.

**Comment by pdet** [comment]
I've managed to get the same behavior in the python front.

It seems to be a deadlock when getting to the get next batches within the arrow scans
``` 0  0x00007fa3a5cc3e92 in pthread_cond_wait@@GLIBC_2.3.2 () from /lib64/libpthread.so.0
#1  0x00007fa3a3de77d0 in std::condition_variable::wait(std::unique_lock<std::mutex>&) () from /lib64/libstdc++.so.6
#2  0x00007fa39f5fb38b in arrow::dataset::ScanBatchesState::Pop() () from /export/scratch1/home/holanda/R/x86_64-redhat-linux-gnu-library/4.0/arrow/libs/arrow.so
#3  0x00007fa39f5bffe7 in arrow::Result<arrow::dataset::TaggedRecordBatch> arrow::Iterator<arrow::dataset::TaggedRecordBatch>::Next<arrow::FunctionIterator<arrow::dataset::SyncScanner::ScanBatches(arrow::Iterator<std::shared_ptr<arrow::dataset::ScanTask> >)::{lambda()#1}, arrow::dataset::TaggedRecordBatch> >(void*) () from /export/scratch1/home/holanda/R/x86_64-redhat-linux-gnu-library/4.0/arrow/libs/arrow.so
#4  0x00007fa39f596fb7 in arrow::dataset::(anonymous namespace)::ScannerRecordBatchReader::ReadNext(std::shared_ptr<arrow::RecordBatch>*) () from /export/scratch1/home/holanda/R/x86_64-redhat-linux-gnu-library/4.0/arrow/libs/arrow.so
#5  0x00007fa39fa156cc in arrow::(anonymous namespace)::ExportedArrayStream::StaticGetNext(ArrowArrayStream*, ArrowArray*) () from /export/scratch1/home/holanda/R/x86_64-redhat-linux-gnu-library/4.0/arrow/libs/arrow.so

#6  0x00007fa3a1b6064a in duckdb::ArrowArrayStreamWrapper::GetNextChunk (this=0x5587c5a1b0b0) at /export/scratch1/home/holanda/duckdb/src/common/arrow_wrapper.cpp:56
```

**Comment by jonkeane** [comment]
I took a look at this, and indeed, I can reproduce this hang using the Arrow R package + pyarrow package. I've created [a Jira for it](https://issues.apache.org/jira/browse/ARROW-13480), and will see that someone on the Arrow side takes a look at it.
