### ISSUE TITLE
CSV with Chinese name cannot copy into DuckDB in Windows

### ISSUE THREAD

**Issue by yxmm-wxe** [duckdb/duckdb#2628]
Environment: Linux
Version: 0.3.1 duckdb_jdbc
Test SQL: 
```
copy "中文" from 'temp/中文_1637219468798.csv' (DELIMITER ',', QUOTE '"', ESCAPE '"', HEADER)
```
Test Result: Successful

---

Environment: Windows
Version: 0.3.1 duckdb_jdbc
Test SQL: 
```
copy "中文" from 'temp\中文_1637219468798.csv' (DELIMITER ',', QUOTE '"', ESCAPE '"', HEADER)
```
Test Result:
```
java.sql.SQLException: IO Error: No files found that match the pattern "temp\中文_1637220463030.csv"
	at org.duckdb.DuckDBNative.duckdb_jdbc_prepare(Native Method) ~[duckdb_jdbc-0.3.1.jar:?]
	at org.duckdb.DuckDBPreparedStatement.prepare(DuckDBPreparedStatement.java:73) ~[duckdb_jdbc-0.3.1.jar:?]
	at org.duckdb.DuckDBPreparedStatement.<init>(DuckDBPreparedStatement.java:55) ~[duckdb_jdbc-0.3.1.jar:?]
	at org.duckdb.DuckDBConnection.prepareStatement(DuckDBConnection.java:55) ~[duckdb_jdbc-0.3.1.jar:?]
	at org.duckdb.DuckDBConnection.prepareStatement(DuckDBConnection.java:168) ~[duckdb_jdbc-0.3.1.jar:?]
```
The file ‘temp\中文_1637220463030.csv’ indeed exist.

If the file name doesn't contain Chinese, the statement will be executed successfully.

Part of my sample code for generating the copy statement:

```java
public static void main(String[] args) {
        String tableName = "中文";
        String tempFilePath = "temp" + System.getProperty("file.separator") + getTempCsvFileName(tableName);

        String sql = buildCopyStatement(tableName, tempFilePath);
}

private static String buildCopyStatement(String tableName, String tempFilePath) {
        return "copy \"" + tableName + "\" from '" + tempFilePath + "' (DELIMITER ',', QUOTE '\"', ESCAPE '\"', HEADER)";
}

private static String getTempCsvFileName(String tableName) {
        return tableName + "_" + System.currentTimeMillis() + ".csv";
}
```

I'd like to know if it is an issue with my code or DuckDB.

_Originally posted by @yxmm-wxe in https://github.com/duckdb/duckdb/discussions/2624_

**Comment by akdor1154** [comment]
It looks like DuckDB assumes sane filesystem access APIs, which is not true for Windows unfortunately.
For now, maybe this would work as a workaround? Referencing code from https://stackoverflow.com/a/21817846 . I don't have a Windows system here to test though, sorry.
```java
String tempFilePathShort = GetShortPathName(tempFilePath);
String sql = buildCopyStatement(tableName, tempFilePathShort)
```

**Comment by Mytherin** [comment]
This should be fixed in the master now. Thanks for the report!
