### ISSUE TITLE
JDBC import database error

### ISSUE THREAD

**Issue by Cinzq4615** [duckdb/duckdb#3273]
#### What happens?
JDBC import database error

#### To Reproduce
`@Test 
   public void importDuckDB() throws SQLException, IOException { 

       final String EXPORT_SQL_TEMPLATE = "EXPORT DATABASE '%s' (FORMAT PARQUET);"; 
       String path = "export"; 
       File export = new File(path); 
       if (export.exists()) { 
           export.delete(); 
       } 
       export.mkdir(); 
       System.out.println(export.getAbsolutePath()); 
       try (Connection conn = DriverManager.getConnection("jdbc:duckdb:db001"); Statement stmt = conn.createStatement();) { 
           stmt.execute("CREATE SCHEMA IF NOT EXISTS mydb"); 
           stmt.execute("CREATE TABLE IF NOT EXISTS mydb.student(id INTEGER,name VARCHAR,PRIMARY KEY(id))"); 
           stmt.execute(String.format(EXPORT_SQL_TEMPLATE, path)); 
       } 

       final String IMPORT_SQL_TEMPLATE = "IMPORT DATABASE '%s';"; 

       try (Connection conn = DriverManager.getConnection("jdbc:duckdb:db002"); Statement stmt = conn.createStatement();) { 
           stmt.execute(String.format(IMPORT_SQL_TEMPLATE, path)); 
       } 

   }

error info:
java.sql.SQLException: Cannot prepare multiple statements at once! 

     at org.duckdb.DuckDBNative.duckdb_jdbc_prepare(Native Method) 
     at org.duckdb.DuckDBPreparedStatement.prepare(DuckDBPreparedStatement.java:73) 
     at org.duckdb.DuckDBPreparedStatement.execute(DuckDBPreparedStatement.java:121)
`

#### Environment (please complete the following information):
 - OS: win10
 - DuckDB Version: 0.3.1
 - DuckDB Client: jdbc-0.3.1

**Comment by Alex-Monahan** [comment]
Thanks for using DuckDB! Does this same issue happen on version 0.3.2?

**Comment by Cinzq4615** [comment]
> Thanks for using DuckDB! Does this same issue happen on version 0.3.2?

yes,this same issue also  happen on version 0.3.2

**Comment by rsund** [comment]
Probably needs something similar than in #1102 and #3107.

**Comment by rsund** [comment]
In any case, you could try to execute the statements in `schema.sql` and `load.sql` (generated by `EXPORT` to the same folder as exported tables) manually (or in a loop) one by one.
