### ISSUE TITLE
org.apache.kafka.connect.errors.ConnectException: null (STRING) type doesn't have a mapping to the SQL database column type

### ISSUE THREAD

**Issue by hzzxcw** [duckdb/duckdb#3325]
I am trying out debezium to sync a mysql database to duckdb.
However, I got the following errors:
```
org.apache.kafka.connect.errors.ConnectException: null (STRING) type doesn't have a mapping to the SQL database column type

at io.confluent.connect.jdbc.dialect.GenericDatabaseDialect.getSqlType(GenericDatabaseDialect.java:1918)

at io.confluent.connect.jdbc.dialect.GenericDatabaseDialect.writeColumnSpec(GenericDatabaseDialect.java:1834)

at io.confluent.connect.jdbc.dialect.GenericDatabaseDialect.lambda$writeColumnsSpec$39(GenericDatabaseDialect.java:1823)

at io.confluent.connect.jdbc.util.ExpressionBuilder.append(ExpressionBuilder.java:560)

at io.confluent.connect.jdbc.util.ExpressionBuilder$BasicListBuilder.of(ExpressionBuilder.java:599)

at io.confluent.connect.jdbc.dialect.GenericDatabaseDialect.writeColumnsSpec(GenericDatabaseDialect.java:1825)

at io.confluent.connect.jdbc.dialect.GenericDatabaseDialect.buildCreateTableStatement(GenericDatabaseDialect.java:1742)

at io.confluent.connect.jdbc.sink.DbStructure.create(DbStructure.java:121)

at io.confluent.connect.jdbc.sink.DbStructure.createOrAmendIfNecessary(DbStructure.java:67)

at io.confluent.connect.jdbc.sink.BufferedRecords.add(BufferedRecords.java:123)

at io.confluent.connect.jdbc.sink.JdbcDbWriter.write(JdbcDbWriter.java:74)

at io.confluent.connect.jdbc.sink.JdbcSinkTask.put(JdbcSinkTask.java:84)

at org.apache.kafka.connect.runtime.WorkerSinkTask.deliverMessages(WorkerSinkTask.java:581)

at org.apache.kafka.connect.runtime.WorkerSinkTask.poll(WorkerSinkTask.java:329)

at org.apache.kafka.connect.runtime.WorkerSinkTask.iteration(WorkerSinkTask.java:232)

at org.apache.kafka.connect.runtime.WorkerSinkTask.execute(WorkerSinkTask.java:201)

at org.apache.kafka.connect.runtime.WorkerTask.doRun(WorkerTask.java:182)

at org.apache.kafka.connect.runtime.WorkerTask.run(WorkerTask.java:231)

at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515)

at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)

at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)

at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)

at java.base/java.lang.Thread.run(Thread.java:829)
```

And for Sqlite, It worked well.

I am wondering whether it is technically feasible to achieve synchronization from MySQL to DuckDB.

**Comment by Alex-Monahan** [comment]
Very interesting use case!

I don't have a solution, but I do have a workaround idea.

We just released a way to scan SQLite databases and do the query processing in DuckDB. That allows SQLite to handle the many small transactions from CDC (alongside reads, using their WAL mode), and DuckDB to handle the analytics! 
[SQLite Scanner](https://github.com/duckdblabs/sqlitescanner)

**Comment by hannes** [comment]
I mean `null (STRING) type doesn't have a mapping to the SQL database column type` kind of tells you what's up. Can you set those mappings somewhere?

**Comment by hzzxcw** [comment]
> Very interesting use case!
> 
> I don't have a solution, but I do have a workaround idea.
> 
> We just released a way to scan SQLite databases and do the query processing in DuckDB. That allows SQLite to handle the many small transactions from CDC (alongside reads, using their WAL mode), and DuckDB to handle the analytics! One challenge to bear in mind with DuckDB for CDC is that the same process that is receiving the CDC statements also needs to be the one that is doing analytical reads. DuckDB can either have 1 process doing read/write, or multiple read only processes. [SQLite Scanner](https://github.com/duckdblabs/sqlitescanner)

thank you very much,i'll try it.

**Comment by Jens-H** [comment]
The GenericDatabaseDialect.java implementation of getSqlType does not look very promising:

`protected String getSqlType(SinkRecordField f) {
    throw new ConnectException(String.format(
        "%s (%s) type doesn't have a mapping to the SQL database column type", f.schemaName(),
        f.schemaType()
    ));
  }`

**Comment by hannes** [comment]
Maybe its possible to set the postgres dialect in debezium? Might work. There is indeed not much we can do from our side.
