### ISSUE TITLE
"Resource temporarily unavailable error" showing up seemingly at random

### ISSUE THREAD

**Issue by jlorince** [duckdb/duckdb#3391]
#### What happens?
Using the python bindings, we will occasionally get a "resource temporarily unavailable" error when running:

`con = duckdb.connect(database=":memory:", read_only=False)`

I've searched the GitHub repo for this error message and couldn't find it, so am pretty confused as to what is going on here. Can you shed any light on this? This is happening before we try running a query or doing anything with the connection.

#### To Reproduce
N/a....as far as I can tell it happens at random.

#### Environment (please complete the following information):
 - OS: [e.g. iOS]: Debian
 - DuckDB Version: [e.g. 22]: 0.3.1
 - DuckDB Client: [e.g. Python]: python

#### Before Submitting

- [ ] **Have you tried this on the latest `master` branch?**
* **Python**: `pip install duckdb --upgrade --pre`
* **R**: `install.packages("https://github.com/duckdb/duckdb/releases/download/master-builds/duckdb_r_src.tar.gz", repos = NULL)`
* **Other Platforms**: You can find binaries [here](https://github.com/duckdb/duckdb/releases/tag/master-builds) or compile from source.

- [ ] **Have you tried the steps to reproduce? Do they include all relevant data and configuration? Does the issue you report still appear there?**

**Comment by Alex-Monahan** [comment]
Hello! 

Sorry you are running into this. Could you try the latest master branch and see if you have the same problem?

```python
pip install duckdb --pre --upgrade
```

**Comment by jlorince** [comment]
Happy to try but this happens irregularly  (it's actually one of our customers at Hex that hit it), so i can't reproduce on my local machine on master or 0.3.1. Our one hypothesis is that this is an OOM issue. Would you expect that error if trying to create a connection when there is low free memory?

**Comment by maclockard** [comment]
We've also started to see this error with R bindings as well:
```
Error in h(simpleError(msg, call)): error in evaluating the argument 'drv' in selecting a method for function 'dbConnect': duckdb_startup_R: Failed to open database: Resource temporarily unavailable
```

**Comment by ccolgrove** [comment]
hi @hannes I'd also like to bump this one – we're still seeing it unfortunately

**Comment by hannes** [comment]
Hi team hex, happy to have another look at this, but we cannot reproduce this with the information in this issue. Is there any more information you could share?

**Comment by hannes** [comment]
The error message is a bit confusing, because it points to `EAGAIN`, which seems to be mostly caused by non-blocking IO, which DuckDB does not use. Are you running DuckDB on a VM with a remote hard disk?

**Comment by RAbraham** [comment]
I can confirm this too.
```
self.con = duckdb.connect("full path"])

```
I get
```
RuntimeError: IO Error: Could not set lock on file "/home/rajiv/Documents/dev/bht/ml-evaluation/indexing/db/prod/metrics.db": Resource temporarily unavailable

```

I'm on `0.3.1`. I tried both on our ssd drive and main drive.

**Comment by jlorince** [comment]
Hi @hannes bringing this back to your attention again because it's started cropping up for us (again, seemingly at random). Apologies for missing your last question when you commented, but no I don't think the scenario you describe applies to us (we're running in a k8s container in EKS). FWIW we are seeing this more on small kernels (2-4GB RAM), so I wonder if this could be a memory issue? Would you expect this error possibly if there was insufficient available memory?

**Comment by hannes** [comment]
We have had some reports regarding issues on Kubernetes. Is this still happening with the latest dev version of DuckDB? Are you setting a memory limit and temp directories?

**Comment by jlorince** [comment]
We definitely have memory limits set, but what exactly do you mean re: temp directories? We're currently using duckdb 0.4.0

**Comment by jlorince** [comment]
Unfortunately difficult to do that because the issue only happens on our deployed infra, so I can't just push the dev version. We'll be updating to 0.5.1 soon, though, so hopefully that helps

**Comment by hannes** [comment]
I would recommend going straight to 0.6.0 once it's out on Monday If I may recommend something

**Comment by evanzummeren** [comment]
Was dealing with the same error using the nodejs bindings and duckdb 0.6.0. In my case the fix was pretty straightforward: I was creating new database connections for every query and forgot to close them.

**Comment by stemangiola** [comment]
I understand that new database connections should not be created for every query, but since many people do, is there a solution to that? It seems that once the error pops up there is nothing we can do, to drop old connections.

**Comment by Mytherin** [comment]
I’m happy to have another look at this issue but we haven’t been able to reproduce it ourselves. Do you have a reproducible example you could share?

**Comment by stemangiola** [comment]
I agree it is not easy to reproduce (I did a quick stress test and nothing), but I bet that if you stop saving connection in a variable and pipe from a new connection, you will encounter it soon.

Even if the behaviour is rare, it is very impactful. When it happens, the only apparent solution I found is to restart the session (detaching the package does not work), which sometimes can hold 40 Gb of analyses and many hours of work.

**Comment by SphtKr** [comment]
I may have a reproducible case, of this or something very much like it. I have hit this the last three or four times (consistently) in a script to import the MIMIC-III clinical dataset into a DuckDB database file... 

https://github.com/MIT-LCP/mimic-code/blob/206c0f7375e181e3928fdfd9559fcf6eb2cabb4e/mimic-iii/buildmimic/duckdb/import_duckdb.py#L309-L323

What I'm doing may not be the best way, but I close the DB in a `finally` block (in case any exceptions occurred and then immediately reopen it again--and the reopen is getting `RuntimeError: Resource temporarily unavailable` on the `.connect` call. The previous set of operations, if they succeed, load a large amount of data and create some large indexes... so I am inferring that the close call is not "finishing" somehow at the OS level?

This is Ubuntu 22.04, DuckDB 0.7.1 from PyPI, and--perhaps relevant--the DB file has been written both to an EXT4 volume on an LVM LV (on a NVMe SSD) and onto an exFAT drive attached to USB. I have 64GB RAM +64GB swap (partition) configured and this process does take a large amount of RAM. To really reproduce my case you would need to get the full MIMIC-III dataset, which is not open access, though.

Anything I can do easily to capture some kind of evidence? I'm moderately familiar with things like GDB but don't have a lot of experience debugging Python internals.

**Comment by maclockard** [comment]
bump

**Comment by zhuwenxing** [comment]
I can reproduce this issue by running the following script repeatedly
```
import duckdb
con = duckdb.connect('demo.db')
```
In the first run, it works well, but in second run, it reports error `duckdb.duckdb.IOException: IO Error: Could not set lock on file "/xxx": Resource temporarily unavailable`

I guess the reason maybe that I did not close the connection. Because It works well after adding `con.close()`

```
import duckdb
con = duckdb.connect('demo.db')
con.close()
```
But the problem is that, if I made a mistake like l did not close the connect, then this db file can not be used anymore and I have no solution for it.

**Comment by stemangiola** [comment]
> But the problem is that, if I made a mistake like l did not close the connect, then this db file can not be used anymore and I have no solution for it.

I second. It would be highly desirable that `duckdb` is robust to very-large (infinite) calls to `duckdb.connect`.

**Comment by hannes** [comment]
@zhuwenxing which OS are you running this on?

**Comment by szarnyasg** [comment]
@zhuwenxing can you please share the OS you encountered this issue on? It would really help narrow down the scope and catch this elusive issue.

**Comment by zhuwenxing** [comment]
> can you please share the OS you encountered this issue on? It would really help narrow down the scope and catch the root cause of this elusive issue.

@szarnyasg 
It is MacBook Pro 2020 with macOS 13.4.1

**Comment by szarnyasg** [comment]
So it's an Intel MBP. Thanks!

**Comment by bencarpena** [comment]
Error persists for me too... Resource temporarily unavailable

**Comment by ila** [comment]
same here, was developing my extension with a pre-existing and while it runs just fine in debug mode, it gives me this error in release. what I tried so far: activating and deactivating the python venv, deleting and recreating the database, nothing works. ubuntu 23.04, intel i7 12th gen

**Comment by Mytherin** [comment]
Could you share the full error you receive? Or is it only `Resource temporarily unavailable`? I suspect this might be file-system dependent and have to do with file locks.

**Comment by ila** [comment]
yes, the error was just this. ANYWAY I think I fixed it - the problem was the WAL, probably the WAL file was still somehow attached to the previous database file (created in debug mode???) so even though I did delete the file, the WAL was still there and that was the unavailable resource, not the database itself (this explanation still doesn't make any sense to me but I am confident the WAL is the culprit here so maybe if anyone else has this problem, this information can help)

deleting the WAL fixed my particular use case :)

**Comment by ila** [comment]
there's no database file - I am creating it from scratch by just passing it in the CLI.

restarting the laptop didn't help either. 

changing path doesn't help either.

it's funny because in debug mode, whatever I do just works, just tried again and I am beyond confused

**Comment by ila** [comment]
did not try with `reldebug` (yet) but manually switching cmake targets (eg, compiling duckdb/shell first, and then my extension in `release` fixed it. so perhaps it's a makefile issue with the new extension loading method? (note that I was recompiling all targets in every single step of this, I would *hope* I am not that underslept to only compile 1 extension in release mode and the rest in debug)

another funny thing I noticed is that  even though I clicked on "compile all targets" in clion and executing shell, the extension was still loaded compiled in debug mode (all my #debug stuff was still there). recompiling it in release once again worked.

at this point this is beyond my knowledge but I'll consider it fixed (for now), although if some of your customers is still having this problem I might still be able to provide (or reproduce) the issue and debug it further. let me know :)

**Comment by shribe** [comment]
I see this error when:

- duckdb invoked with long-running query as subprocess from some higher-level language
- parent process quits
- duckdb does not quit immediately--keeps running for a length of time that suggests it is running the query to completion

After that duckdb process terminates, the error goes away, new duckdb process can be started.

**Comment by AKhileshPothuri** [comment]
Hey guys,
I faced the same issue with the latest `Master` branch as well. In my case, I have been creating a new connection everytime my user gives an input. What worked for me was closing the connection once the task is completed, (or) creating one connection in my main class and using the same connection to perform the similarity search everytime I get a new input. Hope this helps!

**Comment by Mytherin** [comment]
Could you share on what OS you were running that you encountered this error, and what the exact error is?

**Comment by AKhileshPothuri** [comment]
> Could you share on what OS you were running that you encountered this error, and what the exact error is?

I was running it on my Linux virtual machine. The error I encountered was `Runtime Error: Resource temporarily unavailable` . This was point to the `self._conn= duckdb.connect() `  in the `duckdb.py` file.

**Comment by Mytherin** [comment]
Which version of Linux? Could you share the output of:

```py
import platform
print(platform.platform())
```

**Comment by AKhileshPothuri** [comment]
3.10.0

**Comment by AKhileshPothuri** [comment]
> 3.10.0



> Thanks! Which version of Linux? Could you share the output of:
> 
> ```python
> import platform
> print(platform.platform())
> ```

3.10.0

**Comment by Mytherin** [comment]
Ah I meant the exact version of Linux (i.e. Ubuntu LTS 22, or similar). That seems like the Python version?

**Comment by Mytherin** [comment]
I think I have figured this out now - the problem is that Linux/MacOS have a system-wide thread limit. DuckDB creates background threads when a new database object is created, so if you are creating many (in-memory) databases and not closing them you are creating new threads until the thread limit is reached. At some point you can run out of system threads, e.g.:

```py
import duckdb
l = []
l.append(duckdb.connect())

for i in range(100000000):
    l.append(duckdb.connect())

``` 

Eventually runs into:

```
Traceback (most recent call last):
  File "/Users/myth/Programs/duckdb/test.py", line 7, in <module>
RuntimeError: thread constructor failed: Resource temporarily unavailable
```

I have a fix up for this here now that catches this situation and stops launching background threads in this case - https://github.com/duckdb/duckdb/pull/11236

**Comment by shribe** [comment]
> I think I have figured out at least one instance of this error - the problem is that Linux/MacOS have a system-wide thread limit. 

To be clear, this was not my problem. I was doing one db at a time.

**Comment by AKhileshPothuri** [comment]
> I think I have figured out at least one instance of this error - the problem is that Linux/MacOS have a system-wide thread limit. DuckDB creates background threads when a new database object is created, so if you are creating many (in-memory) databases and not closing them you are creating new threads until the thread limit is reached. At some point you can run out of system threads, e.g.:
> 
> ```python
> import duckdb
> l = []
> l.append(duckdb.connect())
> 
> for i in range(100000000):
>     l.append(duckdb.connect())
> ```
> 
> Eventually runs into:
> 
> ```
> Traceback (most recent call last):
>   File "/Users/myth/Programs/duckdb/test.py", line 7, in <module>
> RuntimeError: thread constructor failed: Resource temporarily unavailable
> ```
> 
> I have a fix up for this here now that catches this situation and stops launching background threads in this case - #11236

I update duckdb to 0.10.1 to get this fix, but I'm still facing the same issue.

**Comment by Mytherin** [comment]
That fix is not in v0.10.1. You can try the nightly using `pip install duckdb --pre --upgrade`
