### ISSUE TITLE
java.lang.IllegalArgumentException: No enum constant org.duckdb.DuckDBColumnType.STRUCT

### ISSUE THREAD

**Issue by heuermh** [duckdb/duckdb#3687]
#### What happens?

When querying `ResultSetMetaData` from JDBC on a Parquet file with nested records, an `IllegalArgumentException` is thrown.

#### To Reproduce

See https://github.com/heuermh/bdg-formats-duckdb

```
$ duckdb-tools describe -i fragments.adam/part-r-00000.gz.parquet
java.lang.IllegalArgumentException: No enum constant org.duckdb.DuckDBColumnType.STRUCT(referenceName VARCHAR, start BIGINT, originalStart BIGINT, end BIGINT, mappingQuality INTEGER, readName VARCHAR, sequence VARCHAR, qualityScores VARCHAR, cigar VARCHAR, originalCigar VARCHAR, basesTrimmedFromStart INTEGER, basesTrimmedFromEnd INTEGER, readPaired BOOLEAN, properPair BOOLEAN, readMapped BOOLEAN, mateMapped BOOLEAN, failedVendorQualityChecks BOOLEAN, duplicateRead BOOLEAN, readNegativeStrand BOOLEAN, mateNegativeStrand BOOLEAN, primaryAlignment BOOLEAN, secondaryAlignment BOOLEAN, supplementaryAlignment BOOLEAN, mismatchingPositions VARCHAR, originalQualityScores VARCHAR, readGroupId VARCHAR, readGroupSampleId VARCHAR, mateAlignmentStart BIGINT, mateReferenceName VARCHAR, insertSize BIGINT, readInFragment INTEGER, attributes VARCHAR)[]
	at java.lang.Enum.valueOf(Enum.java:238)
	at org.duckdb.DuckDBColumnType.valueOf(DuckDBColumnType.java:3)
	at org.duckdb.DuckDBResultSetMetaData.TypeNameToType(DuckDBResultSetMetaData.java:51)
	at org.duckdb.DuckDBResultSetMetaData.<init>(DuckDBResultSetMetaData.java:29)
	at org.duckdb.DuckDBNative.duckdb_jdbc_meta(Native Method)
	at org.duckdb.DuckDBPreparedStatement.prepare(DuckDBPreparedStatement.java:76)
	at org.duckdb.DuckDBPreparedStatement.executeQuery(DuckDBPreparedStatement.java:129)
	at org.dishevelled.bio.duckdb.Describe.call(Describe.java:48)
	at org.dishevelled.bio.duckdb.Describe.call(Describe.java:27)
	at picocli.CommandLine.executeUserObject(CommandLine.java:1953)
	at picocli.CommandLine.access$1300(CommandLine.java:145)
	at picocli.CommandLine$RunLast.executeUserObjectOfLastSubcommandWithSameParent(CommandLine.java:2358)
	at picocli.CommandLine$RunLast.handle(CommandLine.java:2352)
	at picocli.CommandLine$RunLast.handle(CommandLine.java:2314)
	at picocli.CommandLine$AbstractParseResultHandler.execute(CommandLine.java:2179)
	at picocli.CommandLine$RunLast.execute(CommandLine.java:2316)
	at picocli.CommandLine.execute(CommandLine.java:2078)
	at org.dishevelled.bio.duckdb.Tools.main(Tools.java:44)
```

#### Environment (please complete the following information):
 - DuckDB Version: 0.3.3
 - DuckDB Client: JDBC

#### Before Submitting

- [ ] **Have you tried this on the latest `master` branch?**
* **Python**: `pip install duckdb --upgrade --pre`
* **R**: `install.packages("https://github.com/duckdb/duckdb/releases/download/master-builds/duckdb_r_src.tar.gz", repos = NULL)`
* **Other Platforms**: You can find binaries [here](https://github.com/duckdb/duckdb/releases/tag/master-builds) or compile from source.

- [ ] **Have you tried the steps to reproduce? Do they include all relevant data and configuration? Does the issue you report still appear there?**

**Comment by heuermh** [comment]
Possible duplicate of #2915

**Comment by Jens-H** [comment]
As far as I know structs are not implemented in the JDBC driver. Maybe you can extract the struct into normal rows via SQL before they arrive as a result set in the driver.

**Comment by Jack-Corbett** [comment]
@Jens-H would you mind provide an example of doing this? As this would be a huge help to my project if there was a work around

**Comment by Jens-H** [comment]
Sorry, I have never used structs and can only point to the docs.

**Comment by Jack-Corbett** [comment]
@Jens-H no problem at all, thank you for the suggestion I'll take a look

**Comment by hannes** [comment]
Indeed STRUCTs are not supported in the JDBC driver yet. I am also not so sure how this could be done cleanly in the standard API. Happy to consider suggestions/pull requests though.

**Comment by Mause** [comment]
Fixed in https://github.com/duckdb/duckdb/pull/7000
