### ISSUE TITLE
Calling select * from duckdb_functions() in DBeaver fails with Internal JDBC driver error

### ISSUE THREAD

**Issue by alexboks** [duckdb/duckdb#4305]
### What happens?

Calling select * from duckdb_functions() OR pragma_functions() in DBeaver fails with Internal JDBC driver error

### To Reproduce

`select * from duckdb_functions()`
`select * from pragma_functions()`

### OS:

Windows

### DuckDB Version:

0.4.0

### DuckDB Client:

JDBC

### Full Name:

Alex Bokser

### Affiliation:

-

### Have you tried this on the latest `master` branch?

- [X] I agree

### Have you tried the steps to reproduce? Do they include all relevant data and configuration? Does the issue you report still appear there?

- [X] I agree

**Comment by Alex-Monahan** [comment]
Thanks! Are there any other details about the error that you could provide?

**Comment by alexboks** [comment]
I was trying to see what macros I had created on a database. (So not in-memory). Using the latest driver version I could download through DBeaver (maven). Not sure what other details would be useful but happy to provide

**Comment by Mause** [comment]
> I was trying to see what macros I had created on a database. (So not in-memory). Using the latest driver version I could download through DBeaver (maven). Not sure what other details would be useful but happy to provide 

Are you able to provide the error itself?

**Comment by palmaresk8** [comment]
For the `SELECT * FROM duckdb_functions();` query, the error log is this

> !SESSION 2022-08-06 09:09:06.153 -----------------------------------------------

> eclipse.buildId=unknown
> java.version=11.0.12
> java.vendor=Eclipse Foundation
> BootLoader constants: OS=win32, ARCH=x86_64, WS=win32, NL=en
> Command-line arguments:  -os win32 -ws win32 -arch x86_64
> 
> !ENTRY org.jkiss.dbeaver.model 4 0 2022-08-06 09:09:13.758
> !MESSAGE No CSSEngine
> 
> !ENTRY org.jkiss.dbeaver.model 2 0 2022-08-06 09:09:39.130
> !MESSAGE Can't fetch database data types: SQL Error
> 
> !ENTRY org.jkiss.dbeaver.model 4 0 2022-08-06 09:09:59.089
> !MESSAGE SQL Error: Internal jdbc driver error
> !SUBENTRY 1 org.jkiss.dbeaver.model 4 0 2022-08-06 09:09:59.090
> !MESSAGE SQL Error: Internal jdbc driver error
> !SUBENTRY 2 org.jkiss.dbeaver.model 4 0 2022-08-06 09:09:59.090
> !MESSAGE Internal jdbc driver error
> !STACK 0
> java.sql.SQLException: Internal jdbc driver error
> 	at org.jkiss.dbeaver.model.impl.jdbc.exec.JDBCStatementImpl.handleExecuteError(JDBCStatementImpl.java:294)
> 	at org.jkiss.dbeaver.model.impl.jdbc.exec.JDBCStatementImpl.execute(JDBCStatementImpl.java:331)
> 	at org.jkiss.dbeaver.model.impl.jdbc.exec.JDBCStatementImpl.lambda$0(JDBCStatementImpl.java:131)
> 	at org.jkiss.dbeaver.utils.SecurityManagerUtils.wrapDriverActions(SecurityManagerUtils.java:94)
> 	at org.jkiss.dbeaver.model.impl.jdbc.exec.JDBCStatementImpl.executeStatement(JDBCStatementImpl.java:131)
> 	at org.jkiss.dbeaver.ui.editors.sql.execute.SQLQueryJob.executeStatement(SQLQueryJob.java:577)
> 	at org.jkiss.dbeaver.ui.editors.sql.execute.SQLQueryJob.lambda$1(SQLQueryJob.java:486)
> 	at org.jkiss.dbeaver.model.exec.DBExecUtils.tryExecuteRecover(DBExecUtils.java:172)
> 	at org.jkiss.dbeaver.ui.editors.sql.execute.SQLQueryJob.executeSingleQuery(SQLQueryJob.java:493)
> 	at org.jkiss.dbeaver.ui.editors.sql.execute.SQLQueryJob.extractData(SQLQueryJob.java:894)
> 	at org.jkiss.dbeaver.ui.editors.sql.SQLEditor$QueryResultsContainer.readData(SQLEditor.java:3642)
> 	at org.jkiss.dbeaver.ui.controls.resultset.ResultSetJobDataRead.lambda$0(ResultSetJobDataRead.java:118)
> 	at org.jkiss.dbeaver.model.exec.DBExecUtils.tryExecuteRecover(DBExecUtils.java:172)
> 	at org.jkiss.dbeaver.ui.controls.resultset.ResultSetJobDataRead.run(ResultSetJobDataRead.java:116)
> 	at org.jkiss.dbeaver.ui.controls.resultset.ResultSetViewer$ResultSetDataPumpJob.run(ResultSetViewer.java:4891)
> 	at org.jkiss.dbeaver.model.runtime.AbstractJob.run(AbstractJob.java:105)
> 	at org.eclipse.core.internal.jobs.Worker.run(Worker.java:63)
> Caused by: java.lang.IllegalArgumentException: No enum constant org.duckdb.DuckDBColumnType.VARCHAR[]
> 	at java.base/java.lang.Enum.valueOf(Unknown Source)
> 	at org.duckdb.DuckDBColumnType.valueOf(DuckDBColumnType.java:3)
> 	at org.duckdb.DuckDBResultSetMetaData.TypeNameToType(DuckDBResultSetMetaData.java:51)
> 	at org.duckdb.DuckDBResultSetMetaData.<init>(DuckDBResultSetMetaData.java:29)
> 	at org.duckdb.DuckDBNative.duckdb_jdbc_meta(Native Method)
> 	at org.duckdb.DuckDBPreparedStatement.prepare(DuckDBPreparedStatement.java:102)
> 	at org.duckdb.DuckDBPreparedStatement.execute(DuckDBPreparedStatement.java:173)
> 	at org.jkiss.dbeaver.model.impl.jdbc.exec.JDBCStatementImpl.execute(JDBCStatementImpl.java:329)
> 	... 15 more
> !SUBENTRY 3 org.jkiss.dbeaver.model 4 0 2022-08-06 09:09:59.090
> !MESSAGE No enum constant org.duckdb.DuckDBColumnType.VARCHAR[]
> !STACK 0
> java.lang.IllegalArgumentException: No enum constant org.duckdb.DuckDBColumnType.VARCHAR[]
> 	at java.base/java.lang.Enum.valueOf(Unknown Source)
> 	at org.duckdb.DuckDBColumnType.valueOf(DuckDBColumnType.java:3)
> 	at org.duckdb.DuckDBResultSetMetaData.TypeNameToType(DuckDBResultSetMetaData.java:51)
> 	at org.duckdb.DuckDBResultSetMetaData.<init>(DuckDBResultSetMetaData.java:29)
> 	at org.duckdb.DuckDBNative.duckdb_jdbc_meta(Native Method)
> 	at org.duckdb.DuckDBPreparedStatement.prepare(DuckDBPreparedStatement.java:102)
> 	at org.duckdb.DuckDBPreparedStatement.execute(DuckDBPreparedStatement.java:173)
> 	at org.jkiss.dbeaver.model.impl.jdbc.exec.JDBCStatementImpl.execute(JDBCStatementImpl.java:329)
> 	at org.jkiss.dbeaver.model.impl.jdbc.exec.JDBCStatementImpl.lambda$0(JDBCStatementImpl.java:131)
> 	at org.jkiss.dbeaver.utils.SecurityManagerUtils.wrapDriverActions(SecurityManagerUtils.java:94)
> 	at org.jkiss.dbeaver.model.impl.jdbc.exec.JDBCStatementImpl.executeStatement(JDBCStatementImpl.java:131)
> 	at org.jkiss.dbeaver.ui.editors.sql.execute.SQLQueryJob.executeStatement(SQLQueryJob.java:577)
> 	at org.jkiss.dbeaver.ui.editors.sql.execute.SQLQueryJob.lambda$1(SQLQueryJob.java:486)
> 	at org.jkiss.dbeaver.model.exec.DBExecUtils.tryExecuteRecover(DBExecUtils.java:172)
> 	at org.jkiss.dbeaver.ui.editors.sql.execute.SQLQueryJob.executeSingleQuery(SQLQueryJob.java:493)
> 	at org.jkiss.dbeaver.ui.editors.sql.execute.SQLQueryJob.extractData(SQLQueryJob.java:894)
> 	at org.jkiss.dbeaver.ui.editors.sql.SQLEditor$QueryResultsContainer.readData(SQLEditor.java:3642)
> 	at org.jkiss.dbeaver.ui.controls.resultset.ResultSetJobDataRead.lambda$0(ResultSetJobDataRead.java:118)
> 	at org.jkiss.dbeaver.model.exec.DBExecUtils.tryExecuteRecover(DBExecUtils.java:172)
> 	at org.jkiss.dbeaver.ui.controls.resultset.ResultSetJobDataRead.run(ResultSetJobDataRead.java:116)
> 	at org.jkiss.dbeaver.ui.controls.resultset.ResultSetViewer$ResultSetDataPumpJob.run(ResultSetViewer.java:4891)
> 	at org.jkiss.dbeaver.model.runtime.AbstractJob.run(AbstractJob.java:105)
> 	at org.eclipse.core.internal.jobs.Worker.run(Worker.java:63)
> 

So the critical part seems to be:

> java.lang.IllegalArgumentException: No enum constant org.duckdb.DuckDBColumnType.VARCHAR[]

**Comment by Alex-Monahan** [comment]
Correct - lists are not supported in JDBC just yet. A workaround is to cast the offending columns to varchar's. This is now a duplicate of #2915

**Comment by Mause** [comment]
Fixed in https://github.com/duckdb/duckdb/pull/7000
