### ISSUE TITLE
No files found that match the pattern "/data/sku.parquet

### ISSUE THREAD

**Issue by kiwimg** [duckdb/duckdb#4373]
### What happens?

The Mac OS and windows systems can operate normally, but the following errors occur in the CentOS 8 system:
This parquet file exists and is valid
 don't know what caused it
`
Caused by: java.sql.SQLException: java.sql.SQLException: IO Error: No files found that match the pattern "/data/sku.parquet"
	at org.duckdb.DuckDBPreparedStatement.prepare(DuckDBPreparedStatement.java:106) ~[duckdb_jdbc-0.4.0.jar!/:na]
	at org.duckdb.DuckDBPreparedStatement.executeQuery(DuckDBPreparedStatement.java:174) ~[duckdb_jdbc-0.4.0.jar!/:na]
	at com.zaxxer.hikari.pool.ProxyStatement.executeQuery(ProxyStatement.java:110) ~[HikariCP-5.0.1.jar!/:na]
	at com.zaxxer.hikari.pool.HikariProxyStatement.executeQuery(HikariProxyStatement.java) ~[HikariCP-5.0.1.jar!/:na]
	at org.springframework.jdbc.core.JdbcTemplate$1QueryStatementCallback.doInStatement(JdbcTemplate.java:439) ~[spring-jdbc-5.1.3.RELEASE.jar!/:5.1.3.RELEASE]
	at org.springframework.jdbc.core.JdbcTemplate.execute(JdbcTemplate.java:376) ~[spring-jdbc-5.1.3.RELEASE.jar!/:5.1.3.RELEASE]
	... 25 common frames omitted
Caused by: java.sql.SQLException: IO Error: No files found that match the pattern "/data/sku.parquet"
	at org.duckdb.DuckDBNative.duckdb_jdbc_prepare(Native Method) ~[duckdb_jdbc-0.4.0.jar!/:na]
	at org.duckdb.DuckDBPreparedStatement.prepare(DuckDBPreparedStatement.java:96) ~[duckdb_jdbc-0.4.0.jar!/:na]
	... 30 common frames omitted
`

### To Reproduce

"SELECT *  FROM '/data/sku.parquet';

### OS:

centos 8

### DuckDB Version:

4.0

### DuckDB Client:

duckdb_jdbc 4.0

### Full Name:

tony

### Affiliation:

java 11

### Have you tried this on the latest `master` branch?

- [X] I agree

### Have you tried the steps to reproduce? Do they include all relevant data and configuration? Does the issue you report still appear there?

- [X] I agree

**Comment by Mytherin** [comment]
`/data` is an unusual directory, does DuckDB have sufficient permissions to read the directory and the files?

**Comment by kiwimg** [comment]
> `/data` is an unusual directory, does DuckDB have sufficient permissions to read the directory and the files?

drwxr-xr-x 2 root root      4096 Aug 13 16:30  sku.parquet

**Comment by kiwimg** [comment]
> > `/data` is an unusual directory, does DuckDB have sufficient permissions to read the directory and the files?
> 
> drwxr-xr-x 2 root root 4096 Aug 13 16:30 sku.parquet

 `/data`  is mount directory
