### ISSUE TITLE
Caused by: java.sql.SQLException: Unknown type UBIGINT

### ISSUE THREAD

**Issue by kiwimg** [duckdb/duckdb#4376]
### What happens?

Caused by: java.sql.SQLException: Unknown type UBIGINT
	at org.duckdb.DuckDBResultSetMetaData.getColumnClassName(DuckDBResultSetMetaData.java:164)
	at org.apache.ibatis.executor.resultset.ResultSetWrapper.<init>(ResultSetWrapper.java:62)
	at org.apache.ibatis.executor.resultset.DefaultResultSetHandler.getFirstResultSet(DefaultResultSetHandler.java:257)
	at org.apache.ibatis.executor.resultset.DefaultResultSetHandler.handleResultSets(DefaultResultSetHandler.java:194)
	at org.apache.ibatis.executor.statement.PreparedStatementHandler.query(PreparedStatementHandler.java:65)
	at org.apache.ibatis.executor.statement.RoutingStatementHandler.query(RoutingStatementHandler.java:79)
	at org.apache.ibatis.executor.ReuseExecutor.doQuery(ReuseExecutor.java:60)
	at org.apache.ibatis.executor.BaseExecutor.queryFromDatabase(BaseExecutor.java:325)
	at org.apache.ibatis.executor.BaseExecutor.query(BaseExecutor.java:156)
	at org.apache.ibatis.executor.CachingExecutor.query(CachingExecutor.java:109)
	at com.github.pagehelper.PageInterceptor.intercept(PageInterceptor.java:132)
	at org.apache.ibatis.plugin.Plugin.invoke(Plugin.java:62)
	at com.sun.proxy.$Proxy158.query(Unknown Source)
	at org.apache.ibatis.session.defaults.DefaultSqlSession.selectList(DefaultSqlSession.java:151)
	at org.apache.ibatis.session.defaults.DefaultSqlSession.selectList(DefaultSqlSession.java:145)
	at org.apache.ibatis.session.defaults.DefaultSqlSession.selectList(DefaultSqlSession.java:140)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
	at org.mybatis.spring.SqlSessionTemplate$SqlSessionInterceptor.invoke(SqlSessionTemplate.java:427)
	... 50 more

### To Reproduce

CREATE TABLE  sku
(

    `id` UInt64,
     ......
)

SELECT * FROM '/data/sku.parquet

org.duckdb.DuckDBResultSetMetaData
![1660394462908](https://user-images.githubusercontent.com/13777509/184494500-b0524744-89fe-452e-8bae-45cc1f651376.png)

### OS:

centos 8

### DuckDB Version:

4.0

### DuckDB Client:

java  JDBC

### Full Name:

tony

### Affiliation:

tony

### Have you tried this on the latest `master` branch?

- [X] I agree

### Have you tried the steps to reproduce? Do they include all relevant data and configuration? Does the issue you report still appear there?

- [X] I agree

**Comment by kiwimg** [comment]
getColumnClassName  add a  case types.java_ OBJECT

**Comment by hannes** [comment]
Happy to review a PR!

**Comment by Mause** [comment]
Looks like this was fixed in https://github.com/duckdb/duckdb/pull/7262
