### ISSUE TITLE
DuckDB Segfault during updates

### ISSUE THREAD

**Issue by aarashy** [duckdb/duckdb#4450]
### What happens?

Hello,

My database is in a state where running a query like the following throws a segfault and crashes my process:

```
update {table_name} 
    set {hugeint_column} = {any value}, {text_column} = {any value} 
    where {primary_key} = {value}
```

### To Reproduce

I'm working hard to try to produce a minimal set of SQL queries that reproduces this from a clean slate, but I'm finding it challenging. Simply creating a table, inserting a row or two, and then executing an UPDATE of this shape isn't immediately working.

What I do have is a database file where, every time I open it and run this specific query, the process crashes. I can share this database file privately with anybody who would like to help debug.

@hannes / @Mytherin -- Do you have any advice for debugging segfaults like this? Ideally I would like to use a debugger such as GDB to step through the code execution and find the line that's throwing the segfault. I don't see resources for debug setup in `https://github.com/duckdb/duckdb/blob/c0a4ab96c626426961c207f49c19aa81448e91da/CONTRIBUTING.md`.

### OS:

iOS / docker

### DuckDB Version:

0.4.0, also 0.3.4

### DuckDB Client:

Rust and CLI

### Full Name:

Aarash Heydari

### Affiliation:

Dataland

### Have you tried this on the latest `master` branch?

- [X] I agree

### Have you tried the steps to reproduce? Do they include all relevant data and configuration? Does the issue you report still appear there?

- [X] I agree

**Comment by Tishj** [comment]
Hey, thanks for the issue!
For development we build duckdb with `make debug` and then run it with a debugger attached (like gdb or lldb)

**Comment by hannes** [comment]
Could you please try to create a reproducible example?

**Comment by aarashy** [comment]
@Tishj, I am having trouble using GDB with the debug build and wonder if you have any advice. I'm doing the following:

Terminal 1: start running DuckDB with `./build/debug/duckdb`

Terminal 2: attach GDB with 

```
sudo gdb --pid {process ID}
(gdb) continue
```

but when I go back to terminal 1 and try to create a table, I'm hitting this error suddenly:
```
D create table t (id int, col varchar);
AddressSanitizer:DEADLYSIGNAL
=================================================================
==17009==ERROR: AddressSanitizer: SEGV on unknown address 0x7ff78796d5a0 (pc 0x000106e095e3 bp 0x7ff7bb96d650 sp 0x7ff7bb96d360 T0)
==17009==The signal is caused by a READ memory access.
    #0 0x106e095e3 in duckdb::ScalarFunction duckdb::GetLeastGreatestFunction<duckdb::date_t, duckdb::GreaterThan>(duckdb::LogicalType const&) least.cpp
    #1 0x106dc813d in void duckdb::RegisterLeastGreatest<duckdb::GreaterThan>(duckdb::BuiltinFunctions&, std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&) least.cpp:119
    #2 0x106dc6e34 in duckdb::GreatestFun::RegisterFunction(duckdb::BuiltinFunctions&) least.cpp:132
    #3 0x1079227f8 in void duckdb::BuiltinFunctions::Register<duckdb::GreatestFun>() function.hpp:189
    #4 0x1079225d3 in duckdb::BuiltinFunctions::RegisterGenericFunctions() generic_functions.cpp:9
    #5 0x107d58120 in duckdb::BuiltinFunctions::Initialize() function.cpp:114
    #6 0x10b55c02d in duckdb::StorageManager::Initialize() storage_manager.cpp:70
    #7 0x10aaae7bf in duckdb::DatabaseInstance::Initialize(char const*, duckdb::DBConfig*) database.cpp:134
    #8 0x10aab172d in duckdb::DuckDB::DuckDB(char const*, duckdb::DBConfig*) database.cpp:141
    #9 0x10aab1aa8 in duckdb::DuckDB::DuckDB(char const*, duckdb::DBConfig*) database.cpp:140
    #10 0x1046b2a08 in std::__1::unique_ptr<duckdb::DuckDB, std::__1::default_delete<duckdb::DuckDB> > duckdb::make_unique<duckdb::DuckDB, char const*&, duckdb::DBConfig*>(char const*&, duckdb::DBConfig*&&) helper.hpp:41
    #11 0x1046b1fed in sqlite3_open_v2 sqlite3_api_wrapper.cpp:97
    #12 0x1045b2935 in open_db shell.c:14246
    #13 0x10468b88d in runOneSqlLine shell.c:19987
    #14 0x1045e8f9a in process_input shell.c:20106
    #15 0x1045b00b8 in main shell.c:20900
    #16 0x11ed514fd in start+0x1cd (dyld:x86_64+0x54fd)

==17009==Register values:
rax = 0x702d53eb057b0001  rbx = 0x00007ff7bb96d500  rcx = 0x0000000000000001  rdx = 0x00001ffef772d9f8  
rdi = 0x00007ff7bb96cfe0  rsi = 0x00007ff7bb96e450  rbp = 0x00007ff7bb96d650  rsp = 0x00007ff7bb96d360  
 r8 = 0x0000200000000000   r9 = 0x0000000000000000  r10 = 0xffffffffffffffff  r11 = 0x00000fffffffffff  
r12 = 0x000000011edcc3a0  r13 = 0x00007ff7bb971738  r14 = 0x00000001045aba00  r15 = 0x000000011edb8010  
AddressSanitizer can not provide additional info.
SUMMARY: AddressSanitizer: SEGV least.cpp in duckdb::ScalarFunction duckdb::GetLeastGreatestFunction<duckdb::date_t, duckdb::GreaterThan>(duckdb::LogicalType const&)
==17009==ABORTING
Abort trap: 6
```

**Comment by lnkuiper** [comment]
Try `gdb --args ./build/debug/duckdb`

**Comment by aarashy** [comment]
@lnkuiper -- how should I interact with the DuckDB CLI process when invoking it in that way? Do you just pipe stdin from a file, like so? I was hoping to be able to submit commands interactively as a TTY style. (sorry if this is just basics of GDB that I am asking you)
```
(gdb) run < sql_commands.sql
```

**Comment by lnkuiper** [comment]
That is strange. The CLI prompt should just show up after you do `run`. Something might be wrong with your duckdb build

**Comment by hannes** [comment]
@aarashy can you perhaps double-check if the issue is resolved with latest `master`?

**Comment by aarashy** [comment]
@hannes It's tricky.... you see, if I use `EXPORT DATABASE` / `IMPORT DATABASE` within the same DuckDB version (v0.4.0 release) and run my UPDATE query, it actually succeeds. Only when I open the database file directly and run my query does it segfault. 

If export/import even within the same version causes me to dodge the bug, it seems moot to import from a different version and test there.

I really want to get a grip on using GDB to find the segfault. I found the following post about the issue I was running into: https://superuser.com/questions/1662649/gdb-hangs-after-new-thread-on-macos

I wonder what your stdout for `make debug` is. Mine is the following. I wonder if its a problem with using clang vs. g++ or something per the above thread
 ```
mkdir -p build/debug && \
	cd build/debug && \
	cmake        -DBUILD_PARQUET_EXTENSION=TRUE -DCMAKE_BUILD_TYPE=Debug ../.. && \
	cmake --build . --config Debug
-- The C compiler identification is AppleClang 13.0.0.13000029
-- The CXX compiler identification is AppleClang 13.0.0.13000029
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Check for working C compiler: /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/cc - skipped
-- Detecting C compile features
-- Detecting C compile features - done
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Check for working CXX compiler: /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/c++ - skipped
-- Detecting CXX compile features
-- Detecting CXX compile features - done
 ```

**Comment by aarashy** [comment]
Will close this issue in hopes that it really was a dupe of https://github.com/duckdb/duckdb/issues/4401. 

If someone with a working GDB setup can show me their `make debug` output like above, that would be helpful to me
