### ISSUE TITLE
JDBC 0.4.0 fails with `GLIBC_2.23' not found` on Centos 7

### ISSUE THREAD

**Issue by karayv** [duckdb/duckdb#4529]
### What happens?

I'm getting an error while trying to run integration tests with DuckDB:
```
08:56:01  [31m  Cause: java.lang.UnsatisfiedLinkError: /tmp/libduckdb_java251203987240672711.so: /lib64/libm.so.6: version `GLIBC_2.23' not found (required by /tmp/libduckdb_java251203987240672711.so)[0m
08:56:01  [31m  at java.lang.ClassLoader$NativeLibrary.load(Native Method)[0m
08:56:01  [31m  at java.lang.ClassLoader.loadLibrary0(ClassLoader.java:1950)[0m
08:56:01  [31m  at java.lang.ClassLoader.loadLibrary(ClassLoader.java:1832)[0m
08:56:01  [31m  at java.lang.Runtime.load0(Runtime.java:811)[0m
08:56:01  [31m  at java.lang.System.load(System.java:1088)[0m
08:56:01  [31m  at org.duckdb.DuckDBNative.<clinit>(DuckDBNative.java:44)[0m
08:56:01  [31m  at org.duckdb.DuckDBDatabase.<init>(DuckDBDatabase.java:22)[0m
08:56:01  [31m  at org.duckdb.DuckDBDriver.connect(DuckDBDriver.java:35)[0m
08:56:01  [31m  at java.sql.DriverManager.getConnection(DriverManager.java:664)[0m
08:56:01  [31m  at java.sql.DriverManager.getConnection(DriverManager.java:270)[0m
```

Centos 7 is very popular, in fact I'm struggling to find a replacement image. Centos 7 has glibc version 2.17. Please suggest a workaround or fix. 

### To Reproduce

Import `org.duckdb:duckdb_jdbc:0.4.0` to a scala project. 
Using the scala code create in-memory DB as described in the DuckDB documentation.
Create a table. Perform insert, select and delete. 

I'm sure this can be reproduced using java as well.

### OS:

centos-release-7-9.2009.1.el7.centos.x86_64

### DuckDB Version:

0.4.0

### DuckDB Client:

org.duckdb:duckdb_jdbc:0.4.0

### Full Name:

Andrii Karaivanskyi

### Affiliation:

Indeed

### Have you tried this on the latest `master` branch?

- [ ] I agree

### Have you tried the steps to reproduce? Do they include all relevant data and configuration? Does the issue you report still appear there?

- [X] I agree

**Comment by hannes** [comment]
You could compile from source?

**Comment by karayv** [comment]
Right. The problem is that I have latest Centos 7. I have no idea why they would use 2012 library.
```
$ ldd --version
ldd (GNU libc) 2.17
Copyright (C) 2012 Free Software Foundation, Inc.
This is free software; see the source for copying conditions.  There is NO
warranty; not even for MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.
Written by Roland McGrath and Ulrich Drepper.
```

I actually never attempted to compile duckdb from source. If this what is meant by "Have you tried this on the latest master branch?". Unchecking.

**Comment by karayv** [comment]
Hm, I guess I was wrong about the latest centos.
```
docker pull centos  
docker run --rm -it --entrypoint bash 5d0da3dc9764
# ldd --version
ldd (GNU libc) 2.28
Copyright (C) 2018 Free Software Foundation, Inc.
This is free software; see the source for copying conditions.  There is NO
warranty; not even for MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.
Written by Roland McGrath and Ulrich Drepper.
```

**Comment by karayv** [comment]
I was able to build from master using cmake that I needed also to build. Though I'm not sure how this can help with JDBC.

```
$ ./build/release/
CMakeFiles/  duckdb       extension/   src/         test/        third_party/ tools/       
bash-4.2$ ./build/release/duckdb 
v0.4.1-dev2356 73530d93c
Enter ".help" for usage hints.
Connected to a transient in-memory database.
Use ".open FILENAME" to reopen on a persistent database.
D create table test123(tt int);
D insert into test123 values (100)
> ;
D select * from test123;
┌─────┐
│ tt  │
├─────┤
│ 100 │
└─────┘
```

**Comment by hannes** [comment]
You can `export BUILD_JDBC=1` before the make and it should build a JDBC driver for you as well

**Comment by karayv** [comment]
Just for the history, I used this docker file to build the lib, that I placed in my classpath

```Dockerfile
FROM centos:centos7 as prepare_build_tools

SHELL ["/bin/bash", "-c"]

RUN yum -y update
RUN yum -y install make
RUN yum -y install gcc-c++

RUN yum -y install wget
RUN wget https://cmake.org/files/v3.24/cmake-3.24.1.tar.gz
RUN tar zxvf cmake-3.* && \
    cd cmake-3.* && \
    ./bootstrap --prefix=/usr/local -- -DCMAKE_USE_OPENSSL=OFF && \
    make -j$(nproc) && \
    make install

RUN yum -y install git
RUN yum -y install libstdc++-static
RUN yum -y install java-1.8.0-openjdk-devel
RUN yum -y install zip
RUN git clone -b v0.5.1 https://github.com/duckdb/duckdb.git
RUN cd duckdb/ && \
    BUILD_JDBC=1 make

RUN zip /libduckdb_java.so_linux_amd64.zip duckdb/build/release/tools/jdbc/libduckdb_java.so_linux_amd64

FROM scratch
COPY --from=prepare_build_tools /libduckdb_java.so_linux_amd64.zip /libduckdb_java.so_linux_amd64.zip
```

And I run docker lie this
```shell
DOCKER_BUILDKIT=1 docker build --output type=local,dest=$(pwd)/ .
```

This copies the zip lib files to the current local folder. I don't need the whole jdbc, I just need the native library. Depending on what you use you can import the jar from maven central for instance, and then just have the lib in your immediate classpath. I believe it takes precedence over the lib built with the wrong glibc inside the jar.

**Comment by karayv** [comment]
I've noticed when I turn off in-memory processing my JVM crashes:

```
#
# A fatal error has been detected by the Java Runtime Environment:
#
#  SIGSEGV (0xb) at pc=0x00007fba1e656ec0, pid=71, tid=0x00007fba177fe700
#
# JRE version: OpenJDK Runtime Environment (Zulu 8.64.0.19-CA-linux64) (8.0_345-b01) (build 1.8.0_345-b01)
# Java VM: OpenJDK 64-Bit Server VM (25.345-b01 mixed mode linux-amd64 compressed oops)
# Problematic frame:
# [thread 140437226510080 also had an error][thread 140437176153856 also had an error]

[thread 140437209724672 also had an error]
[thread 140445482055424 also had an error]
[thread 140437201331968 also had an error]
[thread 140437218117376 also had an error]
C[thread 140437109012224 also had an error]
  [libduckdb_java255012610357608919.so+0x1083ec0][thread 140437125797632 also had an error]
[thread 140437192939264 also had an error][thread 140437167761152 also had an error]

[thread 140437134190336 also had an error]
  void duckdb::ListExtractTemplate<duckdb::string_t, true, false>(unsigned long, duckdb::UnifiedVectorFormat&, duckdb::UnifiedVectorFormat&, duckdb::Vector&, unsigned long, duckdb::Vector&)+0x160
#
# Core dump written. Default location: /mnt/kubernetes/sandbox/core or core.71
#
# An error report file with more information is saved as:
# /mnt/kubernetes/sandbox/hs_err_pid71.log
[thread 140437142583040 also had an error]
[thread 140437067048704 also had an error]
[thread 140437050263296 also had an error]
[thread 140436991514368 also had an error]
[thread 140437159368448 also had an error]
[thread 140437184546560 also had an error]
[thread 140437016692480 also had an error]
[thread 140437117404928 also had an error]
[thread 140437083834112 also had an error]
[thread 140437075441408 also had an error]
[thread 140437058656000 also had an error]
[thread 140437100619520 also had an error]
[thread 140436999907072 also had an error]
[thread 140437025085184 also had an error][thread 140436983121664 also had an error]

[thread 140437008299776 also had an error]
[thread 140437033477888 also had an error]
[thread 140437092226816 also had an error]
[thread 140437041870592 also had an error]
#
# If you would like to submit a bug report, please visit:
#   http://www.azul.com/support/
#
```
This is on v0.5.1, though I think I saw this on 0.4.1 as well. @hannes do you think this may be related to the fact the library is built in centos7? Or this deserves a dedicated ticket? When I run my integration tests on my mac I don't see this happening, however, the environment and the data are completely different.

**Comment by karayv** [comment]
I've just discovered I can reproduce this on Mac. I'll create a separate ticket
