### ISSUE TITLE
Pandas categorical conversion error: "ValueError: codes need to be between -1 and len(categories)-1"

### ISSUE THREAD

**Issue by pankajp** [duckdb/duckdb#4747]
### What happens?

There's a pandas Exception when there is null in an enum type column with `128 < num_possible_values_in_enum < 256`. This is probably because the dtype of the column is supposedly int8 inside duckdb, but is converted to int16 at some point when the `-1` mapping for `null` is translated to `255` instead.

```
{'cls': <class 'pandas.core.arrays.categorical.Categorical'>, 'codes': array([**255**,   1,  72,  83,  94, 105, 116, 127, 138, 149,   2,  13,  24,
        35,  46,  57,  68,  69,  70,  71,  73,  74,  75,  76,  77,  78,
        79,  80,  81,  82,  84,  85,  86,  87,  88,  89,  90,  91,  92,
        93,  95,  96,  97,  98,  99, 100, 101, 102, 103, 104, 106, 107,
       108, 109, 110, 111, 112, 113, 114, 115, 117, 118, 119, 120, 121,
       122, 123, 124, 125, 126, 128, 129, 130, 131, 132, 133, 134, 135,
       136, 137, 139, 140, 141, 142, 143, 144, 145, 146, 147, 148, 150,
       151, 152, 153, 154, 155, 156, 157, 158, 159,   3,   4,   5,   6,
         7,   8,   9,  10,  11,  12,  14,  15,  16,  17,  18,  19,  20,
        21,  22,  23,  25,  26,  27,  28,  29,  30,  31,  32,  33,  34,
        36,  37,  38,  39,  40,  41,  42,  43,  44,  45,  47,  48,  49,
        50,  51,  52,  53,  54,  55,  56,  58,  59,  60,  61,  62,  63,
        64,  65,  66,  67], dtype=int16), 'categories': None, 'ordered': None, 'dtype': CategoricalDtype(categories=['A0', 'A1', 'A10', 'A100', 'A101', 'A102', 'A103', 'A104',
                  'A105', 'A106',
                  ...
                  'A90', 'A91', 'A92', 'A93', 'A94', 'A95', 'A96', 'A97',
                  'A98', 'A99'],
, ordered=True)}
Traceback (most recent call last):
  File "/lan/csv/geomrd1/usr/pankaj/proj/duckdb/cat-bug.py", line 15, in <module>
    print(db.execute('''select nullif(a, 'A0') from df''').fetchdf())
  File "/lan/csv/geomrd1/usr/pankaj/proj/duckdb/cat-bug.py", line 8, in from_codes
    return from_codes_orig(codes, categories=categories, ordered=ordered, dtype=dtype)
  File "/lan/csv/geomrd1/usr/pankaj/proj/duckdb/pyenv/lib/python3.10/site-packages/pandas/core/arrays/categorical.py", line 709, in from_codes
    raise ValueError("codes need to be between -1 and len(categories)-1")
ValueError: codes need to be between -1 and len(categories)-1
```

### To Reproduce

```
import pandas as pd
import duckdb

# patch for debug prints, not needed to reproduce the problem
from_codes_orig = pd.core.arrays.categorical.Categorical.from_codes
def from_codes(cls, codes, categories=None, ordered=None, dtype=None):
    print(locals())
    return from_codes_orig(codes, categories=categories, ordered=ordered, dtype=dtype)
pd.core.arrays.categorical.Categorical.from_codes = classmethod(from_codes)

num_codes = 160  # Passes with < 128
db = duckdb.connect()
df = pd.DataFrame({'a':pd.Series(f'A{i}' for i in range(num_codes))}).astype('category')
db.register('df', df)
print(db.execute('''select nullif(a, 'A0') from df''').fetchdf())
```

### OS:

Linux

### DuckDB Version:

0.5.1-dev271

### DuckDB Client:

Python

### Full Name:

Pankaj Pandey

### Affiliation:

Cadence (not using duckdb in any official product)

### Have you tried this on the latest `master` branch?

- [X] I agree

### Have you tried the steps to reproduce? Do they include all relevant data and configuration? Does the issue you report still appear there?

- [X] I agree

**Comment by pankajp** [comment]
The following line seems to be relevant. `-1` is probably not valid for unsigned `DUCKDB_T uint8` to `NUMPY_T int16` conversion
``` 
template <class DUCKDB_T, class NUMPY_T>
static bool ConvertColumnCategoricalTemplate(idx_t target_offset, data_ptr_t target_data, UnifiedVectorFormat &idata,
                                             idx_t count) {
...
    if (!idata.validity.RowIsValidUnsafe(src_idx)) {
        out_ptr[offset] = duckdb_py_convert::RegularConvert::template ConvertValue<DUCKDB_T, NUMPY_T>(-1);
    }
...
```
