### ISSUE TITLE
Python reading and writing with threads sometimes crashes

### ISSUE THREAD

**Issue by Alex-Monahan** [duckdb/duckdb#4844]
### What happens?

We have gotten a few questions about how to run inserts and selects asynchronously in Python, so I have wanted to put a guide together. However, I've run into 2 issues:

~50% of the time, running the code below causes my Python process in VS Code to crash. Here is the error traceback (which sometimes is not even shown before the process crashes):
```python
Exception in thread write_thread_28:
Traceback (most recent call last):
  File "C:\ProgramData\Anaconda3\envs\py_10_duckdb\lib\threading.py", line 1009, in _bootstrap_inner
    self.run()
  File "C:\ProgramData\Anaconda3\envs\py_10_duckdb\lib\threading.py", line 946, in run
    self._target(*self._args, **self._kwargs)
  File "c:\Users\Alex\Documents\DuckDB\scratch_work\threading_guide_script_read_write_timestamps.py", line 20, in write_from_thread
    result = duckdb_con.execute("""INSERT INTO my_inserts VALUES (?) RETURNING current_timestamp as my_time""", (thread_name,)).fetchall()
duckdb.Error: Invalid Error: bad_weak_ptr
```

In addition, sometimes there is a write operation that fails to complete. I spin up 50 write threads, but the final table only ends up with 49 rows. Is it possible to have a write fail when coming from Python due to an existing reader, or a reader that comes in afterwards while the write it happening? I had thought that the requests were serialized in some way on the connection, but is the optimistic concurrency control portion of DuckDB's MVCC coming into play here also? I may need to add a lock on the Python side if so...

### To Reproduce

```python
import duckdb
from threading import Thread, current_thread
import pandas as pd
import random

# duckdb_con = duckdb.connect('peristent_db.duckdb') 
duckdb_con = duckdb.connect() # Pass in no parameters for an in memory database

duckdb_con.execute("""CREATE OR REPLACE TABLE my_inserts (thread_name varchar)""")

write_thread_count = 50
read_thread_count = 50
threads = []
print_list = []

def write_from_thread(duckdb_con,print_list):
    # Insert a row with the name of the thread
    thread_name = str(current_thread().name)
    print_list.append(thread_name + ' starting write')
    result = duckdb_con.execute("""INSERT INTO my_inserts VALUES (?) RETURNING current_timestamp as my_time""", (thread_name,)).fetchall()
    # duckdb_con.commit()
    # print(str(results))
    print_list.append(thread_name + ' ' + str(result))
    # print_list.append('Inserted ' + str(result[0][0]) + ' rows at ' + str(result[0][1]))

def read_from_thread(duckdb_con,print_list):
    thread_name = str(current_thread().name)
    print_list.append(thread_name + ' starting read')
    results = duckdb_con.execute("""SELECT count(*) as row_counter from my_inserts""").fetchall()
    if len(results) > 0:
        print_list.append(thread_name + ' read ' + str(results[0][0]) + ' rows')
    else:
        print_list.append(thread_name + ' read 0 rows')

# Create multiple writer and reader threads (in the same process) 
# Pass in the same connection as an argument
for i in range(write_thread_count):
    threads.append(Thread(target=write_from_thread,
                            args=(duckdb_con,print_list,),
                            name='write_thread_'+str(i)))

for j in range(read_thread_count):
    threads.append(Thread(target=read_from_thread,
                            args=(duckdb_con,print_list,),
                            name='read_thread_'+str(j)))

# Shuffle the threads to simulate a mix of readers and writers
random.seed(6) # Set the seed to ensure consistent results when testing
random.shuffle(threads)

for thread in threads:
    thread.start()

for thread in threads:
    thread.join()

print('\n'.join(print_list))
print(duckdb_con.execute("""SELECT * FROM my_inserts""").df())

```
Results (Note the write_thread_20 with an empty result set from the insert operation failing, and the output dataframe with a max index of 48 (only 49 rows):

```python
write_thread_20 starting write
read_thread_21 starting read
write_thread_20 []
write_thread_48 starting write
read_thread_21 read 0 rows
write_thread_48 [(datetime.datetime(2022, 9, 30, 0, 23, 13, 314000),)]
write_thread_13 starting write
write_thread_13 [(datetime.datetime(2022, 9, 30, 0, 23, 13, 315000),)]
write_thread_30 starting write
write_thread_30 [(datetime.datetime(2022, 9, 30, 0, 23, 13, 316000),)]
write_thread_29 starting write
write_thread_29 [(datetime.datetime(2022, 9, 30, 0, 23, 13, 317000),)]
write_thread_3 starting write
write_thread_3 [(datetime.datetime(2022, 9, 30, 0, 23, 13, 319000),)]
read_thread_43 starting read
read_thread_43 read 5 rows
write_thread_26 starting write
write_thread_26 [(datetime.datetime(2022, 9, 30, 0, 23, 13, 321000),)]
write_thread_28 starting write
write_thread_28 [(datetime.datetime(2022, 9, 30, 0, 23, 13, 322000),)]
read_thread_37 starting read
read_thread_37 read 7 rows
write_thread_43 starting write
write_thread_43 [(datetime.datetime(2022, 9, 30, 0, 23, 13, 325000),)]
write_thread_14 starting write
write_thread_14 [(datetime.datetime(2022, 9, 30, 0, 23, 13, 326000),)]
write_thread_8 starting write
write_thread_8 [(datetime.datetime(2022, 9, 30, 0, 23, 13, 327000),)]
write_thread_21 starting write
write_thread_21 [(datetime.datetime(2022, 9, 30, 0, 23, 13, 329000),)]
read_thread_28 starting read
read_thread_28 read 11 rows
write_thread_9 starting write
read_thread_9 starting read
write_thread_9 [(datetime.datetime(2022, 9, 30, 0, 23, 13, 331000),)]
read_thread_9 read 12 rows
read_thread_48 starting read
read_thread_48 read 12 rows
read_thread_29 starting read
read_thread_29 read 12 rows
read_thread_0 starting read
read_thread_0 read 12 rows
read_thread_16 starting read
read_thread_16 read 12 rows
read_thread_44 starting read
read_thread_44 read 12 rows
write_thread_16 starting write
write_thread_16 [(datetime.datetime(2022, 9, 30, 0, 23, 13, 339000),)]
read_thread_1 starting read
read_thread_1 read 13 rows
write_thread_6 starting write
write_thread_6 [(datetime.datetime(2022, 9, 30, 0, 23, 13, 342000),)]
read_thread_39 starting read
read_thread_39 read 14 rows
read_thread_45 starting read
read_thread_45 read 14 rows
read_thread_36 starting read
read_thread_36 read 14 rows
write_thread_45 starting write
write_thread_45 [(datetime.datetime(2022, 9, 30, 0, 23, 13, 346000),)]
read_thread_32 starting read
read_thread_32 read 15 rows
write_thread_35 starting write
write_thread_35 [(datetime.datetime(2022, 9, 30, 0, 23, 13, 349000),)]
read_thread_49 starting read
read_thread_49 read 16 rows
write_thread_17 starting write
write_thread_17 [(datetime.datetime(2022, 9, 30, 0, 23, 13, 351000),)]
write_thread_39 starting write
write_thread_39 [(datetime.datetime(2022, 9, 30, 0, 23, 13, 353000),)]
read_thread_24 starting read
read_thread_24 read 18 rows
read_thread_26 starting read
read_thread_26 read 18 rows
write_thread_49 starting write
write_thread_49 [(datetime.datetime(2022, 9, 30, 0, 23, 13, 356000),)]
read_thread_13 starting read
read_thread_13 read 19 rows
write_thread_7 starting write
write_thread_7 [(datetime.datetime(2022, 9, 30, 0, 23, 13, 359000),)]
read_thread_35 starting read
read_thread_35 read 20 rows
write_thread_22 starting write
write_thread_22 [(datetime.datetime(2022, 9, 30, 0, 23, 13, 361000),)]
write_thread_19 starting write
write_thread_19 [(datetime.datetime(2022, 9, 30, 0, 23, 13, 362000),)]
write_thread_27 starting write
write_thread_27 [(datetime.datetime(2022, 9, 30, 0, 23, 13, 364000),)]
write_thread_38 starting write
write_thread_38 [(datetime.datetime(2022, 9, 30, 0, 23, 13, 365000),)]
write_thread_15 starting write
write_thread_15 [(datetime.datetime(2022, 9, 30, 0, 23, 13, 366000),)]
read_thread_11 starting read
read_thread_11 read 25 rows
read_thread_38 starting read
read_thread_38 read 25 rows
write_thread_1 starting write
write_thread_1 [(datetime.datetime(2022, 9, 30, 0, 23, 13, 370000),)]
read_thread_5 starting read
read_thread_5 read 26 rows
write_thread_44 starting write
write_thread_44 [(datetime.datetime(2022, 9, 30, 0, 23, 13, 372000),)]
read_thread_8 starting read
read_thread_8 read 27 rows
write_thread_36 starting write
write_thread_36 [(datetime.datetime(2022, 9, 30, 0, 23, 13, 374000),)]
read_thread_31 starting read
read_thread_31 read 28 rows
read_thread_40 starting read
read_thread_40 read 28 rows
read_thread_3 starting read
read_thread_3 read 28 rows
write_thread_31 starting write
write_thread_31 [(datetime.datetime(2022, 9, 30, 0, 23, 13, 379000),)]
write_thread_23 starting write
write_thread_23 [(datetime.datetime(2022, 9, 30, 0, 23, 13, 380000),)]
write_thread_41 starting write
write_thread_41 [(datetime.datetime(2022, 9, 30, 0, 23, 13, 382000),)]
read_thread_27 starting read
read_thread_27 read 31 rows
read_thread_14 starting read
read_thread_14 read 31 rows
read_thread_7 starting read
read_thread_7 read 31 rows
read_thread_15 starting read
read_thread_15 read 31 rows
write_thread_5 starting write
write_thread_5 [(datetime.datetime(2022, 9, 30, 0, 23, 13, 388000),)]
read_thread_17 starting read
read_thread_17 read 32 rows
write_thread_37 starting write
write_thread_37 [(datetime.datetime(2022, 9, 30, 0, 23, 13, 390000),)]
read_thread_42 starting read
read_thread_42 read 33 rows
read_thread_30 starting read
read_thread_30 read 33 rows
read_thread_6 starting read
read_thread_6 read 33 rows
write_thread_32 starting write
write_thread_32 [(datetime.datetime(2022, 9, 30, 0, 23, 13, 395000),)]
read_thread_33 starting read
read_thread_33 read 34 rows
write_thread_46 starting write
write_thread_46 [(datetime.datetime(2022, 9, 30, 0, 23, 13, 398000),)]
read_thread_41 starting read
read_thread_41 read 35 rows
write_thread_42 starting write
write_thread_42 [(datetime.datetime(2022, 9, 30, 0, 23, 13, 400000),)]
read_thread_4 starting read
read_thread_4 read 36 rows
write_thread_11 starting write
write_thread_11 [(datetime.datetime(2022, 9, 30, 0, 23, 13, 402000),)]
read_thread_46 starting read
read_thread_46 read 37 rows
read_thread_20 starting read
read_thread_20 read 37 rows
read_thread_22 starting read
read_thread_22 read 37 rows
write_thread_24 starting write
write_thread_24 [(datetime.datetime(2022, 9, 30, 0, 23, 13, 407000),)]
write_thread_12 starting write
write_thread_12 [(datetime.datetime(2022, 9, 30, 0, 23, 13, 408000),)]
read_thread_19 starting read
read_thread_19 read 39 rows
read_thread_18 starting read
read_thread_18 read 39 rows
read_thread_2 starting read
read_thread_2 read 39 rows
write_thread_25 starting write
write_thread_25 [(datetime.datetime(2022, 9, 30, 0, 23, 13, 413000),)]
read_thread_47 starting read
read_thread_47 read 40 rows
write_thread_34 starting write
write_thread_34 [(datetime.datetime(2022, 9, 30, 0, 23, 13, 416000),)]
write_thread_2 starting write
write_thread_2 [(datetime.datetime(2022, 9, 30, 0, 23, 13, 417000),)]
write_thread_40 starting write
write_thread_40 [(datetime.datetime(2022, 9, 30, 0, 23, 13, 418000),)]
write_thread_47 starting write
write_thread_47 [(datetime.datetime(2022, 9, 30, 0, 23, 13, 420000),)]
read_thread_10 starting read
read_thread_10 read 44 rows
read_thread_25 starting read
read_thread_25 read 44 rows
read_thread_34 starting read
read_thread_34 read 44 rows
write_thread_18 starting write
write_thread_18 [(datetime.datetime(2022, 9, 30, 0, 23, 13, 425000),)]
write_thread_0 starting write
write_thread_0 [(datetime.datetime(2022, 9, 30, 0, 23, 13, 426000),)]
write_thread_4 starting write
write_thread_4 [(datetime.datetime(2022, 9, 30, 0, 23, 13, 427000),)]
write_thread_33 starting write
write_thread_33 [(datetime.datetime(2022, 9, 30, 0, 23, 13, 428000),)]
read_thread_12 starting read
read_thread_12 read 48 rows
write_thread_10 starting write
write_thread_10 [(datetime.datetime(2022, 9, 30, 0, 23, 13, 431000),)]
read_thread_23 starting read
read_thread_23 read 49 rows
        thread_name
0   write_thread_48
1   write_thread_13
2   write_thread_30
3   write_thread_29
4    write_thread_3
5   write_thread_26
6   write_thread_28
7   write_thread_43
8   write_thread_14
9    write_thread_8
10  write_thread_21
11   write_thread_9
12  write_thread_16
13   write_thread_6
14  write_thread_45
15  write_thread_35
16  write_thread_17
17  write_thread_39
18  write_thread_49
19   write_thread_7
20  write_thread_22
21  write_thread_19
22  write_thread_27
23  write_thread_38
24  write_thread_15
25   write_thread_1
26  write_thread_44
27  write_thread_36
28  write_thread_31
29  write_thread_23
30  write_thread_41
31   write_thread_5
32  write_thread_37
33  write_thread_32
34  write_thread_46
35  write_thread_42
36  write_thread_11
37  write_thread_24
38  write_thread_12
39  write_thread_25
40  write_thread_34
41   write_thread_2
42  write_thread_40
43  write_thread_47
44  write_thread_18
45   write_thread_0
46   write_thread_4
47  write_thread_33
48  write_thread_10
```

### OS:

Windows

### DuckDB Version:

0.5.1

### DuckDB Client:

Python

### Full Name:

Alex Monahan

### Affiliation:

Intel and DuckDB Labs

### Have you tried this on the latest `master` branch?

- [X] I agree

### Have you tried the steps to reproduce? Do they include all relevant data and configuration? Does the issue you report still appear there?

- [X] I agree

**Comment by Alex-Monahan** [comment]
I retested with 0.6.0 and 0.6.1.dev247 and I still have an issue with VS code crashing. The error message varies between crashing with no message, and displaying one of these 2:

![image](https://user-images.githubusercontent.com/52226177/205455261-a9087f16-f684-4913-94e7-c3910cb000b8.png)

and
```python
Exception has occurred: InvalidInputException
Invalid Input Error: Attempting to execute an unsuccessful or closed pending query result
  File "C:\Users\Alex\Documents\DuckDB\scratch_work\threading_guide_script_read_write_timestamps.py", line 29, in read_from_thread
    results = duckdb_con.execute("""SELECT count(*) as row_counter from my_inserts""").fetchall()
```

**Comment by Alex-Monahan** [comment]
I edited the code to create a thread-local connection using `.cursor()` and now this is working consistently on both 0.6.0 and 0.6.1.dev247! I think maybe just a more graceful failure or improved error message if trying to reuse the same connection across threads is all that remains? I'll put together a small guide with the cursor approach now that it is working smoothly. Thanks for your work on this folks!

**Comment by szarnyasg** [comment]
On MacOS and v0.8.1, I get heap corruption:
```
$ python3 my.py
Python(61970,0x2bf22f000) malloc: Heap corruption detected, free list is damaged at 0x600002bd8630
*** Incorrect guard value: 0
Python(61970,0x2bf22f000) malloc: *** set a breakpoint in malloc_error_break to debug
[1]    61970 abort      python3 my.py
```
With a freshly built package, `0.8.2-dev4121`, I get:
```
$ python3 my.py
Exception in thread write_thread_29:
Traceback (most recent call last):
  File "/opt/homebrew/Cellar/python@3.11/3.11.5/Frameworks/Python.framework/Versions/3.11/lib/python3.11/threading.py", line 1038, in _bootstrap_inner
    self.run()
  File "/opt/homebrew/Cellar/python@3.11/3.11.5/Frameworks/Python.framework/Versions/3.11/lib/python3.11/threading.py", line 975, in run
    self._target(*self._args, **self._kwargs)
  File "/Users/gabor/tmp/my.py", line 20, in write_from_thread
    result = duckdb_con.execute("""INSERT INTO my_inserts VALUES (?) RETURNING current_timestamp as my_time""", (thread_name,)).fetchall()
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
duckdb.duckdb.InvalidInputException: Invalid Input Error: Attempting to execute an unsuccessful or closed pending query result
Error: Invalid Error:
Python(68394,0x29402b000) malloc: Heap corruption detected, free list is damaged at 0x600001cc4150
*** Incorrect guard value: 0
Python(68394,0x29402b000) malloc: *** set a breakpoint in malloc_error_break to debug
[1]    68394 abort      python3 my.py
```

**Comment by szarnyasg** [comment]
Okay, I no longer get heap corruption with 0.9.2 (tested on Linux and Mac). I'm documenting this in the web repo and closing this - @Alex-Monahan let us know if there's something else to be done.
