### ISSUE TITLE
JDBC initial error

### ISSUE THREAD

**Issue by Cauchy-NY** [duckdb/duckdb#4928]
### What happens?

I used JDBC to create a memory database, but got these errors. It says /libduckdb_java.so_osx_universal not found, but I found it in my library.

```
java.io.IOException: /libduckdb_java.so_osx_universal not found
	at org.duckdb.DuckDBNative.<clinit>(DuckDBNative.java:48)
	at org.duckdb.DuckDBDatabase.<init>(DuckDBDatabase.java:22)
	at org.duckdb.DuckDBDriver.connect(DuckDBDriver.java:35)
	at java.sql.DriverManager.getConnection(DriverManager.java:664)
	at java.sql.DriverManager.getConnection(DriverManager.java:270)
...
Caused by: java.lang.UnsatisfiedLinkError: org.duckdb.DuckDBNative.duckdb_jdbc_startup([BZ)Ljava/nio/ByteBuffer;
	at org.duckdb.DuckDBNative.duckdb_jdbc_startup(Native Method)
	at org.duckdb.DuckDBDatabase.<init>(DuckDBDatabase.java:22)
	at org.duckdb.DuckDBDriver.connect(DuckDBDriver.java:35)
	at java.sql.DriverManager.getConnection(DriverManager.java:664)
	at java.sql.DriverManager.getConnection(DriverManager.java:270)
```

<img width="386" alt="image" src="https://user-images.githubusercontent.com/30664307/194753791-ab3c0f8d-4195-4d69-b6ef-8e9bf2dddaab.png">

### To Reproduce

pom file

```
private boolean testConnection() {
        try {
            Class.forName("org.duckdb.DuckDBDriver");
            DriverManager.getConnection("jdbc:duckdb:");
            return true;
        } catch (ClassNotFoundException | SQLException e) {
            return false;
        }
    }
```

```
<dependencies>
    <dependency>
      <groupId>cn.edu.tsinghua</groupId>
      <artifactId>iginx-core</artifactId>
      <version>${project.version}</version>
      <scope>provided</scope>
    </dependency>
    <dependency>
      <groupId>org.duckdb</groupId>
      <artifactId>duckdb_jdbc</artifactId>
      <version>0.5.1</version>
    </dependency>
  </dependencies>

  <build>
    <plugins>
      <plugin>
        <groupId>org.apache.maven.plugins</groupId>
        <artifactId>maven-dependency-plugin</artifactId>
        <version>2.10</version>
        <executions>
          <execution>
            <id>copy-dependencies</id>
            <phase>package</phase>
            <goals>
              <goal>copy-dependencies</goal>
            </goals>
            <configuration>
              <outputDirectory>../../core/target/iginx-core-${project.version}/driver/parquet/</outputDirectory>
              <excludeScope>provided</excludeScope>
            </configuration>
          </execution>
        </executions>
      </plugin>
      <plugin>
        <groupId>org.apache.maven.plugins</groupId>
        <artifactId>maven-antrun-plugin</artifactId>
        <version>1.7</version>
        <executions>
          <execution>
            <id>copy-native-libraries</id>
            <phase>package</phase>
            <goals>
              <goal>run</goal>
            </goals>
            <configuration>
              <target>
                <copy todir="../../core/target/iginx-core-${project.version}/driver/parquet/">
                  <fileset dir="${project.basedir}/target/">
                    <include name="*.jar"/>
                  </fileset>
                </copy>
              </target>
            </configuration>
          </execution>
        </executions>
      </plugin>
    </plugins>
  </build>
```

### OS:

MacOS

### DuckDB Version:

0.5.1

### DuckDB Client:

JDBC

### Full Name:

Jensen Wang

### Affiliation:

Tsinghua University

### Have you tried this on the latest `master` branch?

- [X] I agree

### Have you tried the steps to reproduce? Do they include all relevant data and configuration? Does the issue you report still appear there?

- [X] I agree

**Comment by Mause** [comment]
Hi, thanks for raising this issue. Are you able to give us a bit more information, eg, which version of MacOS you're using, which version of Java/the JDK you're using?

**Comment by Mause** [comment]
The complete stack trace would also be helpful, if available

**Comment by Cauchy-NY** [comment]
Thanks for your reply, here is more information

MacOS: Monterey 12.6
JDK: 1.8.0_212
complete stack trace:
```
java.io.IOException: /libduckdb_java.so_osx_universal not found
	at org.duckdb.DuckDBNative.<clinit>(DuckDBNative.java:48)
	at org.duckdb.DuckDBDatabase.<init>(DuckDBDatabase.java:22)
	at org.duckdb.DuckDBDriver.connect(DuckDBDriver.java:35)
	at java.sql.DriverManager.getConnection(DriverManager.java:664)
	at java.sql.DriverManager.getConnection(DriverManager.java:270)
	at cn.edu.tsinghua.iginx.parquet.ParquetStorage.testConnection(ParquetStorage.java:143)
	at cn.edu.tsinghua.iginx.parquet.ParquetStorage.<init>(ParquetStorage.java:119)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.lang.reflect.Constructor.newInstance(Constructor.java:423)
	at cn.edu.tsinghua.iginx.engine.physical.storage.StorageManager.initStorage(StorageManager.java:111)
	at cn.edu.tsinghua.iginx.engine.physical.storage.StorageManager.<init>(StorageManager.java:52)
	at cn.edu.tsinghua.iginx.engine.physical.storage.execute.StoragePhysicalTaskExecutor.<init>(StoragePhysicalTaskExecutor.java:65)
	at cn.edu.tsinghua.iginx.engine.physical.storage.execute.StoragePhysicalTaskExecutor.<clinit>(StoragePhysicalTaskExecutor.java:61)
	at cn.edu.tsinghua.iginx.engine.physical.PhysicalEngineImpl.<init>(PhysicalEngineImpl.java:54)
	at cn.edu.tsinghua.iginx.engine.physical.PhysicalEngineImpl.<clinit>(PhysicalEngineImpl.java:43)
	at cn.edu.tsinghua.iginx.engine.StatementExecutor.<clinit>(StatementExecutor.java:49)
	at cn.edu.tsinghua.iginx.IginxWorker.<init>(IginxWorker.java:69)
	at cn.edu.tsinghua.iginx.IginxWorker.<clinit>(IginxWorker.java:57)
	at cn.edu.tsinghua.iginx.Iginx.startServer(Iginx.java:53)
	at cn.edu.tsinghua.iginx.Iginx.main(Iginx.java:49)
2022-10-09 19:04:33,257 [main] ERROR - [cn.edu.tsinghua.iginx.engine.physical.storage.StorageManager.initStorage:122] unexpected error when process engine parquet: {}
java.lang.reflect.InvocationTargetException
	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.lang.reflect.Constructor.newInstance(Constructor.java:423)
	at cn.edu.tsinghua.iginx.engine.physical.storage.StorageManager.initStorage(StorageManager.java:111)
	at cn.edu.tsinghua.iginx.engine.physical.storage.StorageManager.<init>(StorageManager.java:52)
	at cn.edu.tsinghua.iginx.engine.physical.storage.execute.StoragePhysicalTaskExecutor.<init>(StoragePhysicalTaskExecutor.java:65)
	at cn.edu.tsinghua.iginx.engine.physical.storage.execute.StoragePhysicalTaskExecutor.<clinit>(StoragePhysicalTaskExecutor.java:61)
	at cn.edu.tsinghua.iginx.engine.physical.PhysicalEngineImpl.<init>(PhysicalEngineImpl.java:54)
	at cn.edu.tsinghua.iginx.engine.physical.PhysicalEngineImpl.<clinit>(PhysicalEngineImpl.java:43)
	at cn.edu.tsinghua.iginx.engine.StatementExecutor.<clinit>(StatementExecutor.java:49)
	at cn.edu.tsinghua.iginx.IginxWorker.<init>(IginxWorker.java:69)
	at cn.edu.tsinghua.iginx.IginxWorker.<clinit>(IginxWorker.java:57)
	at cn.edu.tsinghua.iginx.Iginx.startServer(Iginx.java:53)
	at cn.edu.tsinghua.iginx.Iginx.main(Iginx.java:49)
Caused by: java.lang.UnsatisfiedLinkError: org.duckdb.DuckDBNative.duckdb_jdbc_startup([BZ)Ljava/nio/ByteBuffer;
	at org.duckdb.DuckDBNative.duckdb_jdbc_startup(Native Method)
	at org.duckdb.DuckDBDatabase.<init>(DuckDBDatabase.java:22)
	at org.duckdb.DuckDBDriver.connect(DuckDBDriver.java:35)
	at java.sql.DriverManager.getConnection(DriverManager.java:664)
	at java.sql.DriverManager.getConnection(DriverManager.java:270)
	at cn.edu.tsinghua.iginx.parquet.ParquetStorage.testConnection(ParquetStorage.java:143)
	at cn.edu.tsinghua.iginx.parquet.ParquetStorage.<init>(ParquetStorage.java:119)
	... 15 more
```

**Comment by Mause** [comment]
@hannes / @mytherin I'm not sure which of the DuckDB folks have access to MacOS? I can't replicate this on Ubuntu at least. My guess is maybe something related to locale?

**Comment by hannes** [comment]
Its odd that the .so files are in the org.duckdb folder I thought they should be in the root? My guess is this is related to your build process that reshuffles files and moves the shared objects into this subfolder, which causes the init to fail. We could actually recursively scan the class path for the .so file to work around this and similar jar shading issues?

**Comment by Mause** [comment]
> Its odd that the .so files are in the org.duckdb folder I thought they should be in the root? My guess is this is related to your build process that reshuffles files and moves the shared objects into this subfolder, which causes the init to fail. We could actually recursively scan the class path for the .so file to work around this and similar jar shading issues?

I'm not sure that they are, that's just their folder explorer displaying it oddly

**Comment by Cauchy-NY** [comment]
Hi guys, I have solved this problem.
In multi-module maven project. if you only add duckdb-jdbc dependency to the sub moudle where you use it, it will cause this problem. I added the duckdb-jdbc dependency to the parent pom, and it works fine now.

**Comment by YouJiacheng** [comment]
To whom it may concern:
The root cause of this problem is that the project("IGinX") encountered this issue use custom classloader to load duckdb-jdbc, while the custom classloader didn't override `getResource` method.
A workaround is that add duckdb-jdbc's JAR into classpath(of App classloader, or any parent of custom classloader), since the default implementation of `getResource` will delegate the work to parent classloader, and App classloader will search resource in classpath.
Adding duckdb-jdbc dependency to the parent pom actually add duckdb-jdbc's JAR into classpath, since the startup script of the project will add all JARs required by the parent module into classpath.
Here is an example for overriding `getResource` method:
```java
    @Override
    public URL getResource(String name) {
        URL res = findLocalResource(name);
        if (res != null) {
            return res;
        }
        return super.getResource(name);
    }
    
    private URL findLocalResource(String name) {
        for (File jar : Jars) {
            try (JarFile jarFile = new JarFile(jar)) {
                if (jarFile.getJarEntry(name) != null) {
                    return new URL("jar:" + jar.toURI().toURL().toString() + "!/" + name);
                }
            } catch (IOException e) {
                e.printStackTrace();
            }
        }
        return null;
    }

    @Override
    protected URL findResource(String name) {
        return findLocalResource(name);
    }
```
In the above snippet, `Jars` is a member variable of the custom classloader, which stores the paths of all JARs managed by the classloader instance.
