### ISSUE TITLE
SQLancer CI Run Failing

### ISSUE THREAD

**Issue by Mytherin** [duckdb/duckdb#5031]
The SQLancer CI run on the master branch seems to be failing recently, due to some changes in the JDBC driver.

```
2022-10-19T08:53:48.0118785Z --------------------- RUNNING SQLANCER ----------------------
2022-10-19T08:53:48.0168845Z   File "/home/runner/work/duckdb/duckdb/scripts/run_sqlancer.py", line 99, in <module>
2022-10-19T08:53:48.0169690Z     with open('duckdb-queries.log', 'r') as f:
2022-10-19T08:53:48.0170207Z FileNotFoundError: [Errno 2] No such file or directory: 'duckdb-queries.log'
2022-10-19T08:53:48.0171037Z java -jar /home/runner/work/duckdb/duckdb/sqlancer/target/sqlancer-2.0.0.jar --num-queries 1000 --num-threads 1 --random-seed 393795551 --log-each-select=true --timeout-seconds 600 duckdb
2022-10-19T08:53:48.0171685Z --------------------- SQLANCER FAILURE ----------------------
2022-10-19T08:53:48.0172015Z SQLANCER EXITED WITH CODE 255
2022-10-19T08:53:48.0172431Z --------------------- SQLANCER ERROR LOG ----------------------
2022-10-19T08:53:48.0173330Z SQLancer failed creating a test database, indicating that SQLancer might have failed connecting to the DBMS. In order to change the username, password, host and port, you can use the --username, --password, --host and --port options.
2022-10-19T08:53:48.0173798Z 
2022-10-19T08:53:48.0173805Z 
2022-10-19T08:53:48.0174044Z java.sql.SQLException: Catalog Error: unrecognized configuration parameter "password"
2022-10-19T08:53:48.0174724Z 
2022-10-19T08:53:48.0174842Z Did you mean: "null_order"
2022-10-19T08:53:48.0175198Z 	at org.duckdb.DuckDBNative.duckdb_jdbc_startup(Native Method)
2022-10-19T08:53:48.0175619Z 	at org.duckdb.DuckDBDatabase.<init>(DuckDBDatabase.java:25)
2022-10-19T08:53:48.0176015Z 	at org.duckdb.DuckDBDriver.connect(DuckDBDriver.java:36)
2022-10-19T08:53:48.0176464Z 	at java.sql/java.sql.DriverManager.getConnection(DriverManager.java:677)
2022-10-19T08:53:48.0176941Z 	at java.sql/java.sql.DriverManager.getConnection(DriverManager.java:228)
2022-10-19T08:53:48.0177444Z 	at sqlancer.duckdb.DuckDBProvider.createDatabase(DuckDBProvider.java:153)
2022-10-19T08:53:48.0178364Z 	at sqlancer.duckdb.DuckDBProvider.createDatabase(DuckDBProvider.java:1)
2022-10-19T08:53:48.0178874Z 	at sqlancer.Main$DBMSExecutor.testConnection(Main.java:287)
2022-10-19T08:53:48.0179258Z 	at sqlancer.Main.executeMain(Main.java:442)
2022-10-19T08:53:48.0179603Z 	at sqlancer.Main.main(Main.java:251)
2022-10-19T08:53:48.0179787Z 
```

@Mause could you perhaps have a look when you have time?

**Comment by Mytherin** [comment]
The CI uses the code [here](https://github.com/Mytherin/sqlancer). Feel free to send a PR there if you want to adjust it.
