### ISSUE TITLE
pip install in centos7 error

### ISSUE THREAD

**Issue by wonb168** [duckdb/duckdb#5098]
My OS is centos7.4:
pip install error:
from __future__ import annotations
        ^
    SyntaxError: future feature annotations is not defined
```
pip3 install duckdb==0.5.1
WARNING: Running pip install with root privileges is generally not a good idea. Try `pip3 install --user` instead.
Collecting duckdb
  Downloading https://files.pythonhosted.org/packages/9b/b3/6794582d52767b668eb92cf04b587f9804155435d11f3c22fa0c468189ef/duckdb-0.5.1.tar.gz (13.5MB)
    100% |████████████████████████████████| 13.5MB 65kB/s
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/tmp/pip-build-e7xaeyug/duckdb/setup.py", line 305, in <module>
        "Changelog": "https://github.com/duckdb/duckdb/releases",
      File "/usr/lib/python3.6/site-packages/setuptools/__init__.py", line 129, in setup
        return distutils.core.setup(**attrs)
      File "/usr/lib64/python3.6/distutils/core.py", line 108, in setup
        _setup_distribution = dist = klass(attrs)
      File "/usr/lib/python3.6/site-packages/setuptools/dist.py", line 370, in __init__
        k: v for k, v in attrs.items()
      File "/usr/lib64/python3.6/distutils/dist.py", line 281, in __init__
        self.finalize_options()
      File "/usr/lib/python3.6/site-packages/setuptools/dist.py", line 529, in finalize_options
        ep.load()(self, ep.name, value)
      File "/usr/lib/python3.6/site-packages/pkg_resources/__init__.py", line 2318, in load
        return self.resolve()
      File "/usr/lib/python3.6/site-packages/pkg_resources/__init__.py", line 2324, in resolve
        module = __import__(self.module_name, fromlist=['__name__'], level=0)
      File "/tmp/pip-build-e7xaeyug/duckdb/.eggs/setuptools_scm-7.0.5-py3.6.egg/setuptools_scm/__init__.py", line 5
        from __future__ import annotations
        ^
    SyntaxError: future feature annotations is not defined
```

**Comment by Mause** [comment]
Looks like `setuptools_scm` has dropped support for Python 3.6 (https://github.com/pypa/setuptools_scm/blob/main/CHANGELOG.rst#v700), for now you'll have to use a more recent Python version
