### ISSUE TITLE
'403 Forbidden' for AWS s3 presigned URL

### ISSUE THREAD

**Issue by chrisbrain** [duckdb/duckdb#5310]
Hi. I am creating an Amazon s3 presigned URL to a CSV file using their Javascript SDK. The URL downloads the file fine in a browser which confirms it's OK, but if I use it in the duck cli or via the npm package with:

`create view test as select * from read_csv_auto('...presigned url...');`

I get `403 (Forbidden)`.

You can also test this by locating a CSV file in s3 via the AWS admin console and creating the URL with 'Object actions' ->  'Share with a presigned URL'.

**Comment by Mause** [comment]
Can you please include all the version information requested in the issue template?

**Comment by chrisbrain** [comment]
Hi - it's:

OS: Ubuntu 20.04.5 LTS
DuckDB Version: 0.5.1
DuckDB Client: npm

Also tried duck db cli but that's actually 0.5.0.

**Comment by Mause** [comment]
Okay, can you please try with the latest master version instead? You can install it with `duckdb@next`

**Comment by chrisbrain** [comment]
Hi @Mause - Now I am getting a new errror:

```
Error: Connection created on database that was not yet initialized
at default_connection (node_modules/duckdb/lib/duckdb.js:384:32)
at Database.exec (node_modules/duckdb/lib/duckdb.js:558:5)
```

This at the place in my javascript where I am issuing the:
```
INSTALL httpfs;
LOAD httpfs;
```

Requests ahead of creating the view.

If I pause the code slightly before running this it then proceeds to give me the same `403 (Forbidden)` error as before.

**Comment by koenvo** [comment]
Are your sure the cors configuration on the bucket is set correctly?

**Comment by Mause** [comment]
> Hi @Mause - Now I am getting a new errror:
> 
> ```
> Error: Connection created on database that was not yet initialized
> at default_connection (node_modules/duckdb/lib/duckdb.js:384:32)
> at Database.exec (node_modules/duckdb/lib/duckdb.js:558:5)
> ```
> 
> This at the place in my javascript where I am issuing the:
> ```
> INSTALL httpfs;
> LOAD httpfs;
> ```
> 
> Requests ahead of creating the view.
> 
> If I pause the code slightly before running this it then proceeds to give me the same `403 (Forbidden)` error as before.

Can you please confirm that you're waiting for the database to startup (with the callback) before you call `exec`?

**Comment by chrisbrain** [comment]
> Are your sure the cors configuration on the bucket is set correctly?

Actually no, I am not doing anything with CORS. I may be missing something but can't quite see why this would be relevant, I thought CORS was a protection mechanism related to browser requests.

I can curl request the file using the presigned URL OK.

**Comment by chrisbrain** [comment]
> Can you please confirm that you're waiting for the database to startup (with the callback) before you call `exec`?

Yes I think I can confirm that - I am issuing those commands using the duckdb.exec method and waiting the callback. Also I have not seen that new error before (i.e. on 0.5.0 and 0.5.1, only when I tried the @next.

**Comment by Mause** [comment]
> > Can you please confirm that you're waiting for the database to startup (with the callback) before you call `exec`?
> 
> Yes I think I can confirm that - I am issuing those commands using the duckdb.exec method and waiting the callback. Also I have not seen that new error before (i.e. on 0.5.0 and 0.5.1, only when I tried the @next).

Are you waiting for the callback you passed to the `Database` constructor?

**Comment by chrisbrain** [comment]
@Mause OK I sorry didn't realise you had to do that now, that looks like a change in @next relative to 0.5.1 (and not in docs - e.g. https://duckdb.org/docs/api/nodejs/overview).

But now I am doing that (i.e. waiting on callback as 3rd param to .ctor) the `Connection created on database that was not yet initialized` error is no more but I still get the `403 (Forbidden)`.

If this is CORS related then I am stil confused as this is not running in a browser and if it were I would expect the browser to enforce this on any http requests coming from the page. This is happening running from the CLI or duckdb running server side in nodejs.

**Comment by Mause** [comment]
@chrisbrain it's not a new requirement sorry, but a workaround for a bug that needs to be fixed

I'm not sure if we've done any/much testing with presigned urls to be honest, I'll see if I have time to investigate this week

**Comment by chrisbrain** [comment]
Ah I see - OK well I think I confirmed it's still happening on the latest pre release version.

FWIW Dropbox has a kind-of-similar feature where they let you generated a URL which is valid for a few hours and that appears to be working fine with duckdb.

Thanks and appreciate anything you can do!

**Comment by chrisbrain** [comment]
I am suspecting now that this happens because in the background duck is making both HTTP HEAD and GET requests and the presigned URLs are only for GET.

If that's the case it's quite unfortunate as this seems it would have provided a neat way to connect duck views to s3 files disparate buckets with different credentials.

Not sure if this is worth any thought but perhaps duckdb could be put into a mode where it uses GET to simulate HEAD requests as I saw mentioned here:
https://stackoverflow.com/a/39663152

But it may have other implications.

**Comment by buckett** [comment]
I also bumped into this problem, I think it's failing on the HEAD request as you mention, the error I was getting was:

`Invalid Error: Unable to connect to URL "https://....`

and that looks to be thrown when a non 200 response is returned from the HEAD request: https://github.com/duckdb/duckdb/blob/master/extension/httpfs/httpfs.cpp#L490

It would have been easier to spot what was going wrong if the error message had have said:

`Invalid Error: Unable to make HEAD request to URL "https://...`

I'll just workaround this by downloading the files and then loading them locally.
