### ISSUE TITLE
Fetching a TIMESTAMP column results in an error

### ISSUE THREAD

**Issue by mrigger** [duckdb/duckdb#532]
Consider the following statements:

```sql
CREATE TABLE t0(c0 DATETIME);
INSERT INTO t0 VALUES(DATE '1-1-1');
SELECT t0.c0 FROM t0; -- Not implemented type: TIMESTAMP
```
When using JDBC to execute the `SELECT` using the ` java.sql.ResultSet.getString(int columnIndex)` method, the following exception is thrown:

```
java.sql.SQLException: Not implemented type: TIMESTAMP
	at nl.cwi.da.duckdb.DuckDBResultSet.getObject(DuckDBResultSet.java:129)
	at nl.cwi.da.duckdb.DuckDBResultSet.getString(DuckDBResultSet.java:153)
```
I suspect that this might be easy to reproduce; if not, I'll supply a reduced form of the test driver that I'm using.

I found this based on 3f0eb5134512c6097805998ccc5eb44476534736.

**Comment by hannesmuehleisen** [comment]
Yes as it says I have not implemented the `TIMESTAMP` type yet in the JDBC driver. It will be soon.

**Comment by mrigger** [comment]
Great! Since this seems like an expected limitation, feel free to tag this (and other such issues) as an enhancement.

**Comment by Jens-H** [comment]
This test case is running without exception using master:
```
	public static void test_532() throws Exception {
		Connection conn = DriverManager.getConnection("jdbc:duckdb:");
		Statement stmt = conn.createStatement();

		ResultSet rs;

		stmt.execute("CREATE TABLE t0(c0 DATETIME);");
		stmt.execute("INSERT INTO t0 VALUES(DATE '1-1-1');");
		rs = stmt.executeQuery("SELECT t0.c0 FROM t0; ");

        rs.next();

		try {
            System.out.println( rs.getObject(1));
		} catch (Exception e) {
            System.out.println(e);
		}
		try {
            System.out.println( rs.getString(1));
		} catch (Exception e) {
            System.out.println(e);
		}
        }
```

**Comment by hannes** [comment]
Indeed this seems fixed
