### ISSUE TITLE
Building the Node.js client fails

### ISSUE THREAD

**Issue by tobilg** [duckdb/duckdb#5686]
### What happens?

I'm currently trying to build the Node.js client for Amazon Linux 2, to use it in a AWS Lambda function layer. When running `make` in the `tools/nodejs` directory, I unfortunately see this error:

```bash
#11 20.58 ../src/duckdb_node.hpp:3:10: fatal error: duckdb.hpp: No such file or directory
#11 20.58  #include "duckdb.hpp"
```

The build fails subsequently.

The full log is:

```bash
#11 0.426 npm install --build-from-source                                                                                               
#11 14.40 npm WARN deprecated @npmcli/move-file@2.0.1: This functionality has been moved to @npmcli/fs                                  
#11 14.84 npm WARN deprecated querystring@0.2.0: The querystring API is considered Legacy. new code should use the URLSearchParams API instead.                                                                                                                                 
#11 18.47 
#11 18.47 > duckdb@0.2.4 install
#11 18.47 > node-pre-gyp install --fallback-to-build
#11 18.47 
#11 18.58 node-pre-gyp info it worked if it ends with ok
#11 18.58 node-pre-gyp info using node-pre-gyp@1.0.10
#11 18.58 node-pre-gyp info using node@16.18.1 | linux | x64
#11 18.65 node-pre-gyp info build requesting source compile
#11 18.74 gyp info it worked if it ends with ok
#11 18.75 gyp info using node-gyp@9.1.0
#11 18.75 gyp info using node@16.18.1 | linux | x64
#11 18.77 gyp info ok 
#11 18.91 gyp info it worked if it ends with ok
#11 18.91 gyp info using node-gyp@9.1.0
#11 18.91 gyp info using node@16.18.1 | linux | x64
#11 19.15 gyp info find Python using Python version 3.7.15 found at "/usr/bin/python3"
#11 19.29 gyp http GET https://nodejs.org/download/release/v16.18.1/node-v16.18.1-headers.tar.gz
#11 19.35 gyp http 200 https://nodejs.org/download/release/v16.18.1/node-v16.18.1-headers.tar.gz
#11 19.85 gyp http GET https://nodejs.org/download/release/v16.18.1/SHASUMS256.txt
#11 19.86 gyp http 200 https://nodejs.org/download/release/v16.18.1/SHASUMS256.txt
#11 19.87 gyp info spawn /usr/bin/python3
#11 19.87 gyp info spawn args [
#11 19.87 gyp info spawn args   '/var/lang/lib/node_modules/npm/node_modules/node-gyp/gyp/gyp_main.py',
#11 19.87 gyp info spawn args   'binding.gyp',
#11 19.87 gyp info spawn args   '-f',
#11 19.87 gyp info spawn args   'make',
#11 19.87 gyp info spawn args   '-I',
#11 19.87 gyp info spawn args   '/tmp/duckdb/duckdb-0.6.1/tools/nodejs/build/config.gypi',
#11 19.87 gyp info spawn args   '-I',
#11 19.87 gyp info spawn args   '/var/lang/lib/node_modules/npm/node_modules/node-gyp/addon.gypi',
#11 19.87 gyp info spawn args   '-I',
#11 19.87 gyp info spawn args   '/root/.cache/node-gyp/16.18.1/include/node/common.gypi',
#11 19.87 gyp info spawn args   '-Dlibrary=shared_library',
#11 19.87 gyp info spawn args   '-Dvisibility=default',
#11 19.87 gyp info spawn args   '-Dnode_root_dir=/root/.cache/node-gyp/16.18.1',
#11 19.87 gyp info spawn args   '-Dnode_gyp_dir=/var/lang/lib/node_modules/npm/node_modules/node-gyp',
#11 19.87 gyp info spawn args   '-Dnode_lib_file=/root/.cache/node-gyp/16.18.1/<(target_arch)/node.lib',
#11 19.87 gyp info spawn args   '-Dmodule_root_dir=/tmp/duckdb/duckdb-0.6.1/tools/nodejs',
#11 19.87 gyp info spawn args   '-Dnode_engine=v8',
#11 19.87 gyp info spawn args   '--depth=.',
#11 19.87 gyp info spawn args   '--no-parallel',
#11 19.87 gyp info spawn args   '--generator-output',
#11 19.87 gyp info spawn args   'build',
#11 19.87 gyp info spawn args   '-Goutput_dir=.'
#11 19.87 gyp info spawn args ]
#11 20.42 gyp info ok 
#11 20.52 gyp info it worked if it ends with ok
#11 20.53 gyp info using node-gyp@9.1.0
#11 20.53 gyp info using node@16.18.1 | linux | x64
#11 20.55 gyp info spawn make
#11 20.55 gyp infomake[1]: Entering directory `/tmp/duckdb/duckdb-0.6.1/tools/nodejs/build'
#11 20.55  spawn args [ 'BUILDTYPE=Release', '-C', 'build' ]
#11 20.57   CXX(target) Release/obj.target/duckdb/src/duckdb_node.o
#11 20.58 In file included from ../src/duckdb_node.cpp:1:0:
#11 20.58 ../src/duckdb_node.hpp:3:10: fatal error: duckdb.hpp: No such file or directory
#11 20.58  #include "duckdb.hpp"
#11 20.58           ^~~~~~~~~~~~
#11 20.58 compilation terminated.
#11 20.58 make[1]: *** [Release/obj.target/duckdb/src/duckdb_node.o] Error 1
#11 20.58 make[1]: Leaving directory `/tmp/duckdb/duckdb-0.6.1/tools/nodejs/build'
#11 20.58 gyp ERR! build error 
#11 20.58 gyp ERR! stack Error: `make` failed with exit code: 2
#11 20.58 gyp ERR! stack     at ChildProcess.onExit (/var/lang/lib/node_modules/npm/node_modules/node-gyp/lib/build.js:201:23)
#11 20.58 gyp ERR! stack     at ChildProcess.emit (node:events:513:28)
#11 20.58 gyp ERR! stack     at Process.ChildProcess._handle.onexit (node:internal/child_process:293:12)
#11 20.58 gyp ERR! System Linux 5.4.0-1094-azure
#11 20.59 gyp ERR! command "/var/lang/bin/node" "/var/lang/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "build" "--fallback-to-build" "--module=/tmp/duckdb/duckdb-0.6.1/tools/nodejs/lib/binding/duckdb.node" "--module_name=duckdb" "--module_path=/tmp/duckdb/duckdb-0.6.1/tools/nodejs/lib/binding" "--napi_version=8" "--node_abi_napi=napi" "--napi_build_version=0" "--node_napi_label=node-v93"
#11 20.59 gyp ERR! cwd /tmp/duckdb/duckdb-0.6.1/tools/nodejs
#11 20.59 gyp ERR! node -v v16.18.1
#11 20.59 gyp ERR! node-gyp -v v9.1.0
#11 20.59 gyp ERR! not ok 
#11 20.60 node-pre-gyp ERR! build error 
#11 20.61 node-pre-gyp ERR! stack Error: Failed to execute '/var/lang/bin/node /var/lang/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js build --fallback-to-build --module=/tmp/duckdb/duckdb-0.6.1/tools/nodejs/lib/binding/duckdb.node --module_name=duckdb --module_path=/tmp/duckdb/duckdb-0.6.1/tools/nodejs/lib/binding --napi_version=8 --node_abi_napi=napi --napi_build_version=0 --node_napi_label=node-v93' (1)
#11 20.61 node-pre-gyp ERR! stack     at ChildProcess.<anonymous> (/tmp/duckdb/duckdb-0.6.1/tools/nodejs/node_modules/@mapbox/node-pre-gyp/lib/util/compile.js:89:23)
#11 20.61 node-pre-gyp ERR! stack     at ChildProcess.emit (node:events:513:28)
#11 20.62 node-pre-gyp ERR! stack     at maybeClose (node:internal/child_process:1100:16)
#11 20.62 node-pre-gyp ERR! stack     at Process.ChildProcess._handle.onexit (node:internal/child_process:304:5)
#11 20.62 node-pre-gyp ERR! System Linux 5.4.0-1094-azure
#11 20.62 node-pre-gyp ERR! command "/var/lang/bin/node" "/tmp/duckdb/duckdb-0.6.1/tools/nodejs/node_modules/.bin/node-pre-gyp" "install" "--fallback-to-build"
#11 20.62 node-pre-gyp ERR! cwd /tmp/duckdb/duckdb-0.6.1/tools/nodejs
#11 20.62 node-pre-gyp ERR! node -v v16.18.1
#11 20.63 node-pre-gyp ERR! node-pre-gyp -v v1.0.10
#11 20.63 node-pre-gyp ERR! not ok 
#11 20.63 Failed to execute '/var/lang/bin/node /var/lang/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js build --fallback-to-build --module=/tmp/duckdb/duckdb-0.6.1/tools/nodejs/lib/binding/duckdb.node --module_name=duckdb --module_path=/tmp/duckdb/duckdb-0.6.1/tools/nodejs/lib/binding --napi_version=8 --node_abi_napi=napi --napi_build_version=0 --node_napi_label=node-v93' (1)
#11 20.65 npm notice 
#11 20.65 npm notice New major version of npm available! 8.19.2 -> 9.2.0
#11 20.65 npm notice Changelog: <https://github.com/npm/cli/releases/tag/v9.2.0>
#11 20.65 npm notice Run `npm install -g npm@9.2.0` to update!
#11 20.65 npm notice 
#11 20.66 npm ERR! code 1
#11 20.66 npm ERR! path /tmp/duckdb/duckdb-0.6.1/tools/nodejs
#11 20.66 npm ERR! command failed
#11 20.66 npm ERR! command sh -c -- node-pre-gyp install --fallback-to-build
#11 20.66 
#11 20.66 npm ERR! A complete log of this run can be found in:
#11 20.66 npm ERR!     /root/.npm/_logs/2022-12-13T13_51_25_561Z-debug-0.log
#11 20.69 make: *** [node_modules] Error 1
```

### To Reproduce

Running `make` in the `tools/nodejs` directory to build the Node.js client.

### OS:

Amazon Linux 2

### DuckDB Version:

0.6.1

### DuckDB Client:

none

### Full Name:

TobiLG

### Affiliation:

none

### Have you tried this on the latest `master` branch?

- [X] I agree

### Have you tried the steps to reproduce? Do they include all relevant data and configuration? Does the issue you report still appear there?

- [X] I agree

**Comment by Tishj** [comment]
If you want to build from source, it's usually a good idea to look at the `yml` files we use to do this for the CI

**Comment by Mause** [comment]
Hi, is there a particular reason you're not able to use the prebuilt version?

The Makefile is a little bit out of date, but if you run the configure script first it should work okay

**Comment by Mause** [comment]
Which version of GCC are you trying to use? Might be worth updating given that internal error

**Comment by tobilg** [comment]
Thanks again @Mause. The error might have been caused due to lack of memory, I'm currently running the build on a beefier machine... Will report back.

Amazon Linux 2 is pretty old, I guess that's the reason why GCC is at version ``.

This is the `Dockerfile` I'm using at the moment:

```Dockerfile
FROM amazon/aws-lambda-nodejs:16

RUN yum update -y && \
  yum -y install aws-cli && \
  yum -y install openssl11-devel && \
  yum install make -y && \
  yum install yum install gcc-c++ -y && \
  yum install git zip -y && \
  yum install cmake3 -y && \
  yum remove cmake -y && \
  ln -s /usr/bin/cmake3 /usr/bin/cmake

RUN mkdir -p /tmp/from-git && cd /tmp/from-git && git clone https://github.com/duckdb/duckdb.git --branch v0.6.1

RUN cd /tmp/from-git/duckdb/tools/nodejs && ./configure && make
```

**Comment by tobilg** [comment]
Unfortunately still no success, not sure if due to lack of memory. Build VM has 11gb assigned...

```bash
#8 0.215 ++ dirname ./configure                                                                                                                               
#8 0.217 + cd .                                                                                                                                               
#8 0.217 + '[' '!' -f ../../scripts/amalgamation.py ']'                                                                                                       
#8 0.219 + cd ../..                                                                                                                                           
#8 0.219 + python3 scripts/amalgamation.py --extended --source=tools/nodejs/src/duckdb.cpp --header=tools/nodejs/src/duckdb.hpp
#8 1.482 -----------------------
#8 1.482 -- Writing tools/nodejs/src/duckdb.hpp --
#8 1.482 -----------------------
#8 1.482 ------------------------
#8 1.482 -- Writing tools/nodejs/src/duckdb.cpp --
#8 1.482 ------------------------
#8 1.489 + cd ../..
#8 1.489 + python3 scripts/parquet_amalgamation.py
#8 1.658 -----------------------
#8 1.658 -- Writing src/amalgamation/parquet-amalgamation.hpp --
#8 1.658 -----------------------
#8 1.658 ------------------------
#8 1.658 -- Writing src/amalgamation/parquet-amalgamation.cpp --
#8 1.658 ------------------------
#8 1.666 + cp src/amalgamation/parquet-amalgamation.cpp src/amalgamation/parquet-amalgamation.hpp tools/nodejs/src/
#8 1.679 npm install --build-from-source
#8 19.93 npm WARN deprecated @npmcli/move-file@2.0.1: This functionality has been moved to @npmcli/fs
#8 20.69 npm WARN deprecated querystring@0.2.0: The querystring API is considered Legacy. new code should use the URLSearchParams API instead.
#8 25.10 
#8 25.10 > duckdb@0.2.4 install
#8 25.10 > node-pre-gyp install --fallback-to-build
#8 25.10 
#8 25.20 node-pre-gyp info it worked if it ends with ok
#8 25.20 node-pre-gyp info using node-pre-gyp@1.0.10
#8 25.20 node-pre-gyp info using node@16.18.1 | linux | x64
#8 25.27 node-pre-gyp info build requesting source compile
#8 25.35 gyp info it worked if it ends with ok
#8 25.35 gyp info using node-gyp@9.1.0
#8 25.35 gyp info using node@16.18.1 | linux | x64
#8 25.37 gyp info ok 
#8 25.45 gyp info it worked if it ends with ok
#8 25.46 gyp info using node-gyp@9.1.0
#8 25.46 gyp info using node@16.18.1 | linux | x64
#8 25.52 gyp info find Python using Python version 3.7.15 found at "/usr/bin/python3"
#8 25.65 gyp http GET https://nodejs.org/download/release/v16.18.1/node-v16.18.1-headers.tar.gz
#8 25.86 gyp http 200 https://nodejs.org/download/release/v16.18.1/node-v16.18.1-headers.tar.gz
#8 26.40 gyp http GET https://nodejs.org/download/release/v16.18.1/SHASUMS256.txt
#8 26.48 gyp http 200 https://nodejs.org/download/release/v16.18.1/SHASUMS256.txt
#8 26.49 gyp info spawn /usr/bin/python3
#8 26.49 gyp info spawn args [
#8 26.49 gyp info spawn args   '/var/lang/lib/node_modules/npm/node_modules/node-gyp/gyp/gyp_main.py',
#8 26.49 gyp info spawn args   'binding.gyp',
#8 26.49 gyp info spawn args   '-f',
#8 26.49 gyp info spawn args   'make',
#8 26.49 gyp info spawn args   '-I',
#8 26.49 gyp info spawn args   '/tmp/from-git/duckdb/tools/nodejs/build/config.gypi',
#8 26.49 gyp info spawn args   '-I',
#8 26.49 gyp info spawn args   '/var/lang/lib/node_modules/npm/node_modules/node-gyp/addon.gypi',
#8 26.49 gyp info spawn args   '-I',
#8 26.50 gyp info spawn args   '/root/.cache/node-gyp/16.18.1/include/node/common.gypi',
#8 26.50 gyp info spawn args   '-Dlibrary=shared_library',
#8 26.50 gyp info spawn args   '-Dvisibility=default',
#8 26.50 gyp info spawn args   '-Dnode_root_dir=/root/.cache/node-gyp/16.18.1',
#8 26.50 gyp info spawn args   '-Dnode_gyp_dir=/var/lang/lib/node_modules/npm/node_modules/node-gyp',
#8 26.50 gyp info spawn args   '-Dnode_lib_file=/root/.cache/node-gyp/16.18.1/<(target_arch)/node.lib',
#8 26.50 gyp info spawn args   '-Dmodule_root_dir=/tmp/from-git/duckdb/tools/nodejs',
#8 26.50 gyp info spawn args   '-Dnode_engine=v8',
#8 26.50 gyp info spawn args   '--depth=.',
#8 26.50 gyp info spawn args   '--no-parallel',
#8 26.50 gyp info spawn args   '--generator-output',
#8 26.50 gyp info spawn args   'build',
#8 26.50 gyp info spawn args   '-Goutput_dir=.'
#8 26.50 gyp info spawn args ]
#8 26.70 gyp info ok 
#8 26.79 gyp info it worked if it ends with ok
#8 26.79 gyp info using node-gyp@9.1.0
#8 26.79 gyp info using node@16.18.1 | linux | x64
#8 26.81 gyp info spawn make
#8 26.82 gyp info spawn args [ 'BUILDTYPE=Release', '-C', 'build' ]
#8 26.82 make[1]: Entering directory `/tmp/from-git/duckdb/tools/nodejs/build'
#8 26.82   CXX(target) Release/obj.target/duckdb/src/duckdb_node.o
#8 31.99   CXX(target) Release/obj.target/duckdb/src/database.o
#8 38.51   CXX(target) Release/obj.target/duckdb/src/data_chunk.o
#8 44.51   CXX(target) Release/obj.target/duckdb/src/connection.o
#8 51.12   CXX(target) Release/obj.target/duckdb/src/statement.o
#8 57.81   CXX(target) Release/obj.target/duckdb/src/utils.o
#8 62.87   CXX(target) Release/obj.target/duckdb/src/parquet-amalgamation.o
#8 68.90 In file included from /usr/include/c++/7/cassert:44:0,
#8 68.90                  from ../src/parquet-amalgamation.cpp:42609:
#8 68.90 ../src/parquet-amalgamation.cpp: In member function ‘const ParquetRowGroup& duckdb::ParquetReader::GetGroup(duckdb::ParquetReaderScanState&)’:
#8 68.90 ../src/parquet-amalgamation.cpp:43148:53: warning: comparison of unsigned expression >= 0 is always true [-Wtype-limits]
#8 68.90   D_ASSERT(state.group_idx_list[state.current_group] >= 0 &&
#8 68.90 ../src/parquet-amalgamation.cpp:43148:2: note: in expansion of macro ‘D_ASSERT’
#8 68.90   D_ASSERT(state.group_idx_list[state.current_group] >= 0 &&
#8 68.90   ^~~~~~~~
#8 102.2 At global scope:
#8 102.2 cc1plus: warning: unrecognized command line option ‘-Wno-redundant-move’
#8 102.2 cc1plus: warning: unrecognized command line option ‘-Wno-redundant-move’
#8 102.8   CXX(target) Release/obj.target/duckdb/src/duckdb.o
#8 110.5 ../src/duckdb.cpp: In function ‘duckdb::hash_t duckdb::Hash(T) [with T = float; duckdb::hash_t = long unsigned int]’:
#8 110.5 ../src/duckdb.cpp:45688:36: warning: dereferencing type-punned pointer will break strict-aliasing rules [-Wstrict-aliasing]
#8 110.5   uint32_t uval = *((uint32_t *)&val);
#8 110.5                                     ^
#8 110.5 ../src/duckdb.cpp: In function ‘duckdb::hash_t duckdb::Hash(T) [with T = double; duckdb::hash_t = long unsigned int]’:
#8 110.5 ../src/duckdb.cpp:45696:36: warning: dereferencing type-punned pointer will break strict-aliasing rules [-Wstrict-aliasing]
#8 110.5   uint64_t uval = *((uint64_t *)&val);
#8 110.5                                     ^
#8 141.9 third_party/libpg_query/scan.l: In function ‘int duckdb_libpgquery::core_yylex(duckdb_libpgquery::core_YYSTYPE*, int*, duckdb_libpgquery::yyscan_t)’:
#8 141.9 third_party/libpg_query/scan.l:761:12: warning: variable ‘identlen’ set but not used [-Wunused-but-set-variable]
#8 141.9 third_party/libpg_query/scan.l:776:12: warning: variable ‘identlen’ set but not used [-Wunused-but-set-variable]
#8 141.9 third_party/libpg_query/src_backend_parser_scan.cpp: In function ‘int duckdb_libpgquery::yy_get_next_buffer(duckdb_libpgquery::yyscan_t)’:
#8 141.9 third_party/libpg_query/src_backend_parser_scan.cpp:2917:41: warning: comparison between signed and unsigned integer expressions [-Wsign-compare]
#8 174.8 ../src/duckdb.cpp: In instantiation of ‘static void duckdb::EmptyPatasWriter::Operation(VALUE_TYPE, bool, void*) [with VALUE_TYPE = float]’:
#8 174.8 ../src/duckdb.cpp:211288:28:   required from ‘bool duckdb::PatasState<T, EMPTY>::Update(T, bool) [with OP = duckdb::EmptyPatasWriter; T = float; bool EMPTY = true]’
#8 174.8 ../src/duckdb.cpp:211430:3:   required from ‘bool duckdb::PatasAnalyze(duckdb::AnalyzeState&, duckdb::Vector&, duckdb::idx_t) [with T = float; duckdb::idx_t = long unsigned int]’
#8 174.8 ../src/duckdb.cpp:211985:110:   required from here
#8 174.8 ../src/duckdb.cpp:211412:29: warning: dereferencing type-punned pointer will break strict-aliasing rules [-Wstrict-aliasing]
#8 174.8    state_wrapper->WriteValue(*(EXACT_TYPE *)(&uncompressed_value), is_valid);
#8 174.8                              ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
#8 174.8 ../src/duckdb.cpp: In instantiation of ‘static void duckdb::EmptyPatasWriter::Operation(VALUE_TYPE, bool, void*) [with VALUE_TYPE = double]’:
#8 174.8 ../src/duckdb.cpp:211288:28:   required from ‘bool duckdb::PatasState<T, EMPTY>::Update(T, bool) [with OP = duckdb::EmptyPatasWriter; T = double; bool EMPTY = true]’
#8 174.8 ../src/duckdb.cpp:211430:3:   required from ‘bool duckdb::PatasAnalyze(duckdb::AnalyzeState&, duckdb::Vector&, duckdb::idx_t) [with T = double; duckdb::idx_t = long unsigned int]’
#8 174.8 ../src/duckdb.cpp:211993:114:   required from here
#8 174.8 ../src/duckdb.cpp:211412:29: warning: dereferencing type-punned pointer will break strict-aliasing rules [-Wstrict-aliasing]
#8 182.4 ../src/duckdb.cpp: In instantiation of ‘void duckdb::ChimpCompressionState<T>::WriteValue(duckdb::ChimpCompressionState<T>::CHIMP_TYPE, bool) [with T = float; duckdb::ChimpCompressionState<T>::CHIMP_TYPE = unsigned int]’:
#8 182.4 ../src/duckdb.cpp:208512:14:   required from ‘void duckdb::ChimpCompressionState<T>::Append(duckdb::UnifiedVectorFormat&, duckdb::idx_t) [with T = float; duckdb::idx_t = long unsigned int]’
#8 182.4 ../src/duckdb.cpp:208650:2:   required from ‘void duckdb::ChimpCompress(duckdb::CompressionState&, duckdb::Vector&, duckdb::idx_t) [with T = float; duckdb::idx_t = long unsigned int]’
#8 182.4 ../src/duckdb.cpp:209006:9:   required from ‘duckdb::CompressionFunction duckdb::GetChimpFunction(duckdb::PhysicalType) [with T = float]’
#8 182.4 ../src/duckdb.cpp:209015:38:   required from here
#8 182.4 ../src/duckdb.cpp:208526:29: warning: dereferencing type-punned pointer will break strict-aliasing rules [-Wstrict-aliasing]
#8 182.4     T floating_point_value = *(T *)(&value);
#8 182.4                              ^~~~~~~~~~~~~~
#8 182.5 ../src/duckdb.cpp: In instantiation of ‘void duckdb::ChimpCompressionState<T>::WriteValue(duckdb::ChimpCompressionState<T>::CHIMP_TYPE, bool) [with T = double; duckdb::ChimpCompressionState<T>::CHIMP_TYPE = long unsigned int]’:
#8 182.5 ../src/duckdb.cpp:208512:14:   required from ‘void duckdb::ChimpCompressionState<T>::Append(duckdb::UnifiedVectorFormat&, duckdb::idx_t) [with T = double; duckdb::idx_t = long unsigned int]’
#8 182.5 ../src/duckdb.cpp:208650:2:   required from ‘void duckdb::ChimpCompress(duckdb::CompressionState&, duckdb::Vector&, duckdb::idx_t) [with T = double; duckdb::idx_t = long unsigned int]’
#8 182.5 ../src/duckdb.cpp:209006:9:   required from ‘duckdb::CompressionFunction duckdb::GetChimpFunction(duckdb::PhysicalType) [with T = double]’
#8 182.5 ../src/duckdb.cpp:209017:39:   required from here
#8 182.5 ../src/duckdb.cpp:208526:29: warning: dereferencing type-punned pointer will break strict-aliasing rules [-Wstrict-aliasing]
#8 182.5 ../src/duckdb.cpp: In instantiation of ‘static void duckdb::PatasCompressionState<T>::PatasWriter::Operation(VALUE_TYPE, bool, void*) [with VALUE_TYPE = float; T = float]’:
#8 182.5 ../src/duckdb.cpp:211288:28:   required from ‘bool duckdb::PatasState<T, EMPTY>::Update(T, bool) [with OP = duckdb::PatasCompressionState<float>::PatasWriter; T = float; bool EMPTY = false]’
#8 182.5 ../src/duckdb.cpp:211582:4:   required from ‘void duckdb::PatasCompressionState<T>::Append(duckdb::UnifiedVectorFormat&, duckdb::idx_t) [with T = float; duckdb::idx_t = long unsigned int]’
#8 182.5 ../src/duckdb.cpp:211661:2:   required from ‘void duckdb::PatasCompress(duckdb::CompressionState&, duckdb::Vector&, duckdb::idx_t) [with T = float; duckdb::idx_t = long unsigned int]’
#8 182.5 ../src/duckdb.cpp:211985:110:   required from here
#8 182.5 ../src/duckdb.cpp:211488:30: warning: dereferencing type-punned pointer will break strict-aliasing rules [-Wstrict-aliasing]
#8 182.5     state_wrapper->WriteValue(*(EXACT_TYPE *)(&value));
#8 182.5                               ^~~~~~~~~~~~~~~~~~~~~~~
#8 182.5 ../src/duckdb.cpp: In instantiation of ‘static void duckdb::PatasCompressionState<T>::PatasWriter::Operation(VALUE_TYPE, bool, void*) [with VALUE_TYPE = double; T = double]’:
#8 182.5 ../src/duckdb.cpp:211288:28:   required from ‘bool duckdb::PatasState<T, EMPTY>::Update(T, bool) [with OP = duckdb::PatasCompressionState<double>::PatasWriter; T = double; bool EMPTY = false]’
#8 182.5 ../src/duckdb.cpp:211582:4:   required from ‘void duckdb::PatasCompressionState<T>::Append(duckdb::UnifiedVectorFormat&, duckdb::idx_t) [with T = double; duckdb::idx_t = long unsigned int]’
#8 182.5 ../src/duckdb.cpp:211661:2:   required from ‘void duckdb::PatasCompress(duckdb::CompressionState&, duckdb::Vector&, duckdb::idx_t) [with T = double; duckdb::idx_t = long unsigned int]’
#8 182.5 ../src/duckdb.cpp:211993:114:   required from here
#8 182.5 ../src/duckdb.cpp:211488:30: warning: dereferencing type-punned pointer will break strict-aliasing rules [-Wstrict-aliasing]
#8 548.0 g++: internal compiler error: Killed (program cc1plus)
#8 548.0 Please submit a full bug report,
#8 548.0 with preprocessed source if appropriate.
#8 548.0 See <http://bugzilla.redhat.com/bugzilla> for instructions.
#8 548.0 make[1]: *** [Release/obj.target/duckdb/src/duckdb.o] Error 4
#8 548.1 make[1]: Leaving directory `/tmp/from-git/duckdb/tools/nodejs/build'
#8 548.3 gyp ERR! build error 
#8 548.4 gyp ERR! stack Error: `make` failed with exit code: 2
#8 548.4 gyp ERR! stack     at ChildProcess.onExit (/var/lang/lib/node_modules/npm/node_modules/node-gyp/lib/build.js:201:23)
#8 548.4 gyp ERR! stack     at ChildProcess.emit (node:events:513:28)
#8 548.4 gyp ERR! stack     at Process.ChildProcess._handle.onexit (node:internal/child_process:293:12)
#8 548.4 gyp ERR! System Linux 5.10.104-linuxkit
#8 548.4 gyp ERR! command "/var/lang/bin/node" "/var/lang/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "build" "--fallback-to-build" "--module=/tmp/from-git/duckdb/tools/nodejs/lib/binding/duckdb.node" "--module_name=duckdb" "--module_path=/tmp/from-git/duckdb/tools/nodejs/lib/binding" "--napi_version=8" "--node_abi_napi=napi" "--napi_build_version=0" "--node_napi_label=node-v93"
#8 548.4 gyp ERR! cwd /tmp/from-git/duckdb/tools/nodejs
#8 548.4 gyp ERR! node -v v16.18.1
#8 548.4 gyp ERR! node-gyp -v v9.1.0
#8 548.4 gyp ERR! not ok 
#8 548.7 node-pre-gyp ERR! build error 
#8 548.7 node-pre-gyp ERR! stack Error: Failed to execute '/var/lang/bin/node /var/lang/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js build --fallback-to-build --module=/tmp/from-git/duckdb/tools/nodejs/lib/binding/duckdb.node --module_name=duckdb --module_path=/tmp/from-git/duckdb/tools/nodejs/lib/binding --napi_version=8 --node_abi_napi=napi --napi_build_version=0 --node_napi_label=node-v93' (1)
#8 548.7 node-pre-gyp ERR! stack     at ChildProcess.<anonymous> (/tmp/from-git/duckdb/tools/nodejs/node_modules/@mapbox/node-pre-gyp/lib/util/compile.js:89:23)
#8 548.7 node-pre-gyp ERR! stack     at ChildProcess.emit (node:events:513:28)
#8 548.7 node-pre-gyp ERR! stack     at maybeClose (node:internal/child_process:1100:16)
#8 548.7 node-pre-gyp ERR! stack     at Process.ChildProcess._handle.onexit (node:internal/child_process:304:5)
#8 548.7 node-pre-gyp ERR! System Linux 5.10.104-linuxkit
#8 548.7 node-pre-gyp ERR! command "/var/lang/bin/node" "/tmp/from-git/duckdb/tools/nodejs/node_modules/.bin/node-pre-gyp" "install" "--fallback-to-build"
#8 548.7 node-pre-gyp ERR! cwd /tmp/from-git/duckdb/tools/nodejs
#8 548.7 node-pre-gyp ERR! node -v v16.18.1
#8 548.7 node-pre-gyp ERR! node-pre-gyp -v v1.0.10
#8 548.7 node-pre-gyp ERR! not ok 
#8 548.8 Failed to execute '/var/lang/bin/node /var/lang/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js build --fallback-to-build --module=/tmp/from-git/duckdb/tools/nodejs/lib/binding/duckdb.node --module_name=duckdb --module_path=/tmp/from-git/duckdb/tools/nodejs/lib/binding --napi_version=8 --node_abi_napi=napi --napi_build_version=0 --node_napi_label=node-v93' (1)
#8 549.3 npm notice 
#8 549.3 npm notice New major version of npm available! 8.19.2 -> 9.2.0
#8 549.3 npm notice Changelog: <https://github.com/npm/cli/releases/tag/v9.2.0>
#8 549.3 npm notice Run `npm install -g npm@9.2.0` to update!
#8 549.3 npm notice 
#8 549.4 npm ERR! code 1
#8 549.4 npm ERR! path /tmp/from-git/duckdb/tools/nodejs
#8 549.4 npm ERR! command failed
#8 549.4 npm ERR! command sh -c -- node-pre-gyp install --fallback-to-build
#8 549.5 
#8 549.5 npm ERR! A complete log of this run can be found in:
#8 549.5 npm ERR!     /root/.npm/_logs/2022-12-13T14_38_33_790Z-debug-0.log
#8 549.6 make: *** [node_modules] Error 1
```

**Comment by tobilg** [comment]
With 16gb for the VM, the build succeeded.

**Comment by Tishj** [comment]
That's quite a large amount of RAM, are you sure you're not trying to run this build with way too many workers?

**Comment by Mytherin** [comment]
The RAM requirement is caused by the Node client using the amalgamation build. I am going to have a look at stripping this and switching over to `package_build` like the other clients.

**Comment by tobilg** [comment]
I'm not an eypert, but I guess it uses the settings from https://github.com/duckdb/duckdb/blob/master/tools/nodejs/Makefile#L10 @Mytherin...

Another question: Now that the binary is created, is there a way to generate the package the same way as it's published to NPM? 

Thanks for all the help
