### ISSUE TITLE
attaching a duckdb file from azure using fsspec does not work

### ISSUE THREAD

**Issue by Mause** [duckdb/duckdb#6240]
### What happens?

attaching a duckdb file from azure using fsspec does not work

### To Reproduce

using this code

```py
import duckdb
import adlfs ,os
from dotenv import load_dotenv
load_dotenv()
AZURE_STORAGE_ACCOUNT_NAME = os.getenv('AZURE_STORAGE_ACCOUNT_NAME') 
AZURE_STORAGE_ACCOUNT_KEY = os.getenv('AZURE_STORAGE_ACCOUNT_KEY') 
table_path = os.getenv('table_path') 
fs = adlfs.AzureBlobFileSystem(account_name=AZURE_STORAGE_ACCOUNT_NAME, account_key=AZURE_STORAGE_ACCOUNT_KEY )
duckdb.register_filesystem(fs)

duckdb.query(f''' load httpfs;
PRAGMA enable_object_cache;
PRAGMA disable_progress_bar;
SET enable_http_metadata_cache=true ;
ATTACH  '{table_path}/TPCH/tpch.duckdb' as db ;
use db
  ''')
```

i get this error

```
Exception ignored in: <function AzureBlobFile.__del__ at 0x000001BFBF448A60>
Traceback (most recent call last):
  File "[c:\Users\mimoune.djouallah\AppData\Local\Programs\Python\Python310\lib\site-packages\adlfs\spec.py](file:///C:/Users/mimoune.djouallah/AppData/Local/Programs/Python/Python310/lib/site-packages/adlfs/spec.py)", line 2102, in __del__
    self.close()
  File "[c:\Users\mimoune.djouallah\AppData\Local\Programs\Python\Python310\lib\site-packages\adlfs\spec.py](file:///C:/Users/mimoune.djouallah/AppData/Local/Programs/Python/Python310/lib/site-packages/adlfs/spec.py)", line 1919, in close
    super().close()
  File "[c:\Users\mimoune.djouallah\AppData\Local\Programs\Python\Python310\lib\site-packages\fsspec\spec.py](file:///C:/Users/mimoune.djouallah/AppData/Local/Programs/Python/Python310/lib/site-packages/fsspec/spec.py)", line 1728, in close
    if not self.forced:
AttributeError: 'AzureBlobFile' object has no attribute 'forced'
Output exceeds the [size limit](command:workbench.action.openSettings?[). Open the full output data [in a text editor](command:workbench.action.openLargeOutput?039bd1a6-10b9-4241-b5dc-2a00667970e4)
---------------------------------------------------------------------------
Error                                     Traceback (most recent call last)
c:\Users\mimoune.djouallah\Desktop\azure\azure_Read.ipynb Cell 6 in <cell line: 1>()
----> [1](vscode-notebook-cell:/c%3A/Users/mimoune.djouallah/Desktop/azure/azure_Read.ipynb#W3sZmlsZQ%3D%3D?line=0) duckdb.query(f''' load httpfs;
      [2](vscode-notebook-cell:/c%3A/Users/mimoune.djouallah/Desktop/azure/azure_Read.ipynb#W3sZmlsZQ%3D%3D?line=1) PRAGMA enable_object_cache;
      [3](vscode-notebook-cell:/c%3A/Users/mimoune.djouallah/Desktop/azure/azure_Read.ipynb#W3sZmlsZQ%3D%3D?line=2) PRAGMA disable_progress_bar;
      [4](vscode-notebook-cell:/c%3A/Users/mimoune.djouallah/Desktop/azure/azure_Read.ipynb#W3sZmlsZQ%3D%3D?line=3) SET enable_http_metadata_cache=true ;
      [5](vscode-notebook-cell:/c%3A/Users/mimoune.djouallah/Desktop/azure/azure_Read.ipynb#W3sZmlsZQ%3D%3D?line=4) ATTACH  '{table_path}/TPCH/tpch.duckdb' as db ;
      [6](vscode-notebook-cell:/c%3A/Users/mimoune.djouallah/Desktop/azure/azure_Read.ipynb#W3sZmlsZQ%3D%3D?line=5) use db
      [7](vscode-notebook-cell:/c%3A/Users/mimoune.djouallah/Desktop/azure/azure_Read.ipynb#W3sZmlsZQ%3D%3D?line=6)   ''')

Error: Invalid Error: NotImplementedError: File mode not supported

At:
  c:\Users\mimoune.djouallah\AppData\Local\Programs\Python\Python310\lib\site-packages\adlfs\spec.py(1880): __init__
  c:\Users\mimoune.djouallah\AppData\Local\Programs\Python\Python310\lib\site-packages\adlfs\spec.py(1756): _open
  c:\Users\mimoune.djouallah\AppData\Local\Programs\Python\Python310\lib\site-packages\fsspec\spec.py(1094): open
  C:\Users\mimoune.djouallah\AppData\Local\Temp\ipykernel_26520\745453902.py(1): <cell line: 1>
  c:\Users\mimoune.djouallah\AppData\Local\Programs\Python\Python310\lib\site-packages\IPython\core\interactiveshell.py(3398): run_code
  c:\Users\mimoune.djouallah\AppData\Local\Programs\Python\Python310\lib\site-packages\IPython\core\interactiveshell.py(3338): run_ast_nodes
  c:\Users\mimoune.djouallah\AppData\Local\Programs\Python\Python310\lib\site-packages\IPython\core\interactiveshell.py(3135): run_cell_async
  c:\Users\mimoune.djouallah\AppData\Local\Programs\Python\Python310\lib\site-packages\IPython\core\async_helpers.py(129): _pseudo_sync_runner
  c:\Users\mimoune.djouallah\AppData\Local\Programs\Python\Python310\lib\site-packages\IPython\core\interactiveshell.py(2936): _run_cell
  c:\Users\mimoune.djouallah\AppData\Local\Programs\Python\Python310\lib\site-packages\IPython\core\interactiveshell.py(2881): run_cell
  c:\Users\mimoune.djouallah\AppData\Local\Programs\Python\Python310\lib\site-packages\ipykernel\zmqshell.py(528): run_cell
...
  c:\Users\mimoune.djouallah\AppData\Local\Programs\Python\Python310\lib\site-packages\traitlets\config\application.py(976): launch_instance
  c:\Users\mimoune.djouallah\AppData\Local\Programs\Python\Python310\lib\site-packages\ipykernel_launcher.py(17): <module>
  c:\Users\mimoune.djouallah\AppData\Local\Programs\Python\Python310\lib\runpy.py(86): _run_code
  c:\Users\mimoune.djouallah\AppData\Local\Programs\Python\Python310\lib\runpy.py(196): _run_module_as_main
```

### OS:

Windows

### DuckDB Version:

0.6.2.dev2480

### DuckDB Client:

Python

### Full Name:

Mimoune

### Affiliation:

Personal

### Have you tried this on the latest `master` branch?

- [X] I agree

### Have you tried the steps to reproduce? Do they include all relevant data and configuration? Does the issue you report still appear there?

- [X] I agree

**Comment by Mause** [comment]
Created from https://github.com/duckdb/duckdb/discussions/6217

**Comment by Mause** [comment]
okay, @djouallah

thankfully the "Not mode not supported" and "self.forced" errors aren't from DuckDB, they're from adlfs not supporting read+write file modes, plus a race condition in their `__del__` method, you can replicate that using this code sample:

```py
import os
import adlfs
from dotenv import load_dotenv

load_dotenv()
AZURE_STORAGE_ACCOUNT_NAME = os.getenv('AZURE_STORAGE_ACCOUNT_NAME') 
AZURE_STORAGE_ACCOUNT_KEY = os.getenv('AZURE_STORAGE_ACCOUNT_KEY') 
table_path = os.getenv('table_path') 
fs = adlfs.AzureBlobFileSystem(account_name=AZURE_STORAGE_ACCOUNT_NAME, account_key=AZURE_STORAGE_ACCOUNT_KEY )

obj = fs.open(f'{table_path}/TPCH/tpch.duckdb', 'rb+', seekable=True)
```

what that means is, until the `adlfs` library supports read+write mode (if they ever do), you can only attach databases in read only mode, like so:

```py
duckdb.query(f'''
PRAGMA enable_object_cache;
PRAGMA disable_progress_bar;
SET enable_http_metadata_cache=true ;
ATTACH '{table_path}/TPCH/tpch.duckdb' as db (READ_ONLY);
use db
''')
```

**Comment by djouallah** [comment]
@Mause thanks a lot my bad, I thought the attach was read only by default, my apology

**Comment by Mause** [comment]
> @Mause thanks a lot my bad, I thought the attach was read only by default, my apology

No worries.
I've raised the adlfs bug on their side as https://github.com/fsspec/adlfs/issues/397 at least, so hopefully the error will be less confusing once that's fixed
