### ISSUE TITLE
DuckDB cannot work on Linux aarch64 system with PAGE_SIZE of 64k.

### ISSUE THREAD

**Issue by Shawn201107** [duckdb/duckdb#6476]
### What happens?

DuckDB cannot work on Linux aarch64 system with PAGE_SIZE of 64k. I have tried to recompile duckdb on Linux system, it still cannot work. While it can work on Linux aarch64 system with PAGE_SIZE of 4k.

### To Reproduce

1. Prepare a Linux aarch64 system with PAGE_SIZE of 64k. I created a `RHEL 8.6 arm64` VM on Azure.
```
[xavier@RHEL8Testing ~]$ uname -a
Linux RHEL8Testing 4.18.0-372.9.1.el8.aarch64 #1 SMP Fri Apr 15 22:01:11 EDT 2022 aarch64 aarch64 aarch64 GNU/Linux

[xavier@RHEL8Testing ~]$ getconf PAGESIZE
65536
```
2. Run duckdb CLI and run sql statement `SELECT 'quack' AS my_column;`.
```
[xavier@RHEL8Testing duckdb_cli]$ ./duckdb
v0.6.0 2213f9c946
Enter ".help" for usage hints.
Connected to a transient in-memory database.
Use ".open FILENAME" to reopen on a persistent database.
D SELECT 'quack' AS my_column;
Segmentation fault (core dumped)
```
3. Or using JDBC to get a connection of duckdb.
```
java.sql.SQLException: Invalid Error: std::bad_alloc
        at org.duckdb.DuckDBNative.duckdb_jdbc_startup(Native Method)
        at org.duckdb.DuckDBDatabase.<init>(DuckDBDatabase.java:28)
        at org.duckdb.DuckDBDriver.connect(DuckDBDriver.java:38)
        at java.sql.DriverManager.getConnection(DriverManager.java:664)
        at java.sql.DriverManager.getConnection(DriverManager.java:270)
        at Main.main(Main.java:11)
```

### OS:

RHEL 8.6 arm64

### DuckDB Version:

0.6.0

### DuckDB Client:

CLI, JDBC

### Full Name:

ShawnWu

### Affiliation:

Personal

### Have you tried this on the latest `master` branch?

- [X] I agree

### Have you tried the steps to reproduce? Do they include all relevant data and configuration? Does the issue you report still appear there?

- [X] I agree

**Comment by hannes** [comment]
Can you try with `BUILD_JEMALLOC_EXTENSION=0` on the `cmake` command line?

**Comment by Shawn201107** [comment]
Ok, I will try it.

**Comment by Shawn201107** [comment]
I have tried to using `BUILD_JDBC=1 BUILD_JEMALLOC_EXTENSION=0 make` to recompile. It doesn't seem to be working.

Run duckdb CLI and run sql statement `SELECT 'quack' AS my_column;`.
```
[xavier@RHEL8Testing duckdb_cli]$ ./duckdb
v0.6.0 2213f9c946
Enter ".help" for usage hints.
Connected to a transient in-memory database.
Use ".open FILENAME" to reopen on a persistent database.
D SELECT 'quack' AS my_column;
Segmentation fault (core dumped)
```

Use JDBC to get a connection of duckdb, 
```
#
# A fatal error has been detected by the Java Runtime Environment:
#
#  SIGSEGV (0xb) at pc=0x0000ffff7675a864, pid=11977, tid=0x0000ffffaf64f1e0
#
# JRE version: OpenJDK Runtime Environment (8.0_362-b09) (build 1.8.0_362-b09)
# Java VM: OpenJDK 64-Bit Server VM (25.362-b09 mixed mode linux-aarch64 compressed oops)
# Problematic frame:
# C  [libduckdb_java2335199867687113056.so+0x93a864]  duckdb::UndoBuffer::CreateEntry(duckdb::UndoFlags, unsigned long)+0x2c
#
# Failed to write core dump. Core dumps have been disabled. To enable core dumping, try "ulimit -c unlimited" before starting Java again
#
# An error report file with more information is saved as:
# /home/xavier/hs_err_pid11977.log
#
# If you would like to submit a bug report, please visit:
#   https://bugzilla.redhat.com/enter_bug.cgi?product=Red%20Hat%20Enterprise%20Linux%208&component=java-1.8.0-openjdk
# The crash happened outside the Java Virtual Machine in native code.
# See problematic frame for where to report the bug.
#
Aborted (core dumped)
```

And I also tried to compile the master branch, it still doesn't work.
```
[xavier@RHEL8Testing release]$ ./duckdb
v0.7.1-dev415 ae3510f069
Enter ".help" for usage hints.
Connected to a transient in-memory database.
Use ".open FILENAME" to reopen on a persistent database.
D SELECT 'quack' AS my_column;
Error: unable to open database ":memory:": Out of Memory Error: Failed to allocate block of 2048 bytes
```

**Comment by Shawn201107** [comment]
I tried version 0.5.1, it can work. So I think it maybe a bug introduced after 0.6.0. @hannes 

```
[xavier@RHEL8Testing duckdb_cli_0.5.1]# ./duckdb
v0.5.1 7c111322d
Enter ".help" for usage hints.
Connected to a transient in-memory database.
Use ".open FILENAME" to reopen on a persistent database.
D SELECT 'quack' AS my_column;
┌───────────┐
│ my_column │
├───────────┤
│ quack     │
└───────────┘
D
```

**Comment by Mytherin** [comment]
0.6.0 is when we started including `jemalloc`. In your build it looks like you are passing `BUILD_JEMALLOC_EXTENSION=0` to make instead of to cmake - likely still building with jemalloc.  Try building like so:

```bash
mkdir build
cd build
cmake -DBUILD_JEMALLOC_EXTENSION=0 ..
cmake --build .
```

**Comment by Shawn201107** [comment]
@Mytherin Thanks for sharing the example. I tried it, but the following output was found in the process of building. It still seems to be built with jemalloc. `cmake -DBUILD_JEMALLOC_EXTENSION=0 ..` doesn't seem to be working.

```
……
[ 59%] Building CXX object extension/jemalloc/jemalloc/CMakeFiles/jemalloc.dir/src/tsd.cpp.o
[ 59%] Building CXX object extension/jemalloc/jemalloc/CMakeFiles/jemalloc.dir/src/witness.cpp.o
[ 59%] Built target jemalloc
[ 59%] Building CXX object extension/jemalloc/CMakeFiles/jemalloc_extension.dir/jemalloc-extension.cpp.o
[ 59%] Linking CXX static library libjemalloc_extension.a
[ 59%] Built target jemalloc_extension
……
```

After the building, I tried to run CLI and run sql statement `SELECT 'quack' AS my_column;`. The error still exists.
```
[xavier@RHEL8Testing build]$ ./duckdb
v0.6.0 2213f9c946
Enter ".help" for usage hints.
Connected to a transient in-memory database.
Use ".open FILENAME" to reopen on a persistent database.
D SELECT 'quack' AS my_column;
Segmentation fault (core dumped)
```

Are there any parameters missing on my `cmake` command line?

**Comment by Mytherin** [comment]
Are you compiling the latest set of sources?

**Comment by Shawn201107** [comment]
@Mytherin Thanks for reminding! I tried to compile the latest master branch via `cmake -DBUILD_JEMALLOC_EXTENSION=0 ..`. It works!

```
[xavier@RHEL8Testing build]$ ./duckdb
v0.7.2-dev14 c817201fa8
Enter ".help" for usage hints.
Connected to a transient in-memory database.
Use ".open FILENAME" to reopen on a persistent database.
D SELECT 'quack' AS my_column;
┌───────────┐
│ my_column │
│  varchar  │
├───────────┤
│ quack     │
└───────────┘
D
```
