### ISSUE TITLE
Empty structs are serialized as varchar in Parquet files and may trigger core dumps after export/import

### ISSUE THREAD

**Issue by chumbert2** [duckdb/duckdb#6481]
### What happens?

(This is related to the closed issue <https://github.com/duckdb/duckdb/issues/6443>.)

The type of an empty struct is not preserved when it is copied to a Parquet file (saved as `varchar`).
A core dumps may occur when the DB imported.

### To Reproduce

```bash
cat <<EOF > data.ndjson
{"c1":"val11","c2":{"k1":"val11","k2":{}}}
{"c1":"val21","c2":{"k1":"val21","k2":{}}}
EOF
```

```
In duckdb CLI
v0.7.1-dev369 c907a24be7 (include the fix for #6443)
Built from source as follows:
EXTENSION_STATIC_BUILD=1 BUILD_PYTHON=1 BUILD_JSON=1 make

create table t as select * from read_ndjson_auto('data.ndjson');

-- type of k2 is json as expected.
select * from t;
┌─────────┬─────────────────────────────┐
│   c1    │             c2              │
│ varchar │ struct(k1 varchar, k2 json) │
├─────────┼─────────────────────────────┤
│ val11   │ {'k1': val11, 'k2': {}}     │
│ val21   │ {'k1': val21, 'k2': {}}     │
└─────────┴─────────────────────────────┘

copy t to 'data.parquet';


-- Reload data from the Parquet file.
select * from 'data.parquet';
-- As expected, the error "Node has no children but should" is not present anymore (fixed in #6443),
-- but the type of k2 is now varchar (expected: json).
┌─────────┬────────────────────────────────┐
│   c1    │               c2               │
│ varchar │ struct(k1 varchar, k2 varchar) │
├─────────┼────────────────────────────────┤
│ val11   │ {'k1': val11, 'k2': {}}        │
│ val21   │ {'k1': val21, 'k2': {}}        │
└─────────┴────────────────────────────────┘

-- (See below)
export database 'dump';
```

If I export the database and then import it in a new DuckDB session, a core dump occurs.

```
duckdb
v0.7.1-dev369 c907a24be7
Enter ".help" for usage hints.
Connected to a transient in-memory database.
Use ".open FILENAME" to reopen on a persistent database.
D import database 'dump';
Segmentation fault (core dumped)
```

```
user@t490:~/src/duckdb$ gdb ./build/debug/duckdb core
GNU gdb (Debian 13.1-2) 13.1
Copyright (C) 2023 Free Software Foundation, Inc.
License GPLv3+: GNU GPL version 3 or later <http://gnu.org/licenses/gpl.html>
This is free software: you are free to change and redistribute it.
There is NO WARRANTY, to the extent permitted by law.
Type "show copying" and "show warranty" for details.
This GDB was configured as "x86_64-linux-gnu".
Type "show configuration" for configuration details.
For bug reporting instructions, please see:
<https://www.gnu.org/software/gdb/bugs/>.
Find the GDB manual and other documentation resources online at:
    <http://www.gnu.org/software/gdb/documentation/>.

For help, type "help".
Type "apropos word" to search for commands related to "word"...
Reading symbols from ./build/debug/duckdb...
[New LWP 16927]
[New LWP 16930]
[New LWP 16928]
[New LWP 16934]
[New LWP 16932]
[New LWP 16929]
[New LWP 16933]
[New LWP 16931]
[Thread debugging using libthread_db enabled]
Using host libthread_db library "/lib/x86_64-linux-gnu/libthread_db.so.1".
Core was generated by `./build/debug/duckdb'.
Program terminated with signal SIGSEGV, Segmentation fault.
#0  std::__uniq_ptr_impl<duckdb::ArenaChunk, std::default_delete<duckdb::ArenaChunk> >::_M_ptr (this=0x18)
    at /usr/include/c++/12/bits/unique_ptr.h:191
191	     pointer    _M_ptr() const noexcept { return std::get<0>(_M_t); }
[Current thread is 1 (Thread 0x7fce77e66780 (LWP 16927))]
(gdb) bt
#0  std::__uniq_ptr_impl<duckdb::ArenaChunk, std::default_delete<duckdb::ArenaChunk> >::_M_ptr (this=0x18)
    at /usr/include/c++/12/bits/unique_ptr.h:191
#1  0x0000562c012afd16 in std::unique_ptr<duckdb::ArenaChunk, std::default_delete<duckdb::ArenaChunk> >::get (this=0x18)
    at /usr/include/c++/12/bits/unique_ptr.h:462
#2  0x0000562c012afb22 in std::unique_ptr<duckdb::ArenaChunk, std::default_delete<duckdb::ArenaChunk> >::operator bool (this=0x18)
    at /usr/include/c++/12/bits/unique_ptr.h:479
#3  0x0000562c0128b490 in duckdb::ArenaAllocator::Reset (this=0x8) at /home/user/src/duckdb/src/storage/arena_allocator.cpp:81
#4  0x0000562c02555e8c in duckdb::JSONAllocator::Reset (this=0x8) at /home/user/src/duckdb/extension/json/include/json_common.hpp:30
#5  0x0000562c02554d53 in duckdb::CastVarcharToJSON (source=..., result=..., count=2, parameters=...)
    at /home/user/src/duckdb/extension/json/json_functions.cpp:193
#6  0x0000562c0156b28e in duckdb::VectorStringToStruct::StringToNestedTypeCastLoop (source_data=0x7fce77e33640, source_mask=..., result=..., 
    result_mask=..., count=2, parameters=..., 
    sel=0x562c038b41f0 <duckdb::FlatVector::IncrementalSelectionVector()::INCREMENTAL_SELECTION_VECTOR>)
    at /home/user/src/duckdb/src/function/cast/string_cast.cpp:226
#7  0x0000562c015ba95a in duckdb::StringToNestedTypeCast<duckdb::VectorStringToStruct> (source=..., result=..., count=2, parameters=...)
    at /home/user/src/duckdb/src/function/cast/string_cast.cpp:336
#8  0x0000562c00d32d05 in duckdb::VectorOperations::TryCast (set=..., input=..., source=..., result=..., count=2, 
    error_message=0x7ffd76bff4f0, strict=false) at /home/user/src/duckdb/src/common/vector_operations/vector_cast.cpp:17
#9  0x0000562c00d32eac in duckdb::VectorOperations::TryCast (context=..., source=..., result=..., count=2, error_message=0x7ffd76bff4f0, 
    strict=false) at /home/user/src/duckdb/src/common/vector_operations/vector_cast.cpp:35
#10 0x0000562c01b5b445 in duckdb::BaseCSVReader::Flush (this=0x562c04e96090, insert_chunk=..., try_add_line=false)
    at /home/user/src/duckdb/src/execution/operator/persistent/base_csv_reader.cpp:479
#11 0x0000562c01b65d6a in duckdb::BufferedCSVReader::TryParseSimpleCSV (this=0x562c04e96090, insert_chunk=..., error_message="")
    at /home/user/src/duckdb/src/execution/operator/persistent/buffered_csv_reader.cpp:1374
#12 0x0000562c01b66764 in duckdb::BufferedCSVReader::TryParseCSV (this=0x562c04e96090, parser_mode=duckdb::ParserMode::PARSING, 
    insert_chunk=..., error_message="") at /home/user/src/duckdb/src/execution/operator/persistent/buffered_csv_reader.cpp:1462
#13 0x0000562c01b66484 in duckdb::BufferedCSVReader::ParseCSV (this=0x562c04e96090, insert_chunk=...)
    at /home/user/src/duckdb/src/execution/operator/persistent/buffered_csv_reader.cpp:1439
#14 0x0000562c01938fbc in duckdb::SingleThreadedCSVFunction (context=..., data_p=..., output=...)
    at /home/user/src/duckdb/src/function/table/read_csv.cpp:673
#15 0x0000562c01939b06 in duckdb::ReadCSVFunction (context=..., data_p=..., output=...)
    at /home/user/src/duckdb/src/function/table/read_csv.cpp:764
#16 0x0000562c01ba321b in duckdb::PhysicalTableScan::GetData (this=0x562c04e8dce0, context=..., chunk=..., gstate_p=..., lstate=...)
    at /home/user/src/duckdb/src/execution/operator/scan/physical_table_scan.cpp:83
#17 0x0000562c01177905 in duckdb::PipelineExecutor::FetchFromSource (this=0x562c04e394d0, result=...)
    at /home/user/src/duckdb/src/parallel/pipeline_executor.cpp:366
#18 0x0000562c0117663c in duckdb::PipelineExecutor::Execute (this=0x562c04e394d0, max_chunks=50)
    at /home/user/src/duckdb/src/parallel/pipeline_executor.cpp:47
#19 0x0000562c01179ffa in duckdb::PipelineTask::ExecuteTask (this=0x562c04e90f30, mode=duckdb::TaskExecutionMode::PROCESS_PARTIAL)
--Type <RET> for more, q to quit, c to continue without paging--
    at /home/user/src/duckdb/src/parallel/pipeline.cpp:37
#20 0x0000562c01170fe7 in duckdb::ExecutorTask::Execute (this=0x562c04e90f30, mode=duckdb::TaskExecutionMode::PROCESS_PARTIAL)
    at /home/user/src/duckdb/src/parallel/executor_task.cpp:17
#21 0x0000562c01173553 in duckdb::Executor::ExecuteTask (this=0x562c04e38fa0) at /home/user/src/duckdb/src/parallel/executor.cpp:396
#22 0x0000562c010920a1 in duckdb::ClientContext::ExecuteTaskInternal (this=0x562c04e302c0, lock=..., result=...)
    at /home/user/src/duckdb/src/main/client_context.cpp:438
#23 0x0000562c010a1ee3 in duckdb::PendingQueryResult::ExecuteTaskInternal (this=0x562c04e92fe0, lock=...)
    at /home/user/src/duckdb/src/main/pending_query_result.cpp:53
#24 0x0000562c010a1f22 in duckdb::PendingQueryResult::ExecuteInternal (this=0x562c04e92fe0, lock=...)
    at /home/user/src/duckdb/src/main/pending_query_result.cpp:58
#25 0x0000562c010a2036 in duckdb::PendingQueryResult::Execute (this=0x562c04e92fe0)
    at /home/user/src/duckdb/src/main/pending_query_result.cpp:70
#26 0x0000562c010a27ad in duckdb::PreparedStatement::Execute (this=0x562c04e35bf0, values=std::vector of length 0, capacity 0, 
    allow_stream_result=false) at /home/user/src/duckdb/src/main/prepared_statement.cpp:73
#27 0x0000562c00ad9643 in duckdb_shell_sqlite3_print_duckbox (pStmt=0x562c04e39970, max_rows=40, max_width=0, null_value=0x7ffd76c00e34 "")
    at /home/user/src/duckdb/tools/sqlite3_api_wrapper/sqlite3_api_wrapper.cpp:237
#28 0x0000562c00ab9625 in exec_prepared_stmt (pArg=0x7ffd76c00d20, pStmt=0x562c04e39970) at /home/user/src/duckdb/tools/shell/shell.c:12897
#29 0x0000562c00aba42f in shell_exec (pArg=0x7ffd76c00d20, zSql=0x562c04e30ba0 "import database 'dump';", pzErrMsg=0x7ffd76c00c80)
    at /home/user/src/duckdb/tools/shell/shell.c:13232
#30 0x0000562c00ac88de in runOneSqlLine (p=0x7ffd76c00d20, zSql=0x562c04e30ba0 "import database 'dump';", in=0x0, startline=1)
    at /home/user/src/duckdb/tools/shell/shell.c:20068
#31 0x0000562c00ac8e69 in process_input (p=0x7ffd76c00d20) at /home/user/src/duckdb/tools/shell/shell.c:20186
#32 0x0000562c00acaa3b in main (argc=1, argv=0x7ffd76c020c8) at /home/user/src/duckdb/tools/shell/shell.c:21007
(gdb) 
```

### OS:

Debian GNU/Linux

### DuckDB Version:

v0.7.1-dev369 c907a24be7

### DuckDB Client:

CLI

### Full Name:

Cyril Humbert

### Affiliation:

Air Liquide

### Have you tried this on the latest `master` branch?

- [X] I agree

### Have you tried the steps to reproduce? Do they include all relevant data and configuration? Does the issue you report still appear there?

- [X] I agree

**Comment by chumbert2** [comment]
The core dump does not occur anymore with v0.8.1.
