### ISSUE TITLE
UDF column type mismatch, expected [NULL], got [BLOB]

### ISSUE THREAD

**Issue by hinxx** [duckdb/duckdb#6532]
### What happens?

When trying to apply a `map` to a BLOB column an error is returned:
```
InvalidInputException: Invalid Input Error: UDF column type mismatch, expected [NULL], got [BLOB]
```

### To Reproduce

```
import duckdb

def nop(df):
    return df

duckdb.values([b'1234']).map(nop)

---------------------------------------------------------------------------
InvalidInputException                     Traceback (most recent call last)
File /data/data/Code/orc/python/venv/lib/python3.8/site-packages/IPython/core/formatters.py:706, in PlainTextFormatter.__call__(self, obj)
    699 stream = StringIO()
    700 printer = pretty.RepresentationPrinter(stream, self.verbose,
    701     self.max_width, self.newline,
    702     max_seq_length=self.max_seq_length,
    703     singleton_pprinters=self.singleton_printers,
    704     type_pprinters=self.type_printers,
    705     deferred_pprinters=self.deferred_printers)
--> 706 printer.pretty(obj)
    707 printer.flush()
    708 return stream.getvalue()

File /data/data/Code/orc/python/venv/lib/python3.8/site-packages/IPython/lib/pretty.py:410, in RepresentationPrinter.pretty(self, obj)
    407                         return meth(obj, self, cycle)
    408                 if cls is not object \
    409                         and callable(cls.__dict__.get('__repr__')):
--> 410                     return _repr_pprint(obj, self, cycle)
    412     return _default_pprint(obj, self, cycle)
    413 finally:

File /data/data/Code/orc/python/venv/lib/python3.8/site-packages/IPython/lib/pretty.py:778, in _repr_pprint(obj, p, cycle)
    776 """A pprint that just redirects to the normal repr function."""
    777 # Find newlines and replace them with p.break_()
...
--> 778 output = repr(obj)
    779 lines = output.splitlines()
    780 with p.group():

InvalidInputException: Invalid Input Error: UDF column type mismatch, expected [NULL], got [BLOB]
```

### OS:

linux

### DuckDB Version:

0.7.1

### DuckDB Client:

python

### Full Name:

Hinko Kocevar

### Affiliation:

ESS ERIC

### Have you tried this on the latest `master` branch?

- [X] I agree

### Have you tried the steps to reproduce? Do they include all relevant data and configuration? Does the issue you report still appear there?

- [X] I agree

**Comment by Tishj** [comment]
I don't think that's caused by the BLOB column, the current implementation of `map` will call the UDF first with an empty dataframe during bind time.
We use the return value of this to figure out the schema of the result of the function.

After altering the udf to print the dtypes of the dataframe, I think I know what's going on:
```py
def nop(df):
	print(df.dtypes)
	return df

duckdb.values([b'1234']).map(nop).fetchall()
```
```
col0    object
dtype: object
col0    object
dtype: object
col0    object
dtype: object
```

An empty dataframe of the type `object` probably gets NULL as the dtype instead

**Comment by Tishj** [comment]
Actually, since we know the original types, we can check if the original type was a type that maps to 'object', and also check if the analyzed type is NULL - and then override it to the original type

That might work

**Comment by hinxx** [comment]
Thanks guys! The PR solves the issue for me!

**Comment by hinxx** [comment]
I might have spoken too soon..

After testing my original use case (I posted the minimal example that failed at the start of this issue) of converting the data type in the `map()` function I get this problem:

```
>>> duckdb.values([msgpack.packb(10000)])
┌──────────────┐
│     col0     │
│     blob     │
├──────────────┤
│ \xCD\x27\x10 │
└──────────────┘

>>> def db_conv(v):
...  def g(vv):
...   return msgpack.unpackb(vv)
...  v['col0'] = v['col0'].apply(g)
...  return v

>>> duckdb.values([msgpack.packb(10000)]).map(db_conv)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
duckdb.InvalidInputException: Invalid Input Error: UDF column type mismatch, expected [BLOB], got [BIGINT]

```


For example, same happens if I want to map an `integer` to `float`  (not what I'm looking for):

```
>>> def db_conv2(v):
...  def g(vv):
...   return float(vv)
...  v['col0'] = v['col0'].apply(g)
...  return v

>>> duckdb.values([10000])
┌───────┐
│ col0  │
│ int16 │
├───────┤
│ 10000 │
└───────┘

>>> duckdb.values([10000]).map(db_conv2)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
duckdb.InvalidInputException: Invalid Input Error: UDF column type mismatch, expected [SMALLINT], got [DOUBLE]

```

but, then this conversion works fine (not what I'm looking for):

```

>>> def db_conv3(v):
...  v['col0'] = v['col0'].astype(float)
...  return v
... 
>>> duckdb.values([10000]).map(db_conv3)
┌─────────┐
│  col0   │
│ double  │
├─────────┤
│ 10000.0 │
└─────────┘


```

I guess it has to do with the way that the output type is inferred, but I'm not familiar with the internals. Would it be possible for `map()` to specify the output format explicitly? In the original use case with the `msgpack.unpackb()` the resulting data type is known only after the blob is unpacked.
