### ISSUE TITLE
:coffee:Java JDBC API > java.sql.SQLFeatureNotSupportedException: getTypeInfo

### ISSUE THREAD

**Issue by adriens** [duckdb/duckdb#6759]
### What happens?

When I ry to get metadata from `jdbc` I get the following exception : 

```
java.sql.SQLFeatureNotSupportedException: getTypeInfo
org.duckdb.DuckDBDatabaseMetaData.getTypeInfo(DuckDBDatabaseMetaData.java:953)
```

Details below:

```
Caused by: java.sql.SQLFeatureNotSupportedException: getTypeInfo
	at org.duckdb.DuckDBDatabaseMetaData.getTypeInfo(DuckDBDatabaseMetaData.java:953)
	at org.apache.commons.dbcp2.DelegatingDatabaseMetaData.getTypeInfo(DelegatingDatabaseMetaData.java:933)
	at org.apache.commons.dbcp2.DelegatingDatabaseMetaData.getTypeInfo(DelegatingDatabaseMetaData.java:933)
```

### To Reproduce

1. Connect to a `duckdb` database through [Java JDBC API](https://duckdb.org/docs/api/java.html)
2. Try to get metadata from the jdbc driver

### OS:

All

### DuckDB Version:

All

### DuckDB Client:

Java

### Full Name:

Adrien SALES

### Affiliation:

NA

### Have you tried this on the latest `master` branch?

- [X] I agree

### Have you tried the steps to reproduce? Do they include all relevant data and configuration? Does the issue you report still appear there?

- [X] I agree

**Comment by sualeh** [comment]
I suggest that the DuckDB JDBC driver return an empty result set rather than throwing `java.sql.SQLFeatureNotSupportedException` for this important call if the data types are not known ahead of time.

**Comment by adriens** [comment]
@sualeh : [:bird: Tweet](https://twitter.com/rastadidi/status/1637232313846349824)

![image](https://user-images.githubusercontent.com/5235127/226145100-dc45f9f7-d197-4640-83a8-7796d601121d.png)

**Comment by adriens** [comment]
:bulb: 
- https://github.com/schemacrawler/SchemaCrawler/pull/1016#issuecomment-1475031206

**Comment by adriens** [comment]
Hi guys, any news abot this feature request ? That has a huge impact on java based intrsopection.

**Comment by Mause** [comment]
@adriens it's not something I've been able to get around to unfortunately, but pull requests are always welcome if this is blocking you

**Comment by adriens** [comment]
In fact, it's bloching anyon who would like to automate database documentation from within third party tools, like schemacrawler.... for example [Use ChatGPT to Explore Your Database Schema - Part 2 ](https://dev.to/sualeh/use-chatgpt-to-explore-your-database-schema-part-2-2429)

**Comment by alexismanin** [comment]
Somewhat related: not only `getTypeInfo` is currently not implemented. Other useful metadata endpoints, like index and foreign key metadata are also unavailable : https://github.com/duckdb/duckdb/blob/cb1c49321d727ff8e727ca66071cc2d5347b8fc6/tools/jdbc/src/main/java/org/duckdb/DuckDBDatabaseMetaData.java#L946.

Is there an official roadmap for JDBC driver evolution development ? Or is it an extension that is more bound to evolve through community contribution ?

**Comment by adriens** [comment]
> Is there an official roadmap for JDBC driver evolution development ? Or is it an extension that is more bound to evolve through community contribution ?

Yup, that would be very ueseful and would open a wide area of optimization and automations around duck :pray:

**Comment by adriens** [comment]
Please don't close the issue :pray:

**Comment by adriens** [comment]
Hi guys, any news for this issue ? 🙏

**Comment by adriens** [comment]
Please dont close it

**Comment by sualeh** [comment]
This should be resolved.

**Comment by adriens** [comment]
Please keep it opened

**Comment by Algebrazebra** [comment]
For past commenters and future readers: 
I believe this issue can be closed, because the `getTypeInfo` was implemented in this [commit](https://github.com/duckdb/duckdb-java/commit/90af5a8b0d265583f3919de80b178b60222be63c).

This commit is also on the release branch for version 1.5, so as far as I can tell it should be included already in the latest version of the driver (haven't tested it though).
