### ISSUE TITLE
INSERT statement returns unexpected exception

### ISSUE THREAD

**Issue by SuriZhang** [duckdb/duckdb#6876]
### What happens?

![image](https://user-images.githubusercontent.com/15933857/227928370-0ce058a1-a91e-4cb5-8df6-62066f1b36f4.png)
Insert into TEXT typed column returns unexpected exception. 

I found this issue from a test for the JDBC driver. The exception returned is:
```
*java.sql.SQLException: java.sql.SQLException: Binder Error: Referenced column "''" not found in FROM clause!
	at org.duckdb.DuckDBPreparedStatement.prepare(DuckDBPreparedStatement.java:116)
	at org.duckdb.DuckDBPreparedStatement.executeUpdate(DuckDBPreparedStatement.java:194)
	```

### To Reproduce

Execute the following statement:

CREATE TABLE table_0 (column_0 TEXT);
INSERT INTO table_0 (column_0) VALUES ("''");

### OS:

Ubuntu amd64

### DuckDB Version:

JDBC 0.7.0

### DuckDB Client:

JDBC

### Full Name:

Suri Zhang

### Affiliation:

National University of Singapore, School of Computing

### Have you tried this on the latest `master` branch?

- [X] I agree

### Have you tried the steps to reproduce? Do they include all relevant data and configuration? Does the issue you report still appear there?

- [X] I agree

**Comment by Tishj** [comment]
`"` is used for column references, so it's looking for the column named `''`

**Comment by SuriZhang** [comment]
> `"` is used for column references, so it's looking for the column named `''` What were you trying to insert? An empty string would just be `VALUES('')`

I see. Thanks
