### ISSUE TITLE
JVM SIGSEGV crash while getting connection to duckdb server

### ISSUE THREAD

**Issue by shreyasGit** [duckdb/duckdb#8021]
### What happens?

I am using java JDBC API to connect to DUCKDB - am using dependency version -i intend to use HTTPFS extention to read and write parquet files to s3.
 <dependency>
    <groupId>org.duckdb</groupId>
    <artifactId>duckdb_jdbc</artifactId>
    <version>0.8.1</version>
</dependency>
i am running the following code as part of a container image based on alpine Zulu 13 JRE
when i execute the following code - I get an SIGSEGV crash

` Class.forName("org.duckdb.DuckDBDriver");
	   logger.info("Driver loaded");
	   Connection conn = null;
	   try {
	    conn = DriverManager.getConnection("jdbc:duckdb:");
	   }
	   catch (SQLException e ) {
		logger.error(e.getMessage() + e.getStackTrace());
	}`

#
# A fatal error has been detected by the Java Runtime Environment:
#
#  SIGSEGV (0xb) at pc=0x000000000063bdc6, pid=1, tid=134
#
# JRE version: OpenJDK Runtime Environment Zulu13.54+17-CA (13.0.14+5) (build 13.0.14+5-MTS)
# Java VM: OpenJDK 64-Bit Server VM Zulu13.54+17-CA (13.0.14+5-MTS, mixed mode, sharing, tiered, compressed oops, serial gc, linux-amd64)
# Problematic frame:
# C  0x000000000063bdc6
#
# Core dump will be written. Default location: /install/citng/service/core.1
#
# An error report file with more information is saved as:
# /install/citng/service/hs_err_pid1.log
#
# If you would like to submit a bug report, please visit:
#   http://www.azul.com/support/
# The crash happened outside the Java Virtual Machine in native code.
# See problematic frame for where to report the bug.

this code works fine on my windows machine running java.
earlier i had glibc issues on alpine - java.lang.UnsatisfiedLinkError: /tmp/libduckdb_java4480084372361105472.so: Error loading shared library ld-linux-x86-64.so.2:
so i installed RUN apk update && apk add --no-cache libc6-compat and error for UnsatisfiedLink error was eliminated.
Now i get an jvm crash, i observe it does not write crash report as well.

### To Reproduce

1. use java client library of version 0.8.1
2. have a simple code to get connection from db -
3. conn = DriverManager.getConnection("jdbc:duckdb:");
4. run this in a Linux alpine environment
5. observe the error
Thanks

### OS:

Alpine linux - X86_64

### DuckDB Version:

0.8.1

### DuckDB Client:

Java

### Full Name:

Shreyas Deshpande

### Affiliation:

SAS

### Have you tried this on the latest `master` branch?

- [X] I agree

### Have you tried the steps to reproduce? Do they include all relevant data and configuration? Does the issue you report still appear there?

- [X] I agree

**Comment by hannes** [comment]
Can you provide a SAS license so we can test this?

**Comment by shreyasGit** [comment]
this is nothing to do with sas, i am running it as a web application in a container

**Comment by shreyasGit** [comment]
# Gradle build will provide the ARG values
ARG REPO

FROM ${REPO}mkt-docker/alpine-zulu13-jre:latest as builder

# label this as an intermediate image that should be cleaned up (since Docker
# isn't taking care of cleaning these up)
#
# https://stackoverflow.com/questions/50126741/how-to-remove-intermediate-images-from-a-build-after-the-build
#
ARG COMMIT
ARG PROJECT
LABEL stage="intermediate-${PROJECT}-${COMMIT}"



COPY service/*.jar /install/citng/service/service.jar
WORKDIR /install/citng/service
RUN java -Djarmode=layertools -jar /install/citng/service/service.jar extract

ARG REPO
FROM ${REPO}mkt-docker/alpine-zulu13-jre:latest

RUN apk update && apk add --no-cache libc6-compat && /sbin/ldconfig /etc/ld.so.conf.d -v && \
ln -s /lib/libc.musl-x86_64.so.1 /lib/ld-linux-x86-64.so.2 


USER sassrv

WORKDIR /install/citng/service
# each of the COPY commands creates an image layer - order from least often changed to most often
# tied to Spring Boot version
COPY --from=builder /install/citng/service/spring-boot-loader/ ./
# Third Party Jars
COPY --from=builder /install/citng/service/dependencies/ ./
# Our unexploded JAR
COPY --from=builder /install/citng/service/snapshot-dependencies/ ./
# Our exploded application code
COPY --from=builder /install/citng/service/application/ ./

EXPOSE 8080

HEALTHCHECK CMD curl --fail http://localhost:8080/auditService/health || exit 1

ARG VERSION
ARG COMMIT
ARG PROJECT

LABEL name=${PROJECT}
LABEL description="CI360 audit Microservice"
LABEL vendor="SAS Institute Inc."
LABEL version=${VERSION}
LABEL commit=${COMMIT}

CMD ["java", \
"-XshowSettings:vm", \
"-Dlogging.config=classpath:logback-spring.xml", \
"-agentlib:jdwp=transport=dt_socket,server=y,suspend=n,address=*:8003", \
"org.springframework.boot.loader.JarLauncher"]

**Comment by shreyasGit** [comment]
`# Gradle build will provide the ARG values
ARG REPO

FROM ${REPO}mkt-docker/alpine-zulu13-jre:latest as builder

# label this as an intermediate image that should be cleaned up (since Docker
# isn't taking care of cleaning these up)
#
# https://stackoverflow.com/questions/50126741/how-to-remove-intermediate-images-from-a-build-after-the-build
#
ARG COMMIT
ARG PROJECT
LABEL stage="intermediate-${PROJECT}-${COMMIT}"



COPY service/*.jar /install/citng/service/service.jar
WORKDIR /install/citng/service
RUN java -Djarmode=layertools -jar /install/citng/service/service.jar extract

ARG REPO
FROM ${REPO}mkt-docker/alpine-zulu13-jre:latest

RUN apk update && apk add --no-cache libc6-compat && /sbin/ldconfig /etc/ld.so.conf.d -v && \
ln -s /lib/libc.musl-x86_64.so.1 /lib/ld-linux-x86-64.so.2 


USER sassrv

WORKDIR /install/citng/service
# each of the COPY commands creates an image layer - order from least often changed to most often
# tied to Spring Boot version
COPY --from=builder /install/citng/service/spring-boot-loader/ ./
# Third Party Jars
COPY --from=builder /install/citng/service/dependencies/ ./
# Our unexploded JAR
COPY --from=builder /install/citng/service/snapshot-dependencies/ ./
# Our exploded application code
COPY --from=builder /install/citng/service/application/ ./

EXPOSE 8080

HEALTHCHECK CMD curl --fail http://localhost:8080/auditService/health || exit 1

ARG VERSION
ARG COMMIT
ARG PROJECT

LABEL name=${PROJECT}
LABEL description="CI360 audit Microservice"
LABEL vendor="SAS Institute Inc."
LABEL version=${VERSION}
LABEL commit=${COMMIT}

CMD ["java", \
"-XshowSettings:vm", \
"-Dlogging.config=classpath:logback-spring.xml", \
"-agentlib:jdwp=transport=dt_socket,server=y,suspend=n,address=*:8003", \
"org.springframework.boot.loader.JarLauncher"]
`

**Comment by shreyasGit** [comment]
these will have custom images we created internally basically you can use this - image from which is inheritedc- https://hub.docker.com/r/azul/zulu-openjdk-alpine

**Comment by Mause** [comment]
Please wrap your code in code blocks so it's formatted nicely

**Comment by shreyasGit** [comment]
OK. code is plainly this
 `Class.forName("org.duckdb.DuckDBDriver");
	   logger.info("Driver loaded");
	   Connection conn = null;
	   try {
	    conn = DriverManager.getConnection("jdbc:duckdb:");
	   }
	   catch (SQLException e ) {
		logger.error(e.getMessage() + e.getStackTrace());
	}`

**Comment by Mause** [comment]
I pared your example down to 
```dockerfile
FROM azul/zulu-openjdk-alpine:13-jre

RUN apk update && apk add --no-cache libc6-compat && /sbin/ldconfig /etc/ld.so.conf.d -v && \
ln -s /lib/libc.musl-x86_64.so.1 /lib/ld-linux-x86-64.so.2 

RUN apk add openssl-dev libstdc++ libssl3 

COPY duckdb_jdbc.jar duckdb.jar

CMD ["java", "-cp", "duckdb.jar", "org.duckdb.test.TestDuckDBJDBC"]
```
which gave me
```
# A fatal error has been detected by the Java Runtime Environment:
#
#  SIGSEGV (0xb) at pc=0x00007f3c9bfc9da0, pid=1, tid=7
#
# JRE version: OpenJDK Runtime Environment Zulu13.54+17-CA (13.0.14+5) (build 13.0.14+5-MTS)
# Java VM: OpenJDK 64-Bit Server VM Zulu13.54+17-CA (13.0.14+5-MTS, mixed mode, sharing, tiered, compressed oops, g1 gc, linux-amd64)
# Problematic frame:
# C  [libduckdb_java1855223738027877407.so+0x4951da0]  std::ios_base::Init::Init()+0x20
```
so, pretty certainly a libc6-compat issue

**Comment by Mause** [comment]
Given that it's part of libstdc++ that's failing to startup, I'm not sure if this is something we can fix without creating a standalone musl build

**Comment by shreyasGit** [comment]
just to update i changed image from alpine to amazon linux to gauge if its alpine and libc6 issue , but still got same kind of error ,  
`#
# A fatal error has been detected by the Java Runtime Environment:
#
#  SIGSEGV (0xb) at pc=0x00007faba504223b, pid=1, tid=133
#
# JRE version: OpenJDK Runtime Environment Corretto-17.0.7.7.1 (17.0.7+7) (build 17.0.7+7-LTS)
# Java VM: OpenJDK 64-Bit Server VM Corretto-17.0.7.7.1 (17.0.7+7-LTS, mixed mode, sharing, tiered, compressed oops, compressed class ptrs, serial gc, linux-amd64)
# Problematic frame:
# C  [libc.so.6+0x3523b]  abort+0x23b
#
# Core dump will be written. Default location: /install/citng/service/core.1
#
# An error report file with more information is saved as:
# /install/citng/service/hs_err_pid1.log
#
# If you would like to submit a bug report, please visit:
#   https://github.com/corretto/corretto-17/issues/
# The crash happened outside the Java Virtual Machine in native code.
# See problematic frame for`

**Comment by Mytherin** [comment]
Any chance this is fixed by #7991 no longer statically linking the C++ library into the JDBC client? Could you try this with the latest nightly build?

**Comment by shreyasGit** [comment]
Thanks what will have to do to try that ? move to a newer version

**Comment by Mytherin** [comment]
See [here](https://duckdb.org/docs/installation/index)

```
Java master builds are available in the sonatype snapshots repository, which can be accessed with the following:
<dependency>
	<groupId>org.duckdb</groupId>
	<artifactId>duckdb_jdbc</artifactId>
	<version>0.9.0-SNAPSHOT</version>
</dependency>

...

<repositories>
	<repository>
		<id>oss-sonatype</id>
		<name>oss-sonatype</name>
		<url>https://oss.sonatype.org/content/repositories/snapshots/</url>
		<snapshots>
			<enabled>true</enabled>
		</snapshots>
	</repository>
</repositories>
		
```

**Comment by Mytherin** [comment]
Alternatively you can access the nightly builds [here](https://github.com/duckdb/duckdb/actions/workflows/Java.yml?query=event%3Arepository_dispatch)

**Comment by shreyasGit** [comment]
had a follow up question from below code I was able to query files on s3 using java client, create a table in duckdb using ctas, but when I copy it back to s3, jvm crashes, maybe it could be some permission issue while writing to s3. my question is in such cases why does jvm crashes? I am evaluating this library to be used in production, so crashing jvm will cause issues. is there a way to avoid this or some pointers. in this case am using amazon Linux image.
`ResultSet success =  stmt.executeQuery("SELECT * from parquet_scan('s3://ci-360-kafka-connect-audit-sinsde1-us-east-1/topics/sinsde-mkt-infra-audit/eiffel/year=2023/month=06/d*/h*/*.parquet');");
	           while (success.next()) {
	               logger.info(success.getString(1));
	               logger.info(success.getString(3));
	           }
	           logger.info("select from s3 executed");

	           boolean success1 =  stmt.execute("CREATE TABLE test AS SELECT * from parquet_scan('s3://ci-360-kafka-connect-audit-sinsde1-us-east-1/topics/sinsde-mkt-infra-audit/eiffel/year=2023/month=06/d*/h*/*.parquet');");
	           logger.info("CTAS execured");
	           success = stmt.executeQuery("show tables");
	           while (success.next()) {
	               logger.info(success.getString(1));

	           }
	           ****boolean success2 = 	stmt.execute("COPY test TO 's3://ci-360-data-dev-us-east-1/consolidated.parquet';");****`

i am able to verify using logs that test table is created.
the jvm crash error is
`# A fatal error has been detected by the Java Runtime Environment:
#
#  SIGSEGV (0xb) at pc=0x00007f3345aa123b, pid=1, tid=132
#
# JRE version: OpenJDK Runtime Environment Corretto-17.0.7.7.1 (17.0.7+7) (build 17.0.7+7-LTS)
# Java VM: OpenJDK 64-Bit Server VM Corretto-17.0.7.7.1 (17.0.7+7-LTS, mixed mode, sharing, tiered, compressed oops, compressed class ptrs, serial gc, linux-amd64)
# Problematic frame:
# C  [libc.so.6+0x3523b]  abort+0x23b
#
# Core dump will be written. Default location: /install/citng/service/core.1
#
# An error report file with more information is saved as:
# /install/citng/service/hs_err_pid1.log
#
# If you would like to submit a bug report, please visit:
#   https://github.com/corretto/corretto-17/issues/
# The crash happened outside the Java Virtual Machine in native code.
# See problematic frame for where to report the bug.
#`

**Comment by shreyasGit** [comment]
Had a follow up question from below code I was able to query files on s3 using java client, create a table in duckdb using ctas, but when I copy it back to s3, jvm crashes, maybe it could be some permission issue while writing to s3. my question is in such cases why does jvm crashes? I am evaluating this library to be used in production, so crashing jvm will cause issues. is there a way to avoid this or some pointers. in this case am using amazon Linux image.
`ResultSet success =  stmt.executeQuery("SELECT * from parquet_scan('s3://ci-360-kafka-connect-audit-sinsde1-us-east-1/topics/sinsde-mkt-infra-audit/eiffel/year=2023/month=06/d*/h*/*.parquet');");
	           while (success.next()) {
	               logger.info(success.getString(1));
	               logger.info(success.getString(3));
	           }
	           logger.info("select from s3 executed");

	           boolean success1 =  stmt.execute("CREATE TABLE test AS SELECT * from parquet_scan('s3://ci-360-kafka-connect-audit-sinsde1-us-east-1/topics/sinsde-mkt-infra-audit/eiffel/year=2023/month=06/d*/h*/*.parquet');");
	           logger.info("CTAS execured");
	           success = stmt.executeQuery("show tables");
	           while (success.next()) {
	               logger.info(success.getString(1));

	           }
	           ****boolean success2 = 	stmt.execute("COPY test TO 's3://ci-360-data-dev-us-east-1/consolidated.parquet';");`

**Comment by Mause** [comment]
@shreyasGit which amazon linux are you using? There are quite a few. An exact docker image tag would be most helpful

**Comment by jethro-huddle-tech** [comment]
We're having the same issue. In our case with the following OS:

```
$ cat /etc/os-release 
VERSION_CODENAME=bionic
ID=ubuntu
VERSION_ID="18.04"
HOME_URL="https://github.com/paketo-buildpacks/bionic-base-stack"
SUPPORT_URL="https://github.com/paketo-buildpacks/bionic-base-stack/blob/main/README.md"
PRIVACY_POLICY_URL="https://www.ubuntu.com/legal/terms-and-policies/privacy-policy"
UBUNTU_CODENAME=bionic
NAME="Ubuntu"
VERSION="18.04.6 LTS (Bionic Beaver)"
ID_LIKE=debian
PRETTY_NAME="Paketo Buildpacks Base Bionic"
BUG_REPORT_URL="https://github.com/paketo-buildpacks/bionic-base-stack/issues/new"
```

**Comment by jethro-huddle-tech** [comment]
@Mytherin @Mause 

I have tried with the latest nightly build of duckdb. With this release I am getting a different error:

```Caused by: java.sql.SQLException: IO Error: Extension "/home/cnb/.duckdb/extensions//linux_amd64_gcc4/httpfs.duckdb_extension" could not be loaded: /home/cnb/.duckdb/extensions//linux_amd64_gcc4/httpfs.duckdb_extension: undefined symbol: _ZTIN6duckdb9ExceptionE```


I also had to enable a setting called `allow_unsigned_extensions` too.

**Comment by Mause** [comment]
You'll get that error if you try to compile from scratch and miss the static build setting.

You should instead follow the instructions on the website to download the snapshot build

Java master builds are available in the sonatype snapshots repository, which can be accessed with the following:

```xml
<dependency>
	<groupId>org.duckdb</groupId>
	<artifactId>duckdb_jdbc</artifactId>
	<version>0.9.0-SNAPSHOT</version>
</dependency>

...

<repositories>
	<repository>
		<id>oss-sonatype</id>
		<name>oss-sonatype</name>
		<url>https://oss.sonatype.org/content/repositories/snapshots/</url>
		<snapshots>
			<enabled>true</enabled>
		</snapshots>
	</repository>
</repositories>
```

**Comment by jethro-huddle-tech** [comment]
This ticket was automatically marked as stale, but it is still an issue.

**Comment by szarnyasg** [comment]
@jethro-huddle-tech Can you please drop me a line at gabor@duckdblabs.com?

**Comment by goldmedal** [comment]
Hi @shreyasGit , I had same experiences. I'm not sure the reason but I guess the crash problem is caused by `zulu` openjdk.
I think `zulu` won't handle the exception thrown by DuckDB. I did some test for it.
```java
    public static void main(String[] args)
    {
        try {
            Connection connection = DriverManager.getConnection("jdbc:duckdb:");
            Statement statement = connection.createStatement();
            statement.execute("set memory_limit='1B'");
            statement.execute("select * from parquet_scan('/path-to-parquet/tiny-customer.parquet') limit 100");
            while   (statement.getResultSet().next()) {
                System.out.println(statement.getResultSet().getString(1));
            }
        }
        catch (Exception e) {
            e.printStackTrace();
        }
    }
```
If used other JDK (in this case, it's adopt-openjdk-11.0.9), it will throw an exception wrapped as a `SQLException`.
```
java.sql.SQLException: java.sql.SQLException: Out of Memory Error: failed to allocate data of size 8 bytes (0 bytes/1 byte used)
	at org.duckdb.DuckDBPreparedStatement.prepare(DuckDBPreparedStatement.java:112)
	at org.duckdb.DuckDBPreparedStatement.execute(DuckDBPreparedStatement.java:183)
	at org.example.JdbcTest.main(JdbcTest.java:18)
Caused by: java.sql.SQLException: Out of Memory Error: failed to allocate data of size 8 bytes (0 bytes/1 byte used)
	at org.duckdb.DuckDBNative.duckdb_jdbc_prepare(Native Method)
	at org.duckdb.DuckDBPreparedStatement.prepare(DuckDBPreparedStatement.java:106)
	... 2 more
```
However, for `zulu`, it will crash jvm and core dumped.
cc. @Mause
