### ISSUE TITLE
[JDBC] DBeaver fails to load data from arrays

### ISSUE THREAD

**Issue by Mause** [duckdb/duckdb#8235]
### What happens?

Since we've added first class support for Arrays in the JDBC driver, complex array types don't seem to be retrievable.

This might just be related to the fact that first class support for structs, maps, etc, haven't been added.

It looks like something is going wrong around here: https://github.com/dbeaver/dbeaver/blob/devel/plugins/org.jkiss.dbeaver.model.jdbc/src/org/jkiss/dbeaver/model/impl/jdbc/data/JDBCCollection.java#L275

### To Reproduce

```sql
select [1];
```
works fine, but
```sql
SELECT [{'x': 1, 'y': 2, 'z': 3},{'x': 4, 'y': 5, 'z': 6}]
```
fails, with
```text
Current error: java.lang.UnsupportedOperationException: Unimplemented method 'getResultSet'
at org.duckdb.DuckDBArray.getResultSet(DuckDBArray.java:63)
at org.jkiss.dbeaver.model.impl.jdbc.data.JDBCCollection.makeCollectionFromResultSet(JDBCCollection.java:388)
at org.jkiss.dbeaver.model.impl.jdbc.data.JDBCCollection.makeCollectionFromArray(JDBCCollection.java:275)
at org.jkiss.dbeaver.model.impl.jdbc.data.handlers.JDBCArrayValueHandler.getValueFromObject(JDBCArrayValueHandler.java:72)
at org.jkiss.dbeaver.model.impl.jdbc.data.handlers.JDBCArrayValueHandler.getValueFromObject(JDBCArrayValueHandler.java:1)
at org.jkiss.dbeaver.model.impl.jdbc.data.handlers.JDBCComplexValueHandler.fetchColumnValue(JDBCComplexValueHandler.java:50)
at org.jkiss.dbeaver.model.impl.jdbc.data.handlers.JDBCArrayValueHandler.fetchColumnValue(JDBCArrayValueHandler.java:60)
at org.jkiss.dbeaver.model.impl.jdbc.data.handlers.JDBCAbstractValueHandler.fetchValueObject(JDBCAbstractValueHandler.java:49)
at org.jkiss.dbeaver.ui.controls.resultset.ResultSetDataReceiver.fetchRow(ResultSetDataReceiver.java:126)
at org.jkiss.dbeaver.ui.editors.sql.execute.SQLQueryJob.fetchQueryData(SQLQueryJob.java:828)
at org.jkiss.dbeaver.ui.editors.sql.execute.SQLQueryJob.executeStatement(SQLQueryJob.java:632)
at org.jkiss.dbeaver.ui.editors.sql.execute.SQLQueryJob.lambda$1(SQLQueryJob.java:491)
at org.jkiss.dbeaver.model.exec.DBExecUtils.tryExecuteRecover(DBExecUtils.java:189)
at org.jkiss.dbeaver.ui.editors.sql.execute.SQLQueryJob.executeSingleQuery(SQLQueryJob.java:498)
at org.jkiss.dbeaver.ui.editors.sql.execute.SQLQueryJob.extractData(SQLQueryJob.java:924)
at org.jkiss.dbeaver.ui.editors.sql.SQLEditor$QueryResultsContainer.readData(SQLEditor.java:3873)
at org.jkiss.dbeaver.ui.controls.resultset.ResultSetJobDataRead.lambda$0(ResultSetJobDataRead.java:123)
at org.jkiss.dbeaver.model.exec.DBExecUtils.tryExecuteRecover(DBExecUtils.java:189)
at org.jkiss.dbeaver.ui.controls.resultset.ResultSetJobDataRead.run(ResultSetJobDataRead.java:121)
at org.jkiss.dbeaver.ui.controls.resultset.ResultSetViewer$ResultSetDataPumpJob.run(ResultSetViewer.java:5096)
at org.jkiss.dbeaver.model.runtime.AbstractJob.run(AbstractJob.java:105)
at org.eclipse.core.internal.jobs.Worker.run(Worker.java:63)
```

### OS:

Windows

### DuckDB Version:

v0.8.1

### DuckDB Client:

JDBC

### Full Name:

Elliana May

### Affiliation:

DuckDB Labs

### Have you tried this on the latest `master` branch?

- [X] I agree

### Have you tried the steps to reproduce? Do they include all relevant data and configuration? Does the issue you report still appear there?

- [X] I agree

**Comment by Mause** [comment]
Looks like DBeaver fixed this upstream in https://github.com/dbeaver/dbeaver/pull/20455

I'll leave this open for implementing `getTypeMap` though

**Comment by bladko-tom** [comment]
@Mause 

This is related ?

Latests DuckDB (8.2.dev1764) + DBeaver 23.1.2. Works fine in DuckDB CLI thou. 

Code
` SELECT TIMESTAMP '2022-10-10 10:10:10'	`

Results

`java.lang.NullPointerException: Cannot load from object array because "this.varlen_data" is null`

**Comment by Mause** [comment]
> @Mause
> 
> This is related ?
> 
> Latests DuckDB (8.2.dev1764) + DBeaver 23.1.2. Works fine in DuckDB CLI thou.
> 
> Code ` SELECT TIMESTAMP '2022-10-10 10:10:10' `
> 
> Results
> 
> `java.lang.NullPointerException: Cannot load from object array because "this.varlen_data" is null`

No, that's a different issue. I'm not able to replicate it either, can you please open a new issue with a bit more information?
