### ISSUE TITLE
[JDBC] Cannot process TIMESTAMP type in DBeaver

### ISSUE THREAD

**Issue by bladko-tom** [duckdb/duckdb#8286]
### What happens?

DBeaver, latests version 23.1.2 + latests DuckDB JDBC build 18 July 2023 (duckdb_jdbc-0.9.0-SNAPSHOT.jar) + Windows 10, x64

```
java.lang.NullPointerException: Cannot load from object array because "this.varlen_data" is null
	at org.duckdb.DuckDBVector.getLazyString(DuckDBVector.java:211)
	at org.duckdb.DuckDBVector.getDate(DuckDBVector.java:248)
	at org.duckdb.DuckDBResultSet.getDate(DuckDBResultSet.java:358)
	at org.jkiss.dbeaver.model.impl.jdbc.exec.JDBCResultSetImpl.getDate(JDBCResultSetImpl.java:419)
	at org.jkiss.dbeaver.model.impl.jdbc.data.handlers.JDBCDateTimeValueHandler.fetchValueObject(JDBCDateTimeValueHandler.java:100)
	at org.jkiss.dbeaver.ui.controls.resultset.ResultSetDataReceiver.fetchRow(ResultSetDataReceiver.java:126)
	at org.jkiss.dbeaver.ui.editors.sql.execute.SQLQueryJob.fetchQueryData(SQLQueryJob.java:838)
	at org.jkiss.dbeaver.ui.editors.sql.execute.SQLQueryJob.executeStatement(SQLQueryJob.java:632)
	at org.jkiss.dbeaver.ui.editors.sql.execute.SQLQueryJob.lambda$1(SQLQueryJob.java:491)
	at org.jkiss.dbeaver.model.exec.DBExecUtils.tryExecuteRecover(DBExecUtils.java:189)
	at org.jkiss.dbeaver.ui.editors.sql.execute.SQLQueryJob.executeSingleQuery(SQLQueryJob.java:498)
	at org.jkiss.dbeaver.ui.editors.sql.execute.SQLQueryJob.extractData(SQLQueryJob.java:934)
	at org.jkiss.dbeaver.ui.editors.sql.SQLEditor$QueryResultsContainer.readData(SQLEditor.java:3921)
	at org.jkiss.dbeaver.ui.controls.resultset.ResultSetJobDataRead.lambda$0(ResultSetJobDataRead.java:123)
	at org.jkiss.dbeaver.model.exec.DBExecUtils.tryExecuteRecover(DBExecUtils.java:189)
	at org.jkiss.dbeaver.ui.controls.resultset.ResultSetJobDataRead.run(ResultSetJobDataRead.java:121)
	at org.jkiss.dbeaver.ui.controls.resultset.ResultSetViewer$ResultSetDataPumpJob.run(ResultSetViewer.java:5101)
	at org.jkiss.dbeaver.model.runtime.AbstractJob.run(AbstractJob.java:105)
	at org.eclipse.core.internal.jobs.Worker.run(Worker.java:63)

```

### To Reproduce

```sql
SELECT TIMESTAMP '2022-10-10 10:10:10' -- ERROR
SELECT DATE '2022-10-10 10:10:10' -- OK
SELECT TIME '2022-10-10 10:10:10' -- NULL
```

Python & CLI works fine without issues, looks like only JDBC is wrong.

### OS:

Windows 10, x64

### DuckDB Version:

JDBC 8.1.2.dev1791

### DuckDB Client:

JDBC

### Full Name:

Tom Bladko

### Affiliation:

Independent 

### Have you tried this on the latest `master` branch?

- [X] I agree

### Have you tried the steps to reproduce? Do they include all relevant data and configuration? Does the issue you report still appear there?

- [X] I agree

**Comment by HuyNguyenNeyuData** [comment]
I also got this problem

**Comment by Mause** [comment]
Unfortunately it looks like this issue is being caused by a change in the latest release of DBeaver, I'm currently investigating if we can work around it or if we'll have to submit a PR to DBeaver itself

**Comment by LonwoLonwo** [comment]
Hello @Mause 

We have on our board also very similar ticket: https://github.com/dbeaver/dbeaver/issues/20236

If you have any thoughts on how to fix it - please share.

**Comment by Mause** [comment]
@LonwoLonwo that does look quite similar yes, so probably has the same cause (https://github.com/dbeaver/dbeaver/pull/20455). Are you a DBeaver developer? If so, do you have any documentation on attaching a debugger to DBeaver so that I can confirm?

**Comment by LonwoLonwo** [comment]
Yes, I am.

We have a few docs:

https://github.com/dbeaver/dbeaver/wiki/Develop-in-Eclipse
https://github.com/dbeaver/dbeaver/wiki/Develop-in-IDEA
https://github.com/dbeaver/dbeaver-workspace-vscode

I also will take a look at the code.

**Comment by Mause** [comment]
My guess is that the mapping between DuckDB types and JDBC types in that PR is too coarse, so previously `getObject` was what was called by DBeaver, and DuckDB handled the mapping internally, whereas now DBeaver is handling the mapping between the JDBC types and the getter method on the `ResultSet` and choosing methods DuckDB doesn't expect (due to the coarse mapping)

**Comment by LonwoLonwo** [comment]
Ok, I can check it with old DBeaver and new DuckDB driver versions.

**Comment by LonwoLonwo** [comment]
Ok, I fixed the data reading for times, etc., from this ticket. (PR is not ready for now)

https://github.com/dbeaver/dbeaver/issues/20236

But what data type is better for geometry from our ticket? I tried to set geometry as binary or struct data type, but I had no luck.

```
java.lang.ClassCastException: class java.nio.DirectByteBuffer cannot be cast to class java.lang.String (java.nio.DirectByteBuffer and java.lang.String are in module java.base of loader 'bootstrap')
	at org.duckdb.DuckDBVector.getLazyString(DuckDBVector.java:211)
	at org.duckdb.DuckDBVector.getObject(DuckDBVector.java:110)
	at org.duckdb.DuckDBResultSet.getObject(DuckDBResultSet.java:161)
	at org.jkiss.dbeaver.model.impl.jdbc.exec.JDBCResultSetImpl.getObject(JDBCResultSetImpl.java:627)
	at org.jkiss.dbeaver.model.impl.jdbc.data.handlers.JDBCContentValueHandler.fetchColumnValue(JDBCContentValueHandler.java:75)
	at org.jkiss.dbeaver.model.impl.jdbc.data.handlers.JDBCContentValueHandler.fetchColumnValue(JDBCContentValueHandler.java:1)
	at org.jkiss.dbeaver.model.impl.jdbc.data.handlers.JDBCAbstractValueHandler.fetchValueObject(JDBCAbstractValueHandler.java:49)
	at org.jkiss.dbeaver.ui.controls.resultset.ResultSetDataReceiver.fetchRow(ResultSetDataReceiver.java:126)
	at org.jkiss.dbeaver.ui.editors.sql.execute.SQLQueryJob.fetchQueryData(SQLQueryJob.java:838)
```

**Comment by LonwoLonwo** [comment]
Hello @bladko-tom 

Please create a ticket on our board: https://github.com/dbeaver/dbeaver/issues

I will fix it there.

**Comment by LonwoLonwo** [comment]
https://github.com/dbeaver/dbeaver/pull/20722
Fixed for timestamps.
The fix will be available in the next DBeaver release on 07-08-2023.

**Comment by szarnyasg** [comment]
I re-ran the queries in DBeaver v23.1.4.202308061552 (release date: Aug 7). This works fine now!
