### ISSUE TITLE
DBeaver (JDBC) errors on Timestamp columns

### ISSUE THREAD

**Issue by Alex-Monahan** [duckdb/duckdb#8322]
### What happens?

If a timestamp column is returned to DBeaver, it fails to render that column and replaces it with an error message instead. Timestamptz works fine though, as does date. 

<img width="1133" alt="Screen Shot 2023-07-20 at 12 46 09 PM" src="https://github.com/duckdb/duckdb/assets/52226177/a7ddbd3a-491a-4304-bbee-8826f651b467">

Full error message is here:

```java
java.lang.NullPointerException: Cannot load from object array because "this.varlen_data" is null
	at org.duckdb.DuckDBVector.getLazyString(DuckDBVector.java:211)
	at org.duckdb.DuckDBVector.getDate(DuckDBVector.java:248)
	at org.duckdb.DuckDBResultSet.getDate(DuckDBResultSet.java:358)
	at org.jkiss.dbeaver.model.impl.jdbc.exec.JDBCResultSetImpl.getDate(JDBCResultSetImpl.java:419)
	at org.jkiss.dbeaver.model.impl.jdbc.data.handlers.JDBCDateTimeValueHandler.fetchValueObject(JDBCDateTimeValueHandler.java:100)
	at org.jkiss.dbeaver.ui.controls.resultset.ResultSetDataReceiver.fetchRow(ResultSetDataReceiver.java:126)
	at org.jkiss.dbeaver.ui.editors.sql.execute.SQLQueryJob.fetchQueryData(SQLQueryJob.java:838)
	at org.jkiss.dbeaver.ui.editors.sql.execute.SQLQueryJob.executeStatement(SQLQueryJob.java:632)
	at org.jkiss.dbeaver.ui.editors.sql.execute.SQLQueryJob.lambda$1(SQLQueryJob.java:491)
	at org.jkiss.dbeaver.model.exec.DBExecUtils.tryExecuteRecover(DBExecUtils.java:189)
	at org.jkiss.dbeaver.ui.editors.sql.execute.SQLQueryJob.executeSingleQuery(SQLQueryJob.java:498)
	at org.jkiss.dbeaver.ui.editors.sql.execute.SQLQueryJob.extractData(SQLQueryJob.java:934)
	at org.jkiss.dbeaver.ui.editors.sql.SQLEditor$QueryResultsContainer.readData(SQLEditor.java:3921)
	at org.jkiss.dbeaver.ui.controls.resultset.ResultSetJobDataRead.lambda$0(ResultSetJobDataRead.java:123)
	at org.jkiss.dbeaver.model.exec.DBExecUtils.tryExecuteRecover(DBExecUtils.java:189)
	at org.jkiss.dbeaver.ui.controls.resultset.ResultSetJobDataRead.run(ResultSetJobDataRead.java:121)
	at org.jkiss.dbeaver.ui.controls.resultset.ResultSetViewer$ResultSetDataPumpJob.run(ResultSetViewer.java:5101)
	at org.jkiss.dbeaver.model.runtime.AbstractJob.run(AbstractJob.java:105)
	at org.eclipse.core.internal.jobs.Worker.run(Worker.java:63)

```

### To Reproduce

```sql
select version(), current_timestamp::timestamp, current_timestamp, current_date;
```

### OS:

MacOS

### DuckDB Version:

0.8.1 and latest nightly build

### DuckDB Client:

JDBC

### Full Name:

Alex Monahan

### Affiliation:

MotherDuck and DuckDB Foundation

### Have you tried this on the latest `master` branch?

- [X] I agree

### Have you tried the steps to reproduce? Do they include all relevant data and configuration? Does the issue you report still appear there?

- [X] I agree

**Comment by bladko-tom** [comment]
same as #8286

**Comment by Alex-Monahan** [comment]
Yup, duplicate of #8286 , just on MacOS. Sorry for the noise!
