### ISSUE TITLE
[Dev] Stack-buffer-underflow when build with constructor elision disabled

### ISSUE THREAD

**Issue by Tishj** [duckdb/duckdb#8347]
### What happens?

To speed up codecov creation I'm attempting to switch the build type from debug to reldebug.
I ran into a lot of spurious failures, on things like `}` of functions.

Read online that these could possibly be fixed by building with `-fno-elide-constructors`.
When I did this, I ran into a crash

### To Reproduce

When building with constructor elision disabled
`CXXFLAGS="-fno-elide-constructors" make debug`

Running this test:
`build/debug/test/unittest "Test iterating over results"`
(test/api/test_results.cpp)

We run into this error:
```
[0/1] (0%): Test iterating over results                                         =================================================================
==82772==ERROR: AddressSanitizer: stack-buffer-underflow on address 0x00016d0f15f0 at pc 0x0001035e082c bp 0x00016d0f1590 sp 0x00016d0f1588
READ of size 8 at 0x00016d0f15f0 thread T0
    #0 0x1035e0828 in std::__1::shared_ptr<duckdb::DataChunk>::operator->() const shared_ptr.h:589
    #1 0x1035d71b8 in int duckdb::QueryResult::QueryResultRow::GetValue<int>(unsigned long long) const query_result.hpp:151
    #2 0x1033b3404 in ____C_A_T_C_H____T_E_S_T____52() test_results.cpp:52
    #3 0x103ccc720 in Catch::TestInvokerAsFunction::invoke() const catch.hpp:14400
    #4 0x103c9d110 in Catch::TestCase::invoke() const catch.hpp:14239
    #5 0x103c9cd3c in Catch::RunContext::invokeActiveTestCase() catch.hpp:13058
    #6 0x103c8ea1c in Catch::RunContext::runCurrentTest(std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> >&, std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> >&) catch.hpp:13031
    #7 0x103c8ac84 in Catch::RunContext::runTest(Catch::TestCase const&) catch.hpp:12792
    #8 0x103cafa88 in Catch::(anonymous namespace)::TestGroup::execute() catch.hpp:13420
    #9 0x103cabbcc in Catch::Session::runInternal() catch.hpp:13632
    #10 0x103caabe8 in Catch::Session::run() catch.hpp:13588
    #11 0x103d42558 in int Catch::Session::run<char>(int, char const* const*) catch.hpp:13269
    #12 0x103d41a20 in main unittest.cpp:81
    #13 0x1a4df3e4c  (<unknown module>)

Address 0x00016d0f15f0 is located in stack of thread T0 at offset 16 in frame
    #0 0x1035d6fe8 in int duckdb::QueryResult::QueryResultRow::GetValue<int>(unsigned long long) const query_result.hpp:150

  This frame has 1 object(s):
    [32, 96) 'ref.tmp' (line 151) <== Memory access at offset 16 underflows this variable
HINT: this may be a false positive if your program uses some custom stack unwind mechanism, swapcontext or vfork
      (longjmp and C++ exceptions *are* supported)
SUMMARY: AddressSanitizer: stack-buffer-underflow shared_ptr.h:589 in std::__1::shared_ptr<duckdb::DataChunk>::operator->() const
Shadow bytes around the buggy address:
  0x00702da3e260: 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00
  0x00702da3e270: 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00
  0x00702da3e280: 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00
  0x00702da3e290: 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00
  0x00702da3e2a0: 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00
=>0x00702da3e2b0: 00 00 00 00 00 00 00 00 00 00 00 00 f1 f1[f1]f1
  0x00702da3e2c0: 00 00 00 00 00 00 00 00 f3 f3 f3 f3 00 00 00 00
  0x00702da3e2d0: 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00
  0x00702da3e2e0: 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00
  0x00702da3e2f0: f1 f1 f1 f1 00 00 f2 f2 00 00 00 f2 f2 f2 f2 f2
  0x00702da3e300: f8 f8 f8 f8 f8 f8 f8 f8 f8 f2 f2 f2 f2 f2 f8 f8
Shadow byte legend (one shadow byte represents 8 application bytes):
  Addressable:           00
  Partially addressable: 01 02 03 04 05 06 07 
  Heap left redzone:       fa
  Freed heap region:       fd
  Stack left redzone:      f1
  Stack mid redzone:       f2
  Stack right redzone:     f3
  Stack after return:      f5
  Stack use after scope:   f8
  Global redzone:          f9
  Global init order:       f6
  Poisoned by user:        f7
  Container overflow:      fc
  Array cookie:            ac
  Intra object redzone:    bb
  ASan internal:           fe
  Left alloca redzone:     ca
  Right alloca redzone:    cb
==82772==ABORTING
```

### OS:

MacOS

### DuckDB Version:

master

### DuckDB Client:

-

### Full Name:

Thijs Bruineman

### Affiliation:

DuckDB Labs

### Have you tried this on the latest `master` branch?

- [X] I agree

### Have you tried the steps to reproduce? Do they include all relevant data and configuration? Does the issue you report still appear there?

- [X] I agree

**Comment by szarnyasg** [comment]
@Tishj is this issue still relevant?

**Comment by Tishj** [comment]
No I dont think so 👍
