### ISSUE TITLE
Python Client read_csv() ignores Delimiter, Quote and Escape Arguments

### ISSUE THREAD

**Issue by Finwood** [duckdb/duckdb#8421]
### What happens?

Given this CSV file [📎 647671e0.csv](https://github.com/duckdb/duckdb/files/12209226/647671e0.csv), the DuckDB Python client seems to ignore the `read_csv()` arguments for `delimiter`, `quotechar` and `escapechar`.

Even though the three above mentioned parameters are set explicitly,

```python
duckdb.read_csv(CSV_FILE, header=True, skiprows=1, delimiter=",", quotechar='"', escapechar="\\", dtype=COLUMNS)
```

the CSV import fails with the following error message, indicating delimiter, quote and escape character are auto-detected:

```shell
> python read_csv.py
Traceback (most recent call last):
  File "/home/lasse/src/parflux/read_csv.py", line 18, in <module>
    duckdb.read_csv(
duckdb.duckdb.InvalidInputException: Invalid Input Error: Error in file "647671e0.csv" on line 30: unterminated quotes. (  file=647671e0.csv
  delimiter='   ' (auto detected)
  quote='"' (auto detected)
  escape='' (auto detected)
  header=1
  sample_size=20480
  ignore_errors=0
  all_varchar=0)
```

The error is consistent with calling `read_csv_auto()` directly from SQL:

```sql
select * from read_csv_auto('647671e0.csv');
```

Importing the CSV file from SQL without auto-detect works as expected:

```sql
select * from read_csv(
    '647671e0.csv',
    header=True,
    skip=1,
    sep=',',
    quote='"',
    escape='\',
    columns={
        '_col0': 'VARCHAR',
        'result': 'VARCHAR',
        'table': 'BIGINT',
        '_time': 'TIMESTAMPTZ',
        '_measurement': 'VARCHAR',
        'bench_test': 'VARCHAR',
        'flight_id': 'VARCHAR',
        'flight_status': 'VARCHAR',
        'log_level': 'VARCHAR',
        'sys_uuid': 'VARCHAR',
        'message': 'VARCHAR'
    }
);
```

### To Reproduce

1. download [📎 647671e0.csv](https://github.com/duckdb/duckdb/files/12209226/647671e0.csv)
2. execute the below Python script

```python
import duckdb

CSV_FILE = "647671e0.csv"
COLUMNS = {
    "_col0": "VARCHAR",
    "result": "VARCHAR",
    "table": "BIGINT",
    "_time": "TIMESTAMPTZ",
    "_measurement": "VARCHAR",
    "bench_test": "VARCHAR",
    "flight_id": "VARCHAR",
    "flight_status": "VARCHAR",
    "log_level": "VARCHAR",
    "sys_uuid": "VARCHAR",
    "message": "VARCHAR",
}

duckdb.read_csv(
    CSV_FILE,
    header=True,
    skiprows=1,
    delimiter=",",
    quotechar='"',
    escapechar="\\",
    dtype=COLUMNS,
)
```

### OS:

Linux, Fedora Server 36, x86_64

### DuckDB Version:

0.8.1

### DuckDB Client:

Python

### Full Name:

Lasse Fröhner

### Affiliation:

starcopter

### Have you tried this on the latest `master` branch?

- [X] I agree

### Have you tried the steps to reproduce? Do they include all relevant data and configuration? Does the issue you report still appear there?

- [X] I agree

**Comment by Tishj** [comment]
Hmm interesting, this seems to break our Box renderer
```
┌──────────┬─────────┬───────┬───────────────────────────────┬─────────────────┬────────────┬────────────────────────────┬───────────────┬───────────┬──────────────────────────────────────┬───────────────────────────────────────────────────────────────────────────────────────────────┐
│ column00 │ result  │ table │             _time             │  _measurement   │ bench_test │         flight_id          │ flight_status │ log_level │               sys_uuid               │                                            message                                            │
│ varchar  │ varchar │ int64 │   timestamp with time zone    │     varchar     │  varchar   │          varchar           │    varchar    │  varchar  │               varchar                │                                            varchar                                            │
├──────────┼─────────┼───────┼───────────────────────────────┼─────────────────┼────────────┼────────────────────────────┼───────────────┼───────────┼──────────────────────────────────────┼───────────────────────────────────────────────────────────────────────────────────────────────┤
│ NULL     │ _result │     0 │ 2023-05-31 16:24:36.166678+02 │ logged_messages │ False      │ 01H1S35DSKVBFT2GRMX7S23BC9 │ PASS          │ INFO      │ 0002000000003636353934385119003b0032 │ [commander] Takeoff detected                                                                        │
│ NULL     │ _result │     0 │ 2023-05-31 16:25:04.12191+02  │ logged_messages │ False      │ 01H1S35DSKVBFT2GRMX7S23BC9 │ PASS          │ INFO      │ 0002000000003636353934385119003b0032 │ [commander] Landing detected                                                                        │
│ NULL     │ _result │     0 │ 2023-05-31 16:25:05.127837+02 │ logged_messages │ False      │ 01H1S35DSKVBFT2GRMX7S23BC9 │ PASS          │ INFO      │ 0002000000003636353934385119003b0032 │ [commander] Disarmed by landing                                                                  │
│ NULL     │ _result │     1 │ 2023-05-31 16:25:51.814473+02 │ logged_messages │ False      │ 01H1S37SZ4VRTH2HFWQ2PE3JN5 │ WARNING       │ INFO      │ 0002000000003636353934385119003b0032 │ [commander] Takeoff detected                                                                        │
│ NULL     │ _result │     1 │ 2023-05-31 16:26:24.849541+02 │ logged_messages │ False      │ 01H1S37SZ4VRTH2HFWQ2PE3JN5 │ WARNING       │ INFO      │ 0002000000003636353934385119003b0032 │ [commander] Landing detected                                                                        │
│ NULL     │ _result │     1 │ 2023-05-31 16:26:25.858165+02 │ logged_messages │ False      │ 01H1S37SZ4VRTH2HFWQ2PE3JN5 │ WARNING       │ INFO      │ 0002000000003636353934385119003b0032 │ [vehicle_imu] ACC 1 (2490386) offset committed: [-0.101 0.195 -0.053]->[-0.123 0.107 -0.129]) │
│ NULL     │ _result │     2 │ 2023-05-31 16:26:24.748908+02 │ logged_messages │ False      │ 01H1S37SZ4VRTH2HFWQ2PE3JN5 │ WARNING       │ WARNING   │ 0002000000003636353934385119003b0032 │ [commander] Kill-switch engaged                                                                  │
│ NULL     │ _result │     3 │ 2023-05-31 16:28:42.448271+02 │ logged_messages │ False      │ 01H1S3BY5EKMS4RRJWSEJ2PFK2 │ WARNING       │ INFO      │ 0002000000003636353934385119003b0032 │ [commander] Takeoff detected                                                                        │
│ NULL     │ _result │     3 │ 2023-05-31 16:31:19.948154+02 │ logged_messages │ False      │ 01H1S3BY5EKMS4RRJWSEJ2PFK2 │ WARNING       │ INFO      │ 0002000000003636353934385119003b0032 │ [commander] Landing detected                                                                        │
│ NULL     │ _result │     3 │ 2023-05-31 16:31:20.955221+02 │ logged_messages │ False      │ 01H1S3BY5EKMS4RRJWSEJ2PFK2 │ WARNING       │ INFO      │ 0002000000003636353934385119003b0032 │ [commander] Disarmed by landing                                                                  │
│  ·       │    ·    │     · │               ·               │        ·        │   ·        │             ·              │    ·          │  ·        │                  ·                   │                ·                                                                              │
│  ·       │    ·    │     · │               ·               │        ·        │   ·        │             ·              │    ·          │  ·        │                  ·                   │                ·                                                                              │
│  ·       │    ·    │     · │               ·               │        ·        │   ·        │             ·              │    ·          │  ·        │                  ·                   │                ·                                                                              │
│ NULL     │ _result │    15 │ 2023-05-31 18:47:05.428597+02 │ logged_messages │ False      │ 01H1SAPT98GKTZYK0DH09943ZT │ WARNING       │ INFO      │ 0002000000003636353934385119003b0032 │ [commander] Kill-switch engaged                                                                  │
│ NULL     │ _result │    16 │ 2023-05-31 18:37:21.403343+02 │ logged_messages │ False      │ 01H1SAPT98GKTZYK0DH09943ZT │ WARNING       │ WARNING   │ 0002000000003636353934385119003b0032 │ [commander] Motor failure detected                                                                    │
│ NULL     │ _result │    16 │ 2023-05-31 18:47:06.211374+02 │ logged_messages │ False      │ 01H1SAPT98GKTZYK0DH09943ZT │ WARNING       │ WARNING   │ 0002000000003636353934385119003b0032 │ [commander] Motor recovered                                                                          │
│ NULL     │ _result │    17 │ 2023-05-31 19:12:01.608221+02 │ logged_messages │ False      │ 01H1SCQDVME5Q88HB7N7YVPC3H │ WARNING       │ INFO      │ 0002000000003636353934385119003b0032 │ [commander] Takeoff detected                                                                        │
│ NULL     │ _result │    17 │ 2023-05-31 19:17:45.160216+02 │ logged_messages │ False      │ 01H1SCQDVME5Q88HB7N7YVPC3H │ WARNING       │ INFO      │ 0002000000003636353934385119003b0032 │ [commander] Landing detected                                                                        │
│ NULL     │ _result │    17 │ 2023-05-31 19:17:46.173924+02 │ logged_messages │ False      │ 01H1SCQDVME5Q88HB7N7YVPC3H │ WARNING       │ INFO      │ 0002000000003636353934385119003b0032 │ [vehicle_imu] ACC 1 (2490386) offset committed: [0.068 -0.039 -0.127]->[0.074 0.162 -0.151])  │
│ NULL     │ _result │    18 │ 2023-05-31 19:16:26.049831+02 │ logged_messages │ False      │ 01H1SCQDVME5Q88HB7N7YVPC3H │ WARNING       │ WARNING   │ 0002000000003636353934385119003b0032 │ [commander] Motor failure detected                                                                    │
│ NULL     │ _result │    18 │ 2023-05-31 19:17:46.194896+02 │ logged_messages │ False      │ 01H1SCQDVME5Q88HB7N7YVPC3H │ WARNING       │ WARNING   │ 0002000000003636353934385119003b0032 │ [commander] Motor recovered                                                                          │
│ NULL     │ _result │    19 │ 2023-05-31 19:25:58.746933+02 │ logged_messages │ False      │ 01H1SD7J6V62CN3YTJ7QS7715D │ WARNING       │ INFO      │ 0002000000003636353934385119003b0032 │ [commander] Landing detected                                                                        │
│ NULL     │ _result │    20 │ 2023-05-31 19:22:26.896489+02 │ logged_messages │ False      │ 01H1SD7J6V62CN3YTJ7QS7715D │ WARNING       │ WARNING   │ 0002000000003636353934385119003b0032 │ [commander] Motor failure detected                                                                    │
├──────────┴─────────┴───────┴───────────────────────────────┴─────────────────┴────────────┴────────────────────────────┴───────────────┴───────────┴──────────────────────────────────────┴───────────────────────────────────────────────────────────────────────────────────────────────┤
│ 49 rows (20 shown)                                                                                                                                                                                                                                                             11 columns │
└───────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────┘
```

**Comment by Tishj** [comment]
This seems to be fixed by #8387 

I did however had to alter your example, as I was getting:
```
Traceback (most recent call last):
  File "/Users/thijs/DuckDBLabs/duckdb/tmp/read_csv_glob.py", line 18, in <module>
    rel = duckdb.read_csv(CSV_FILE, header=True, skiprows=1, delimiter=",", quotechar='"', escapechar="\\", dtype=COLUMNS)
duckdb.duckdb.BinderException: Binder Error: COLUMN_TYPES error: Columns with names: "_col0" do not exist in the CSV File
```

The code I used to test was this:
```py
import duckdb

CSV_FILE="tmp/647671e0.csv"
COLUMNS= {
	'result': 'VARCHAR',
	'table': 'BIGINT',
	'_time': 'TIMESTAMPTZ',
	'_measurement': 'VARCHAR',
	'bench_test': 'VARCHAR',
	'flight_id': 'VARCHAR',
	'flight_status': 'VARCHAR',
	'log_level': 'VARCHAR',
	'sys_uuid': 'VARCHAR',
	'message': 'VARCHAR'
}

rel = duckdb.read_csv(CSV_FILE, header=True, skiprows=1, delimiter=",", quotechar='"', escapechar="\\", dtype=COLUMNS)
rel.show()
```

**Comment by Finwood** [comment]
> this seems to break our Box renderer

There's literal tab characters in the data ¯\_(ツ)_/¯

> I did however had to alter your example

Incredibly sorry, I must have pasted the wrong code snippet after all 🙈 

> This seems to be fixed by https://github.com/duckdb/duckdb/pull/8387

Awesome, thanks!

**Comment by pdet** [comment]
@szarnyasg it seems that @Tishj already added this test in a merged PR:
https://github.com/duckdb/duckdb/pull/8387

I'm closing the issue. Feel free to reopen if I got sth wrong.
