### ISSUE TITLE
DBeaver geometry display error

### ISSUE THREAD

**Issue by LonwoLonwo** [duckdb/duckdb#8456]
### What happens?

The original ticket is here: https://github.com/dbeaver/dbeaver/issues/20236

The display of geometries is buggy:
```
install spatial;
load spatial;
select st_point(0, 0);
```
displays: 
```
java.lang.ClassCastException: class java.nio.DirectByteBuffer cannot be cast to class java.lang.String (java.nio.DirectByteBuffer and java.lang.String are in module java.base of loader 'bootstrap')
	at org.duckdb.DuckDBVector.getLazyString(DuckDBVector.java:211)
	at org.duckdb.DuckDBVector.getObject(DuckDBVector.java:110)
	at org.duckdb.DuckDBResultSet.getObject(DuckDBResultSet.java:161)
	at org.jkiss.dbeaver.model.impl.jdbc.exec.JDBCResultSetImpl.getAttributeValue(JDBCResultSetImpl.java:147)
	at org.jkiss.dbeaver.model.impl.data.DefaultValueHandler.fetchValueObject(DefaultValueHandler.java:49)
	at org.jkiss.dbeaver.ui.controls.resultset.ResultSetDataReceiver.fetchRow(ResultSetDataReceiver.java:126)
	at org.jkiss.dbeaver.ui.editors.sql.execute.SQLQueryJob.fetchQueryData(SQLQueryJob.java:828)
	at org.jkiss.dbeaver.ui.editors.sql.execute.SQLQueryJob.executeStatement(SQLQueryJob.java:632)
	at org.jkiss.dbeaver.ui.editors.sql.execute.SQLQueryJob.lambda$1(SQLQueryJob.java:491)
	at org.jkiss.dbeaver.model.exec.DBExecUtils.tryExecuteRecover(DBExecUtils.java:189)
	at org.jkiss.dbeaver.ui.editors.sql.execute.SQLQueryJob.executeSingleQuery(SQLQueryJob.java:498)
	at org.jkiss.dbeaver.ui.editors.sql.execute.SQLQueryJob.extractData(SQLQueryJob.java:924)
	at org.jkiss.dbeaver.ui.editors.sql.SQLEditor$QueryResultsContainer.readData(SQLEditor.java:3895)
	at org.jkiss.dbeaver.ui.controls.resultset.ResultSetJobDataRead.lambda$0(ResultSetJobDataRead.java:123)
	at org.jkiss.dbeaver.model.exec.DBExecUtils.tryExecuteRecover(DBExecUtils.java:189)
	at org.jkiss.dbeaver.ui.controls.resultset.ResultSetJobDataRead.run(ResultSetJobDataRead.java:121)
	at org.jkiss.dbeaver.ui.controls.resultset.ResultSetViewer$ResultSetDataPumpJob.run(ResultSetViewer.java:5096)
	at org.jkiss.dbeaver.model.runtime.AbstractJob.run(AbstractJob.java:105)
	at org.eclipse.core.internal.jobs.Worker.run(Worker.java:63)
```

I tried adding recognitions for geometry types from DBeaver side, but I had no luck.

### To Reproduce

```
install spatial;
load spatial;
select st_point(0, 0);
```

Execute these in the SQL Editor of DBeaver

### OS:

Windows

### DuckDB Version:

DuckDB v0.8.1

### DuckDB Client:

DBeaver 23.1.4

### Full Name:

Anastasiia Volkova

### Affiliation:

DBeaver

### Have you tried this on the latest `master` branch?

I have tested with a master build

### Have you tried the steps to reproduce? Do they include all relevant data and configuration? Does the issue you report still appear there?

- [X] Yes, I have

**Comment by LonwoLonwo** [comment]
Coll, thanks. Will wait for the next release to check.

**Comment by Mause** [comment]
@LonwoLonwo it's available to test with the latest snapshot version:

![image](https://github.com/duckdb/duckdb/assets/1405026/43d03138-aa26-4eea-918f-b6f48adc2870)
