### ISSUE TITLE
Node DuckDB import on Linux/ARM fails with ERR_DLOPEN_FAILED

### ISSUE THREAD

**Issue by gka** [duckdb/duckdb#8909]
### What happens?

On a fresh Ubuntu22/aarch64 machine with Node 18, when importing the `duckdb` node package I am getting this error:

```
node:internal/modules/cjs/loader:1340
  return process.dlopen(module, path.toNamespacedPath(filename));
                 ^

Error: /home/ubuntu/test/node_modules/duckdb/lib/binding/duckdb.node: cannot open shared object file: No such file or directory
    at Module._extensions..node (node:internal/modules/cjs/loader:1340:18)
    at Module.load (node:internal/modules/cjs/loader:1119:32)
    at Module._load (node:internal/modules/cjs/loader:960:12)
    at Module.require (node:internal/modules/cjs/loader:1143:19)
    at require (node:internal/modules/cjs/helpers:121:18)
    at Object.<anonymous> (/home/ubuntu/test/node_modules/duckdb/lib/duckdb-binding.js:4:15)
    at Module._compile (node:internal/modules/cjs/loader:1256:14)
    at Module._extensions..js (node:internal/modules/cjs/loader:1310:10)
    at Module.load (node:internal/modules/cjs/loader:1119:32)
    at Module._load (node:internal/modules/cjs/loader:960:12) {
  code: 'ERR_DLOPEN_FAILED'
}
```

### To Reproduce

Run this on a fresh Ubuntu/ARM system with Node 18 installed (e.g. `t4g.micro` on EC2)

```shell
$ lsb_release -a
No LSB modules are available.
Distributor ID:	Ubuntu
Description:	Ubuntu 22.04.3 LTS
Release:	22.04
Codename:	jammy

$ uname -a
Linux ip-172-31-40-67 5.19.0-1025-aws #26~22.04.1-Ubuntu SMP Mon Apr 24 01:58:03 UTC 2023 aarch64 aarch64 aarch64 GNU/Linux

$ node --version
v18.17.1

$ mkdir test && cd test && npm init -y
Wrote to /home/ubuntu/test/package.json

$ npm install duckdb

added 144 packages, and audited 145 packages in 10s

18 packages are looking for funding
  run `npm fund` for details

found 0 vulnerabilities

$ echo "import duckdb from 'duckdb';" > test.mjs

$ node test.mjs
node:internal/modules/cjs/loader:1340
  return process.dlopen(module, path.toNamespacedPath(filename));
                 ^

Error: /home/ubuntu/test/node_modules/duckdb/lib/binding/duckdb.node: cannot open shared object file: No such file or directory
    at Module._extensions..node (node:internal/modules/cjs/loader:1340:18)
    at Module.load (node:internal/modules/cjs/loader:1119:32)
    at Module._load (node:internal/modules/cjs/loader:960:12)
    at Module.require (node:internal/modules/cjs/loader:1143:19)
    at require (node:internal/modules/cjs/helpers:121:18)
    at Object.<anonymous> (/home/ubuntu/test/node_modules/duckdb/lib/duckdb-binding.js:4:15)
    at Module._compile (node:internal/modules/cjs/loader:1256:14)
    at Module._extensions..js (node:internal/modules/cjs/loader:1310:10)
    at Module.load (node:internal/modules/cjs/loader:1119:32)
    at Module._load (node:internal/modules/cjs/loader:960:12) {
  code: 'ERR_DLOPEN_FAILED'
}

Node.js v18.17.1
```

### OS:

Linux, aarch64

### DuckDB Version:

0.8.1

### DuckDB Client:

Node

### Full Name:

Gregor Aisch

### Affiliation:

Datawrapper

### Have you tried this on the latest `main` branch?

I have tested with a release build (and could not test with a main build)

### Have you tried the steps to reproduce? Do they include all relevant data and configuration? Does the issue you report still appear there?

- [X] Yes, I have

**Comment by Mause** [comment]
Hey there, thanks for the super detailed issue! Is there any chance you could provide the `npm install` logs in detailed mode? Also checking if the duckdb.node native binding file exists at all would be super helpful

**Comment by gka** [comment]
Hi, do you mean `npm i --verbose`?

```
$ npm i --verbose
npm verb cli /usr/bin/node /usr/bin/npm
npm info using npm@9.6.7
npm info using node@v18.17.1
npm verb title npm i
npm verb argv "i" "--loglevel" "verbose"
npm verb logfile logs-max:10 dir:/home/ubuntu/.npm/_logs/2023-09-13T10_35_11_667Z-
npm verb logfile /home/ubuntu/.npm/_logs/2023-09-13T10_35_11_667Z-debug-0.log
npm http fetch POST 200 https://registry.npmjs.org/-/npm/v1/security/advisories/bulk 724ms
npm info run duckdb@0.8.1 install node_modules/duckdb node-pre-gyp install --fallback-to-build
npm info run duckdb@0.8.1 install { code: 0, signal: null }

added 144 packages, and audited 145 packages in 5s

18 packages are looking for funding
  run `npm fund` for details

found 0 vulnerabilities
npm verb exit 0
npm info ok
```

also, here's the full npm log: [2023-09-13T10_35_11_667Z-debug-0.log](https://github.com/duckdb/duckdb/files/12596440/2023-09-13T10_35_11_667Z-debug-0.log)

The file does seem to exist:

```
$ ll /home/ubuntu/test/node_modules/duckdb/lib/binding/duckdb.node
-rwxr-xr-x 1 ubuntu ubuntu 47772768 Jun 13 09:32 /home/ubuntu/test/node_modules/duckdb/lib/binding/duckdb.node*
```

**Comment by gka** [comment]
Btw, I've also tried to download and run the duckdb binary directly (from [here](https://github.com/duckdb/duckdb/releases/download/v0.8.1/duckdb_cli-linux-aarch64.zip)) and it works fine.

**Comment by Mause** [comment]
Oh interesting, what's the result of `file duckdb.node` then?

**Comment by gka** [comment]
ah, it looks like it has the wrong architecture: 

```
$ file node_modules/duckdb/lib/binding/duckdb.node
node_modules/duckdb/lib/binding/duckdb.node: ELF 64-bit LSB shared object, x86-64, version 1 (GNU/Linux), dynamically linked, BuildID[sha1]=e11d8bbba849abe4ebab251d09a61b482448b181, not stripped
```

**Comment by Mause** [comment]
If you need a workaround for now, you should be able to do `npm install --install-from-source`

**Comment by gka** [comment]
I did some more digging, and it looks like `node-pre-gyp` is downloading the correct archive (at least judging by the filename): https://duckdb-node.s3.amazonaws.com/duckdb-v0.8.1-node-v108-linux-arm64.tar.gz 

```
~/test/node_modules/duckdb$ npx node-pre-gyp reinstall 
node-pre-gyp info it worked if it ends with ok
node-pre-gyp info using node-pre-gyp@1.0.11
node-pre-gyp info using node@18.17.1 | linux | arm64
node-pre-gyp info check checked for "/home/ubuntu/test/node_modules/duckdb/lib/binding/duckdb.node" (not found)
node-pre-gyp http GET https://duckdb-node.s3.amazonaws.com/duckdb-v0.8.1-node-v108-linux-arm64.tar.gz
node-pre-gyp info install unpacking binding/duckdb.node
node-pre-gyp info extracted file count: 1
[duckdb] Success: "/home/ubuntu/test/node_modules/duckdb/lib/binding/duckdb.node" is installed via remote
node-pre-gyp info ok
```

But the contained `bindings/duckdb.node` is x86-64, so perhaps the archive is just contains the wrong build version?

**Comment by gka** [comment]
OK, I'm fairly convinced by now that the x64 and arm64 archives contain the same `duckdb.node` binaries 😅 

```
$ wget https://duckdb-node.s3.amazonaws.com/duckdb-v0.8.1-node-v108-linux-arm64.tar.gz
$ wget https://duckdb-node.s3.amazonaws.com/duckdb-v0.8.1-node-v108-linux-x64.tar.gz
$ tar xf duckdb-v0.8.1-node-v108-linux-arm64.tar.gz --directory=arm64
$ tar xf duckdb-v0.8.1-node-v108-linux-x64.tar.gz --directory=x64
$ stat -f "%z bytes" arm64/binding/duckdb.node
47772768 bytes
$ stat -f "%z bytes" x64/binding/duckdb.node
47772768 bytes
$ file arm64/binding/duckdb.node
arm64/binding/duckdb.node: ELF 64-bit LSB shared object, x86-64, version 1 (GNU/Linux), dynamically linked, BuildID[sha1]=e11d8bbba849abe4ebab251d09a61b482448b181, not stripped
➜ file x64/binding/duckdb.node
x64/binding/duckdb.node: ELF 64-bit LSB shared object, x86-64, version 1 (GNU/Linux), dynamically linked, BuildID[sha1]=e11d8bbba849abe4ebab251d09a61b482448b181, not stripped
```
