### ISSUE TITLE
INTERNAL Error: Attempted to access index 1 within vector of size 1

### ISSUE THREAD

**Issue by jbaranski** [duckdb/duckdb#9433]
### What happens?

When attempting to use an `ORDER BY` clause in a query, I get the below error. Without the `ORDER BY` clause, there is no issue with the query and it executes successfully.

After the error is received, the database is in a bad state/crashed, and I must re-connect to run more queries.

Query:
```
SELECT UNNEST(player_statistics) FROM 
	(SELECT player.id AS player_id,
         UNNEST (player_stats.statistics).team.id AS team_id,
         UNNEST (player_stats.statistics).games.appearences * UNNEST (player_stats.statistics).games.minutes AS totals
	 FROM player_stats) AS player_statistics
WHERE team_id = 48
AND totals > 0
ORDER BY totals
```

```
org.jkiss.dbeaver.model.sql.DBSQLException: SQL Error: java.sql.SQLException: INTERNAL Error: Attempted to access index 1 within vector of size 1
	at org.jkiss.dbeaver.model.impl.jdbc.exec.JDBCStatementImpl.executeStatement(JDBCStatementImpl.java:133)
	at org.jkiss.dbeaver.ui.editors.sql.execute.SQLQueryJob.executeStatement(SQLQueryJob.java:583)
	at org.jkiss.dbeaver.ui.editors.sql.execute.SQLQueryJob.lambda$1(SQLQueryJob.java:492)
	at org.jkiss.dbeaver.model.exec.DBExecUtils.tryExecuteRecover(DBExecUtils.java:190)
	at org.jkiss.dbeaver.ui.editors.sql.execute.SQLQueryJob.executeSingleQuery(SQLQueryJob.java:499)
	at org.jkiss.dbeaver.ui.editors.sql.execute.SQLQueryJob.extractData(SQLQueryJob.java:947)
	at org.jkiss.dbeaver.ui.editors.sql.SQLEditor$QueryResultsContainer.readData(SQLEditor.java:4100)
	at org.jkiss.dbeaver.ui.controls.resultset.ResultSetJobDataRead.lambda$0(ResultSetJobDataRead.java:123)
	at org.jkiss.dbeaver.model.exec.DBExecUtils.tryExecuteRecover(DBExecUtils.java:190)
	at org.jkiss.dbeaver.ui.controls.resultset.ResultSetJobDataRead.run(ResultSetJobDataRead.java:121)
	at org.jkiss.dbeaver.ui.controls.resultset.ResultSetViewer$ResultSetDataPumpJob.run(ResultSetViewer.java:5164)
	at org.jkiss.dbeaver.model.runtime.AbstractJob.run(AbstractJob.java:105)
	at org.eclipse.core.internal.jobs.Worker.run(Worker.java:63)
Caused by: java.sql.SQLException: java.sql.SQLException: INTERNAL Error: Attempted to access index 1 within vector of size 1
	at org.duckdb.DuckDBPreparedStatement.prepare(DuckDBPreparedStatement.java:112)
	at org.duckdb.DuckDBPreparedStatement.execute(DuckDBPreparedStatement.java:183)
	at org.jkiss.dbeaver.model.impl.jdbc.exec.JDBCStatementImpl.execute(JDBCStatementImpl.java:330)
	at org.jkiss.dbeaver.model.impl.jdbc.exec.JDBCStatementImpl.executeStatement(JDBCStatementImpl.java:131)
	... 12 more
Caused by: java.sql.SQLException: INTERNAL Error: Attempted to access index 1 within vector of size 1
	at org.duckdb.DuckDBNative.duckdb_jdbc_prepare(Native Method)
	at org.duckdb.DuckDBPreparedStatement.prepare(DuckDBPreparedStatement.java:106)
	... 15 more
```

### To Reproduce

1. Download the following duckdb database file: https://github.com/jbaranski/duck-db-bug-report/blob/main/data.db
2. Connect to the database in DBeaver (I used `Version 23.2.3.202310221533`) on MacOS `Ventura 13.4.1` with an `M1` chip.
3. Run the query successfully:
```
SELECT UNNEST(player_statistics) FROM 
	(SELECT player.id AS player_id,
         UNNEST (player_stats.statistics).team.id AS team_id,
         UNNEST (player_stats.statistics).games.appearences * UNNEST (player_stats.statistics).games.minutes AS totals
	 FROM player_stats) AS player_statistics
WHERE team_id = 48
AND totals > 0
```
4. Run the same query with an `ORDER BY` clause, it breaks:
```
SELECT UNNEST(player_statistics) FROM 
	(SELECT player.id AS player_id,
         UNNEST (player_stats.statistics).team.id AS team_id,
         UNNEST (player_stats.statistics).games.appearences * UNNEST (player_stats.statistics).games.minutes AS totals
	 FROM player_stats) AS player_statistics
WHERE team_id = 48
AND totals > 0
ORDER BY totals
```

### OS:

MacOS - Ventura 13.4.1

### DuckDB Version:

0.9.1

### DuckDB Client:

Java/DBeaver

### Full Name:

Jeff Baranski

### Affiliation:

Hobby Project / No Affiliation

### Have you tried this on the latest `main` branch?

I have tested with a main build

### Have you tried the steps to reproduce? Do they include all relevant data and configuration? Does the issue you report still appear there?

- [X] Yes, I have

**Comment by l1t1** [comment]
reproduced in pure CLI
```
D:\>duckdb\duckdb091 data.db
v0.9.1 401c8061c6
Enter ".help" for usage hints.
D SELECT UNNEST(player_statistics) FROM
>       (SELECT player.id AS player_id,
>          UNNEST (player_stats.statistics).team.id AS team_id,
>          UNNEST (player_stats.statistics).games.appearences * UNNEST (player_stats.statistics).games.minutes AS totals
>        FROM player_stats) AS player_statistics
> WHERE team_id = 48
> AND totals > 0;
┌───────────┬─────────┬────────┐
│ player_id │ team_id │ totals │
│   int64   │  int64  │ int64  │
├───────────┼─────────┼────────┤
│      2869 │      48 │   3521 │
│     19361 │      48 │   2359 │
│     19428 │      48 │   5760 │
│     18955 │      48 │    165 │
│     18955 │      48 │    165 │
│     18955 │      48 │    165 │
│     18955 │      48 │    165 │
│     18955 │      48 │    165 │
│     18955 │      48 │    165 │
│     18819 │      48 │   4808 │
│      1243 │      48 │   3822 │
│     15911 │      48 │    355 │
│      1646 │      48 │   5696 │
│      1697 │      48 │    840 │
│      2938 │      48 │   4347 │
│     21694 │      48 │   4249 │
│      2284 │      48 │   5760 │
│       261 │      48 │     54 │
│     18817 │      48 │    222 │
│      1231 │      48 │   5736 │
│      2726 │      48 │   5760 │
│       253 │      48 │   5760 │
├───────────┴─────────┴────────┤
│ 22 rows            3 columns │
└──────────────────────────────┘
D SELECT UNNEST(player_statistics) FROM
>       (SELECT player.id AS player_id,
>          UNNEST (player_stats.statistics).team.id AS team_id,
>          UNNEST (player_stats.statistics).games.appearences * UNNEST (player_stats.statistics).games.minutes AS totals
>        FROM player_stats) AS player_statistics
> WHERE team_id = 48
> AND totals > 0
> ORDER BY totals;
Error: INTERNAL Error: Attempted to access index 1 within vector of size 1
```
