### ISSUE TITLE
While connecting with DBeaver foreign key relationship is not shown in ER diagram

### ISSUE THREAD

**Issue by fuubarbaz** [duckdb/duckdb#9468]
### What happens?

I'm trying to get rid of sqlite and replace it with duckdb. One of the key requirement I have is smooth integration with dbeaver.
Seems like the current version of dbeaver doesn't show constraints correctly for duckdb. I mean foreign key relationship is not correctly show in ER Diagram.
I hope this is the right place to create this particular issue. 

![image](https://github.com/duckdb/duckdb/assets/76524463/a426dda7-7c3b-4636-85d1-9835af9b4b20)

![image](https://github.com/duckdb/duckdb/assets/76524463/4b712a29-6afe-4b3f-93d4-470428e5d375)

![image](https://github.com/duckdb/duckdb/assets/76524463/c1de67b4-009e-48b6-8564-7d0d9ae2a08e)

### To Reproduce

- Install and connect dbeaver with duckdb as mentioned in the page https://duckdb.org/docs/guides/sql_editors/dbeaver
- Right click on the connection and create new sql script.
- Paste the following 
`CREATE TABLE students(id INTEGER PRIMARY KEY, name VARCHAR); 
CREATE TABLE exams(exam_id INTEGER REFERENCES students(id), grade INTEGER);
INSERT INTO students VALUES (2, 'Student 2');
INSERT INTO exams VALUES (2, 20);`
- Expand database and then right click on main and select View Diagram.

### OS:

Windows

### DuckDB Version:

0.91

### DuckDB Client:

0.91

### Full Name:

Vivek Kumar Jain

### Affiliation:

ASML

### Have you tried this on the latest `main` branch?

I have tested with a release build (and could not test with a main build)

### Have you tried the steps to reproduce? Do they include all relevant data and configuration? Does the issue you report still appear there?

- [X] Yes, I have

**Comment by LonwoLonwo** [comment]
As I can see, it is not supported by the driver:

```
java.sql.SQLFeatureNotSupportedException: getImportedKeys
	at org.duckdb.DuckDBDatabaseMetaData.getImportedKeys(DuckDBDatabaseMetaData.java:947)
	at org.jkiss.dbeaver.model.impl.jdbc.exec.JDBCDatabaseMetaDataImpl.getImportedKeys(JDBCDatabaseMetaDataImpl.java:1206)
	at org.jkiss.dbeaver.ext.generic.model.meta.GenericMetaModel.prepareForeignKeysLoadStatement(GenericMetaModel.java:765)
	at org.jkiss.dbeaver.ext.generic.model.ForeignKeysCache.prepareObjectsStatement(ForeignKeysCache.java:78)
	at org.jkiss.dbeaver.ext.generic.model.ForeignKeysCache.prepareObjectsStatement(ForeignKeysCache.java:1)
	at org.jkiss.dbeaver.model.impl.jdbc.cache.JDBCCompositeCache.loadObjects(JDBCCompositeCache.java:298)
```

Does DuckDB have plans to support foreign key info for the driver side? The duckdb_constraints contains some necessary info.

**Comment by rsmckinney** [comment]
This is a rather large hole in the driver. Are there plans to implement this? If not, would you accept an external PR?

**Comment by Mause** [comment]
External PRs are always welcome

**Comment by wyhaya** [comment]
Are we just missing a method to get a list of foreign keys in DuckDB?

```sql
-- SQLite
SELECT * FROM pragma_foreign_key_list("...");
-- MySQL
SELECT * FROM INFORMATION_SCHEMA.KEY_COLUMN_USAGE WHERE referenced_column_name IS NOT NULL;
-- SQL Server
SELECT * FROM sys.foreign_key_columns;

-- DuckDB
???
```

**Comment by rsmckinney** [comment]
```sql
-- DuckDB (as far as I know)
SELECT * FROM duckdb_constraints WHERE constraint_type = 'FOREIGN KEY' . . .
```
But the results don't provide PK linkage, instead it just dumps the FK ddl sql. I have an implementation of this method that parses the FK sql to produce the PK linkage. It's not that complicated and is working fine.

I'd like to make a pull request for duckdb-java, however that project is hard to deal with, it's not really setup for actual Java dev. For now I have one-off implementations like this one where the duckdb JDBC driver fails... there's are too many of these to count.

**Comment by bskubi** [comment]
I am also having this issue. Hope a fix is forthcoming! Thanks.
