### ISSUE TITLE
Typeof does not work when using JDBC

### ISSUE THREAD

**Issue by mrigger** [duckdb/duckdb#966]
When using `ResultSet.executeQuery` with a query that uses `typeof` (e.g., `SELECT typeof(1);`), the following exception is thrown:

```
Caused by: java.sql.SQLException: Catalog: Scalar Function with name typeof does not exist!
	at org.duckdb.DuckDBNative.duckdb_jdbc_prepare(Native Method)
	at org.duckdb.DuckDBPreparedStatement.prepare(DuckDBPreparedStatement.java:73)
	at org.duckdb.DuckDBPreparedStatement.executeQuery(DuckDBPreparedStatement.java:127)
```

**Comment by mrigger** [comment]
On a related note, it seems that queries like `SELECT 1` or `SELECT 1 FROM t0` currently result in the following exception:

```
java.lang.ArrayIndexOutOfBoundsException: -1
	at org.duckdb.DuckDBResultSet.check_and_null(DuckDBResultSet.java:147)
	at org.duckdb.DuckDBResultSet.getString(DuckDBResultSet.java:152)
```
In the `check_and_null` method, the `chunk_idx` unexpectedly is 0.

**Comment by jonathanswenson** [comment]
This appears to work now -- `select typeof(1)` returns INTEGER. 

Additionally `select 1` returns data when using the getString method for the first column (`getString(1)`)

**Comment by hannes** [comment]
Indeed this is fixed. Adding a test case.
