### ISSUE TITLE
[python] read_csv does not accept iterable of filenames

### ISSUE THREAD

**Issue by ADevAJ** [duckdb/duckdb#9723]
### What happens?
```
Python\Python311\Lib\site-packages\duckdb\filesystem.py", line 58, in add_file
    raise ValueError("Can not read from a non file-like object")
ValueError: Can not read from a non file-like object
```
### To Reproduce
```python
import duckdb
from io import StringIO

con = duckdb.connect()
file1 = StringIO('one,two,three,four\n1,2,3,4\n1,2,3,4\n1,2,3,4')
file2 = StringIO('one,two,three,four\n5,6,7,8\n5,6,7,8\n5,6,7,8')
file3 = StringIO('one,two,three,four\n9,10,11,12\n9,10,11,12\n9,10,11,12')
files = [file1, file2, file3] # same Error raised if files = ["/*.csv"] glob patterns, string literal file paths or pathlib.Path objects
rel = con.read_csv(files)
res = rel.fetchall()
assert res == [
	(1, 2, 3, 4),
	(1, 2, 3, 4),
	(1, 2, 3, 4),
	(5, 6, 7, 8),
	(5, 6, 7, 8),
	(5, 6, 7, 8),
	(9, 10, 11, 12),
	(9, 10, 11, 12),
	(9, 10, 11, 12),
]
```
### OS:

Windows 10 Pro Build 19045.3570 x64

### DuckDB Version:

0.9.3dev42

### DuckDB Client:

Python 3.11.3 64-bit

### Full Name:

A Ovitz

### Affiliation:

USC

### Have you tried this on the latest `main` branch?

I have tested with a main build

### Have you tried the steps to reproduce? Do they include all relevant data and configuration? Does the issue you report still appear there?

- [X] Yes, I have

**Comment by l1t1** [comment]
your code raises other errors in my Linux system. 
```
# python3
Python 3.10.12 (main, Jun 11 2023, 05:26:28) [GCC 11.4.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import duckdb
>>> from io import StringIO
>>>
>>> con = duckdb.connect()
>>> file1 = StringIO('one,two,three,four\n1,2,3,4\n1,2,3,4\n1,2,3,4')
>>> file2 = StringIO('one,two,three,four\n5,6,7,8\n5,6,7,8\n5,6,7,8')
>>> file3 = StringIO('one,two,three,four\n9,10,11,12\n9,10,11,12\n9,10,11,12')
>>> files = [file1, file2, file3] # same Error raised if files = ["/*.csv"] glob patterns, string literal file paths or pathlib.Path objects
>>> rel = con.read_csv(files)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
duckdb.InvalidInputException: Invalid Input Error: Required module 'pyduckdb.filesystem' failed to import, due to the following Python exception:
ModuleNotFoundError: No module named 'fsspec'

At:
  /usr/local/lib/python3.10/dist-packages/pyduckdb/filesystem.py(1): <module>
  <frozen importlib._bootstrap>(241): _call_with_frames_removed
  <frozen importlib._bootstrap_external>(883): exec_module
  <frozen importlib._bootstrap>(703): _load_unlocked
  <frozen importlib._bootstrap>(1006): _find_and_load_unlocked
  <frozen importlib._bootstrap>(1027): _find_and_load
  <stdin>(1): <module>

>>> rel = con.read_csv(file1)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
duckdb.InvalidInputException: Invalid Input Error: This operation could not be completed because required module 'fsspec' is not installed
```

**Comment by Tishj** [comment]
As said above, we require `fsspec` when providing an iterable of filenames.
The error you posted is not expected.

It's raised by us when this check fails on the provided object:
```py
def is_file_like(obj):
    # We only care that we can read from the file
    return hasattr(obj, "read") and hasattr(obj, "seek")
```
